import { test } from 'node:test';
import assert from 'node:assert/strict';
import { emptyExecutiveState, type RoadmapPlan, type PerformanceRow } from './types.ts';
import { delayDays, money, readPlanDate, dateBounds, savePlan, mergeRows, publishImport } from './model.ts';
import { normalizeRows, parseCsv } from './import.ts';
import { projectPerformance, comparableGrowth } from './projection.ts';
import { canApprovePerformance } from './access.ts';

const row:PerformanceRow={key:'a',product:'CASH_COLLECTION',source:'source',date:'2026-08-03',kind:'CASH_IN',amount:1500000,currency:'EGP',businessUnit:'UNASSIGNED',runner:'r',supplier:'s',terminal:'t'};
const plan:RoadmapPlan={id:'',name:'Delivery plan',squad:'Acceptance',workstream:'Payments',owner:'Product lead',outcome:'Launch service',start:{value:'2027-01',precision:'MONTH'},target:{value:'2027-03',precision:'MONTH'},originalTarget:null,actual:null,forecast:null,status:'COMMITTED',carryover:false,delayReason:'',nextAction:'',nextActionOwner:'',source:'Reviewed plan',revision:0,updatedAt:'',updatedBy:''};
test('composing batch publications cannot partially mutate the stored state on a later conflict',()=>{
  const original=emptyExecutiveState();
  const metadata={fileName:'first.csv',digest:'first',product:'CASH_COLLECTION' as const,source:'source',periodStart:'2026-08-01',periodEnd:'2026-08-31',coverage:'COMPLETE' as const,recordedAt:'2026-10-04',recordedBy:'Owner',rowCount:1,excluded:0,note:''};
  assert.throws(()=>{
    const intermediate=publishImport(original,[row],metadata);
    publishImport(intermediate,[{...row,amount:1}],{...metadata,fileName:'second.csv',digest:'second'});
  });
  assert.equal(original.rows.length,0);
  assert.equal(original.imports.length,0);
});
test('business reporting approval is limited to organization leadership',()=>{assert.equal(canApprovePerformance({role:'VIEWER',platformRole:null,isProductLead:true}),false);assert.equal(canApprovePerformance({role:'MEMBER',platformRole:null,isProductLead:false}),false);assert.equal(canApprovePerformance({role:'MEMBER',platformRole:null,isProductLead:true}),true);assert.equal(canApprovePerformance({role:'ORG_OWNER',platformRole:null,isProductLead:false}),true);});
test('money is represented in exact integer cents',()=>{assert.equal(money('47,710,304.00'),4771030400);assert.equal(money('0.29'),29);});
test('invalid, negative and excessive precision amounts are rejected',()=>{for(const value of ['',null,'oops','1,23','-1','1.001'])assert.throws(()=>money(value));});
test('CSV handles BOM, escaped quotes, commas and multiline fields',()=>{assert.deepEqual(parseCsv('\uFEFFid,note\r\n1,"hello, ""world""\nnext"\r\n'),[{id:'1',note:'hello, "world"\nnext'}]);});
test('malformed CSV is rejected',()=>{assert.throws(()=>parseCsv('a,b\n"broken'));assert.throws(()=>parseCsv('a,a\n1,2'));assert.throws(()=>parseCsv('a\n1,2'));});
test('wallet footer is excluded and refunds remain a separate type',()=>{const base={Date:'Monday, August 31,2026 11:59:51 PM',Type:'Meeza Digital Receive (P)',Amount:'100.00',Currency:'EGP',Response:'0 - Approved','System Reference':'123'};const result=normalizeRows([base,{...base,Type:'Meeza Digital Refund',Amount:'5','System Reference':'124'},{...base,Date:'Total sales',Amount:'',Currency:'',Response:'',Type:'','System Reference':''}],'WALLET');assert.equal(result.rows.length,2);assert.equal(result.excluded,1);assert.equal(result.rows[1]!.kind,'REFUND');});
test('wallet unknown types and missing transaction IDs fail closed',()=>{assert.throws(()=>normalizeRows([{Date:'2026-08-01',Type:'other',Amount:'10',Currency:'EGP',Response:'0 - Approved','System Reference':'1'}],'WALLET'));assert.throws(()=>normalizeRows([{Date:'2026-08-01',Type:'Meeza Digital Receive (P)',Amount:'10',Currency:'EGP',Response:'0 - Approved','System Reference':''}],'WALLET'));});
test('cash-in and payments do not imply BP or FS',()=>{const result=normalizeRows([{transaction_id:'1',transaction_timestamp:'2026-08-03 10:00:00',transaction_type:'payment',amount:'5',supplier_id:'s',runner_id:'r',terminal_id:'t'}],'CASH_COLLECTION');assert.equal(result.rows[0]!.kind,'PAYMENT');assert.equal(result.rows[0]!.businessUnit,'UNASSIGNED');});
test('PGW filters failed attempts without calling them success',()=>{const result=normalizeRows([{'Transaction Reference':'1','Transaction Date':'2026-08-01','Transaction Type':'SALE','Transaction Status':'SUCCESS',Amount:'10'},{'Transaction Reference':'2','Transaction Date':'2026-08-01','Transaction Type':'SALE','Transaction Status':'FAILED',Amount:'10'}],'PGW');assert.equal(result.rows.length,1);assert.equal(result.excluded,1);});
test('transaction overlap is deduplicated, conflicting content rejected atomically',()=>{assert.equal(mergeRows([row],[row,row]).duplicates,2);assert.equal(mergeRows([],[row,row]).added.length,1);assert.throws(()=>mergeRows([row],[{...row,amount:2}]));});
test('duplicate file publication is refused',()=>{const meta={fileName:'a.csv',digest:'abc',product:'CASH_COLLECTION' as const,source:'source',periodStart:'2026-08-01',periodEnd:'2026-08-31',coverage:'COMPLETE' as const,recordedAt:'2026-10-04',recordedBy:'Owner',rowCount:1,excluded:0,note:''};const state=publishImport(emptyExecutiveState(),[row],meta);assert.throws(()=>publishImport(state,[row],meta));assert.equal(state.rows.length,1);});
test('month and quarter precision never manufacture exact dates',()=>{assert.deepEqual(readPlanDate('2027-Q2','QUARTER'),{value:'2027-Q2',precision:'QUARTER'});assert.deepEqual(dateBounds({value:'2027-Q2',precision:'QUARTER'}),['2027-04-01','2027-06-30']);assert.equal(delayDays({value:'2027-03',precision:'MONTH'},'2027-04-01'),null);assert.throws(()=>readPlanDate('2027-02-30','DAY'));});
test('the first committed target survives revisions and audit history is kept',()=>{const initial=savePlan(emptyExecutiveState(),plan,'Owner','2026-10-04T12:00:00Z');const first=initial.plans[0]!;const next=savePlan(initial,{...first,target:{value:'2027-04',precision:'MONTH'},delayReason:'External dependency'},'Owner','2026-10-04T13:00:00Z');assert.deepEqual(next.plans[0]!.originalTarget,plan.target);assert.equal(next.planEvents.length,2);assert.deepEqual(next.planEvents[1]!.before?.target,plan.target);});
test('stale plan revisions cannot overwrite other edits',()=>{const state=savePlan(emptyExecutiveState(),plan,'Owner','2026-10-04');assert.throws(()=>savePlan(state,{...state.plans[0]!,revision:0},'Owner','2026-10-04'));});
test('future actual dates and reverse solution windows are rejected',()=>{assert.throws(()=>savePlan(emptyExecutiveState(),{...plan,actual:'2027-01-01'},'Owner','2026-10-04'));assert.throws(()=>savePlan(emptyExecutiveState(),{...plan,start:{value:'2027-08',precision:'MONTH'}},'Owner','2026-10-04'));});
test('target changes require a recorded reason after commitment',()=>{const state=savePlan(emptyExecutiveState(),plan,'Owner','2026-10-04');assert.throws(()=>savePlan(state,{...state.plans[0]!,target:{value:'2027-05',precision:'MONTH'}},'Owner','2026-10-04'));});
test('Cash Collection projection separates flows and counts distinct network',()=>{const state=emptyExecutiveState();state.rows=[row,{...row,key:'b',kind:'PAYMENT',amount:420000},{...row,key:'c',kind:'CASH_IN',amount:500000,runner:'r2'}];const p=projectPerformance(state,'CASH_COLLECTION')[0]!;assert.equal(p.cashIn,2000000);assert.equal(p.payments,420000);assert.equal(p.runners,2);assert.equal(p.terminals,1);assert.equal(p.complete,false);});
test('month coverage is declared, not inferred from transaction bounds',()=>{const state=emptyExecutiveState();state.rows=[row];state.imports=[{id:'a',fileName:'a',digest:'x',product:'CASH_COLLECTION',source:'source',periodStart:'2026-08-01',periodEnd:'2026-08-31',coverage:'COMPLETE',recordedAt:'',recordedBy:'',rowCount:1,added:1,duplicates:0,excluded:0,note:''}];assert.equal(projectPerformance(state,'CASH_COLLECTION')[0]!.complete,true);});
test('growth refuses partial, non-adjacent and changed-source comparisons',()=>{const s=emptyExecutiveState();s.rows=[row];const base=projectPerformance(s,'CASH_COLLECTION')[0]!;assert.equal(comparableGrowth(base,{...base,month:'2026-07'},'cashIn'),null);assert.equal(comparableGrowth({...base,complete:true},{...base,complete:true,month:'2026-07'},'cashIn'),0);assert.equal(comparableGrowth({...base,complete:true},{...base,complete:true,month:'2026-06'},'cashIn'),null);assert.equal(comparableGrowth({...base,complete:true},{...base,complete:true,month:'2026-07',sources:['other']},'cashIn'),null);});
