import type {ClaimWithEvidence} from '../domain/types.ts';
import type {InitiativeContext} from '../workspace/readiness.ts';
import {normalise,contextKey,isBlank} from './normalise.ts';
export interface Applicability {contextId?:string|null;effectiveDate?:string|null;}
export function applicabilityParts(a:Applicability):string[]{return [...(a.contextId?[`ctx:${a.contextId.toLowerCase()}`]:[]),...(a.effectiveDate?[`date:${a.effectiveDate}`]:[])];}
export function sameApplicability(a:Applicability,b:Applicability):boolean{return (a.contextId?.toLowerCase()||null)===(b.contextId?.toLowerCase()||null)&&(a.effectiveDate||null)===(b.effectiveDate||null);}
export function calendarDate(value:string):boolean {if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const parts=value.split('-').map(Number);const y=parts[0]!,m=parts[1]!,d=parts[2]!;const days=[31,y%4===0&&(y%100!==0||y%400===0)?29:28,31,30,31,30,31,31,30,31,30,31];return y>=1&&m>=1&&m<=12&&d>=1&&d<=days[m-1]!;}
export function validateApplicability(a:Applicability,contexts:readonly InitiativeContext[],workspaceId:string,initiativeId:string,existing?:Applicability):{contextId:string|null;effectiveDate:string|null;contextName:string|null}{const contextId=a.contextId?.trim().toLowerCase()||null,effectiveDate=a.effectiveDate?.trim()||null;if(effectiveDate&&!calendarDate(effectiveDate))throw Error('Enter an effective date as a valid calendar date.');const context=contextId?contexts.find(c=>c.id.toLowerCase()===contextId&&c.workspaceId===workspaceId&&c.initiativeId===initiativeId):null;if(contextId&&!context)throw Error('This context is unavailable in the initiative.');if(context?.retiredAt&&contextId!==existing?.contextId?.toLowerCase())throw Error('Choose an active context for a new record.');return {contextId,effectiveDate,contextName:context?.label??null};}
export function notCompared(claims:readonly ClaimWithEvidence[]):{claimIds:[string,string];attribute:string}[]{const eligible=claims.filter(c=>c.status==='ACTIVE'&&!isBlank(c.subject)&&!isBlank(c.attribute)&&!isBlank(c.value));const result:{claimIds:[string,string];attribute:string}[]=[];for(let i=0;i<eligible.length;i++)for(let j=i+1;j<eligible.length;j++){const a=eligible[i]!,b=eligible[j]!;if(a.initiativeId===b.initiativeId&&normalise(a.subject)===normalise(b.subject)&&normalise(a.attribute)===normalise(b.attribute)&&contextKey(a.phase)===contextKey(b.phase)&&!sameApplicability(a,b)&&a.supersededByClaimId!==b.id&&b.supersededByClaimId!==a.id)result.push({claimIds:[a.id,b.id],attribute:a.attribute});}return result;}
