-- Local-only hosted-schema acceptance. No real accounts or production data.
\set ON_ERROR_STOP on
do $$ begin if current_database() !~ '^prodwise_platform_preflight_[0-9a-f]{32}$' then raise exception 'DISPOSABLE_PREFLIGHT_DATABASE_REQUIRED';end if;end $$;
begin;
set constraints all deferred;
insert into auth.users(id,email) values('e0160000-0000-4000-8000-000000000001','guest@demo.test');
insert into public.users(id,auth_user_id,email,display_name) values('e0160000-0000-4000-8000-000000000001','e0160000-0000-4000-8000-000000000001','guest@demo.test','Fictional guest');
insert into preflight.ids values('entry-user','e0160000-0000-4000-8000-000000000001');
set role service_role;
select public.platform_create_organization(preflight.id('platform'),'Fictional entry Demo',array['demo.test'],array[]::text[]);
reset role;
insert into preflight.ids select 'entry-org',id from public.organizations where name='Fictional entry Demo';
insert into preflight.ids select 'entry-workspace',id from public.workspaces where organization_id=preflight.id('entry-org');
set role service_role;
select public.platform_provision_membership(preflight.id('platform'),preflight.id('entry-org'),'guest@demo.test','ORG_OWNER',false,'Local synthetic entry fixture',repeat('1',64));
select public.platform_provision_membership(preflight.id('platform'),preflight.id('entry-org'),'owner@alpha.test','ORG_OWNER',true,'Fictional backup owner permits guest revocation tests',repeat('3',64));
reset role;
insert into preflight.ids select 'entry-member',id from public.organization_memberships where user_id=preflight.id('entry-user') and organization_id=preflight.id('entry-org');
insert into public.demo_scenarios(workspace_id,organization_id,canonical_version,scenario_at) values(preflight.id('entry-workspace'),preflight.id('entry-org'),'entry-test',now());
insert into public.demo_entry_config(workspace_id,user_id,enabled) values(preflight.id('entry-workspace'),preflight.id('entry-user'),true);
select preflight.assert(not has_function_privilege('anon','public.create_demo_session(text,text)','EXECUTE'),'anonymous cannot call session creator');
select preflight.assert(not has_function_privilege('authenticated','public.read_demo_session(text)','EXECUTE'),'authenticated cannot inspect sessions');
select preflight.assert(not has_table_privilege('anon','public.demo_sessions','SELECT'),'anonymous cannot read hashes');
select preflight.assert(not has_table_privilege('service_role','public.demo_entry_config','UPDATE'),'runtime cannot redirect config');
select preflight.assert(not has_table_privilege('service_role','public.demo_sessions','DELETE'),'logout cannot erase rate history');
select preflight.assert(not has_column_privilege('service_role','public.demo_sessions','workspace_id','UPDATE'),'runtime cannot retarget sessions');
set role service_role;
select preflight.assert(public.create_demo_session(repeat('a',64),repeat('a',64))->>'workspaceId'=preflight.id('entry-workspace')::text,'creation pins configured workspace');
select preflight.assert(public.read_demo_session(repeat('a',64))->>'role'='ORG_OWNER','guest keeps demo operational authority');
select preflight.assert(public.read_demo_session(repeat('a',64))->'platformRole'='null'::jsonb,'guest has no platform grant');
select preflight.assert((public.require_workspace_member(preflight.id('entry-workspace'),preflight.id('entry-member'),true,true)).role='ORG_OWNER','existing admin and write checks pass in Demo');
select preflight.refused(format('select public.require_workspace_member(%L,%L,false,false)','10000000-0000-4000-8000-000000000001',preflight.id('entry-member')),'ACCESS_DENIED');
select preflight.refused(format('select public.delivery_read_workspace(%L,%L)',preflight.id('workspace-b'),preflight.id('entry-member')),'ACCESS_DENIED');
select preflight.refused(format('select public.auth_business_rpc(%L,%L,''set_finding_note'',jsonb_build_object(''p_initiative_id'',''11111111-1111-4111-8111-111111111111'',''p_fingerprint'',''entry-test'',''p_input'',''{}''::jsonb))',preflight.id('entry-workspace'),preflight.id('entry-member')),'ACCESS_DENIED');
select preflight.refused(format('select public.platform_configure_policy(%L,%L,array[''demo.test''],array[]::text[])',preflight.id('entry-user'),preflight.id('entry-org')),'PLATFORM_OWNER|PLATFORM_REQUIRED|ACCESS_DENIED');
select preflight.refused('select public.read_demo_session(repeat(''f'',64))','DEMO_SESSION_EXPIRED');
select preflight.refused('select public.create_demo_session(''bad'',repeat(''c'',64))','DEMO_UNAVAILABLE');
reset role;
savepoint entry_case;
update public.demo_entry_config set enabled=false;
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
update public.organizations set status='ARCHIVED' where id=preflight.id('entry-org');
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
update public.workspaces set status='ARCHIVED' where id=preflight.id('entry-workspace');
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
update public.users set active=false where id=preflight.id('entry-user');
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
update public.organization_memberships set role='ADMIN' where id=preflight.id('entry-member');
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
set role service_role;
select public.grant_platform_owner(preflight.id('platform'),preflight.id('entry-user'),'Fictional promotion revokes guest access');
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
set role service_role;
select public.platform_provision_membership(preflight.id('platform'),preflight.id('org-b'),'guest@demo.test','MEMBER',true,'Fictional cross-org revocation test',repeat('2',64));
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_UNAVAILABLE');
rollback to entry_case;
savepoint entry_case;
update public.demo_sessions set expires_at=created_at+interval '1 microsecond' where token_hash=repeat('a',64);
set role service_role;
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_SESSION_EXPIRED');
rollback to entry_case;
set role service_role;
update public.demo_sessions set revoked_at=clock_timestamp() where token_hash=repeat('a',64);
select preflight.refused('select public.read_demo_session(repeat(''a'',64))','DEMO_SESSION_EXPIRED');
do $$ begin for i in 1..10 loop
 perform public.create_demo_session(md5('test-'||i)||md5('test-'||i),repeat('b',64));
 update public.demo_sessions set revoked_at=clock_timestamp() where token_hash=md5('test-'||i)||md5('test-'||i);
end loop;end $$;
select preflight.refused('select public.create_demo_session(repeat(''d'',64),repeat(''b'',64))','DEMO_RATE_LIMIT');
select preflight.assert((select count(*)=10 from public.demo_sessions where request_hash=repeat('b',64) and revoked_at is not null),'ten logged-out rows still enforce rate budget');
reset role;
rollback;
select preflight.assert((select count(*)=0 from public.demo_entry_config),'test config rolled back; migration enables no public entry by default');
