\set ON_ERROR_STOP on
begin;
do $$begin if current_database() !~ '^prodwise_second_[0-9a-f]{32}$' then raise exception 'LOCAL_ONLY';end if;end$$;
set local role service_role;
do $$declare w uuid:='d2000000-0000-4000-8000-000000000002';m uuid:='d2000000-0000-4000-8000-000000000003';actor uuid;iid uuid;new_slug text;c1 uuid:=gen_random_uuid();c2 uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();z uuid:=gen_random_uuid();fp text;result_id uuid;stamp timestamptz;begin
select user_id into actor from public.organization_memberships where id=m;
new_slug:=public.create_managed_initiative(w,m,jsonb_build_object('requestId',gen_random_uuid(),'name','Synthetic minimum applicability test','businessLine','FS','stage','DISCOVERY','ownerMemberId',m));select id into iid from public.initiatives where workspace_id=w and initiatives.slug=new_slug;
insert into public.initiative_contexts(id,workspace_id,initiative_id,label,created_by) values(c1,w,iid,'Synthetic Phase 1',actor),(c2,w,iid,'Synthetic Phase 2',actor);
insert into public.claims(id,workspace_id,initiative_id,type,status,subject,attribute,value,domain,context_id,effective_date,origin) values(a,w,iid,'REQUIREMENT','UNVERIFIED','Receipt','Window','27','PRODUCT',c1,'2026-12-31','HUMAN_ENTRY'),(b,w,iid,'REQUIREMENT','UNVERIFIED','Receipt','Window','30','PRODUCT',c1,'2026-12-31','HUMAN_ENTRY'),(z,w,iid,'REQUIREMENT','UNVERIFIED','Receipt','Window','40','PRODUCT',c2,'2026-12-31','HUMAN_ENTRY');
select updated_at into stamp from public.claims where id=a;perform public.verify_claim(a,stamp,'DIRECT_KNOWLEDGE','Synthetic verification',actor::text,'Synthetic Reviewer');select updated_at into stamp from public.claims where id=b;perform public.verify_claim(b,stamp,'DIRECT_KNOWLEDGE','Synthetic verification',actor::text,'Synthetic Reviewer');select updated_at into stamp from public.claims where id=z;perform public.verify_claim(z,stamp,'DIRECT_KNOWLEDGE','Synthetic verification',actor::text,'Synthetic Reviewer');
fp:=public.decision_hash(array['CONFLICT_SAME_ATTRIBUTE_V1',iid::text,'receipt','window',null,'27','30']||public.context_parts(c1,'2026-12-31'));
if public.queue_current_finding(w,iid,fp) is null or jsonb_array_length(public.queue_current_finding(w,iid,fp)->'claimIds')<>2 then raise exception 'CONTEXT_COMPARISON';end if;
perform public.assign_finding_confirmer(jsonb_build_object('initiativeId',iid,'fingerprint',fp,'subject','Receipt','attribute','Window','phase',null,'cycle','FIRST','label','Synthetic Confirmer','actor',jsonb_build_object('id',actor,'label','Synthetic Reviewer')));
perform public.resolve_conflict(jsonb_build_object('initiativeId',iid,'fingerprint',fp,'contentDigest',public.queue_current_finding(w,iid,fp)->>'digest','ruleId','CONFLICT_SAME_ATTRIBUTE_V1','subject','Receipt','attribute','Window','phase',null,'valuesRecorded',(select string_agg(value,' | ' order by id) from public.claims where id in (a,b)),'outcome','CHOSE_EXISTING','chosenClaimId',a,'correctedValue',null,'decisionDomain',null,'rationale','Synthetic scoped decision','actor',jsonb_build_object('id',actor,'label','Synthetic Reviewer'),'members',(select jsonb_agg(jsonb_build_object('id',id,'expectedUpdatedAt',updated_at,'keep',id=a) order by id) from public.claims where id in (a,b))));
select updated_at into stamp from public.claims where id=a;
result_id:=public.revise_claim_applicability(w,m,a,stamp,jsonb_build_object('initiativeId',iid,'type','REQUIREMENT','subject','Receipt','attribute','Window','value','27','domain','PRODUCT','contextId',c2,'effectiveDate','2026-12-31','reason','Synthetic new phase','evidenceIds','[]'::jsonb));
if (select status from public.claims where id=result_id)<>'UNVERIFIED' or (select status from public.claims where id=a)<>'SUPERSEDED' or (select superseded_by_claim_id from public.claims where id=a)<>result_id or (select evidence_anchor_id from public.claims where id=result_id) is not null then raise exception 'REVISION_TRUST';end if;
begin perform public.revise_claim_applicability(w,m,a,stamp,jsonb_build_object('initiativeId',iid,'reason','Stale repeat'));raise exception 'STALE_ACCEPTED';exception when others then if sqlerrm<>'CLAIM_STALE' then raise;end if;end;
begin update public.claims set context_id=c1 where id=result_id;raise exception 'DIRECT_CONTEXT_MUTATION';exception when others then if sqlerrm<>'APPLICABILITY_REQUIRES_REVISION' then raise;end if;end;
raise notice 'PASS: same-context conflict group excludes other phase, immutable unverified revision, stale retry rejected, ordinary applicability mutation blocked';end$$;
set constraints all immediate;rollback;

