import { BusinessLine } from '@/components/primitives/BusinessLine';
import Link from 'next/link';
import {BUSINESS_LINE_LABEL,STAGE_LABEL} from '@/lib/domain/labels';
import type {Initiative} from '@/lib/domain/types';
import {readDelivery} from '@/lib/delivery/repository';
import {readManagement} from '@/lib/data/management-read';
import {buildPortfolioProjection} from '@/lib/workspace/portfolio';
import {ownerFor} from '@/lib/delivery/model';
import {isDemoGuestSession} from '@/lib/auth/service';
import {canBusinessWrite} from '@/lib/auth/roles';
import {isDemoWriteEnabled} from '@/lib/env';
import {OrganizationControl} from './OrganizationControl';
import {ShellActions} from './ShellActions';
import {WorkspaceTabs} from './WorkspaceTabs';
import {readRelationships} from '@/lib/data/relationships';
import styles from './WorkspaceHeader.module.css';
export async function WorkspaceHeader({initiative}:{initiative:Initiative}){
 const [d,m,rel]=await Promise.all([readDelivery(),readManagement(),readRelationships()]);const row=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,asOf:d.presentation.scenarioAt??new Date().toISOString(),management:m,relationships:rel.relationships}).rows.find(x=>x.initiative.id===initiative.id);const ownerId=ownerFor(d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId),initiative.id);const owner=d.source.members.find(m=>m.id===ownerId);const guest=await isDemoGuestSession();
 return <header className={styles.header}><div className={styles.inner}><div className={styles.identity}><div className={styles.headerOrg}><OrganizationControl identity={{access:d.ctx,presentation:d.presentation,guest}} compact/></div><nav aria-label="Breadcrumb"><Link prefetch={false} href="/initiatives">Initiatives</Link><span>/</span></nav><h1 data-workspace-title title={initiative.name}>{initiative.name}</h1><span className={styles.stage}>{STAGE_LABEL[initiative.stage]}</span><span className={styles.meta}><BusinessLine code={initiative.businessLine}/></span><span className={styles.owner}>Owner · {owner?.displayName??'No owner recorded'}</span>{row&&<>{!row.setup.ready&&<Link prefetch={false} className={styles.signal} data-tone="open" href={`/initiatives/${initiative.slug}/setup?step=review`}><span aria-hidden="true">○</span>{row.setup.label} · {row.setup.completed}/{row.setup.total}</Link>}<Link prefetch={false} className={styles.signal} data-tone={row.attention.length?'attention':'ok'} href={`/initiatives/${initiative.slug}#attention`}><span aria-hidden="true">{row.attention.length?'!':'·'}</span>{row.attention.length?`${row.attention.length} need attention`:row.snapshot.claims.length?'No open items in current checks':'Not assessed'}</Link></>}{initiative.isDemo&&<span className={styles.meta}>Synthetic demo</span>}{d.ctx.role==='VIEWER'&&<span className={styles.meta}>Viewer · read-only</span>}<span className={styles.headerActions}>{canBusinessWrite(d.ctx)&&!initiative.archivedAt&&isDemoWriteEnabled&&<details className={styles.addMenu}><summary>Add evidence</summary><div role="group" aria-label="Add evidence"><Link prefetch={false} href={`/initiatives/${initiative.slug}/evidence/new?kind=meeting`}>Meeting notes<small>Decisions, commitments, risks and questions from a meeting</small></Link><Link prefetch={false} href={`/initiatives/${initiative.slug}/evidence/new`}>Paste evidence<small>A document excerpt, email text or other source</small></Link><Link prefetch={false} href={`/initiatives/${initiative.slug}/evidence`}>Saved evidence<small>Resume reviewing proposals</small></Link></div></details>}<Link prefetch={false} href={`/initiatives/${initiative.slug}/manage`} className={styles.manage}>{d.ctx.role==='VIEWER'?'Initiative details':'Manage initiative'}</Link></span></div>{initiative.archivedAt&&<p role="status" className={styles.meta}>Archived · read-only. Records and history are preserved. An administrator can restore this initiative in Manage initiative.</p>}<WorkspaceTabs slug={initiative.slug}/><ShellActions/></div></header>;
}
