'use server';
import {revalidatePath} from 'next/cache';
import {requireBusinessWriteAccess} from '@/lib/auth/access';
import {assertFormWorkspace} from '@/lib/auth/scope';
import {getRepository} from '@/lib/data';
import {submitEvidence,readWithAI,decideProposal} from '@/lib/evidence/service';
export interface EvidenceActionState {error:string|null;submissionId?:string;message?:string;result?:{type:string;id:string}|null;batch?:{proposalId:string;result:{type:string;id:string}|null;error:string|null}[];}
export async function evidenceAction(_previous:EvidenceActionState,form:FormData):Promise<EvidenceActionState>{
 const text=(k:string)=>String(form.get(k)??'');try{const ctx=await requireBusinessWriteAccess();assertFormWorkspace(form,ctx);const i=await getRepository().getInitiativeBySlug(text('slug'));if(!i)throw Error('Initiative unavailable.');const operation=text('operation');
 if(operation==='SUBMIT'){const submissionId=await submitEvidence({initiativeId:i.id,workspaceId:ctx.workspaceId,title:text('title'),text:text('text'),sourceItemId:text('sourceItemId')||null,requestId:text('requestId'),meeting:text('kind')==='MEETING_NOTES'?{date:text('meetingDate'),attendees:text('attendees')||null}:null});return {error:null,submissionId};}
 if(operation==='READ'){await readWithAI(text('submissionId'),text('requestId'));return {error:null,message:'Reading attempt finished. Review its status and proposals below.'};}
 if(operation==='REPROPOSE'){const svc=await import('@/lib/evidence/service');const inventory=await svc.readEvidence(i.id);const proposal=inventory.proposals.find(p=>p.id===text('proposalId'));if(!proposal)throw Error('Proposal unavailable.');await svc.controlEvidence(proposal.submissionId,'REPROPOSE',proposal.id);return {error:null,message:'A new proposal was made against the current delivery record. Review it before accepting.'};}
 if(operation==='CORRECT_MEETING'){const {correctMeeting}=await import('@/lib/evidence/service');await correctMeeting({submissionId:text('submissionId'),expectedRevision:Number(text('expectedRevision')),title:text('title'),meetingDate:text('meetingDate'),attendeesText:text('attendees')||null});return {error:null,message:'Meeting details corrected. The notes themselves are unchanged.'};}
 if(!['CONFIRM','REJECT','EDIT','HUMAN_ENTRY'].includes(operation))throw Error('Unsupported evidence command.');const evidence=await import('@/lib/evidence/service');const current=await evidence.readEvidence(i.id);const proposal=current.proposals.find(p=>p.id===text('proposalId'));if(!proposal)throw Error('Proposal unavailable in this initiative.');const result=await decideProposal({id:text('proposalId'),version:Number(text('version')),requestId:text('requestId'),operation:operation as 'CONFIRM'|'REJECT'|'EDIT'|'HUMAN_ENTRY',reason:text('reason'),contextId:text('contextId')||null,effectiveDate:text('effectiveDate')||null,payload:operation==='EDIT'||operation==='HUMAN_ENTRY'?{...proposal.payload,value:text('value')}:undefined,assigneeMemberId:text('assigneeMemberId')||null,dueDate:text('dueDate')||null});return {error:null,result,message:operation==='EDIT'?'Wording fix saved. It still needs your decision.':result?'Accepted. Open the result below — Knowledge entries start as not yet verified.':'Proposal rejected. No product record was created.'};
 }catch(e){return {error:e instanceof Error?e.message:'Evidence command failed.'};}finally{revalidatePath(`/initiatives/${text('slug')}`,'layout');revalidatePath('/weekly-review');revalidatePath('/roadmap');revalidatePath('/');}
}
export async function batchEvidenceAction(_previous:EvidenceActionState,form:FormData):Promise<EvidenceActionState>{
 const slug=String(form.get('slug')??'');try{const ctx=await requireBusinessWriteAccess();assertFormWorkspace(form,ctx);const i=await getRepository().getInitiativeBySlug(slug);if(!i)throw Error('Initiative unavailable.');const evidence=await import('@/lib/evidence/service');const current=await evidence.readEvidence(i.id);const commands=JSON.parse(String(form.get('commands')??'[]')) as {id:string;version:number;requestId:string}[];if(!Array.isArray(commands)||!commands.length||commands.length>20||new Set(commands.map(c=>c.id)).size!==commands.length)throw Error('Select 1–20 distinct proposals.');const results:NonNullable<EvidenceActionState['batch']>=[];for(const c of commands){try{if(!current.proposals.some(p=>p.id===c.id))throw Error('Proposal unavailable.');const result=await decideProposal({...c,operation:'CONFIRM',reason:String(form.get('reason')??'Reviewed exact supporting quote in batch')});results.push({proposalId:c.id,result,error:null});}catch(e){results.push({proposalId:c.id,result:null,error:e instanceof Error?e.message:'Not accepted.'});}}return {error:null,batch:results,message:`${results.filter(r=>!r.error).length} accepted; ${results.filter(r=>r.error).length} not accepted. Each was saved separately, so the accepted ones stand.`};}catch(e){return {error:e instanceof Error?e.message:'Batch failed.'};}finally{revalidatePath(`/initiatives/${slug}`,'layout');revalidatePath('/weekly-review');revalidatePath('/');}
}
