import Link from 'next/link';import {notFound} from 'next/navigation';
import {readDelivery} from '@/lib/delivery/repository';import {readEvidence} from '@/lib/evidence/service';import {canBusinessWrite} from '@/lib/auth/roles';import {isDemoWriteEnabled} from '@/lib/env';import styles from '@/components/evidence/evidence.module.css';import {sameTextAs} from '@/lib/evidence/already-recorded';
export const metadata={title:'Saved evidence'};
const short=(iso:string)=>new Date(iso.length===10?`${iso}T12:00:00Z`:iso).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:iso.length===10?'UTC':'Africa/Cairo'});
export default async function EvidenceIndex({params}:{params:Promise<{slug:string}>}){const [{slug},d]=await Promise.all([params,readDelivery()]);const i=d.source.snapshots.find(s=>s.initiative.slug===slug)?.initiative;if(!i)notFound();const e=await readEvidence(i.id);const writer=canBusinessWrite(d.ctx)&&!i.archivedAt&&isDemoWriteEnabled;
 // Meetings are placed by the date they happened; pasted evidence by when it was saved.
 const rows=e.submissions.map(s=>{const m=e.meetings?.find(x=>x.submissionId===s.id);const ps=e.proposals.filter(p=>p.submissionId===s.id);return {s,m,when:m?.meetingDate??s.createdAt.slice(0,10),pending:ps.filter(p=>p.status==='PENDING').length,confirmed:ps.filter(p=>p.status==='CONFIRMED'||p.status==='SUPERSEDED_BY_HUMAN_ENTRY').length,read:e.attempts.some(a=>a.submissionId===s.id&&a.status==='READY'),same:sameTextAs(s,e.submissions,id=>e.proposals.filter(p=>p.submissionId===id&&p.status!=='PENDING').length)};}).sort((a,b)=>b.when.localeCompare(a.when));
 return <div className={styles.page}><header className={styles.heading}><div><p className={styles.eyebrow}>{i.name}</p><h2>Saved evidence</h2><p>Meeting notes and pasted sources, kept exactly as saved. Open one to review what was proposed from it and confirm what becomes a record.</p></div>{writer&&<div className={styles.actionsRow}><Link className={styles.control} href={`/initiatives/${slug}/evidence/new?kind=meeting`} prefetch={false}>Add meeting notes</Link><Link className={styles.control} href={`/initiatives/${slug}/evidence/new`} prefetch={false}>Paste evidence</Link></div>}</header>
 {!rows.length?<div className={styles.empty}><h4>No evidence has been saved for this initiative yet.</h4><p>Paste meeting notes or a document excerpt. AI proposals stay separate from confirmed records until a person accepts them.</p></div>:
 <ol className={styles.list}>{rows.map(({s,m,when,pending,confirmed,read,same})=><li key={s.id} className={styles.item}><time dateTime={when}>{short(when)}</time><div><h3><span className={styles.itemKind}>{m?'Meeting':'Pasted'}</span><span className="visually-hidden">: </span><Link href={`/initiatives/${slug}/evidence/${s.id}`} prefetch={false}>{m?.title??s.title}</Link></h3><p>{!read?'Not read yet':`${confirmed} accepted`}{m?.attendeesText?` · With ${m.attendeesText}`:''} · {s.charLength.toLocaleString()} characters</p>{same&&<p className={styles.duplicate}>Same text as <Link href={`/initiatives/${slug}/evidence/${same.id}`} prefetch={false}>{e.meetings?.find(x=>x.submissionId===same.id)?.title??same.title}</Link>, saved {short(same.createdAt)}. Review that one to avoid duplicate records.</p>}</div><span className={styles.pendingBadge}>{pending?`${pending} awaiting decision`:''}</span></li>)}</ol>}
 <p className={styles.meta} style={{marginTop:'var(--s-6)'}}><Link href={`/initiatives/${slug}/sources`} prefetch={false}>All initiative sources →</Link></p></div>;}
