import Link from 'next/link';import {notFound} from 'next/navigation';
import {readDelivery} from '@/lib/delivery/repository';import {readEvidence} from '@/lib/evidence/service';import {canBusinessWrite} from '@/lib/auth/roles';import {isDemoWriteEnabled} from '@/lib/env';import styles from '@/components/evidence/evidence.module.css';
export const metadata={title:'Saved evidence'};
const short=(iso:string)=>new Date(`${iso.slice(0,10)}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
export default async function EvidenceIndex({params}:{params:Promise<{slug:string}>}){const [{slug},d]=await Promise.all([params,readDelivery()]);const i=d.source.snapshots.find(s=>s.initiative.slug===slug)?.initiative;if(!i)notFound();const e=await readEvidence(i.id);const writer=canBusinessWrite(d.ctx)&&!i.archivedAt&&isDemoWriteEnabled;
 // Meetings are placed by the date they happened; pasted evidence by when it was saved.
 const rows=e.submissions.map(s=>{const m=e.meetings?.find(x=>x.submissionId===s.id);const ps=e.proposals.filter(p=>p.submissionId===s.id);return {s,m,when:m?.meetingDate??s.createdAt.slice(0,10),pending:ps.filter(p=>p.status==='PENDING').length,confirmed:ps.filter(p=>p.status==='CONFIRMED'||p.status==='SUPERSEDED_BY_HUMAN_ENTRY').length,read:e.attempts.some(a=>a.submissionId===s.id&&a.status==='READY')};}).sort((a,b)=>b.when.localeCompare(a.when));
 return <div className={styles.page}><header className={styles.heading}><div><p className={styles.eyebrow}>{i.name}</p><h2>Saved evidence</h2><p>Meeting notes and pasted sources, kept exactly as saved. Open one to review what Claude proposed and confirm what becomes a record.</p></div>{writer&&<div className={styles.actionsRow}><Link className={styles.control} href={`/initiatives/${slug}/evidence/new?kind=meeting`} prefetch={false}>Add meeting notes</Link><Link className={styles.control} href={`/initiatives/${slug}/evidence/new`} prefetch={false}>Paste evidence</Link></div>}</header>
 {!rows.length?<div className={styles.empty}><h4>No evidence has been saved for this initiative yet.</h4><p>Paste meeting notes or a document excerpt. AI proposals stay separate from Product Truth until a person confirms them.</p></div>:
 <ol className={styles.list}>{rows.map(({s,m,when,pending,confirmed,read})=><li key={s.id} className={styles.item}><time dateTime={when}>{short(when)}</time><div><h3><span className={styles.itemKind}>{m?'Meeting':'Pasted'}</span><Link href={`/initiatives/${slug}/evidence/${s.id}`} prefetch={false}>{m?.title??s.title}</Link></h3><p>{!read?'Not read yet':`${confirmed} confirmed`}{m?.attendeesText?` · With ${m.attendeesText}`:''} · {s.charLength.toLocaleString()} characters</p></div><span className={styles.pendingBadge}>{pending?`${pending} awaiting decision`:''}</span></li>)}</ol>}
 <p className={styles.meta} style={{marginTop:'var(--s-6)'}}><Link href={`/initiatives/${slug}/sources`} prefetch={false}>All initiative sources →</Link></p></div>;}
