import Link from 'next/link';
import {getRepository} from '@/lib/data';
import {readManagement} from '@/lib/data/management-read';
import {readDelivery} from '@/lib/delivery/repository';
import {buildPortfolioProjection,filterPortfolioRows,type PortfolioFilters,type PortfolioRow} from '@/lib/workspace/portfolio';
import {displayDate} from '@/lib/delivery/roadmap';
import {BUSINESS_LINE_LABEL,STAGE_LABEL,formatDate} from '@/lib/domain/labels';
import {STAGES} from '@/lib/domain/types';
import {canBusinessWrite} from '@/lib/auth/roles';
import {isDemoWriteEnabled} from '@/lib/env';
import {FilterSheet} from '@/components/shell/FilterSheet';
import styles from './initiatives.module.css';
export const dynamic='force-dynamic';
function Target({row:r}:{row:PortfolioRow}){return <>{r.actual?.value.extent==='FULL'?`Live ${displayDate(r.actual.value.date)} (full)`:r.target?.value.date?displayDate(r.target.value.date):r.target?.value.unknown?'Explicitly unknown':'Not recorded'}{r.targetMovement&&<small>Moved {r.targetMovement.days>0?'+':''}{r.targetMovement.days} d from {displayDate(r.targetMovement.from)}</small>}</>;}
export default async function Initiatives({searchParams}:{searchParams:Promise<PortfolioFilters>}){
 const[d,activity,f,management]=await Promise.all([readDelivery(),getRepository().listRecentActivity(150),searchParams,readManagement()]);const p=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,activity,management,asOf:d.presentation.scenarioAt??new Date().toISOString()});const rows=filterPortfolioRows(p.rows,f,p.today);
 const select=(name:string,label:string,options:{value:string;label:string}[])=> <label>{label}<select name={name} defaultValue={f[name as keyof PortfolioFilters]??''}><option value="">All</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 const sortHeader=(value:string,label:string)=><th scope="col" aria-sort={(f.sort??'name')===value?value==='updated'||value==='attention'?'descending':'ascending':'none'}><button type="submit" form="register-sort" name="sort" value={value}>{label}{(f.sort??'name')===value?(value==='updated'||value==='attention'?' ↓':' ↑'):''}</button></th>;
 const controls=<form className={styles.filters}><label className={styles.search}>Search initiatives<input type="search" name="q" defaultValue={f.q??''} placeholder="Initiative name"/></label>
 {select('stage','Stage',STAGES.map(value=>({value,label:STAGE_LABEL[value]})))}
 {select('owner','Owner',[{value:'unassigned',label:'Unassigned'},...d.source.members.filter(m=>m.active).map(m=>({value:m.id,label:m.displayName}))])}
 {select('attention','Attention',[{value:'any',label:'Any reason'},{value:'decision',label:'Decision needed'},{value:'blocker',label:'Recorded blocker'},{value:'past-target',label:'Past target'},{value:'past-milestone',label:'Past milestone'},{value:'support-changed',label:'Supporting evidence changed'}])}
 <details className={styles.moreFilters} open={Boolean(f.line||f.setup||f.record||f.target)||undefined}><summary>More filters{[f.line,f.setup,f.record,f.target].filter(Boolean).length?` · ${[f.line,f.setup,f.record,f.target].filter(Boolean).length}`:''}</summary><div>{select('line','Business line',[...new Set(p.rows.map(r=>r.initiative.businessLine))].map(value=>({value,label:BUSINESS_LINE_LABEL[value]})))}{select('target','Target',[{value:'upcoming',label:'Next 28 days'},{value:'past',label:'Past target · update needed'},{value:'unknown',label:'Unknown'},{value:'moved',label:'Moved in last 28 days'}])}{select('setup','Setup',[{value:'incomplete',label:'Setup incomplete'},{value:'ready',label:'Ready for intelligence'}])}{select('record','Record status',[{value:'active',label:'Active'},{value:'archived',label:'Archived'},{value:'all',label:'Active and archived'}])}{select('sort','Sort',[{value:'name',label:'Name'},{value:'target',label:'Target Live'},{value:'updated',label:'Latest change'},{value:'attention',label:'Attention first'}])}</div></details><div className={styles.filterActions}><button type="submit">Apply filters</button><Link prefetch={false} href="/initiatives">Clear</Link></div></form>;
 return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Portfolio register · {d.presentation.organizationName}</p><h1>Initiatives</h1><p>Recorded work, its coverage and delivery outlook.</p></div>{canBusinessWrite(d.ctx)&&isDemoWriteEnabled&&<Link prefetch={false} className={styles.primary} href="/initiatives/new">Create initiative</Link>}</header>
 <form className={styles.mobileSearch}><label>Search initiatives<input type="search" name="q" defaultValue={f.q??''}/></label>{Object.entries(f).filter(([k,v])=>k!=='q'&&v).map(([k,v])=><input type="hidden" name={k} value={v} key={k}/>)}<button>Search</button></form>
 <FilterSheet count={Object.entries(f).filter(([k,v])=>k!=='sort'&&v).length}>{controls}</FilterSheet><p className={styles.count}>{rows.length} of {p.rows.length} initiatives{Object.values(f).some(Boolean)?' · filters applied':''}</p>
 <form id="register-sort">{Object.entries(f).filter(([k,v])=>k!=='sort'&&v).map(([k,v])=><input type="hidden" name={k} value={v} key={k}/>)}</form>
 {rows.length?<><table className={styles.table}><caption className="visually-hidden">Initiative register with recorded coverage and attention</caption><thead><tr>{sortHeader('name','Initiative')}<th scope="col">Stage</th><th scope="col">Owner</th><th scope="col">Setup</th>{sortHeader('attention','Attention')}{sortHeader('target','Target Live')}{sortHeader('updated','Latest change')}</tr></thead><tbody>{rows.map(r=><tr key={r.initiative.id}><th scope="row"><Link prefetch={false} href={`/initiatives/${r.initiative.slug}`}>{r.initiative.name}</Link><small>{BUSINESS_LINE_LABEL[r.initiative.businessLine]} · {r.initiative.knownReferences?.split(/[\n,]/)[0]??'Reference not recorded'}{r.initiative.isDemo?' · Synthetic':''}</small><span className={styles.compactChange}>{r.latestChange?.sentence??'No recent change recorded'}</span></th><td>{STAGE_LABEL[r.initiative.stage]}</td><td>{r.ownerLabel}</td><td className={styles.setupCell}><Link href={`/initiatives/${r.initiative.slug}/setup?step=review`} aria-label={`${r.setup.label}: ${r.setup.completed} of ${r.setup.total} recorded`}>{r.setup.completed}/{r.setup.total}</Link></td><td className={r.attention.length?styles.attention:undefined}>{r.attention.length?[...new Set(r.attention.map(a=>a.label))].join(' · '):<><span aria-hidden="true">—</span><span className="visually-hidden">No attention reasons recorded</span></>}</td><td><Target row={r}/></td><td className={styles.latestCell}>{r.latestChange?<><span className={styles.oneLine} title={r.latestChange.sentence}>{r.latestChange.sentence}</span><small>{formatDate(r.latestChange.occurredAt)}</small></>:'No recent change recorded'}</td></tr>)}</tbody></table>
 <ul className={styles.mobileList}>{rows.map(r=><li key={r.initiative.id}><Link prefetch={false} href={`/initiatives/${r.initiative.slug}`}>{r.initiative.name}</Link><p>{BUSINESS_LINE_LABEL[r.initiative.businessLine]} · {STAGE_LABEL[r.initiative.stage]}</p><dl><dt>Owner</dt><dd>{r.ownerLabel}</dd><dt>Setup</dt><dd><Link href={`/initiatives/${r.initiative.slug}/setup?step=review`}>{r.setup.label} · {r.setup.completed} of {r.setup.total}</Link></dd><dt>Attention</dt><dd className={r.attention.length?styles.attention:undefined}>{r.attention.length?[...new Set(r.attention.map(a=>a.label))].join(' · '):<><span aria-hidden="true">—</span><span className="visually-hidden">No attention reasons recorded</span></>}</dd><dt>Target Live</dt><dd><Target row={r}/></dd><dt>Latest change</dt><dd>{r.latestChange?.sentence??'No recent change recorded'}</dd></dl></li>)}</ul></>:<section className={styles.empty}><h2>{p.rows.length?'No initiatives match these filters.':`No initiatives recorded in ${d.presentation.organizationName} yet.`}</h2><Link prefetch={false} href="/initiatives">{p.rows.length?'Clear filters':'Open the register'}</Link></section>}
 <p className={styles.note}>Coverage describes the recorded setup and value checks. It is not a readiness assessment. Unknown dates stay unknown.</p></div>;
}
