import Link from "next/link";
import {hasOrganizationAdminAuthority,canBusinessWrite} from "@/lib/auth/roles";
import {readDelivery} from "@/lib/delivery/repository";
import {changesSince,freezeInput,isoWeek,weekValid,latestBaseline,finalizationChecks,nextReviewWeek,ownerFor,sectionDigest} from "@/lib/delivery/model";
import {createWeeklyReviewAction,draftWeeklyReviewAction,finalizeWeeklyReviewAction,refreshWeeklyReviewAction} from "@/lib/delivery/actions";
import {buildPortfolioProjection} from "@/lib/workspace/portfolio";
import {memberLabel} from "@/components/delivery/FactEditor";
import {WriteNotice} from "@/components/delivery/WriteNotice";
import {isDemoWriteEnabled} from "@/lib/env";
import {safeUserLabel} from "@/lib/demo/presentation";
import {displayDate} from "@/lib/delivery/roadmap";
import {WeeklyActionForm} from "@/components/weekly/WeeklyActionForm";
import {SavedNotice} from "@/components/forms/SavedNotice";
import {WeekMenu} from "@/components/weekly/WeekMenu";
import {weekLabel} from "@/lib/domain/labels";
import {SectionRecord} from "@/components/weekly/SectionRecord";
import {SectionAttention} from "@/components/weekly/SectionAttention";
import {SectionCommentary} from "@/components/weekly/SectionCommentary";
import {SectionIndexDisclosure} from "@/components/weekly/SectionIndexDisclosure";
import {weeklyChangeSentence} from "@/lib/delivery/weekly-copy";
import {RecordUpdatePanel} from "@/components/weekly/RecordUpdatePanel";
import {readQuestions} from "@/lib/data/questions";
import {readRisks} from "@/lib/data/risks";
import {readRelationships} from "@/lib/data/relationships";
import {weeklyContextDelta} from "@/lib/workspace/weekly-context";
import {cairoStamp as cutoff,SECTION_STATE,sectionReviewState} from "@/components/weekly/format";
import styles from "@/components/weekly/weekly.module.css";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Weekly Review" };
export const maxDuration=60;
export default async function WeeklyReviewPage({searchParams}:{searchParams:Promise<{week?:string;initiative?:string;view?:string}>}) {
  const [query,{ctx,source,state,presentation},qs,rs,rel]=await Promise.all([searchParams,readDelivery(),readQuestions(),readRisks(),readRelationships()]),now=new Date().toISOString();
  const week=query.week&&weekValid(query.week)?query.week:isoWeek(presentation.scenarioAt??now),review=state.reviews.find(r=>r.workspaceId===ctx.workspaceId&&r.week===week);
  const baseline=review?state.reviews.find(r=>r.id===review.baselineReviewId&&r.workspaceId===ctx.workspaceId&&r.status==="FINAL"&&r.week<review.week):latestBaseline(state,ctx.workspaceId,week);
  const current=freezeInput(source,state,ctx.workspaceId,now),writer=canBusinessWrite(ctx),finalizer=writer&&(hasOrganizationAdminAuthority(ctx)||ctx.isProductLead);
  const thisYear=isoWeek(presentation.scenarioAt??now).slice(0,4);
  const weekStart=(()=>{const d=new Date(`${nextReviewWeek(week).startsOn}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-7);return d.toISOString().slice(0,10);})();
  const weekEnd=(()=>{const d=new Date(`${weekStart}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+6);return d.toISOString().slice(0,10);})();
  const weekRange=`${displayDate(weekStart).replace(weekStart.slice(0,4)===weekEnd.slice(0,4)?/ \d{4}$/:/$^/,"")} – ${displayDate(weekEnd)}`;
  const prevWeek=(()=>{const d=new Date(`${weekStart}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-7);return isoWeek(d.toISOString());})();
  const history=state.reviews.filter(r=>r.workspaceId===ctx.workspaceId).sort((a,b)=>b.week.localeCompare(a.week));
  const href=(slug?:string,view?:string)=>`/weekly-review?week=${week}${slug?`&initiative=${encodeURIComponent(slug)}`:""}${view?`&view=${view}`:""}`;
  const available=new Set(source.snapshots.map(s=>s.initiative.id)),sections=review?.sections.filter(s=>available.has(s.initiativeId))??[];
  const toReview=(s:(typeof sections)[number])=>s.needsRecheck||!(s.editedByMemberId||s.editedByUserId);
  // Open where the person has work: their own unreviewed section first, then any unreviewed one.
  const selected=sections.find(s=>review?.input.snapshots.find(i=>i.initiative.id===s.initiativeId)?.initiative.slug===query.initiative)??sections.find(s=>toReview(s)&&s.ownerMemberId===ctx.memberId)??sections.find(toReview)??sections[0];
  const frozenProjection=review?buildPortfolioProjection({source:review.input,state:{schema:1,facts:review.input.facts,events:review.input.events,reviews:baseline?[baseline]:[]},workspaceId:ctx.workspaceId,asOf:review.input.asOf}):null;
  const checks=review?finalizationChecks(state,source,ctx,review,now,isDemoWriteEnabled):[],ready=checks.every(c=>c.met),stale=review?current.digest!==review.input.digest||(latestBaseline(state,ctx.workspaceId,week)?.id??null)!==review.baselineReviewId:false;
  const affected=review?.sections.filter(s=>!available.has(s.initiativeId)||s.sourceDigest!==sectionDigest(current,s.initiativeId)).length??0;
  const reviewed=review?.sections.filter(s=>!s.needsRecheck&&Boolean(s.editedByMemberId||s.editedByUserId)).length??0;
  const pending=sections.find(s=>s.needsRecheck||!s.editedByMemberId&&!s.editedByUserId);
  const pendingSlug=review?.input.snapshots.find(i=>i.initiative.id===pending?.initiativeId)?.initiative.slug;
  const groups=[...new Set(sections.map(s=>s.ownerMemberId))].sort((a,b)=>memberLabel(review!.input.members,a).localeCompare(memberLabel(review!.input.members,b)));
  const wl=(w:string)=>weekLabel(w,thisYear);
  const ai=review?.aiDrafts.at(-1),unavailable=(review?.sections.length??0)-sections.length;
  const passed=checks.filter(c=>c.met).length;
  const statusText=review?.status==="FINAL"?"Final · read-only":review?"Draft":"Not prepared";
  function sectionBody(section:typeof selected,readonly=false){if(!section||!review)return null;const snap=current.snapshots.find(s=>s.initiative.id===section.initiativeId);if(!snap)return null;const editable=review.status==="DRAFT"&&writer&&!readonly&&(hasOrganizationAdminAuthority(ctx)||ctx.isProductLead||ownerFor(current.facts,section.initiativeId)===ctx.memberId&&section.ownerMemberId===ctx.memberId);const context=weeklyContextDelta({initiativeId:section.initiativeId,slug:snap.initiative.slug,from:baseline?.input.asOf??null,to:review.status==="FINAL"&&review.finalizedAt?review.finalizedAt:now,questions:qs.questions,questionEvents:qs.events,riskEvents:rs.events,relationshipEvents:rel.events,names:Object.fromEntries(source.snapshots.map(x=>[x.initiative.id,x.initiative.name]))});return <div className={styles.section} key={section.initiativeId}>
    <SectionRecord review={review} section={section} baseline={baseline?.input??null}/>
    <SectionAttention review={review} section={section} baseline={baseline?.input??null} baselineLabel={baseline?`${wl(baseline.week)} Final`:undefined} returnTo={href(snap.initiative.slug)} context={context}/>
    <SectionCommentary key={`${section.initiativeId}:${section.revision}`} review={review} section={section} baseline={baseline?.input??null} editable={editable} writesEnabled={isDemoWriteEnabled}/>
    {review.status==="DRAFT"&&writer&&!readonly&&<RecordUpdatePanel snapshot={snap} facts={state.facts} reviewId={review.id} reviewRevision={review.revision} workspaceId={ctx.workspaceId} canFacts={hasOrganizationAdminAuthority(ctx)||ownerFor(state.facts,section.initiativeId)===ctx.memberId} canDecision={writer} writesEnabled={isDemoWriteEnabled}/>}
    <nav className={styles.links} aria-label="Selected initiative navigation"><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}/delivery?returnTo=${encodeURIComponent(href(snap.initiative.slug))}`}>Scope, owner and delivery history</Link><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}/knowledge`}>Initiative Knowledge</Link></nav>
  </div>;}
  return <div className={styles.page}><SavedNotice className={`saved-notice ${styles.savedToast}`}/>
    <header className={styles.pageHead}><div><h1>Weekly Review</h1><p className={styles.meta}><span className={styles.status} data-status={review?.status??"NONE"}><span aria-hidden="true">{review?.status==="FINAL"?"■":review?"◐":"○"}</span>{statusText}</span>{review?.status==="DRAFT"&&<span className={styles.progress}><span>Reviewed <strong>{reviewed}</strong> of <strong>{review.sections.length}</strong></span><span className={styles.meter} aria-hidden="true"><span style={{inlineSize:`${(reviewed/Math.max(1,review.sections.length))*100}%`}}/></span></span>}</p></div>
      <WeekMenu week={week} year={thisYear} range={weekRange} prev={prevWeek} next={nextReviewWeek(week).week} history={history.slice(0,12).map(r=>({week:r.week,status:r.status==="FINAL"?"FINAL":"DRAFT"}))}/></header><WriteNotice ctx={ctx}/>
    {!review?<section className={`${styles.block} ${styles.prepare}`}><h2>Prepare {wl(week)} review</h2><p className={styles.meta}>{baseline?`Compares with ${wl(baseline.week)} Final · ${changesSince(current,baseline.input).length} recorded changes since its cutoff.`:"First review — no previous Final. Starts with an inventory of recorded initiative facts."}</p><p className={styles.meta}>The week labels the meeting. Preparing captures the actual source cutoff. Each PM reviews their sections before a coordinator finalizes.</p>{writer?<WeeklyActionForm action={createWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Prepare ${wl(week)} review`} primary disabled={!isDemoWriteEnabled||week>isoWeek(now)}><input type="hidden" name="week" value={week}/></WeeklyActionForm>:<p className={styles.meta}>Read-only: open an existing Final from the week menu above.</p>}{week>isoWeek(now)&&<p className={styles.meta}>This week has not started. Prepare a review when it begins.</p>}</section>:<>
      <div className={styles.overview}><p><strong>{baseline?`Compared with ${wl(baseline.week)} Final · finalized ${cutoff(baseline.finalizedAt??baseline.input.asOf)} Cairo`:"First review · no previous Final"}</strong></p><p className={styles.meta}>Data as of {cutoff(review.input.asOf)} Cairo time. Comparisons can span skipped weeks or include late-recorded facts.{presentation.isDemo?" Demo edits keep their real timestamps.":""} Initiative updates are confirmed separately from commentary.</p></div>
      {unavailable>0&&<p className={styles.warning}>{unavailable} recorded {unavailable===1?"section is":"sections are"} unavailable under current access. Counts describe the original scope; inaccessible details are hidden. {review.status==="DRAFT"?"Refresh inputs before finalizing.":"The Final remains unchanged."}</p>}
      {review.status==="DRAFT"&&<div className={styles.actionBar}><div className={styles.toolbar}>{stale&&writer?<WeeklyActionForm action={refreshWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label="Update to latest records" primary disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>:pendingSlug&&writer?<Link prefetch={false} className="pw-btn" data-variant="primary" href={href(pendingSlug)}>Review next section</Link>:ready&&finalizer?<a className="pw-btn" data-variant="primary" href="#finalize">Finalize {wl(week)} review ↓</a>:ready?<p className={styles.meta}>Ready — waiting for an Org Owner, Admin, Platform Owner or Product Lead.</p>:<p className={styles.meta}>Every section is reviewed. See the finalize checks below.</p>}{writer&&<div className={styles.withReason}><WeeklyActionForm action={draftWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label="Draft wording" pendingLabel="Drafting…" disabled={!isDemoWriteEnabled||stale} describedBy={!isDemoWriteEnabled||stale?"draft-wording-reason":undefined}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>{(!isDemoWriteEnabled||stale)&&<p id="draft-wording-reason" className="disabled-reason">{!isDemoWriteEnabled?"Changes are disabled in this environment.":"Update to latest records first; wording is drafted from the current snapshot."}</p>}</div>}</div>{stale&&(affected?<p className={styles.warning}><span aria-hidden="true">▲ </span>Initiative records changed after the snapshot · {affected} {affected===1?'section':'sections'} affected. Update to latest records, then re-check the changed {affected===1?'section':'sections'}. Commentary is preserved.</p>:<p className={styles.staleNote}><span aria-hidden="true">○ </span>Initiative records changed after the snapshot, but no section content is affected. The draft still has to be updated to the latest records before it can be finalized{writer?" — use Update to latest records above":""}. Commentary is preserved.</p>)}</div>}
      {review.status==="FINAL"&&(()=>{const next=nextReviewWeek(week),exists=state.reviews.find(r=>r.workspaceId===ctx.workspaceId&&r.week===next.week),started=next.week<=isoWeek(now);return <section className={styles.receipt}><h2><span aria-hidden="true">■ </span>{wl(week)} · Final <span className={styles.lockNote}>Preserved · cannot be edited</span></h2><p>{review.preparedAsFixture?"Prepared synthetic scenario baseline by":"Finalized by"} {safeUserLabel({preparedAsFixture:review.preparedAsFixture,confirmedByLabel:review.finalizedByLabel})} · {cutoff(review.finalizedAt??review.input.asOf)} Cairo.<br/>Data as of {cutoff(review.input.asOf)} Cairo time · {baseline?`Compared with ${wl(baseline.week)} Final`:"No previous Final"}.</p><p><strong>This Final is the baseline for the next review.</strong> It records what management reviewed; it is not a release or business approval.</p><div className={styles.toolbar}>{exists?<Link prefetch={false} className="pw-btn" data-variant="primary" href={`/weekly-review?week=${next.week}`}>Open {wl(next.week)}</Link>:writer?<WeeklyActionForm action={createWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Prepare ${wl(next.week)} review`} redirectTo={`/weekly-review?week=${next.week}`} primary disabled={!started||!isDemoWriteEnabled}><input type="hidden" name="week" value={next.week}/></WeeklyActionForm>:<p className={styles.meta}>Read-only: you cannot prepare a review.</p>}<Link prefetch={false} className="pw-btn" data-variant="secondary" href={href(undefined,"since")}>View changes since {wl(week)} Final</Link><Link prefetch={false} className="pw-btn" data-variant="secondary" href={href(undefined,"all")}>Read full review</Link></div>{!exists&&!started&&<p className={styles.meta}>{wl(next.week)} starts Monday {displayDate(next.startsOn)}. Preparation uses the real calendar, not the scenario date.</p>}{!isDemoWriteEnabled&&<p className={styles.meta}>Review preparation is disabled in this environment.</p>}</section>;})()}
      {ai&&<p className={styles.notice}>{ai.mode==="CLAUDE"?`Claude draft · ${ai.model} selected supported source statements. Human review required.`:`Template draft · ${ai.reason??"Claude wording unavailable; prepared deterministically from recorded facts."}`} · {cutoff(ai.generatedAt)} Cairo. Wording never updates initiative records.</p>}
      <nav className={styles.views} aria-label="Review presentation"><Link prefetch={false} href={href(selected?review.input.snapshots.find(i=>i.initiative.id===selected.initiativeId)?.initiative.slug:undefined)} aria-current={!query.view?"page":undefined}>Section view</Link><Link prefetch={false} href={href(undefined,"all")} aria-current={query.view==="all"?"page":undefined}>Full meeting document · read-only</Link>{review.status==="FINAL"&&<Link prefetch={false} href={href(undefined,"since")} aria-current={query.view==="since"?"page":undefined}>Changes since this Final</Link>}</nav>
      {query.view==="since"&&review.status==="FINAL"?<section className={styles.block}><h2>Current record compared with {wl(week)} Final — not a review</h2><p className={styles.meta}>Current source cutoff · {cutoff(current.asOf)} Cairo. The Final above is unchanged.</p>{changesSince(current,review.input).length?<ul className={styles.changes}>{changesSince(current,review.input).filter(c=>available.has(c.initiativeId)).map(c=><li key={c.id}>{weeklyChangeSentence(c,current,review.input)}</li>)}</ul>:<p>No recorded changes since this Final.</p>}</section>:query.view==="all"?<div className={styles.fullDocument}>{sections.map(s=>sectionBody(s,true))}</div>:<div className={styles.layout}><aside className={styles.index}><SectionIndexDisclosure explicitSelection={Boolean(query.initiative)} count={review.sections.length} currentName={review.input.snapshots.find(i=>i.initiative.id===selected?.initiativeId)?.initiative.name??"No available section"}>{groups.map(owner=><div key={owner??"unassigned"}><h2>{memberLabel(review.input.members,owner)}</h2><ul>{sections.filter(s=>s.ownerMemberId===owner).map(s=>{const row=frozenProjection?.rows.find(r=>r.initiative.id===s.initiativeId),snap=review.input.snapshots.find(i=>i.initiative.id===s.initiativeId)!;const isNew=!baseline?.input.snapshots.some(i=>i.initiative.id===s.initiativeId),badges=[isNew&&baseline?"New":null,row?.targetMovement?`Target ${row.targetMovement.days>=0?"+":""}${row.targetMovement.days} d`:null,...(row?.attention.filter(a=>["DECISION","BLOCKER"].includes(a.kind)).map(a=>a.label)??[])].filter(Boolean).join(" · ");const st=sectionReviewState(s,review.status);return <li key={s.initiativeId}><Link prefetch={false} href={href(snap.initiative.slug)} aria-current={selected?.initiativeId===s.initiativeId?"page":undefined} data-state={st}><span className={styles.indexGlyph} data-state={st} aria-hidden="true">{SECTION_STATE[st].glyph}</span><span className={styles.indexBody}><span className={styles.indexName}>{snap.initiative.name}</span><small data-state={st}>{SECTION_STATE[st].label}</small>{badges&&<small>{badges}</small>}</span></Link></li>;})}</ul></div>)}</SectionIndexDisclosure></aside>{sectionBody(selected)}</div>}
      {review.status==="DRAFT"&&<section className={`${styles.block} ${styles.finalize}`} id="finalize" aria-labelledby="finalize-heading">
        <div className={styles.zoneHead}><h2 id="finalize-heading"><span className={styles.zoneGlyph} data-tone="final" aria-hidden="true">■</span>Finalize {wl(week)}</h2><span className={styles.zoneCount}>{passed} of {checks.length} checks passed</span></div>
        <span className={styles.meter} aria-hidden="true"><span style={{inlineSize:`${(passed/Math.max(1,checks.length))*100}%`}} data-ready={ready||undefined}/></span>
        <ul className={styles.checklist} id="finalize-checklist">{checks.map(check=><li key={check.id} data-met={check.met||undefined}><span className={styles.checkGlyph} aria-hidden="true">{check.met?"✓":"○"}</span><span>{check.met?check.label:check.missing??check.label}</span></li>)}</ul>
        {review.sections.filter(s=>s.needsRecheck||!s.editedByMemberId&&!s.editedByUserId).length>0&&<ul className={styles.pendingSections} aria-label="Sections still needing review">{review.sections.filter(s=>s.needsRecheck||!s.editedByMemberId&&!s.editedByUserId).map(s=>{const item=review.input.snapshots.find(i=>i.initiative.id===s.initiativeId);const st=sectionReviewState(s,review.status);return item&&available.has(s.initiativeId)?<li key={s.initiativeId}><Link prefetch={false} href={href(item.initiative.slug)}><span className={styles.indexGlyph} data-state={st} aria-hidden="true">{SECTION_STATE[st].glyph}</span>{item.initiative.name} · {SECTION_STATE[st].label}</Link></li>:null;})}</ul>}
        <div className={styles.toolbar}>{ready&&finalizer?<WeeklyActionForm action={finalizeWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Finalize ${wl(week)} review`} primary describedBy="finalize-checklist" confirm={{title:`Finalize the ${wl(week)} review?`,body:'Finalizing freezes this review as the shared record for the week and makes it the baseline for the next review. It cannot be edited or undone afterwards. Initiative records are not changed.',action:`Yes, finalize ${wl(week)}`}} disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>:<button disabled className="pw-btn" data-variant="primary" aria-describedby="finalize-checklist">Finalize {wl(week)} review</button>}{!ready&&<p className="disabled-reason">{checks.length-passed} {checks.length-passed===1?"check is":"checks are"} not yet met.</p>}{ready&&!finalizer&&<p className="disabled-reason">Ready — waiting for an Org Owner, Admin, Platform Owner or Product Lead.</p>}</div>
        <p className={styles.meta}>Finalizing freezes this management snapshot. It does not approve a release or business decision. Corrections belong in initiative records and later reviews.</p>
      </section>}
    </>}
  </div>;
}
