import { hasOrganizationAdminAuthority, canBusinessWrite } from "@/lib/auth/roles";
import Link from "next/link";
import { readDelivery } from "@/lib/delivery/repository";
import { changesSince, freezeInput, isoWeek, referencesFor, weekValid } from "@/lib/delivery/model";
import { createWeeklyReviewAction, draftWeeklyReviewAction, finalizeWeeklyReviewAction, refreshWeeklyReviewAction } from "@/lib/delivery/actions";
import { ActionForm } from "@/components/delivery/ActionForm";
import { WeeklySection } from "@/components/delivery/WeeklySection";
import { memberLabel } from "@/components/delivery/FactEditor";
import { WriteNotice } from "@/components/delivery/WriteNotice";
import { isDemoWriteEnabled } from "@/lib/env";
import { safeUserLabel } from "@/lib/demo/presentation";
import { displayDate } from "@/lib/delivery/roadmap";
import styles from "@/components/delivery/delivery.module.css";
export const maxDuration = 60;
function cutoffLabel(value:string) { return new Date(value).toLocaleString("en-GB",{timeZone:"Africa/Cairo",dateStyle:"medium",timeStyle:"short"}); }
export default async function WeeklyReviewPage({searchParams}:{searchParams:Promise<{week?:string}>}) {
  const selection=await searchParams; const {ctx,source,state,presentation}=await readDelivery(); const now=new Date().toISOString(); const week=selection.week && weekValid(selection.week) ? selection.week : isoWeek(presentation.scenarioAt ?? now);
  const review=state.reviews.find(r=>r.workspaceId===ctx.workspaceId && r.week===week); const baseline=review ? state.reviews.find(r=>r.id===review.baselineReviewId && r.workspaceId===ctx.workspaceId && r.status==="FINAL" && r.week<review.week) : undefined;
  const current=freezeInput(source,state,ctx.workspaceId,now); const changes=review ? changesSince(review.input,baseline?.input ?? null) : [];
  const ai=review?.aiDrafts.at(-1); const editable=canBusinessWrite(ctx); const refs=review ? referencesFor(review.input,baseline?.input ?? null) : [];
  const availableIds=new Set(source.snapshots.map(s=>s.initiative.id));
  const unavailableSections=review?.sections.filter(section=>!availableIds.has(section.initiativeId)).length ?? 0;
  const ownerGroups=review ? [...new Set(review.sections.filter(s=>availableIds.has(s.initiativeId)).map(s=>s.ownerMemberId))].sort((a,b)=>memberLabel(review.input.members,a).localeCompare(memberLabel(review.input.members,b))) : [];
  const reviewed=review?.sections.filter(s=>!s.needsRecheck && Boolean(s.editedByMemberId || s.editedByUserId)).length ?? 0;
  const history=state.reviews.filter(r=>r.workspaceId===ctx.workspaceId).sort((a,b)=>b.week.localeCompare(a.week));
  return <div className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>Management review</span><h1>Weekly Product Review</h1><p>One portfolio. Shared updates. A preserved record of what changed.</p></div><nav className={styles.links}><Link href="/">Home</Link><Link href="/roadmap">Roadmap</Link></nav></header>
    <WriteNotice ctx={ctx}/>
    {presentation.isDemo && presentation.scenarioAt && <p className={styles.meta}>Scenario date · {displayDate(presentation.scenarioAt.slice(0,10))}. New confirmations and review edits retain their actual recorded timestamps.</p>}
    <form className={styles.filters}><label className={styles.field}>Review week<input type="week" name="week" defaultValue={week}/></label><button className={styles.button}>Open week</button></form>
    {history.length>0 && <nav className={styles.links} aria-label="Recent weekly reviews">{history.slice(0,6).map(item=><Link key={item.id} href={`/weekly-review?week=${item.week}`} aria-current={item.week===week?"page":undefined}>{item.week} · {item.status==="FINAL"?"Final":"Draft"}</Link>)}</nav>}
    {!review ? <div className={styles.emptyState}><h2>Prepare the shared review for {week}</h2><p>Start with the current portfolio and compare it with the previous final review. Each PM reviews their sections before a Product Lead or Admin finalizes the record.</p><p className={styles.meta}>The week labels the meeting. The actual data cutoff is recorded when inputs are captured.</p>{editable && <ActionForm action={createWeeklyReviewAction} label="Prepare shared weekly review" disabled={!isDemoWriteEnabled}><input type="hidden" name="week" value={week}/></ActionForm>}</div> : <>
      <div className={styles.reviewOverview}><div className={styles.reviewSummary}><span className={styles.eyebrow}>{review.status==="FINAL"?"Preserved meeting record":"Shared working draft"}</span><h2>{review.week} · {review.status==="FINAL"?"Final review":"Portfolio review"}</h2><p>{review.status==="FINAL"?`${review.preparedAsFixture ? "Prepared scenario baseline" : "Finalized by"} · ${safeUserLabel({preparedAsFixture:review.preparedAsFixture,confirmedByLabel:review.finalizedByLabel})}`:`${reviewed} of ${review.sections.length} initiative sections reviewed`}</p><p className={styles.meta}>Snapshot cutoff · {cutoffLabel(review.input.asOf)} Cairo</p>{review.status==="FINAL" && <p className={styles.meta}>Final records this management review. It does not grant business or release approval.</p>}</div><div className={styles.reviewBaseline}><strong>{baseline?`Compared with ${baseline.week} · Final`:"First review · no previous final"}</strong><p>{baseline?`Changes since ${cutoffLabel(baseline.input.asOf)} Cairo.`:"This is a current-state inventory. No weekly change baseline is assumed."}</p><p className={styles.meta}>A comparison can span skipped weeks and include facts recorded later about an earlier date.</p></div></div>
      <div className={styles.pulse}><span><strong>{review.input.snapshots.length}</strong> initiatives</span><span><strong>{new Set(changes.filter(c=>c.kind==="TARGET_LIVE").map(c=>c.initiativeId)).size}</strong> target updates</span><span><strong>{refs.filter(r=>r.id.startsWith("finding:")).length}</strong> recorded value differences</span><span><strong>{reviewed}/{review.sections.length}</strong> {review.preparedAsFixture?"scenario sections prepared":"human reviewed"}</span></div>
      {unavailableSections>0 && <p className={styles.notice}>{unavailableSections} {unavailableSections===1?"section is":"sections are"} unavailable under your current workspace access. Counts describe the original frozen portfolio. {review.status==="DRAFT" ? "Refresh delivery inputs to remove unavailable sections before finalizing." : "This Final preserves its original scope; inaccessible initiative details remain hidden."}</p>}
      {review.status==="DRAFT" && current.digest!==review.input.digest && <p className={styles.warning}>Portfolio inputs changed after this snapshot. Refresh inputs, then review the affected sections before finalizing.</p>}
      {ai && <p className={styles.notice}>{ai.mode==="CLAUDE" ? `AI-drafted · Claude (${ai.model}) selected supported source statements. Human review is required.` : `Template draft · ${ai.reason ?? "Prepared from recorded facts; Claude wording was unavailable."}`}<span className={styles.meta}> · {cutoffLabel(ai.generatedAt)} Cairo</span></p>}
      {review.status==="DRAFT" && editable && <div className={styles.reviewActions}><ActionForm action={refreshWeeklyReviewAction} label="Refresh delivery inputs" disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></ActionForm><ActionForm action={draftWeeklyReviewAction} label="Draft wording with Claude" pendingLabel="Drafting with Claude…" disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></ActionForm>{(hasOrganizationAdminAuthority(ctx) || ctx.isProductLead) && <ActionForm action={finalizeWeeklyReviewAction} label="Finalize reviewed portfolio" disabled={!isDemoWriteEnabled || unavailableSections>0 || reviewed!==review.sections.length || current.digest!==review.input.digest}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></ActionForm>}</div>}
      {review.status==="DRAFT" && <p className={styles.meta}>Review the wording and save each initiative section. Finalization freezes this snapshot; corrections belong in the next review.</p>}
      {ownerGroups.map(owner=><div className={styles.ownerGroup} key={owner ?? "unassigned"}><h2>{memberLabel(review.input.members,owner)}<span>{review.sections.filter(s=>s.ownerMemberId===owner && availableIds.has(s.initiativeId)).length} initiative sections</span></h2>{review.sections.filter(s=>s.ownerMemberId===owner && availableIds.has(s.initiativeId)).map(section=><WeeklySection key={`${section.initiativeId}:${section.revision}`} section={section} review={review} current={current} baseline={baseline?.input ?? null} ctx={ctx}/>)}</div>)}
      <details className={styles.details}><summary>Recorded changes and source statements</summary>{refs.filter(r=>current.snapshots.some(s=>s.initiative.id===r.initiativeId)).map(ref=><p key={ref.id}>{ref.texts[0]}<span className={styles.meta}> · {ref.id}</span></p>)}</details>
    </>}
  </div>;
}
