import Link from "next/link";
import {hasOrganizationAdminAuthority,canBusinessWrite} from "@/lib/auth/roles";
import {readDelivery} from "@/lib/delivery/repository";
import {changesSince,freezeInput,isoWeek,weekValid,latestBaseline,finalizationChecks,nextReviewWeek,ownerFor,sectionDigest} from "@/lib/delivery/model";
import {createWeeklyReviewAction,draftWeeklyReviewAction,finalizeWeeklyReviewAction,refreshWeeklyReviewAction} from "@/lib/delivery/actions";
import {buildPortfolioProjection} from "@/lib/workspace/portfolio";
import {memberLabel} from "@/components/delivery/FactEditor";
import {WriteNotice} from "@/components/delivery/WriteNotice";
import {isDemoWriteEnabled} from "@/lib/env";
import {safeUserLabel} from "@/lib/demo/presentation";
import {displayDate} from "@/lib/delivery/roadmap";
import {WeeklyActionForm} from "@/components/weekly/WeeklyActionForm";
import {SavedNotice} from "@/components/forms/SavedNotice";
import {SectionRecord} from "@/components/weekly/SectionRecord";
import {SectionCommentary} from "@/components/weekly/SectionCommentary";
import {SectionIndexDisclosure} from "@/components/weekly/SectionIndexDisclosure";
import {weeklyChangeSentence} from "@/lib/delivery/weekly-copy";
import {RecordUpdatePanel} from "@/components/weekly/RecordUpdatePanel";
import {readQuestions} from "@/lib/data/questions";
import {readRisks} from "@/lib/data/risks";
import {readRelationships} from "@/lib/data/relationships";
import {weeklyContextDelta} from "@/lib/workspace/weekly-context";
import styles from "@/components/weekly/weekly.module.css";
export const maxDuration=60;
const cutoff=(value:string)=>new Date(value).toLocaleString("en-GB",{timeZone:"Africa/Cairo",dateStyle:"medium",timeStyle:"short"});
export default async function WeeklyReviewPage({searchParams}:{searchParams:Promise<{week?:string;initiative?:string;view?:string}>}) {
  const [query,{ctx,source,state,presentation},qs,rs,rel]=await Promise.all([searchParams,readDelivery(),readQuestions(),readRisks(),readRelationships()]),now=new Date().toISOString();
  const week=query.week&&weekValid(query.week)?query.week:isoWeek(presentation.scenarioAt??now),review=state.reviews.find(r=>r.workspaceId===ctx.workspaceId&&r.week===week);
  const baseline=review?state.reviews.find(r=>r.id===review.baselineReviewId&&r.workspaceId===ctx.workspaceId&&r.status==="FINAL"&&r.week<review.week):latestBaseline(state,ctx.workspaceId,week);
  const current=freezeInput(source,state,ctx.workspaceId,now),writer=canBusinessWrite(ctx),finalizer=writer&&(hasOrganizationAdminAuthority(ctx)||ctx.isProductLead);
  const history=state.reviews.filter(r=>r.workspaceId===ctx.workspaceId).sort((a,b)=>b.week.localeCompare(a.week));
  const href=(slug?:string,view?:string)=>`/weekly-review?week=${week}${slug?`&initiative=${encodeURIComponent(slug)}`:""}${view?`&view=${view}`:""}`;
  const available=new Set(source.snapshots.map(s=>s.initiative.id)),sections=review?.sections.filter(s=>available.has(s.initiativeId))??[];
  const selected=sections.find(s=>review?.input.snapshots.find(i=>i.initiative.id===s.initiativeId)?.initiative.slug===query.initiative)??sections.find(s=>s.needsRecheck||!s.editedAt)??sections[0];
  const frozenProjection=review?buildPortfolioProjection({source:review.input,state:{schema:1,facts:review.input.facts,events:review.input.events,reviews:baseline?[baseline]:[]},workspaceId:ctx.workspaceId,asOf:review.input.asOf}):null;
  const checks=review?finalizationChecks(state,source,ctx,review,now,isDemoWriteEnabled):[],ready=checks.every(c=>c.met),stale=review?current.digest!==review.input.digest||(latestBaseline(state,ctx.workspaceId,week)?.id??null)!==review.baselineReviewId:false;
  const affected=review?.sections.filter(s=>!available.has(s.initiativeId)||s.sourceDigest!==sectionDigest(current,s.initiativeId)).length??0;
  const reviewed=review?.sections.filter(s=>!s.needsRecheck&&Boolean(s.editedByMemberId||s.editedByUserId)).length??0;
  const pending=sections.find(s=>s.needsRecheck||!s.editedByMemberId&&!s.editedByUserId);
  const pendingSlug=review?.input.snapshots.find(i=>i.initiative.id===pending?.initiativeId)?.initiative.slug;
  const groups=[...new Set(sections.map(s=>s.ownerMemberId))].sort((a,b)=>memberLabel(review!.input.members,a).localeCompare(memberLabel(review!.input.members,b)));
  const ai=review?.aiDrafts.at(-1),unavailable=(review?.sections.length??0)-sections.length;
  function sectionBody(section:typeof selected,readonly=false){if(!section||!review)return null;const snap=current.snapshots.find(s=>s.initiative.id===section.initiativeId);if(!snap)return null;const editable=review.status==="DRAFT"&&writer&&!readonly&&(hasOrganizationAdminAuthority(ctx)||ctx.isProductLead||ownerFor(current.facts,section.initiativeId)===ctx.memberId&&section.ownerMemberId===ctx.memberId);const context=weeklyContextDelta({initiativeId:section.initiativeId,slug:snap.initiative.slug,from:baseline?.input.asOf??null,to:review.status==="FINAL"&&review.finalizedAt?review.finalizedAt:now,questions:qs.questions,questionEvents:qs.events,riskEvents:rs.events,relationshipEvents:rel.events,names:Object.fromEntries(source.snapshots.map(x=>[x.initiative.id,x.initiative.name]))});return <div className={styles.section} key={section.initiativeId}><SectionRecord review={review} section={section} baseline={baseline?.input??null} returnTo={href(snap.initiative.slug)}/>{context.length>0&&<section className={styles.contextDelta} aria-label="Risks, questions and dependencies"><h4>Risks, questions & dependencies {baseline?`since ${baseline.week.replace(/^\d{4}-/,"")} Final`:"this period"}</h4><ul>{context.map(l=><li key={l.id} data-kind={l.kind.toLowerCase()}><Link prefetch={false} href={l.href}>{l.text}</Link></li>)}</ul><p>{review.status==="FINAL"?"Derived from recorded events up to finalization. Not part of the stored Final.":"Derived from recorded events. Record changes in the initiative; this list follows."}</p></section>}<SectionCommentary key={`${section.initiativeId}:${section.revision}`} review={review} section={section} baseline={baseline?.input??null} editable={editable} writesEnabled={isDemoWriteEnabled}/>{review.status==="DRAFT"&&writer&&!readonly&&<RecordUpdatePanel snapshot={snap} facts={state.facts} reviewId={review.id} reviewRevision={review.revision} workspaceId={ctx.workspaceId} canFacts={hasOrganizationAdminAuthority(ctx)||ownerFor(state.facts,section.initiativeId)===ctx.memberId} canDecision={writer} writesEnabled={isDemoWriteEnabled}/>}<nav className={styles.links} aria-label="Selected initiative navigation"><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}/delivery?returnTo=${encodeURIComponent(href(snap.initiative.slug))}`}>Scope, owner and delivery history</Link><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}/knowledge`}>Initiative Knowledge</Link></nav></div>;}
  return <div className={styles.page}><SavedNotice/><header className={styles.header}><div><span className={styles.eyebrow}>Portfolio management review</span><h1>Weekly Product Review</h1><p>Current initiative records → reviewed meeting commentary → preserved Final.</p></div><nav className={styles.links} aria-label="Portfolio review navigation"><Link prefetch={false} href="/">Home</Link><Link prefetch={false} href="/roadmap">Roadmap</Link></nav></header><WriteNotice ctx={ctx}/>
    <form className={styles.week}><label>Review week<input type="week" name="week" defaultValue={week}/></label><button className={styles.secondary}>Open week</button><span className={styles.status}>{review?.status==="FINAL"?"Final":review?"Draft":"Not prepared"}</span></form>
    {presentation.isDemo&&<p className={styles.meta}>Synthetic scenario · {displayDate((presentation.scenarioAt??now).slice(0,10))}. Review edits and confirmations retain their actual recorded timestamps.</p>}
    {history.length>0&&<nav className={styles.links} aria-label="Review history">{history.slice(0,6).map(r=><Link prefetch={false} key={r.id} href={`/weekly-review?week=${r.week}`} aria-current={r.week===week?"page":undefined}>{r.week} · {r.status==="FINAL"?"Final":"Draft"}</Link>)}</nav>}
    {!review?<section className={styles.block}><h2>Prepare {week} review</h2><p className={styles.meta}>{baseline?`Compares with ${baseline.week} Final · ${changesSince(current,baseline.input).length} recorded changes since its cutoff.`:"First review — no previous Final. Starts with an inventory of recorded initiative facts."}</p><p className={styles.meta}>The week labels the meeting. Preparing captures the actual source cutoff. Each PM reviews their sections before a coordinator finalizes.</p>{writer?<WeeklyActionForm action={createWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Prepare ${week} review`} primary disabled={!isDemoWriteEnabled||week>isoWeek(now)}><input type="hidden" name="week" value={week}/></WeeklyActionForm>:<p className={styles.meta}>Read-only: open an existing Final from review history.</p>}{week>isoWeek(now)&&<p className={styles.meta}>This week has not started. Prepare a review when it begins.</p>}</section>:<>
      <div className={styles.overview}><p><strong>{baseline?`Compared with ${baseline.week} Final · finalized ${cutoff(baseline.finalizedAt??baseline.input.asOf)} Cairo`:"First review · no previous Final"}</strong></p><p className={styles.meta}>Data as of {cutoff(review.input.asOf)} Cairo time. Comparisons can span skipped weeks or include late-recorded facts.</p><p className={styles.lifecycle}>Prepare · Draft wording · Review sections {reviewed}/{review.sections.length} · Confirm initiative updates separately · Finalize</p></div>
      {unavailable>0&&<p className={styles.warning}>{unavailable} recorded {unavailable===1?"section is":"sections are"} unavailable under current access. Counts describe the original scope; inaccessible details are hidden. {review.status==="DRAFT"?"Refresh inputs before finalizing.":"The Final remains unchanged."}</p>}
      {review.status==="DRAFT"&&<><div className={styles.toolbar}>{stale&&writer?<WeeklyActionForm action={refreshWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label="Update to latest records" primary disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>:ready&&finalizer?<WeeklyActionForm action={finalizeWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Finalize ${week} review`} primary describedBy="finalize-checklist" confirm={{title:`Finalize the ${week} review?`,body:'Finalizing freezes this review as the shared record for the week and makes it the baseline for the next review. It cannot be edited or undone afterwards. Initiative records are not changed.',action:`Yes, finalize ${week}`}} disabled={!isDemoWriteEnabled}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>:pendingSlug&&writer?<Link prefetch={false} className={styles.button} href={href(pendingSlug)}>Review next section</Link>:<p className={styles.meta}>Ready — waiting for an Org Owner, Admin, Platform Owner or Product Lead.</p>}{writer&&<WeeklyActionForm action={draftWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label="Draft wording with Claude" pendingLabel="Drafting with Claude…" disabled={!isDemoWriteEnabled||stale}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="revision" value={review.revision}/></WeeklyActionForm>}</div>{stale&&<p className={styles.warning}>Initiative records changed after the snapshot · {affected} sections affected. Refresh inputs, then re-check changed sections. Commentary is preserved.</p>}</>}
      {review.status==="FINAL"&&(()=>{const next=nextReviewWeek(week),exists=state.reviews.find(r=>r.workspaceId===ctx.workspaceId&&r.week===next.week),started=next.week<=isoWeek(now);return <section className={styles.receipt}><h2>{week} · Final</h2><p>{review.preparedAsFixture?"Prepared synthetic scenario baseline by":"Finalized by"} {safeUserLabel({preparedAsFixture:review.preparedAsFixture,confirmedByLabel:review.finalizedByLabel})} · {cutoff(review.finalizedAt??review.input.asOf)} Cairo.<br/>Data as of {cutoff(review.input.asOf)} Cairo time · {baseline?`Compared with ${baseline.week} Final`:"No previous Final"}.</p><p><strong>This Final is the baseline for the next review.</strong> It records what management reviewed; it is not a release or business approval.</p><div className={styles.toolbar}>{exists?<Link prefetch={false} className={styles.button} href={`/weekly-review?week=${next.week}`}>Open {next.week}</Link>:writer?<WeeklyActionForm action={createWeeklyReviewAction} scopeWorkspaceId={ctx.workspaceId} label={`Prepare ${next.week} review`} redirectTo={`/weekly-review?week=${next.week}`} primary disabled={!started||!isDemoWriteEnabled}><input type="hidden" name="week" value={next.week}/></WeeklyActionForm>:<p className={styles.meta}>Read-only: you cannot prepare a review.</p>}<Link prefetch={false} className={styles.secondary} href={href(undefined,"since")}>View changes since {week} Final</Link><Link prefetch={false} className={styles.secondary} href={href(undefined,"all")}>Read full review</Link></div>{!exists&&!started&&<p className={styles.meta}>{next.week} starts Monday {displayDate(next.startsOn)}. Preparation uses the real calendar, not the scenario date.</p>}{!isDemoWriteEnabled&&<p className={styles.meta}>Review preparation is disabled in this environment.</p>}</section>;})()}
      {ai&&<p className={styles.notice}>{ai.mode==="CLAUDE"?`Claude draft · ${ai.model} selected supported source statements. Human review required.`:`Template draft · ${ai.reason??"Claude wording unavailable; prepared deterministically from recorded facts."}`} · {cutoff(ai.generatedAt)} Cairo. Wording never updates initiative records.</p>}
      <nav className={styles.links} aria-label="Review presentation"><Link prefetch={false} href={href(selected?review.input.snapshots.find(i=>i.initiative.id===selected.initiativeId)?.initiative.slug:undefined)} aria-current={!query.view?"page":undefined}>Section view</Link><Link prefetch={false} href={href(undefined,"all")} aria-current={query.view==="all"?"page":undefined}>Full meeting document · read-only</Link>{review.status==="FINAL"&&<Link prefetch={false} href={href(undefined,"since")} aria-current={query.view==="since"?"page":undefined}>Changes since this Final</Link>}</nav>
      {query.view==="since"&&review.status==="FINAL"?<section className={styles.block}><h2>Current record compared with {week} Final — not a review</h2><p className={styles.meta}>Current source cutoff · {cutoff(current.asOf)} Cairo. The Final above is unchanged.</p>{changesSince(current,review.input).length?<ul className={styles.changes}>{changesSince(current,review.input).filter(c=>available.has(c.initiativeId)).map(c=><li key={c.id}>{weeklyChangeSentence(c,current,review.input)}</li>)}</ul>:<p>No recorded changes since this Final.</p>}</section>:query.view==="all"?<div className={styles.fullDocument}>{sections.map(s=>sectionBody(s,true))}</div>:<div className={styles.layout}><aside className={styles.index}><SectionIndexDisclosure explicitSelection={Boolean(query.initiative)} count={review.sections.length} currentName={review.input.snapshots.find(i=>i.initiative.id===selected?.initiativeId)?.initiative.name??"No available section"}>{groups.map(owner=><div key={owner??"unassigned"}><h2>{memberLabel(review.input.members,owner)}</h2><ul>{sections.filter(s=>s.ownerMemberId===owner).map(s=>{const row=frozenProjection?.rows.find(r=>r.initiative.id===s.initiativeId),snap=review.input.snapshots.find(i=>i.initiative.id===s.initiativeId)!;const isNew=!baseline?.input.snapshots.some(i=>i.initiative.id===s.initiativeId),badges=[isNew&&baseline?"New":null,row?.targetMovement?`Target ${row.targetMovement.days>=0?"+":""}${row.targetMovement.days} d`:null,...(row?.attention.filter(a=>["DECISION","BLOCKER"].includes(a.kind)).map(a=>a.label)??[])].filter(Boolean).join(" · ");return <li key={s.initiativeId}><Link prefetch={false} href={href(snap.initiative.slug)} aria-current={selected?.initiativeId===s.initiativeId?"page":undefined}>{snap.initiative.name}<small>{review.status==="FINAL"?"Final snapshot":s.needsRecheck?"Needs re-check":s.editedByMemberId||s.editedByUserId?"Reviewed":"Needs review"}</small>{badges&&<small>{badges}</small>}</Link></li>;})}</ul></div>)}</SectionIndexDisclosure></aside>{sectionBody(selected)}</div>}
      {review.status==="DRAFT"&&<section className={styles.block}><h2>Finalize prerequisites</h2><ul className={styles.checklist} id="finalize-checklist">{checks.filter(check=>!check.met).map(check=><li key={check.id}><strong>Needs action</strong> · {check.label}</li>)}{checks.every(check=>check.met)&&<li><strong>✓ Ready</strong> · Every check passed</li>}<li className={styles.meta}>{checks.filter(check=>check.met).length} of {checks.length} checks passed</li></ul>{!ready&&<button disabled className={styles.secondary} aria-describedby="finalize-checklist">Finalize {week} review</button>}{review.sections.filter(s=>s.needsRecheck||!s.editedByMemberId&&!s.editedByUserId).map(s=>{const item=review.input.snapshots.find(i=>i.initiative.id===s.initiativeId);return item&&available.has(s.initiativeId)?<p key={s.initiativeId} className={styles.meta}><Link prefetch={false} href={href(item.initiative.slug)}>{item.initiative.name} · {s.needsRecheck?"Needs re-check":"Needs review"}</Link></p>:null;})}<p className={styles.meta}>Finalizing freezes this management snapshot. It does not approve a release or business decision. Corrections belong in initiative records and later reviews.</p></section>}
    </>}
  </div>;
}
