import { BusinessLine } from '@/components/primitives/BusinessLine';
import Link from "next/link";
import {readDelivery} from "@/lib/delivery/repository";
import {listProjectMetrics} from "@/lib/analysis/metrics";
import {STAGE_LABEL,businessLineText} from "@/lib/domain/labels";
import {displayDate} from "@/lib/delivery/roadmap";
import {AnalysisFrame,styles} from "@/components/analysis/AnalysisFrame";
import {DataTable,styles as adminStyles} from "@/components/admin/AdminUI";
export const metadata={title:"Project Analysis"};
export default async function Projects({searchParams}:{searchParams:Promise<{line?:string;stage?:string;measurement?:string}>}){const [data,metrics,query]=await Promise.all([readDelivery(),listProjectMetrics(),searchParams]);const {source,presentation}=data,asOf=presentation.scenarioAt??new Date().toISOString();const all=source.snapshots.map(s=>s.initiative),ids=new Set(metrics.map(m=>m.initiativeId));const rows=all.filter(i=>(!query.line||i.businessLine===query.line)&&(!query.stage||i.stage===query.stage)&&(!query.measurement||(query.measurement==="configured"?ids.has(i.id):!ids.has(i.id))));const qs=new URLSearchParams(Object.entries(query).filter(([,v])=>v) as [string,string][]).toString();const back="/analysis/projects"+(qs?"?"+qs:"");
 return <AnalysisFrame active="projects" title="Project Analysis" organizationName={presentation.organizationName} asOf={asOf} synthetic={presentation.isDemo}><section className={styles.section}><h2>Measurement coverage</h2><p>Measurement is configured for {all.filter(i=>ids.has(i.id)).length} of {all.length} initiatives.</p><p className={styles.meta}>Delivery dates are not performance measures. Missing observations are not zero.</p></section><form className={adminStyles.toolbar} aria-label="Filter project analysis"><label>Business line<select name="line" defaultValue={query.line??""}><option value="">All lines</option>{[...new Set(all.map(i=>i.businessLine))].map(v=><option value={v} key={v}>{businessLineText(v)}</option>)}</select></label><label>Stage<select name="stage" defaultValue={query.stage??""}><option value="">All stages</option>{[...new Set(all.map(i=>i.stage))].map(v=><option value={v} key={v}>{STAGE_LABEL[v]}</option>)}</select></label><label>Measurement<select name="measurement" defaultValue={query.measurement??""}><option value="">All initiatives</option><option value="configured">Configured</option><option value="missing">Not configured</option></select></label><button className={adminStyles.secondary}>Apply</button><Link prefetch={false} className={adminStyles.secondary} href="/analysis/projects">Clear</Link></form><DataTable caption="Project measurement coverage" columns={["Initiative","Business line","Stage","Measurement","Open"]} rows={rows.map(i=>{const entries=metrics.filter(m=>m.initiativeId===i.id),captured=entries.flatMap(m=>m.observations.map(o=>o.capturedAt)).sort().at(-1);return {key:i.id,cells:[i.name,<BusinessLine key="bl" code={i.businessLine}/>,STAGE_LABEL[i.stage],entries.length?`${entries.length} ${entries.length===1?"metric":"metrics"} · ${captured?"last captured "+displayDate(captured.slice(0,10)):"no observations"}`:"Not configured",<Link prefetch={false} key="open" href={"/analysis/projects/"+i.slug+"?back="+encodeURIComponent(back)}>Open {i.name} →</Link>]};})} empty="No initiatives match these filters. Change or clear the filters."/></AnalysisFrame>;
}
