"use client";
import {useRef,useState} from "react";
import {hasOrganizationAdminAuthority,canBusinessWrite} from "@/lib/auth/roles";
import Link from "next/link";
import type {DeliveryFact,DeliveryMember,FactKind,PortfolioSource,WorkspaceAccess} from "@/lib/delivery/types";
import {FACT_KINDS} from "@/lib/delivery/types";

import {saveDeliveryFactAction} from "@/lib/delivery/actions";

import {safeUserLabel} from "@/lib/demo/presentation";
const displayDate=(date:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${date}T00:00:00Z`));
import {WeeklyActionForm} from "@/components/weekly/WeeklyActionForm";
import styles from "./facts.module.css";
export const FACT_LABELS:Record<FactKind,string>={SCOPE:"Delivery phase / scope",OWNER:"Responsible PM",SOLUTION_DEFINED:"Solution baseline — actual",DEV_STARTED:"Development Start — actual",TARGET_LIVE:"Target Live — planned",ACTUAL_LIVE:"Actual Live",NEXT_MILESTONE:"Next milestone — planned",BLOCKER:"Blocker / attention",NEXT_STEP:"Next step"};
const definitions:Partial<Record<FactKind,string>>={SCOPE:"Name the exact phase, pilot or rollout. Dates apply only to this scope. Confirm scope before recording other delivery facts.",SOLUTION_DEFINED:"Actual date the named scope's agreed requirements and proposed approach were confirmed sufficiently for implementation planning. This does not establish development start, release readiness or launch approval.",DEV_STARTED:"Actual date implementation began for this scope. An estimated future start does not belong here.",TARGET_LIVE:"The current human-confirmed production target. Each change preserves its previous value and confirmation reason.",ACTUAL_LIVE:"Actual first production date for real users in this named scope, with partial or full rollout recorded. A missing date does not establish that it is not live.",NEXT_MILESTONE:"Name the next concrete checkpoint. Its date can remain unknown."};
export function memberLabel(members:DeliveryMember[],id:string|null):string{if(!id)return"Unassigned";const m=members.find(m=>m.id===id);return m?`${m.displayName}${m.active?"":" (inactive)"}`:"Owner unavailable";}
export function FactLedger({initiativeId,facts,source,ctx,writesEnabled,changedSupportIds}:{initiativeId:string;facts:DeliveryFact[];source:PortfolioSource;ctx:WorkspaceAccess;writesEnabled:boolean;changedSupportIds:string[]}) {
  const snapshot=source.snapshots.find(s=>s.initiative.id===initiativeId)!;const owner=facts.find(f=>f.initiativeId===initiativeId&&f.kind==="OWNER"&&f.state==="SET")?.value.memberId??null;const[selected,setSelected]=useState<FactKind|null>(null);const editor=useRef<HTMLDivElement>(null);const dirty=useRef(false);
  const canEdit=(kind:FactKind)=>!snapshot.initiative.archivedAt&&canBusinessWrite(ctx)&&(kind==="OWNER"?hasOrganizationAdminAuthority(ctx)||ctx.isProductLead:hasOrganizationAdminAuthority(ctx)||owner===ctx.memberId);
  const fact=selected?facts.find(f=>f.initiativeId===initiativeId&&f.kind===selected):undefined;const value=fact?.state==="SET"?fact.value:null;
  const summary=(kind:FactKind,f:DeliveryFact|undefined)=>{if(!f||f.state!=="SET")return kind==="OWNER"?"Unassigned":"Not recorded";if(f.value.unknown)return "Explicitly unknown";return kind==="OWNER"?memberLabel(source.members,f.value.memberId):[f.value.date?displayDate(f.value.date):null,f.value.text,f.value.dateUnknown?"Date explicitly unknown":null,f.value.extent==="FULL"?"Full named scope":f.value.extent==="PARTIAL"?"Partial named scope":null].filter(Boolean).join(" · ")||"Not recorded";};
  function edit(kind:FactKind){if(dirty.current&&!window.confirm("Your delivery fact has unsaved changes. Change the selected field?"))return;dirty.current=false;setSelected(kind);setTimeout(()=>editor.current?.scrollIntoView({block:"nearest",behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}),0);}
  return <div className={styles.root}><div className={styles.ledger}><table><caption>Human-confirmed delivery record</caption><thead><tr><th>Field</th><th>Current value</th><th>Confirmation and source</th><th>Action</th></tr></thead><tbody>{FACT_KINDS.map(kind=>{const f=facts.find(f=>f.initiativeId===initiativeId&&f.kind===kind),e=source.snapshots.find(s=>s.initiative.id===initiativeId)?.evidence.find(e=>e.id===f?.evidenceId);return <tr key={kind} className={selected===kind?styles.selected:undefined}><th scope="row">{FACT_LABELS[kind]}</th><td>{summary(kind,f)}{f?.state==="RETRACTED"&&<small>Earlier value withdrawn; history retained</small>}</td><td>{f?<><span>{f.preparedAsFixture?"Prepared by":"Confirmed by"} {safeUserLabel(f)}</span><small>{new Date(f.updatedAt).toLocaleString("en-GB",{timeZone:"Africa/Cairo",dateStyle:"medium",timeStyle:"short"})} Cairo · revision {f.revision}</small><small>{f.basis==="EVIDENCE"?<Link prefetch={false} href={`/initiatives/${snapshot.initiative.slug}/sources/${f.evidenceId}/edit`}>{e?.title??"Linked source unavailable"}</Link>:"Direct knowledge"}{f.locator&&` · ${f.locator}`}</small>{changedSupportIds.includes(f.id)&&<small className={styles.warning}>Supporting evidence changed; confirmation preserved</small>}<details><summary>Confirmation reason</summary><p>{f.note}</p></details></>:"No confirmation recorded"}</td><td>{canEdit(kind)&&<button type="button" aria-label={`Edit ${FACT_LABELS[kind]}`} aria-pressed={selected===kind} onClick={()=>edit(kind)} disabled={!writesEnabled}>{selected===kind?"Selected":"Edit"}</button>}</td></tr>;})}</tbody></table></div>
  {!canBusinessWrite(ctx)&&<p className={styles.meta}>Read-only view.</p>}
  <div ref={editor}>{selected&&canEdit(selected)?<section className={styles.editor} key={`${selected}:${fact?.revision??0}`} onChange={()=>{dirty.current=true;}}><h3>Edit {FACT_LABELS[selected]}</h3><p className={styles.meta}>{definitions[selected]??"Confirm the new value and record its basis. Existing history is retained."}</p><p className={styles.meta}>Current: {summary(selected,fact)}. Saving updates this initiative’s Brief, Home and Roadmap. An open Weekly Draft must refresh before finalization; existing Finals stay unchanged.</p><WeeklyActionForm action={saveDeliveryFactAction} label="Confirm and save" scopeWorkspaceId={ctx.workspaceId} disabled={!writesEnabled} watchEdits onSaved={()=>{dirty.current=false;}}>
    <input type="hidden" name="initiativeId" value={initiativeId}/><input type="hidden" name="kind" value={selected}/><input type="hidden" name="revision" value={fact?.revision??0}/><div className={styles.fields}>
    {["SOLUTION_DEFINED","DEV_STARTED","TARGET_LIVE","ACTUAL_LIVE","NEXT_MILESTONE"].includes(selected)&&<label>{selected==="TARGET_LIVE"||selected==="NEXT_MILESTONE"?"Planned date":"Actual date"}<input type="date" name="date" defaultValue={value?.date??""}/></label>}
    {["SCOPE","NEXT_MILESTONE","BLOCKER","NEXT_STEP","ACTUAL_LIVE"].includes(selected)&&<label>{selected==="ACTUAL_LIVE"?"Rollout description (required for partial)":"Description"}<textarea name="text" maxLength={2000} defaultValue={value?.text??""}/></label>}
    {["TARGET_LIVE","DEV_STARTED","NEXT_MILESTONE"].includes(selected)&&<label className={styles.choice}><input type="checkbox" name="unknown" value="yes" defaultChecked={value?.unknown===true}/>Explicitly unknown — leave date and description empty</label>}
    {selected==="NEXT_MILESTONE"&&<label className={styles.choice}><input type="checkbox" name="dateUnknown" value="yes" defaultChecked={value?.dateUnknown===true}/>Milestone is named, but its date is explicitly unknown — leave date empty</label>}
    {selected==="OWNER"&&<label>Responsible PM<select name="memberId" defaultValue={value?.memberId??""}><option value="">Unassigned · withdraw assignment</option>{source.members.filter(m=>m.active&&m.role!=="VIEWER").map(m=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select></label>}
    {selected==="ACTUAL_LIVE"&&<label>Rollout extent<select name="extent" defaultValue={value?.extent??""}><option value="">Choose extent</option><option value="FULL">Full named scope</option><option value="PARTIAL">Partial named scope</option></select></label>}
    <label>Confirmation basis<select name="basis" defaultValue={fact?.basis??"DIRECT_KNOWLEDGE"}><option value="DIRECT_KNOWLEDGE">Direct knowledge</option><option value="EVIDENCE">Current-scope evidence</option></select></label><label>Current-scope source<select name="evidenceId" defaultValue={fact?.evidenceId??""}><option value="">No linked source</option>{snapshot.evidence.filter(e=>e.boundary==="CURRENT_SCOPE").map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Source locator<input name="locator" maxLength={500} defaultValue={fact?.locator??""}/></label><label>Confirmation / change reason<textarea name="note" required maxLength={2000}/></label></div>{fact&&<label className={styles.choice}><input type="checkbox" name="retract" value="yes"/>Withdraw the earlier value and preserve history</label>}
  </WeeklyActionForm><button type="button" className={styles.close} onClick={()=>{if(!dirty.current||window.confirm("Discard this unsaved proposal?")){dirty.current=false;setSelected(null);}}}>Close editor</button></section>:<p className={styles.meta}>Select a field to edit. The assigned PM, Org Owner, Admin or Platform Owner maintains facts. Org administration or Product Lead assigns the PM.</p>}</div></div>;
}
