import {formatDateTime} from "@/lib/domain/labels";
import Link from "next/link";
import type {ReactNode} from "react";
import styles from "./admin.module.css";
export {default as styles} from "./admin.module.css";
export function AdminFrame({scope,organizationName,title,active,children,description}:{scope:"platform"|"organization";organizationName:string;title:string;active:string;children:ReactNode;description?:string}){
 const tabs=scope==="platform"?[["organizations","Organizations"],["users","Users & Access"],["policies","Access Policies"]]:[["settings","Organization"],["users","Users & Access"],["policy","Access Policy"]];
 return <div className={styles.page}><header className={styles.masthead}><div><Link prefetch={false} className={styles.breadcrumb} href="/administration">Administration</Link><p className={styles.eyebrow}>{scope==="platform"?"Platform · All organizations":"Organization · "+organizationName}</p><h1>{title}</h1>{description&&<p className={styles.intro}>{description}</p>}</div><span className={styles.scope}>{scope==="platform"?"Global authority":"Current organization"}</span></header><div className={styles.console}><nav className={styles.subnav} aria-label="Administration sections">{tabs.map(([key,label])=><Link prefetch={false} key={key} href={`/administration/${scope}/${key}`} aria-current={active===key?"page":undefined}>{label}</Link>)}</nav><div className={styles.content}>{children}</div></div></div>;
}
export function Restricted({guest=false}:{guest?:boolean}){return <section className={styles.page}><p className={styles.eyebrow}>Access restricted</p><h1>Administration is unavailable</h1><p>{guest?"Explore Demo includes synthetic product work. Account and organization administration are unavailable in this session.":"Organization administration requires an Org Owner or Admin. Platform administration requires global Platform Owner authority."}</p><Link prefetch={false} className={styles.secondary} href="/">Return to Home</Link></section>;}
export function ManagementNotice({writable}:{writable:boolean}){return !writable?<p className={styles.notice} role="status">Changes are disabled in this environment. Your role and access are unchanged.</p>:null;}
export function DataTable({caption,columns,rows,empty="No records match this view."}:{caption:string;columns:string[];rows:{key:string;cells:ReactNode[]}[];empty?:string}){
 if(!rows.length)return <p className={styles.empty}>{empty}</p>;
 return <><div className={styles.tableWrap}><table className={styles.table}><caption className="visually-hidden">{caption}</caption><thead><tr>{columns.map(c=><th scope="col" key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.key}>{row.cells.map((cell,i)=>i===0?<th scope="row" key={i}>{cell}</th>:<td key={i}>{cell}</td>)}</tr>)}</tbody></table></div><ul className={styles.mobileList} aria-label={caption}>{rows.map(row=><li key={row.key}><div className={styles.mobileTitle}>{row.cells[0]}</div><dl>{row.cells.slice(1).map((cell,i)=><div key={i}><dt>{columns[i+1]}</dt><dd>{cell}</dd></div>)}</dl></li>)}</ul></>;
}
export function Section({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <section className={styles.section}><div className={styles.sectionHead}><h2>{title}</h2>{action}</div>{children}</section>;}
export function Badge({children}:{children:ReactNode}){return <span className={styles.badge}>{children}</span>;}
const ACCESS_EVENT_LABEL:Record<string,string>={SELF_SIGNUP:"Joined through self sign-up",ORGANIZATION_SELF_SIGNUP_CHANGED:"Self sign-up setting changed",INVITATION_ACCEPTED:"Invitation accepted",INVITATION_CREATED:"Invitation sent",INVITATION_REVOKED:"Invitation withdrawn",ROLE_CHANGED:"Role changed",MEMBER_DEACTIVATED:"Access removed",MEMBER_REACTIVATED:"Access restored"};
/** Access events read as sentences, never as stored codes. */
export function accessEventLabel(action:string){const known=ACCESS_EVENT_LABEL[action];if(known)return known;const words=action.toLowerCase().replaceAll("_"," ");return words.charAt(0).toUpperCase()+words.slice(1);}
export function History({events}:{events:{id:string;at:string;action:string;actorLabel?:string;reason?:string;policyOverridden?:boolean}[]}){return <ol className={styles.history}>{events.length?events.slice(0,50).map(e=><li key={e.id}><strong>{accessEventLabel(e.action)}</strong><p>{e.actorLabel??"Recorded operator"} · {formatDateTime(e.at)} Cairo time</p>{e.reason&&<p>{e.reason}</p>}{e.policyOverridden&&<p>Organization email policy overridden</p>}</li>):<li>No recorded access events for this selection.</li>}</ol>;}
