import Link from "next/link";
import {notFound} from "next/navigation";
import {platformSnapshot,userManagementSnapshot,readOrganizationAdministration} from "@/lib/auth/service";
import {hasOrganizationOwnerAuthority} from "@/lib/auth/roles";
import {OpenOrganizationForm} from "./OpenOrganizationForm";
import {selfSignupAction,createOrganizationAction,configurePolicyAction,provisionMembershipAction,replaceOrgOwnersAction,platformInvitationAction} from "@/app/platform/actions";
import {inviteAction,changeMemberAction,invitationAction,renameWorkspaceAction} from "@/app/users/actions";
import {AdminForm} from "./AdminForm";
import {AdminFrame,DataTable,Section,Badge,History,ManagementNotice,styles} from "./AdminUI";
import {activeOrganizationMembers,dateLabel,invitationStatus,roleLabel} from "./model";
import type {adminAccess,PlatformState} from "./access";
type Access=Awaited<ReturnType<typeof adminAccess>>;
type Query=Record<string,string|undefined>;
const roleOptions=(owner:boolean)=>[...(owner?["ADMIN"]:[]),"MEMBER","VIEWER"].map(value=>({value,label:roleLabel(value)}));
const allRoles=["ORG_OWNER","ADMIN","MEMBER","VIEWER"].map(value=>({value,label:roleLabel(value)}));
const person=(s:PlatformState,id:string)=>s.identities.find(x=>x.id===id);
const orderedEvents=<T extends {at:string}>(events:T[])=>[...events].sort((a,b)=>b.at.localeCompare(a.at));
function PolicyText({policy,selfSignup}:{policy:{domains:readonly string[];exactEmails:readonly string[]};selfSignup?:boolean}){return <dl className={styles.details}><div><dt>Allowed domains</dt><dd>{policy.domains.length?policy.domains.join("\n"):"None"}</dd></div><div><dt>Exact email exceptions</dt><dd>{policy.exactEmails.length?policy.exactEmails.join("\n"):"None"}</dd></div>{selfSignup!==undefined&&<div><dt>Self sign-up</dt><dd>{selfSignup?"On — verified addresses allowed by this policy may join as Member":"Off — invitation only"}</dd></div>}</dl>;}
function Filters({query,organizationOptions,statuses,roles=false}:{query:Query;organizationOptions?:{id:string;name:string}[];statuses?:string[];roles?:boolean}){return <form className={styles.toolbar} aria-label="Filter records"><label>Search<input type="search" name="q" defaultValue={query.q??""} placeholder="Name or email"/></label>{statuses&&<label>Status<select name="status" defaultValue={query.status??"ACTIVE"}>{statuses.map(s=><option key={s} value={s}>{s==="ALL"?"All statuses":s.charAt(0)+s.slice(1).toLowerCase()}</option>)}</select></label>}{organizationOptions&&<label>Organization<select name="organization" defaultValue={query.organization??""}><option value="">All organizations</option>{organizationOptions.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}{roles&&<label>Role<select name="role" defaultValue={query.role??""}><option value="">All organization roles</option>{allRoles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label>}<button className={styles.secondary}>Apply</button></form>;}
export async function PlatformConsole({access,path,query}:{access:Access;path:string[];query:Query}){
 const state=await platformSnapshot();const section=path[0]??"organizations",id=path[1];if(!["organizations","users","policies"].includes(section)||path.length>2)notFound();
 const base="/administration/platform",returnTo=base+"/"+section+(id?"/"+id:""),hidden={returnTo};const scopeWorkspaceId=access.ctx.workspaceId;
 const active=(orgId:string)=>activeOrganizationMembers(state.memberships,state.identities,orgId);
 const title=section==="organizations"?(id==="new"?"Create organization":id?state.organizations.find(o=>o.id===id)?.name??"Organization":"Organizations"):section==="users"?(id?person(state,id)?.displayName??"Person":"Users & Access"):id?"Organization access policy":"Access Policies";
 const frame=(content:React.ReactNode)=><AdminFrame scope="platform" organizationName="" title={title} active={section} description="Global platform authority · organization roles and policies remain scoped."><ManagementNotice writable={access.writable}/>{content}</AdminFrame>;
 if(section==="organizations"&&id==="new")return frame(<Section title="Organization details"><AdminForm action={createOrganizationAction} scopeWorkspaceId={scopeWorkspaceId} hidden={hidden} disabled={!access.writable} submit="Create organization" cancelHref={base+"/organizations"} fields={[{name:"name",label:"Organization name",required:true,maxLength:120},{name:"domains",label:"Allowed email domains",type:"textarea",hint:"One domain per line, for example examplebank.com."},{name:"exactEmails",label:"Exact email exceptions",type:"textarea",hint:"Each address allows only that person, not their whole domain."}]}/><p className={styles.summary}>The organization remains in setup until an Org Owner is assigned. Existing organizations and memberships are unchanged.</p><Link prefetch={false} className={styles.textLink} href={base+"/organizations?status=BOOTSTRAPPING"}>Open organizations awaiting an owner →</Link></Section>);
 if(section==="organizations"&&!id){
  const status=["ACTIVE","BOOTSTRAPPING","ARCHIVED","ALL"].includes(query.status??"")?query.status!:"ACTIVE",q=(query.q??"").toLowerCase();
  const rows=state.organizations.filter(o=>(status==="ALL"||o.status===status)&&o.name.toLowerCase().includes(q));
  return frame(<><Section title="Organization register" action={<Link prefetch={false} className={styles.primary} href={base+"/organizations/new"}>Create organization</Link>}><div className={styles.countRow}>{["ACTIVE","BOOTSTRAPPING","ARCHIVED"].map(value=><span key={value}><strong>{state.organizations.filter(o=>o.status===value).length}</strong> {value==="BOOTSTRAPPING"?"in setup":value.toLowerCase()}</span>)}</div><Filters query={{...query,status}} statuses={["ACTIVE","BOOTSTRAPPING","ARCHIVED","ALL"]}/><p className={styles.summary}>{rows.length} of {state.organizations.length} organizations</p><DataTable caption="Platform organizations" columns={["Organization","Status","Active owners","Active members","Platform invites","Policy","Open"]} rows={rows.map(org=>({key:org.id,cells:[<span key="name">{org.name}{"isDemo" in org&&org.isDemo?<small>{org.status==="ARCHIVED"?"Archived synthetic generation":"Synthetic demo"}</small>:null}</span>,<Badge key="status">{org.status==="BOOTSTRAPPING"?"Needs owner":org.status==="ARCHIVED"?"Archived":"Active"}</Badge>,active(org.id).filter(m=>m.role==="ORG_OWNER").length||"0 · needs owner",active(org.id).length,state.invitations.filter(i=>i.organizationId===org.id&&invitationStatus(i,state.capturedAt)==="Pending").length,`${org.emailPolicy.domains.length} ${org.emailPolicy.domains.length===1?"domain":"domains"} · ${org.emailPolicy.exactEmails.length} exact ${org.emailPolicy.exactEmails.length===1?"email":"emails"}`,<Link prefetch={false} key="open" href={base+"/organizations/"+org.id} aria-label={"Open "+org.name}>Open →</Link>]}))}/></Section></>);
 }
 if(section==="organizations"&&id){
  const org=state.organizations.find(o=>o.id===id);if(!org)notFound();const members=state.memberships.filter(m=>m.organizationId===id),owners=active(id).filter(m=>m.role==="ORG_OWNER"),workspaces=state.workspaces.filter(w=>w.organizationId===id&&w.status==="ACTIVE");const archived=org.status==="ARCHIVED";
  const invites=state.invitations.filter(i=>i.organizationId===id);
  return frame(<><div className={styles.detailColumns}><div><Section title="Organization overview"><dl className={styles.details}><div><dt>Status</dt><dd>{org.status}</dd></div><div><dt>Org Owners</dt><dd>{owners.map(m=>person(state,m.userId)?.displayName).join(", ")||"No active owner — setup is incomplete"}</dd></div><div><dt>Active members</dt><dd>{active(id).length}</dd></div></dl><div className={styles.actions}>{org.status==="ACTIVE"&&workspaces.length===1&&owners.length>0&&<OpenOrganizationForm workspaceId={workspaces[0]!.id} scopeWorkspaceId={scopeWorkspaceId}/>}<Link prefetch={false} className={styles.secondary} href={base+"/users?organization="+id}>View organization members</Link></div></Section><Section title="Members"><DataTable caption={"Members of "+org.name} columns={["Person","Organization role","Access","Open"]} rows={members.map(m=>({key:m.id,cells:[person(state,m.userId)?.displayName??"Unavailable identity",roleLabel(m.role),m.active&&person(state,m.userId)?.active?"Active":"Deactivated",<Link prefetch={false} key="open" href={base+"/users/"+m.userId}>Open person →</Link>]}))}/></Section></div><aside className={styles.side}><Section title="Access policy"><PolicyText policy={org.emailPolicy}/><Link prefetch={false} className={styles.textLink} href={base+"/policies/"+id}>Inspect access policy →</Link></Section><Section title="Recorded history"><History events={orderedEvents(state.events.filter(e=>e.organizationId===id))}/></Section></aside></div>
  {!archived&&<nav className={styles.actions} aria-label="Organization access actions"><Link prefetch={false} className={query.action==="grant"?styles.primary:styles.secondary} href={returnTo+"?action=grant"}>Grant organization access</Link><Link prefetch={false} className={styles.secondary} href={returnTo+"?action=replace"}>Replace all owners</Link></nav>}
  {!archived&&query.action==="grant"&&<Section title="Grant organization access"><p className={styles.summary}>Add a person, add another Org Owner, or change an existing membership through a recorded platform action.</p><AdminForm action={provisionMembershipAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,organizationId:id}} disabled={!access.writable} submit="Grant organization access" consequence={"This grants the selected role in "+org.name+". Existing account credentials are unchanged. Any email-policy override is recorded with your identity and reason."} fields={[{name:"email",label:"Person’s email",type:"email",required:true},{name:"role",label:"Organization role",type:"select",value:"MEMBER",options:allRoles,showPrevious:false},{name:"policyOverride",label:"Deliberately override this organization’s email policy",type:"checkbox",hint:"Leave off to enforce the allowed domains and exact email exceptions."},{name:"reason",label:"Reason for this access change",type:"textarea",required:true,maxLength:500}]}/></Section>}
  {!archived&&query.action==="replace"&&members.some(m=>m.active&&person(state,m.userId)?.active)&&<Section title="Replace all organization owners"><p className={styles.notice}>This replaces all current Org Owners. Every other Org Owner becomes an Admin. To keep existing owners, use Grant organization access above.</p><AdminForm action={replaceOrgOwnersAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,organizationId:id}} disabled={!access.writable} submit="Replace all owners" consequence={"Replace all Org Owners of "+org.name+" with the selected person. Existing other owners become Admins. At least one active Org Owner must remain."} fields={[{name:"userId",label:"New Org Owner",type:"select",value:"",previousLabel:owners.map(m=>person(state,m.userId)?.displayName??"Recorded owner").join(", ")||"No active owner",required:true,options:[{value:"",label:"Choose an active member"},...members.filter(m=>m.active&&person(state,m.userId)?.active).map(m=>({value:m.userId,label:person(state,m.userId)?.displayName??"Recorded member"}))]},{name:"reason",label:"Reason",type:"textarea",required:true,maxLength:500}]}/></Section>}
  <Section title="Platform invitations"><DataTable caption={org.name+" platform invitations"} columns={["Email","Role","State","Expires","Open"]} rows={invites.map(i=>({key:i.id,cells:[i.email,roleLabel(i.role),invitationStatus(i,state.capturedAt),dateLabel(i.expiresAt),<Link prefetch={false} key="invite" href={returnTo+"?invite="+i.id}>Open invitation →</Link>]}))}/>{invites.length?invites.filter(i=>i.id===query.invite).map(invite=><section className={styles.section} key={invite.id}><h3>{invite.email}</h3><p className={styles.summary}>{roleLabel(invite.role)} · {invitationStatus(invite,state.capturedAt)} · expires {dateLabel(invite.expiresAt)}</p>{!archived&&!invite.usedAt&&!invite.revokedAt&&<AdminForm action={platformInvitationAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,invitationId:invite.id}} disabled={!access.writable} submit="Update invitation" fields={[{name:"operation",label:"Invitation action",type:"select",value:"resend",options:[{value:"resend",label:"Resend — replace old link"},{value:"revoke",label:"Revoke invitation"}]},{name:"reason",label:"Reason",type:"textarea",required:true,maxLength:500}]}/>}</section>):<p className={styles.empty}>No platform invitations recorded.</p>}</Section></>);
 }
 if(section==="users"&&!id){
  const q=(query.q??"").toLowerCase();const ids=state.identities.filter(p=>(p.displayName+" "+p.email).toLowerCase().includes(q)&&(!query.organization||state.memberships.some(m=>m.userId===p.id&&m.organizationId===query.organization))&&(!query.role||state.memberships.some(m=>m.userId===p.id&&m.role===query.role&&(!query.organization||m.organizationId===query.organization))));
  return frame(<Section title="Global identities"><Filters query={query} organizationOptions={state.organizations} roles/><p className={styles.summary}>{ids.length} identities. Platform authority is independent from organization membership.</p><DataTable caption="Global identities and memberships" columns={["Person","Platform authority","Organizations","Identity status","Open"]} rows={ids.map(p=>({key:p.id,cells:[<span key="p">{p.displayName}<small>{p.email}</small></span>,p.platformRole?<Badge key="role">Platform Owner · global</Badge>:"No platform role",state.memberships.filter(m=>m.userId===p.id).map(m=><p key={m.id}>{state.organizations.find(o=>o.id===m.organizationId)?.name??"Unavailable organization"} · {roleLabel(m.role)}{!m.active?" · deactivated":""}</p>),p.active?"Active":"Deactivated",<Link prefetch={false} key="open" href={base+"/users/"+p.id}>Open {p.displayName} →</Link>]}))}/></Section>);
 }
 if(section==="users"&&id){
  const identity=person(state,id);if(!identity)notFound();const memberships=state.memberships.filter(m=>m.userId===id);
  return frame(<div className={styles.detailColumns}><div><Section title="Identity"><dl className={styles.details}><div><dt>Email</dt><dd>{identity.email}</dd></div><div><dt>Identity status</dt><dd>{identity.active?"Active":"Deactivated"}</dd></div><div><dt>Platform authority</dt><dd>{identity.platformRole?"Platform Owner · global":"No platform role"}</dd></div></dl></Section><Section title="Organization memberships"><DataTable caption={"Memberships for "+identity.displayName} columns={["Organization","Role","Access","Product Lead","Policy","Manage"]} rows={memberships.map(m=>({key:m.id,cells:[state.organizations.find(o=>o.id===m.organizationId)?.name??"Unavailable organization",roleLabel(m.role),m.active?"Active":"Deactivated",m.isProductLead?"Can finalize reviews":"Standard",m.policyOverride?<span key="override">Recorded override<small>{m.policyOverrideReason??"Reason not recorded"}</small></span>:"Organization policy",<Link prefetch={false} key="org" href={base+"/organizations/"+m.organizationId}>Open organization →</Link>]}))}/><p className={styles.summary}>Grant or change organization roles from the named organization. Deactivation of ordinary members is available in that organization’s Users & Access view. Organization roles never grant platform authority.</p></Section></div><aside className={styles.side}><Section title="Recorded access history"><History events={orderedEvents(state.events.filter(e=>e.targetId===id||memberships.some(m=>m.id===e.targetId)))}/></Section></aside></div>);
 }
 if(section==="policies"&&!id)return frame(<Section title="Organization access policies"><DataTable caption="Email policies by organization" columns={["Organization","Allowed domains","Exact email exceptions","Overrides","Open"]} rows={state.organizations.map(org=>({key:org.id,cells:[org.name,org.emailPolicy.domains.join(", ")||"None",org.emailPolicy.exactEmails.join(", ")||"None",state.memberships.filter(m=>m.organizationId===org.id&&m.policyOverride).length,<Link prefetch={false} key="open" href={base+"/policies/"+org.id}>Open policy →</Link>]}))}/></Section>);
 const org=state.organizations.find(o=>o.id===id);if(!org)notFound();
 return frame(<><Section title={org.name}><p className={styles.summary}>This policy belongs only to {org.name}. An exact email exception does not allow its entire domain.</p><PolicyText policy={org.emailPolicy} selfSignup={Boolean((org as {selfSignup?:boolean}).selfSignup)}/></Section>{org.status!=="ARCHIVED"&&<Section title="Self sign-up"><AdminForm action={selfSignupAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,organizationId:org.id}} disabled={!access.writable} submit="Save self sign-up setting" consequence={(org as {selfSignup?:boolean}).selfSignup?"People with verified addresses allowed by "+org.name+"’s policy will no longer be able to join on their own. Existing members are unchanged.":"People who verify an address allowed by "+org.name+"’s policy can join "+org.name+" on their own, as Member only. Roles above Member still require an administrator."} fields={[{name:"enabled",label:"Allow self sign-up for "+org.name,type:"checkbox",value:(org as {selfSignup?:boolean}).selfSignup?"on":""},{name:"reason",label:"Reason",type:"textarea",required:true,maxLength:500,hint:"Recorded in platform history."}]}/></Section>}{org.status!=="ARCHIVED"&&<Section title="Update access policy"><AdminForm action={configurePolicyAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,organizationId:org.id}} disabled={!access.writable} submit="Save organization policy" consequence={"This changes allowed access for "+org.name+" only. Normal organization invitation and access checks use this policy. Other organizations are unchanged."} fields={[{name:"domains",label:"Allowed domains",type:"textarea",value:org.emailPolicy.domains.join("\n"),hint:"One exact domain per line."},{name:"exactEmails",label:"Exact email exceptions",type:"textarea",value:org.emailPolicy.exactEmails.join("\n"),hint:"One exact address per line."}]}/></Section>}<Section title="Recorded policy and access history"><History events={orderedEvents(state.events.filter(e=>e.organizationId===org.id))}/></Section></>);
}
export async function OrganizationConsole({access,path,query}:{access:Access;path:string[];query:Query}){
 const [state,admin]=await Promise.all([userManagementSnapshot(),readOrganizationAdministration()]);const section=path[0]??"users",id=path[1];if(!["settings","users","policy"].includes(section)||path.length>2||id&&section!=="users")notFound();
 const base="/administration/organization",returnTo=base+"/"+section+(id?"/"+id:""),hidden={returnTo},scopeWorkspaceId=access.ctx.workspaceId,owner=hasOrganizationOwnerAuthority(access.ctx);
 const frame=(content:React.ReactNode,title:string)=><AdminFrame scope="organization" organizationName={state.organizationName} title={title} active={section} description="Manage access within this organization. Platform authority remains separate."><ManagementNotice writable={access.writable}/>{content}</AdminFrame>;
 if(section==="settings")return frame(<div className={styles.detailColumns}><Section title="Workspace"><dl className={styles.details}><div><dt>Organization</dt><dd>{state.organizationName}</dd></div><div><dt>Status</dt><dd>{admin.organization.status}</dd></div><div><dt>Org Owners</dt><dd>{state.members.filter(m=>m.active&&m.role==="ORG_OWNER").map(m=>m.displayName).join(", ")||"Not recorded"}</dd></div></dl>{owner?<AdminForm action={renameWorkspaceAction} scopeWorkspaceId={scopeWorkspaceId} hidden={hidden} disabled={!access.writable} submit="Save workspace name" fields={[{name:"name",label:"Workspace name",value:state.workspaceName,required:true,maxLength:120}]}/>:<p className={styles.notice}>Only an Org Owner or Platform Owner can change the workspace name.</p>}</Section><aside className={styles.side}><h2>Ownership</h2><p className={styles.summary}>At least one active Org Owner is required. Owner assignments are managed through Platform administration.</p></aside></div>,"Organization settings");
 if(section==="policy")return frame(<Section title={state.organizationName+" access policy"}><PolicyText policy={admin.organization.emailPolicy}/><p className={styles.notice}>Managed by Platform administration. Normal invitations enforce these domains and exact email exceptions.</p>{access.ctx.platformRole&&<Link prefetch={false} className={styles.secondary} href={"/administration/platform/policies/"+state.organizationId}>Manage this policy</Link>}</Section>,"Access Policy");
 if(id==="invite")return frame(<Section title="Invite a person"><p className={styles.summary}>Invitations expire in seven days. Acceptance verifies the invited email; no public signup is available.</p><AdminForm action={inviteAction} scopeWorkspaceId={scopeWorkspaceId} hidden={hidden} disabled={!access.writable} submit="Create invitation" cancelHref={base+"/users"} fields={[{name:"email",label:"Email",type:"email",required:true,autoComplete:"email"},{name:"role",label:"Organization role",type:"select",value:"MEMBER",options:roleOptions(owner)}]}/><div className={styles.side}><h3>Allowed in {state.organizationName}</h3><PolicyText policy={admin.organization.emailPolicy}/></div></Section>,"Invite a person");
 if(id){
  const member=state.members.find(m=>m.id===id);if(!member)notFound();const protectedAccount=member.role==="ORG_OWNER"||member.platformRole==="PLATFORM_OWNER",restrictedAdmin=member.role==="ADMIN"&&!owner;
  return frame(<div className={styles.detailColumns}><div><Section title="Membership"><dl className={styles.details}><div><dt>Email</dt><dd>{member.email}</dd></div><div><dt>Organization</dt><dd>{state.organizationName}</dd></div><div><dt>Role</dt><dd>{roleLabel(member.role)}</dd></div><div><dt>Access</dt><dd>{member.active?"Active":"Deactivated"}</dd></div>{member.platformRole&&<div><dt>Platform authority</dt><dd>Platform Owner · global</dd></div>}</dl></Section><Section title="Access controls">{protectedAccount?<p className={styles.notice}>Protected account. Organization ownership and platform identities cannot be changed through normal User Management.</p>:restrictedAdmin?<p className={styles.notice}>Only an Org Owner or Platform Owner can change Admin access.</p>:<AdminForm action={changeMemberAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{...hidden,memberId:member.id}} disabled={!access.writable} submit="Update access" consequence={"This changes "+member.displayName+"’s membership in "+state.organizationName+". Deactivation removes organization access; the global identity and other memberships remain."} fields={[{name:"role",label:"Organization role",type:"select",value:member.role,options:roleOptions(owner)},{name:"active",label:"Organization access",type:"select",value:String(member.active),options:[{value:"true",label:"Active"},{value:"false",label:"Deactivated"}]},{name:"isProductLead",label:"Weekly Review finalization",type:"select",value:String(member.isProductLead),options:[{value:"false",label:"Standard access"},{value:"true",label:"Product Lead capability — Admin / Member"}],hint:"A Viewer cannot receive Product Lead capability."}]}/>}</Section></div><aside className={styles.side}><Section title="Recorded membership history"><History events={orderedEvents(state.events.filter(e=>e.targetId===member.id||e.targetId===member.userId))}/></Section></aside></div>,member.displayName);
 }
 const invitations=query.view==="invitations",q=(query.q??"").toLowerCase();
 return frame(<><Section title="Users & Access" action={<Link prefetch={false} className={styles.primary} href={base+"/users/invite"}>Invite a person</Link>}><nav className={styles.tablinks} aria-label="Access records"><Link prefetch={false} href={base+"/users"} aria-current={!invitations?"page":undefined}>Members ({state.members.length})</Link><Link prefetch={false} href={base+"/users?view=invitations"} aria-current={invitations?"page":undefined}>Invitations ({state.invitations.length})</Link></nav>{invitations?<><DataTable caption="Organization invitations" columns={["Email","Role","State","Expires","Managed by","Open"]} rows={state.invitations.map(i=>({key:i.id,cells:[i.email,roleLabel(i.role),invitationStatus(i,state.capturedAt),dateLabel(i.expiresAt),i.provisionedByPlatform?"Platform administration":"Organization administration",<Link prefetch={false} key="invite" href={base+"/users?view=invitations&invite="+i.id}>Open invitation →</Link>]}))}/>{state.invitations.filter(i=>i.id===query.invite&&!i.usedAt&&!i.revokedAt&&!i.provisionedByPlatform&&(owner||i.role!=="ADMIN")).map(i=><Section key={i.id} title={i.email}><AdminForm action={invitationAction} scopeWorkspaceId={scopeWorkspaceId} hidden={{returnTo:base+"/users?view=invitations",inviteId:i.id}} disabled={!access.writable} submit="Update invitation" fields={[{name:"operation",label:"Invitation action",type:"select",value:"resend",options:[{value:"resend",label:"Resend — replace old link"},{value:"revoke",label:"Revoke invitation"}],hint:"Resend invalidates the previous invitation link."}]}/></Section>)}</>:<><Filters query={query} roles/><DataTable caption={state.organizationName+" members"} columns={["Person","Role","Access","Joined via","Product Lead","Owner protection","Open"]} rows={state.members.filter(m=>(m.displayName+" "+m.email).toLowerCase().includes(q)&&(!query.role||m.role===query.role)).map(m=>({key:m.id,cells:[<span key="person">{m.displayName}<small>{m.email}</small></span>,<Badge key="role">{roleLabel(m.role)}</Badge>,m.active?"Active":"Deactivated",m.joinedVia==="SELF_SIGNUP"?"Self sign-up":m.joinedVia==="INVITATION"?"Invitation":m.joinedVia==="PLATFORM"?"Added by platform owner":"Added by an administrator",m.isProductLead?"Product Lead":"—",m.role==="ORG_OWNER"||m.platformRole==="PLATFORM_OWNER"?"Cannot be removed here":"—",<Link prefetch={false} key="open" href={base+"/users/"+m.id}>Open {m.displayName} →</Link>]}))}/></>}</Section></>,"Users & Access");
}
