import Link from 'next/link';
import {notFound} from 'next/navigation';
import {readDelivery} from '@/lib/delivery/repository';
import {readManagement} from '@/lib/data/management-read';
import {ownerFor} from '@/lib/delivery/model';
import {deriveReadiness} from '@/lib/workspace/readiness';
import {canManageInitiative} from '@/lib/workspace/management-policy';
import {isDemoWriteEnabled} from '@/lib/env';
import {ContextManager} from '@/components/initiative/ContextManager';
import {STAGE_LABEL} from '@/lib/domain/labels';
import {SetupDelivery} from '@/components/initiative/SetupDelivery';
import {SourceMapper} from '@/components/initiative/SourceMapper';
import styles from '@/components/initiative/setup.module.css';
export const dynamic='force-dynamic';
export default async function InitiativeSetup({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{step?:string;created?:string}>}){
 const [{slug},q,d,m]=await Promise.all([params,searchParams,readDelivery(),readManagement()]);
 const snapshot=d.source.snapshots.find(s=>s.initiative.slug===slug);if(!snapshot)notFound();
 const i=snapshot.initiative,owner=ownerFor(d.state.facts,i.id),base=`/initiatives/${slug}`;
 const context=m.contexts.find(c=>c.id===i.currentContextId&&!c.retiredAt)??null,mappings=m.mappings.filter(x=>x.initiativeId===i.id&&!x.unlinkedAt);
 const readiness=deriveReadiness({initiative:{...i,workspaceId:d.ctx.workspaceId},facts:d.state.facts,members:d.source.members,claims:snapshot.claims,currentContext:context,activeSourceLinks:mappings.length});
 const step=['delivery','sources','review'].includes(q.step??'')?q.step!:'review',position=step==='delivery'?2:step==='sources'?3:4;
 const titles={delivery:'Delivery context',sources:'Map sources',review:'Review setup'};
 const links=[['basics','Basics',`${base}/manage?section=basics`],['delivery','Delivery context',`${base}/setup?step=delivery`],['sources','Sources',`${base}/setup?step=sources`],['review','Review',`${base}/setup?step=review`]];
 const steps=links.map(([id,label,href],index)=><li key={id}><Link prefetch={false} href={href!} aria-current={step===id?'step':undefined}>{index+1} · {label}</Link></li>);
 return <div className={styles.page}><header className={styles.heading}>{q.created==='1'&&<p role="status">{i.name} was created with its primary owner. Setup continues below.</p>}<h2>{titles[step as keyof typeof titles]}</h2><p>{readiness.label} · {readiness.completed} of {readiness.total} setup requirements. Setup coverage does not replace open attention or release approval.</p></header><ol className={styles.steps} aria-label="Initiative setup">{steps}</ol><details className={styles.mobileSteps}><summary>Step {position} of 4 · {titles[step as keyof typeof titles]} · Steps</summary><ol>{steps}</ol></details>
 <div className={styles.layout}><div>{i.archivedAt?<p>Archived initiatives are read-only. An administrator can restore this record in Manage initiative.</p>:step==='delivery'?<><h3>Current scope / phase</h3><ContextManager slug={slug} updatedAt={i.updatedAt} currentId={i.currentContextId??null} contexts={m.contexts.filter(c=>c.initiativeId===i.id)} editable={isDemoWriteEnabled&&canManageInitiative(d.ctx,'CONTEXT',owner)} legacy={d.state.facts.find(f=>f.initiativeId===i.id&&f.kind==='SCOPE'&&f.state==='SET')?.value.text??null}/><SetupDelivery key={i.currentContextId??'none'} slug={slug} updatedAt={i.updatedAt} facts={d.state.facts.filter(f=>f.initiativeId===i.id)} contextLabel={context?.label??null} editable={isDemoWriteEnabled&&canManageInitiative(d.ctx,'DELIVERY',owner)}/></>:step==='sources'?<><p>Map the references that explain this initiative. A manual reference is not a live connection; add its content before treating it as evidence.</p>{isDemoWriteEnabled&&canManageInitiative(d.ctx,'SOURCE_LINK',owner)&&<SourceMapper slug={slug} name={i.name}/>}<ul>{mappings.map(mapping=>{const item=m.items.find(x=>x.id===mapping.itemId);return item?<li key={mapping.id}><Link href={`/sources/${item.id}`}>{item.name}</Link> · {item.reference} · Manual reference</li>:null;})}</ul><div className={styles.footer}><Link href={`${base}/sources/new`}>Add evidence content</Link><Link href={`${base}/manage?section=sources`}>Manage source mappings</Link></div><p className={styles.hint}>Existing free-text references: {i.knownReferences||'None recorded'}. Unmapped references do not count as linked sources.</p></>:<><h3>{readiness.ready?'Setup complete':'What remains to complete setup'}</h3><p className={styles.hint}>{readiness.ready?'Enough context is recorded to begin deeper analysis. Open items still appear in Attention.':'Complete the missing context or record an explicit unknown where supported. Existing checks continue.'}</p><ul className={styles.checklist}>{[...readiness.requirements].sort((a,b)=>Number(a.met)-Number(b.met)).map(r=><li key={r.key}><strong className={r.met?styles.recorded:styles.missing}>{r.met?(r.detail==='Explicitly unknown'?'Unknown · recorded':'✓ Recorded'):'○ Not yet'}</strong><div><strong>{r.label}</strong><p className={styles.hint}>{r.key==='stage'?STAGE_LABEL[i.stage]:r.detail}</p></div>{r.met?null:<Link href={r.href}>Complete {r.label.charAt(0).toLowerCase()+r.label.slice(1)}</Link>}</li>)}</ul></>}</div><aside className={styles.rail}><strong>{readiness.ready?'Next: open the Brief':'Next meaningful step'}</strong><p>{readiness.next?.detail??'Review evidence, decisions and current commitments in context.'}</p>{readiness.next&&<Link href={readiness.next.href}>{readiness.next.label} →</Link>}</aside></div>
 <footer className={styles.footer}><Link prefetch={false} href={base}>Save and continue later · Back to Brief</Link><Link prefetch={false} href={step==='delivery'?`${base}/setup?step=sources`:step==='sources'?`${base}/setup?step=review`:base}>{step==='delivery'?'Continue to Sources →':step==='sources'?'Review setup →':'Open Brief →'}</Link></footer></div>;
}
