import test from 'node:test';import assert from 'node:assert/strict';import {extractEvidence,modelJson} from './extract.ts';
test('Evidence reading reports provider failure instead of inventing a template or accepting partial output',async()=>{const key=process.env.ANTHROPIC_API_KEY,model=process.env.ANTHROPIC_MODEL;try{process.env.ANTHROPIC_API_KEY='local-test-placeholder';process.env.ANTHROPIC_MODEL='test-model';await assert.rejects(extractEvidence('Synthetic receipt',async()=>new Response('{}',{status:503})),/PROVIDER_FAILED/);await assert.rejects(extractEvidence('Synthetic receipt',async()=>Response.json({stop_reason:'max_tokens',content:[{type:'text',text:'{}'}]})),/INCOMPLETE_RESPONSE/);process.env.ANTHROPIC_API_KEY='';await assert.rejects(extractEvidence('Synthetic receipt'),/NOT_CONFIGURED/);}finally{if(key===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=key;if(model===undefined)delete process.env.ANTHROPIC_MODEL;else process.env.ANTHROPIC_MODEL=model;}});
test('Evidence provider output is filtered before returning accepted proposals',async()=>{const key=process.env.ANTHROPIC_API_KEY,model=process.env.ANTHROPIC_MODEL;try{process.env.ANTHROPIC_API_KEY='local-test-placeholder';process.env.ANTHROPIC_MODEL='test-model';const response=await extractEvidence('Keep receipt',async()=>Response.json({stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify({proposals:[{type:'REQUIREMENT',quote:'Keep receipt',payload:{subject:'Receipt',attribute:'behavior',value:'Keep receipt',domain:'PRODUCT',phase:null}},{type:'OWNER',quote:'Keep receipt',payload:{subject:'Receipt',attribute:'behavior',value:'Keep receipt',domain:'PRODUCT',phase:null}}]})}]}));assert.equal(response.accepted.length,1);assert.equal(response.discarded,1);}finally{if(key===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=key;if(model===undefined)delete process.env.ANTHROPIC_MODEL;else process.env.ANTHROPIC_MODEL=model;}});
test('Model JSON is read whether bare, fenced or wrapped in prose; non-JSON still fails honestly',async()=>{const key=process.env.ANTHROPIC_API_KEY,model=process.env.ANTHROPIC_MODEL;try{process.env.ANTHROPIC_API_KEY='local-test-placeholder';process.env.ANTHROPIC_MODEL='test-model';
 const text='Requirement: Refund confirmations must reach merchants within 5 minutes.';
 const body=JSON.stringify({proposals:[{type:'REQUIREMENT',payload:{subject:'Refund confirmations',attribute:'delivery time',value:'within 5 minutes',domain:'OPERATIONS',phase:null},anchor:{quote:'Refund confirmations must reach merchants within 5 minutes'}}]});
 for(const wrapped of [body,'```json\n'+body+'\n```','Here are the proposals:\n'+body]){const r=await extractEvidence(text,async()=>Response.json({stop_reason:'end_turn',content:[{type:'text',text:wrapped}]}));assert.equal(r.model,'test-model');assert.ok(Array.isArray(r.accepted));}
 assert.deepEqual(modelJson('```\n{"a":1}\n```'),{a:1});assert.equal(modelJson('no json here'),undefined);
 await assert.rejects(extractEvidence(text,async()=>Response.json({stop_reason:'end_turn',content:[{type:'text',text:'I cannot help.'}]})),/READING_FAILED/);
}finally{if(key===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=key;if(model===undefined)delete process.env.ANTHROPIC_MODEL;else process.env.ANTHROPIC_MODEL=model;}});
