import test from 'node:test';import assert from 'node:assert/strict';import {filterCandidates,cosmeticPayload} from './filter.ts';
const payload={subject:'Pilot',attribute:'requirement',value:'Keep receipt',domain:'PRODUCT' as const,phase:null};
test('Evidence filtering drops invented, unanchored and ownership/stage proposals; a verbatim open question is kept (P1)',()=>{const result=filterCandidates('Keep receipt',[{type:'REQUIREMENT',payload,quote:'Keep receipt'},{type:'OWNER',payload,quote:'Keep receipt'},{type:'STAGE',payload,quote:'Keep receipt'},{type:'OPEN_QUESTION',payload,quote:'Keep receipt'},{type:'RISK',payload:{...payload,value:'Launch approved'},quote:'Keep receipt'},{type:'RISK',payload,quote:'invented quote'}]);assert.deepEqual(result.accepted.map(a=>a.type),['REQUIREMENT','OPEN_QUESTION']);assert.equal(result.discarded,4);});
test('Delivery dates must occur exactly in supporting quote; material edits cannot keep AI provenance',()=>{const p={...payload,value:'2026-10-07',factKind:'TARGET_LIVE',date:'2026-10-07'};assert.equal(filterCandidates('Target: early October',[{type:'DELIVERY',payload:p,quote:'Target: early October'}]).accepted.length,0);assert.ok(cosmeticPayload(payload,{...payload,value:' Keep   receipt. '}));assert.equal(cosmeticPayload(payload,{...payload,value:'Discard receipt'}),false);});

const notes='Steering sync. Open: who signs off the fee table? Change: settlement cutoff 18:00.';
const offered=[{ref:'K1',id:'c1',updatedAt:'2026-10-01T10:00:00Z',type:'REQUIREMENT',status:'ACTIVE',subject:'Settlement',attribute:'cutoff',value:'17:00',domain:'OPERATIONS' as const,phase:'Phase 1'},{ref:'K2',id:'c2',updatedAt:'2026-10-01T10:00:00Z',type:'REQUIREMENT',status:'SUPERSEDED',subject:'Old',attribute:'rule',value:'x',domain:'PRODUCT' as const,phase:null}];
test('Meeting reading: a changed requirement takes subject, attribute, domain and phase from the named existing claim, never from AI',()=>{
 const r=filterCandidates(notes,[{type:'CHANGED_REQUIREMENT',quote:'settlement cutoff 18:00',payload:{target:'K1',value:'18:00',subject:'Invented subject',attribute:'invented',domain:'FINANCE',phase:null}}],offered);
 assert.equal(r.accepted.length,1);const p=r.accepted[0]!.payload;assert.equal(p.subject,'Settlement');assert.equal(p.attribute,'cutoff');assert.equal(p.domain,'OPERATIONS');assert.equal(p.phase,'Phase 1');assert.equal(p.targetClaimId,'c1');assert.equal(p.targetClaimUpdatedAt,'2026-10-01T10:00:00Z');});
test('Meeting reading: unknown, superseded or unchanged targets and unanchored questions are discarded',()=>{
 const r=filterCandidates(notes,[{type:'CHANGED_REQUIREMENT',quote:'settlement cutoff 18:00',payload:{target:'K9',value:'18:00',phase:null}},{type:'CHANGED_REQUIREMENT',quote:'settlement cutoff 18:00',payload:{target:'K2',value:'18:00',phase:null}},{type:'CHANGED_REQUIREMENT',quote:'settlement cutoff 18:00',payload:{target:'K1',value:'17:00',phase:null}},{type:'OPEN_QUESTION',quote:'who approves pricing?',payload:{subject:'Pricing',attribute:'question',value:'who approves pricing?',domain:'FINANCE',phase:null}},{type:'OPEN_QUESTION',quote:'who signs off the fee table?',payload:{subject:'Fee table',attribute:'question',value:'who signs off the fee table?',domain:'FINANCE',phase:null}}],offered);
 assert.deepEqual(r.accepted.map(a=>a.type),['OPEN_QUESTION']);assert.equal(r.accepted[0]!.payload.attribute,'question');assert.equal(r.discarded,4);});
