import 'server-only';
import {validateApplicability} from '../review/applicability';
import {currentApplicability} from '../data/applicability-revision';
import {randomUUID} from 'node:crypto';
import {requireWorkspaceAccess,requireBusinessWriteAccess} from '../auth/access';
import {isLocalAuth,adminClient,configuredWorkspaceId} from '../auth/service';
import {withRepositoryContext} from '../auth/repository-context';
import {readStore,writeStoreAtomic,writeStoreWithDelivery,type StoreShape} from '../data/store';
import {readDeliveryFresh,withLocalOwnerLock} from '../delivery/repository';
import {localDeliveryPath} from '../delivery/local-path';
import {factFor,ownerFor,recordFact} from '../delivery/model';
import {reviseCommitment} from '../workspace/commitments';
import {canManageInitiative} from '../workspace/management-policy';
import {mapSourceItems} from '../workspace/source-mapping';
import {normalizeSubmission,sha256Utf8,verifyAnchor,hasLoneSurrogate} from './anchor';
import {extractEvidence,EVIDENCE_PROMPT_VERSION} from './extract';
import {cosmeticPayload} from './filter';
import type {Submission,EvidenceState,ProposalPayload} from './types';

const now=()=>new Date().toISOString();
function scopedInitiative(s:StoreShape,id:string,workspaceId:string,write=false){const i=s.initiatives.find(i=>i.id===id&&i.workspaceId===workspaceId);if(!i)throw Error('Evidence unavailable in this organization.');if(write&&i.archivedAt)throw Error('Archived — restore to edit. Nothing was changed.');return i;}
function state(s:StoreShape,initiativeId:string):EvidenceState{return {submissions:(s.evidenceSubmissions??[]).filter(x=>x.initiativeId===initiativeId),attempts:(s.evidenceAttempts??[]).filter(x=>x.initiativeId===initiativeId),anchors:(s.evidenceAnchors??[]).filter(x=>x.initiativeId===initiativeId),proposals:(s.evidenceProposals??[]).filter(x=>x.initiativeId===initiativeId),confirmations:(s.evidenceConfirmations??[]).filter(x=>x.initiativeId===initiativeId)};}
async function rpc(command:string,args:Record<string,unknown>){const ctx=await requireBusinessWriteAccess();const {data,error}=await adminClient().rpc(command,{p_workspace_id:ctx.workspaceId,p_member_id:ctx.memberId??ctx.actor.id,...args});if(error)throw Error(error.message.includes('STALE')?'This evidence proposal changed. Review the current version; nothing was overwritten.':'Evidence command was refused. Check your access and try again.');return data;}
export async function controlEvidence(submissionId:string,operation:'STOP'|'REPROPOSE',proposalId?:string):Promise<void>{
 const ctx=await requireBusinessWriteAccess();if(!isLocalAuth()){await rpc('control_anchored_evidence',{p_submission_id:submissionId,p_operation:operation,p_proposal_id:proposalId??null});return;}await withRepositoryContext(ctx,async()=>withLocalOwnerLock(ctx,delivery=>writeStoreAtomic(s=>{const sub=s.evidenceSubmissions?.find(x=>x.id===submissionId&&x.workspaceId===ctx.workspaceId);if(!sub)throw Error('Evidence unavailable.');scopedInitiative(s,sub.initiativeId,ctx.workspaceId,true);if(operation==='STOP'){for(const a of s.evidenceAttempts??[])if(a.submissionId===sub.id&&a.workspaceId===ctx.workspaceId&&a.status==='READING'){a.status='STOPPED';a.endedAt=now();}return;}const p=s.evidenceProposals?.find(p=>p.id===proposalId&&p.submissionId===sub.id&&p.workspaceId===ctx.workspaceId);if(!p||p.type!=='DELIVERY'||p.status!=='OUTDATED')throw Error('Only an outdated delivery proposal can be proposed again.');if(!canManageInitiative(ctx,'DELIVERY',ownerFor(delivery.facts,p.initiativeId)))throw Error('Your role cannot propose this delivery update.');const anchor=s.evidenceAnchors?.find(a=>a.id===p.anchorId);if(!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('Anchor unavailable.');(s.evidenceProposals??=[]).push({...p,id:randomUUID(),version:1,baseRevision:factFor(delivery.facts,p.initiativeId,p.payload.factKind!)?.revision??0,status:'PENDING',decidedAt:null,decidedBy:null,reason:null,resultType:null,resultId:null});})));
}
export async function readEvidence(initiativeId:string):Promise<EvidenceState>{const ctx=await requireWorkspaceAccess();let result:EvidenceState;if(isLocalAuth())result=await withRepositoryContext(ctx,async()=>{const s=readStore();scopedInitiative(s,initiativeId,ctx.workspaceId);return structuredClone(state(s,initiativeId));});else{const {data,error}=await adminClient().rpc('read_anchored_evidence',{p_workspace_id:ctx.workspaceId,p_member_id:ctx.memberId??ctx.actor.id,p_initiative_id:initiativeId});if(error)throw Error('Evidence unavailable.');result=data;}return {...result,attempts:result.attempts.map(a=>a.status==='READING'&&Date.now()-Date.parse(a.startedAt)>60_000?{...a,status:'TIMED_OUT',errorCode:'READING_EXPIRED'}:a)};}
export async function submitEvidence(input:{initiativeId:string;workspaceId:string;title:string;text:string;sourceItemId:string|null;requestId:string}):Promise<string>{
 const ctx=await requireBusinessWriteAccess();if(ctx.workspaceId!==input.workspaceId)throw Error('Your organization changed. Reload before saving.');const text=normalizeSubmission(input.text),title=input.title.trim();if(hasLoneSurrogate(text)||!text.trim()||text.length>20000||!title||title.length>200||!/^[0-9a-f-]{36}$/i.test(input.requestId))throw Error('Enter a title and 1–20,000 characters of evidence.');
 if(!isLocalAuth())return String(await rpc('submit_anchored_evidence',{p_input:{...input,text,title,textSha256:sha256Utf8(text),charLength:text.length}}));
 return withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{scopedInitiative(s,input.initiativeId,ctx.workspaceId,true);const previous=s.evidenceSubmissions?.find(x=>x.workspaceId===ctx.workspaceId&&x.requestId===input.requestId);if(previous){if(previous.createdBy!==ctx.actor.id||previous.text!==text||previous.title!==title||previous.initiativeId!==input.initiativeId)throw Error('This submission request was already used.');return previous.id;}
 const id=randomUUID(),at=now();let itemId=input.sourceItemId;
 if(itemId){if(!s.sourceMappings?.some(m=>m.workspaceId===ctx.workspaceId&&m.initiativeId===input.initiativeId&&m.itemId===itemId&&!m.unlinkedAt))throw Error('Choose a currently linked source in this initiative.');}
 else{const library=mapSourceItems({containers:s.sourceContainers??[],items:s.sourceItems??[],mappings:s.sourceMappings??[],events:[]},ctx,{initiativeId:input.initiativeId,provider:'PASTED_EVIDENCE',providerWorkspace:ctx.workspaceId,containerReference:'pasted-evidence',containerName:'Saved pasted evidence',role:'GENERAL',items:[{reference:id,name:title,kind:'PASTED',url:null}]},at);s.sourceContainers=library.containers;s.sourceItems=library.items;s.sourceMappings=library.mappings;itemId=library.items.find(x=>x.reference===id)!.id;}
 const evidenceId=randomUUID();s.evidence.push({id:evidenceId,initiativeId:input.initiativeId,title,sourceType:'DOCUMENT',sourceId:null,sourceReference:id,sourceUrl:null,contentSummary:text,boundary:'CURRENT_SCOPE',occurredAt:null,capturedAt:at,lastVerifiedAt:null,createdBy:ctx.actor.id,createdAt:at,updatedAt:at});
 const submission:Submission={id,workspaceId:ctx.workspaceId,organizationId:ctx.organizationId,initiativeId:input.initiativeId,sourceItemId:itemId!,evidenceId,kind:'PASTED',title,text,textSha256:sha256Utf8(text),charLength:text.length,createdBy:ctx.actor.id,createdAt:at,requestId:input.requestId};(s.evidenceSubmissions??=[]).push(submission);s.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:input.initiativeId,eventType:'EVIDENCE_SAVED',summary:`Evidence saved: ${title}. No product facts confirmed.`,occurredAt:at,entityType:'EVIDENCE',entityId:evidenceId,actorLabel:ctx.actor.label,payload:{submissionId:id,sourceItemId:itemId}});return id;}));
}
export async function readWithAI(submissionId:string,requestId:string):Promise<void>{
 const ctx=await requireBusinessWriteAccess();let submission:Submission;let attemptId:string;
 if(isLocalAuth()){const started=await withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{const sub=s.evidenceSubmissions?.find(x=>x.id===submissionId&&x.workspaceId===ctx.workspaceId);if(!sub)throw Error('Evidence unavailable.');scopedInitiative(s,sub.initiativeId,ctx.workspaceId,true);const prior=s.evidenceAttempts?.find(a=>a.submissionId===submissionId&&a.requestId===requestId);if(prior)return {submission:sub,attemptId:prior.id,replay:true};const id=randomUUID();(s.evidenceAttempts??=[]).push({id,workspaceId:ctx.workspaceId,initiativeId:sub.initiativeId,submissionId,requestId,status:'READING',startedAt:now(),endedAt:null,errorCode:null,model:null,promptVersion:EVIDENCE_PROMPT_VERSION,discardedCount:0});return {submission:structuredClone(sub),attemptId:id,replay:false};}));if(started.replay)return;submission=started.submission;attemptId=started.attemptId;}
 else{const started=await rpc('start_evidence_attempt',{p_submission_id:submissionId,p_request_id:requestId});if(started.replay)return;submission=started.submission;attemptId=started.attemptId;}
 const d=await readDeliveryFresh();
 let output:Awaited<ReturnType<typeof extractEvidence>>|null=null,errorCode:string|null=null;try{output=await extractEvidence(submission.text);}catch(e){errorCode=e instanceof Error&&e.name==='TimeoutError'?'TIMED_OUT':e instanceof Error&&e.message==='NOT_CONFIGURED'?'NOT_CONFIGURED':'READING_FAILED';}
 const completionCtx=await requireBusinessWriteAccess();if(completionCtx.workspaceId!==ctx.workspaceId)throw Error('Organization context changed while reading. Your evidence remains saved.');
 const candidates=output?.accepted.map(c=>({...c,baseRevision:c.type==='DELIVERY'?factFor(d.state.facts,submission.initiativeId,c.payload.factKind!)?.revision??0:0}))??[];
 if(!isLocalAuth()){await rpc('finish_evidence_attempt',{p_attempt_id:attemptId,p_result:{candidates,model:output?.model??null,discardedCount:output?.discarded??0,errorCode}});return;}
 await withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{scopedInitiative(s,submission.initiativeId,ctx.workspaceId,true);const attempt=s.evidenceAttempts?.find(a=>a.id===attemptId&&a.workspaceId===ctx.workspaceId);if(!attempt||attempt.status!=='READING')return;for(const c of candidates){if(!verifyAnchor(submission.text,c.anchor,submission.textSha256))continue;const anchorId=randomUUID();(s.evidenceAnchors??=[]).push({id:anchorId,workspaceId:ctx.workspaceId,initiativeId:submission.initiativeId,submissionId,...c.anchor});(s.evidenceProposals??=[]).push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:submission.initiativeId,submissionId,attemptId,anchorId,type:c.type,payload:c.payload,version:1,baseRevision:c.baseRevision,status:'PENDING',decidedBy:null,decidedAt:null,reason:null,resultType:null,resultId:null});}attempt.status=errorCode==='TIMED_OUT'?'TIMED_OUT':errorCode?'FAILED':'READY';attempt.endedAt=now();attempt.errorCode=errorCode;attempt.model=output?.model??null;attempt.discardedCount=output?.discarded??0;}));
}
export async function decideProposal(input:{id:string;version:number;requestId:string;operation:'CONFIRM'|'REJECT'|'EDIT'|'HUMAN_ENTRY';reason:string;payload?:ProposalPayload;assigneeMemberId?:string|null;dueDate?:string|null;contextId?:string|null;effectiveDate?:string|null}):Promise<{type:string;id:string}|null>{
 if(!['CONFIRM','REJECT','EDIT','HUMAN_ENTRY'].includes(input.operation)||!Number.isInteger(input.version)||!/^[0-9a-f-]{36}$/i.test(input.requestId)||input.reason.length>2000)throw Error('Invalid proposal command.');
 const ctx=await requireBusinessWriteAccess();const d=await readDeliveryFresh();
 if(!isLocalAuth()){
  const {data:row,error}=await adminClient().from('evidence_proposals').select('data').eq('workspace_id',ctx.workspaceId).eq('id',input.id).maybeSingle();if(error||!row)throw Error('Proposal unavailable.');const proposal=row.data as import('./types').Proposal;
  const applies=await currentApplicability(proposal.initiativeId,input);
  let deliveryCommand:Record<string,unknown>|undefined;
  if(input.operation==='CONFIRM'&&proposal.type==='DELIVERY'&&proposal.status==='PENDING'){
   const evidence=await readEvidence(proposal.initiativeId),sub=evidence.submissions.find(s=>s.id===proposal.submissionId)!,anchor=evidence.anchors.find(a=>a.id===proposal.anchorId)!;
   if(!sub||!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('The evidence anchor could not be verified.');
   if((factFor(d.state.facts,proposal.initiativeId,proposal.payload.factKind!)?.revision??0)!==proposal.baseRevision){await rpc('control_anchored_evidence',{p_submission_id:sub.id,p_operation:'MARK_OUTDATED',p_proposal_id:proposal.id});throw Error('The delivery fact changed. Propose again from the current record.');}
   const next=recordFact(d.state,d.source,ctx,{initiativeId:proposal.initiativeId,...applies,kind:proposal.payload.factKind!,expectedRevision:proposal.baseRevision,value:{date:proposal.payload.date??null,text:proposal.payload.factKind==='NEXT_MILESTONE'?proposal.payload.value:null,memberId:null,extent:proposal.payload.extent??null},retract:false,basis:'EVIDENCE',note:input.reason.trim()||`From saved evidence: ${sub.title}`,evidenceId:sub.evidenceId,locator:`UTF16 ${anchor.start}–${anchor.end}`},now());
   deliveryCommand={expectedSource:d.rawSource,expectedState:d.state,nextState:next};
  }
  return rpc('decide_evidence_proposal',{p_input:{...input,delivery:deliveryCommand}});
 }
 return withRepositoryContext(ctx,async()=>withLocalOwnerLock(ctx,delivery=>{const s=readStore();const foundProposal=s.evidenceProposals?.find(p=>p.id===input.id&&p.workspaceId===ctx.workspaceId);if(!foundProposal)throw Error('Proposal unavailable.');let p:import('./types').Proposal=foundProposal;const initiative=scopedInitiative(s,p.initiativeId,ctx.workspaceId,true);const receipt=s.evidenceConfirmations?.find(c=>c.proposalId===p.id);if(receipt){if(receipt.requestId!==input.requestId)throw Error(`Already confirmed by ${receipt.actorLabel}. Open the existing record.`);return {type:receipt.resultType,id:receipt.resultId};}if(p.status!=='PENDING'||p.version!==input.version)throw Error('This proposal changed. Your input is retained; review the current record.');const sub=s.evidenceSubmissions?.find(x=>x.id===p.submissionId&&x.workspaceId===ctx.workspaceId),anchor=s.evidenceAnchors?.find(x=>x.id===p.anchorId&&x.workspaceId===ctx.workspaceId);if(!sub||!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('The evidence anchor could not be verified. Nothing was changed.');
 if(p.type==='DELIVERY'&&!canManageInitiative(ctx,'DELIVERY',ownerFor(delivery.facts,p.initiativeId)))throw Error('Only the initiative owner or administration may decide delivery proposals.');
 if((input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY')&&p.type==='DELIVERY'&&(factFor(delivery.facts,p.initiativeId,p.payload.factKind!)?.revision??0)!==p.baseRevision){writeStoreAtomic(current=>{const stale=current.evidenceProposals!.find(x=>x.id===p.id)!;if(stale.status==='PENDING'&&stale.version===input.version){stale.status='OUTDATED';stale.version++;}});throw Error('The delivery fact changed since this proposal was read. Propose again from the current record.');}
 if(input.operation==='HUMAN_ENTRY'&&p.type==='DELIVERY')throw Error('Use the delivery editor for your own confirmed delivery entry.');
 if(input.operation==='HUMAN_ENTRY'&&(!input.payload?.value.trim()||input.payload.value.length>4000||!input.reason.trim()))throw Error('Your own entry needs a value and a reason.');
 const applies=validateApplicability(input,s.contexts??[],ctx.workspaceId,initiative.id);const isOwn=input.operation==='HUMAN_ENTRY';if(isOwn)p={...p,payload:input.payload!};
 const at=now();if(input.operation==='EDIT'&&(!input.payload||!cosmeticPayload(p.payload,input.payload)))throw Error('This changes the meaning. Add your own entry without AI provenance instead.');
 let nextDelivery=delivery,result:{type:string;id:string}|null=null;
 if((input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY')&&p.type==='DELIVERY'){nextDelivery=recordFact(delivery,d.source,ctx,{initiativeId:initiative.id,...applies,kind:p.payload.factKind!,expectedRevision:p.baseRevision,value:{date:p.payload.date??null,text:p.payload.factKind==='NEXT_MILESTONE'?p.payload.value:null,memberId:null,extent:p.payload.extent??null},retract:false,basis:isOwn?'DIRECT_KNOWLEDGE':'EVIDENCE',note:input.reason.trim()||`From saved evidence: ${sub.title}`,evidenceId:isOwn?null:sub.evidenceId,locator:isOwn?null:`UTF16 ${anchor.start}–${anchor.end}`},at);result={type:'DELIVERY',id:factFor(nextDelivery.facts,initiative.id,p.payload.factKind!)!.id};}
 return writeStoreWithDelivery(localDeliveryPath(process.cwd(),ctx.workspaceId,configuredWorkspaceId()),nextDelivery,current=>{const proposal=current.evidenceProposals!.find(x=>x.id===p.id)!;
  if(input.operation==='EDIT'){proposal.payload=input.payload!;proposal.version++;return null;}
  if((input.operation==='CONFIRM'||isOwn)&&p.type==='ACTION'){const created=reviseCommitment(current.commitments??[],current.commitmentEvents??[],{requestId:input.requestId,expectedRevision:0,title:p.payload.value,assigneeMemberId:input.assigneeMemberId??null,dueDate:input.dueDate??null,status:'OPEN',blockedNote:null,evidenceId:isOwn?null:sub.evidenceId,note:input.reason,origin:isOwn?'HUMAN_ENTRY':'CONFIRMED_AI_PROPOSAL',originRefId:isOwn?null:p.id,originHref:isOwn?null:`/initiatives/${initiative.slug}/evidence/${sub.id}`},ctx,initiative,ownerFor(delivery.facts,initiative.id),d.source.members,[sub.evidenceId],at);(current.commitments??=[]).push(created.action);if(created.event)(current.commitmentEvents??=[]).push(created.event);result={type:'ACTION',id:created.action.id};}
  else if((input.operation==='CONFIRM'||isOwn)&&p.type!=='DELIVERY'&&p.type!=='ACTION'){if(p.type==='OPEN_QUESTION')throw Error('Open question confirmation is not available yet.');const id=randomUUID();current.claims.push({id,initiativeId:initiative.id,...applies,type:p.type,status:'UNVERIFIED',subject:p.payload.subject,attribute:p.payload.attribute,value:p.payload.value,domain:p.payload.domain,phase:p.payload.phase,confidence:null,supersededByClaimId:null,createdBy:ctx.actor.id,createdAt:at,updatedAt:at,origin:'HUMAN_ENTRY',evidenceSubmissionId:isOwn?null:sub.id,evidenceAnchorId:isOwn?null:anchor.id,verifiedAt:null,verifiedActorId:null,verifiedActorLabel:null,verificationBasis:null,verificationNote:null});if(!isOwn)current.claimEvidence.push({claimId:id,evidenceId:sub.evidenceId,createdAt:at,locator:`UTF16 ${anchor.start}–${anchor.end}`,excerpt:anchor.quote});result={type:'KNOWLEDGE',id};}
  proposal.status=input.operation==='REJECT'?'REJECTED':isOwn?'SUPERSEDED_BY_HUMAN_ENTRY':'CONFIRMED';proposal.version++;proposal.decidedAt=at;proposal.decidedBy=ctx.actor.id;proposal.reason=input.reason.trim()||null;proposal.resultType=result?.type??null;proposal.resultId=result?.id??null;if(result)(current.evidenceConfirmations??=[]).push({proposalId:p.id,workspaceId:ctx.workspaceId,initiativeId:initiative.id,proposalVersion:input.version,actorId:ctx.actor.id,actorLabel:ctx.actor.label,at,resultType:result.type,resultId:result.id,requestId:input.requestId});current.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:initiative.id,eventType:isOwn?'AI_PROPOSAL_SUPERSEDED':result?'AI_PROPOSAL_CONFIRMED':'AI_PROPOSAL_REJECTED',summary:result?`Human confirmed ${p.type.toLowerCase()} proposal from ${sub.title}${result.type==='KNOWLEDGE'?' · unverified Knowledge':''}`:`Proposal rejected from ${sub.title}`,occurredAt:at,entityType:result?.type??'EVIDENCE',entityId:result?.id??sub.evidenceId,actorLabel:ctx.actor.label,payload:{proposalId:p.id,submissionId:sub.id,anchorId:anchor.id,receipt:result}});return result;});}));
}
