import 'server-only';
import {validateApplicability} from '../review/applicability';
import {currentApplicability} from '../data/applicability-revision';
import {randomUUID} from 'node:crypto';
import {requireWorkspaceAccess,requireBusinessWriteAccess} from '../auth/access';
import {isLocalAuth,adminClient,configuredWorkspaceId} from '../auth/service';
import {withRepositoryContext} from '../auth/repository-context';
import {readStore,writeStoreAtomic,writeStoreWithDelivery,type StoreShape} from '../data/store';
import {readDeliveryFresh,withLocalOwnerLock} from '../delivery/repository';
import {localDeliveryPath} from '../delivery/local-path';
import {factFor,ownerFor,recordFact} from '../delivery/model';
import {reviseCommitment} from '../workspace/commitments';
import {canManageInitiative} from '../workspace/management-policy';
import {mapSourceItems} from '../workspace/source-mapping';
import {normalizeSubmission,sha256Utf8,verifyAnchor,hasLoneSurrogate} from './anchor';
import {extractEvidence,EVIDENCE_PROMPT_VERSION} from './extract';
import {cosmeticPayload,SUPERSEDABLE,type ReadableClaim} from './filter';
import {reviseQuestion} from '../workspace/questions';
import {relationshipCandidates} from '../workspace/relationships';
import type {Submission,EvidenceState,ProposalPayload} from './types';
import {proposalNoun} from './types';

const now=()=>new Date().toISOString();
function scopedInitiative(s:StoreShape,id:string,workspaceId:string,write=false){const i=s.initiatives.find(i=>i.id===id&&i.workspaceId===workspaceId);if(!i)throw Error('Evidence unavailable in this organization.');if(write&&i.archivedAt)throw Error('Archived — restore to edit. Nothing was changed.');return i;}
function state(s:StoreShape,initiativeId:string):EvidenceState{return {meetings:(s.meetingNotes??[]).filter(x=>x.initiativeId===initiativeId),submissions:(s.evidenceSubmissions??[]).filter(x=>x.initiativeId===initiativeId),attempts:(s.evidenceAttempts??[]).filter(x=>x.initiativeId===initiativeId),anchors:(s.evidenceAnchors??[]).filter(x=>x.initiativeId===initiativeId),proposals:(s.evidenceProposals??[]).filter(x=>x.initiativeId===initiativeId),confirmations:(s.evidenceConfirmations??[]).filter(x=>x.initiativeId===initiativeId)};}
async function rpc(command:string,args:Record<string,unknown>){const ctx=await requireBusinessWriteAccess();const {data,error}=await adminClient().rpc(command,{p_workspace_id:ctx.workspaceId,p_member_id:ctx.memberId??ctx.actor.id,...args});if(error)throw Error(error.message.includes('STALE')?'This evidence proposal changed. Review the current version; nothing was overwritten.':'Evidence command was refused. Check your access and try again.');return data;}
/** STOP answers how many readings it ended (0 when nothing was running); REPROPOSE answers 0. */
export async function controlEvidence(submissionId:string,operation:'STOP'|'REPROPOSE',proposalId?:string):Promise<number>{
 const ctx=await requireBusinessWriteAccess();if(!isLocalAuth()){let running=0;if(operation==='STOP'){const {count}=await adminClient().from('evidence_attempts').select('id',{count:'exact',head:true}).eq('workspace_id',ctx.workspaceId).eq('submission_id',submissionId).eq('data->>status','READING');running=count??0;}await rpc('control_anchored_evidence',{p_submission_id:submissionId,p_operation:operation,p_proposal_id:proposalId??null});return running;}let stopped=0;await withRepositoryContext(ctx,async()=>withLocalOwnerLock(ctx,delivery=>writeStoreAtomic(s=>{const sub=s.evidenceSubmissions?.find(x=>x.id===submissionId&&x.workspaceId===ctx.workspaceId);if(!sub)throw Error('Evidence unavailable.');scopedInitiative(s,sub.initiativeId,ctx.workspaceId,true);if(operation==='STOP'){for(const a of s.evidenceAttempts??[])if(a.submissionId===sub.id&&a.workspaceId===ctx.workspaceId&&a.status==='READING'){a.status='STOPPED';a.endedAt=now();stopped++;}return;}const p=s.evidenceProposals?.find(p=>p.id===proposalId&&p.submissionId===sub.id&&p.workspaceId===ctx.workspaceId);if(!p||p.type!=='DELIVERY'||p.status!=='OUTDATED')throw Error('Only an outdated delivery proposal can be proposed again.');if(!canManageInitiative(ctx,'DELIVERY',ownerFor(delivery.facts,p.initiativeId)))throw Error('Your role cannot propose this delivery update.');const anchor=s.evidenceAnchors?.find(a=>a.id===p.anchorId);if(!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('Anchor unavailable.');(s.evidenceProposals??=[]).push({...p,id:randomUUID(),version:1,baseRevision:factFor(delivery.facts,p.initiativeId,p.payload.factKind!)?.revision??0,status:'PENDING',decidedAt:null,decidedBy:null,reason:null,resultType:null,resultId:null});})));return stopped;
}
export async function readEvidence(initiativeId:string):Promise<EvidenceState>{const ctx=await requireWorkspaceAccess();let result:EvidenceState;if(isLocalAuth())result=await withRepositoryContext(ctx,async()=>{const s=readStore();scopedInitiative(s,initiativeId,ctx.workspaceId);return structuredClone(state(s,initiativeId));});else{const {data,error}=await adminClient().rpc('read_anchored_evidence',{p_workspace_id:ctx.workspaceId,p_member_id:ctx.memberId??ctx.actor.id,p_initiative_id:initiativeId});if(error)throw Error('Evidence unavailable.');result=data;}return {...result,meetings:result.meetings??[],attempts:result.attempts.map(a=>a.status==='READING'&&Date.now()-Date.parse(a.startedAt)>60_000?{...a,status:'TIMED_OUT',errorCode:'READING_EXPIRED'}:a)};}
export const meetingSlug=(title:string)=>title.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'meeting';
export async function submitEvidence(input:{initiativeId:string;workspaceId:string;title:string;text:string;sourceItemId:string|null;requestId:string;meeting?:{date:string;attendees:string|null}|null}):Promise<string>{
 const ctx=await requireBusinessWriteAccess();if(ctx.workspaceId!==input.workspaceId)throw Error('Your organization changed. Reload before saving.');const text=normalizeSubmission(input.text),title=input.title.trim();if(hasLoneSurrogate(text)||!text.trim()||text.length>20000||!title||title.length>200||!/^[0-9a-f-]{36}$/i.test(input.requestId))throw Error('Enter a title and 1–20,000 characters of evidence.');
 const meeting=input.meeting?{date:input.meeting.date,attendees:input.meeting.attendees?.trim()||null}:null;
 if(meeting){if(title.length>160)throw Error('Keep the meeting title under 160 characters.');if(!/^\d{4}-\d{2}-\d{2}$/.test(meeting.date)||Number.isNaN(Date.parse(meeting.date))||new Date(meeting.date).toISOString().slice(0,10)!==meeting.date)throw Error('Add the meeting date so decisions and dates are placed correctly.');if(meeting.attendees&&meeting.attendees.length>500)throw Error('Keep attendees under 500 characters.');}
 if(!isLocalAuth())return String(meeting?await rpc('submit_meeting_notes',{p_input:{...input,text,title,textSha256:sha256Utf8(text),charLength:text.length,meeting}}):await rpc('submit_anchored_evidence',{p_input:{...input,text,title,textSha256:sha256Utf8(text),charLength:text.length}}));
 return withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{scopedInitiative(s,input.initiativeId,ctx.workspaceId,true);const previous=s.evidenceSubmissions?.find(x=>x.workspaceId===ctx.workspaceId&&x.requestId===input.requestId);if(previous){if(previous.createdBy!==ctx.actor.id||previous.text!==text||previous.title!==title||previous.initiativeId!==input.initiativeId)throw Error('This submission request was already used.');return previous.id;}
 const id=randomUUID(),at=now();let itemId=input.sourceItemId;
 if(itemId){if(!s.sourceMappings?.some(m=>m.workspaceId===ctx.workspaceId&&m.initiativeId===input.initiativeId&&m.itemId===itemId&&!m.unlinkedAt))throw Error('Choose a currently linked source in this initiative.');}
 else{const reference=meeting?`meeting:${meeting.date}:${meetingSlug(title)}:${id.slice(0,8)}`:id;const library=mapSourceItems({containers:s.sourceContainers??[],items:s.sourceItems??[],mappings:s.sourceMappings??[],events:[]},ctx,meeting?{initiativeId:input.initiativeId,provider:'MEETING_NOTES',providerWorkspace:ctx.workspaceId,containerReference:'meeting-notes',containerName:'Meeting notes',role:'GENERAL',items:[{reference,name:title,kind:'MEETING_NOTES',url:null}]}:{initiativeId:input.initiativeId,provider:'PASTED_EVIDENCE',providerWorkspace:ctx.workspaceId,containerReference:'pasted-evidence',containerName:'Saved pasted evidence',role:'GENERAL',items:[{reference,name:title,kind:'PASTED',url:null}]},at);s.sourceContainers=library.containers;s.sourceItems=library.items;s.sourceMappings=library.mappings;itemId=library.items.find(x=>x.reference===reference)!.id;}
 const evidenceId=randomUUID();s.evidence.push({id:evidenceId,initiativeId:input.initiativeId,title,sourceType:'DOCUMENT',sourceId:null,sourceReference:id,sourceUrl:null,contentSummary:text,boundary:'CURRENT_SCOPE',occurredAt:null,capturedAt:at,lastVerifiedAt:null,createdBy:ctx.actor.id,createdAt:at,updatedAt:at});
 const submission:Submission={id,workspaceId:ctx.workspaceId,organizationId:ctx.organizationId,initiativeId:input.initiativeId,sourceItemId:itemId!,evidenceId,kind:meeting?'MEETING_NOTES':'PASTED',title,text,textSha256:sha256Utf8(text),charLength:text.length,createdBy:ctx.actor.id,createdAt:at,requestId:input.requestId};(s.evidenceSubmissions??=[]).push(submission);if(meeting)(s.meetingNotes??=[]).push({submissionId:id,workspaceId:ctx.workspaceId,initiativeId:input.initiativeId,title,meetingDate:meeting.date,attendeesText:meeting.attendees,revision:1,createdBy:ctx.actor.id,createdAt:at,updatedBy:ctx.actor.id,updatedAt:at});s.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:input.initiativeId,eventType:meeting?'MEETING_NOTES_SAVED':'EVIDENCE_SAVED',summary:meeting?`Meeting notes added: ${title} (${meeting.date}). No product facts confirmed.`:`Evidence saved: ${title}. No product facts confirmed.`,occurredAt:at,entityType:'EVIDENCE',entityId:evidenceId,actorLabel:ctx.actor.label,payload:{submissionId:id,sourceItemId:itemId,...(meeting?{meetingDate:meeting.date}:{})}});return id;}));
}
export async function readWithAI(submissionId:string,requestId:string):Promise<void>{
 const ctx=await requireBusinessWriteAccess();let submission:Submission;let attemptId:string;
 if(isLocalAuth()){const started=await withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{const sub=s.evidenceSubmissions?.find(x=>x.id===submissionId&&x.workspaceId===ctx.workspaceId);if(!sub)throw Error('Evidence unavailable.');scopedInitiative(s,sub.initiativeId,ctx.workspaceId,true);const prior=s.evidenceAttempts?.find(a=>a.submissionId===submissionId&&a.requestId===requestId);if(prior)return {submission:sub,attemptId:prior.id,replay:true};const id=randomUUID();(s.evidenceAttempts??=[]).push({id,workspaceId:ctx.workspaceId,initiativeId:sub.initiativeId,submissionId,requestId,status:'READING',startedAt:now(),endedAt:null,errorCode:null,model:null,promptVersion:EVIDENCE_PROMPT_VERSION,discardedCount:0});return {submission:structuredClone(sub),attemptId:id,replay:false};}));if(started.replay)return;submission=started.submission;attemptId=started.attemptId;}
 else{const started=await rpc('start_evidence_attempt',{p_submission_id:submissionId,p_request_id:requestId});if(started.replay)return;submission=started.submission;attemptId=started.attemptId;}
 const d=await readDeliveryFresh();
 const offered:ReadableClaim[]=(d.source.snapshots.find(x=>x.initiative.id===submission.initiativeId)?.claims??[]).filter(c=>SUPERSEDABLE.includes(c.status)&&['REQUIREMENT','BUSINESS_RULE','DECISION','ASSUMPTION','DEPENDENCY'].includes(c.type)).slice(0,40).map((c,n)=>({ref:`K${n+1}`,id:c.id,updatedAt:c.updatedAt,type:c.type,status:c.status,subject:c.subject,attribute:c.attribute,value:c.value,domain:c.domain,phase:c.phase}));
 let output:Awaited<ReturnType<typeof extractEvidence>>|null=null,errorCode:string|null=null;try{output=await extractEvidence(submission.text,fetch,{kind:submission.kind,claims:offered});}catch(e){errorCode=e instanceof Error&&e.name==='TimeoutError'?'TIMED_OUT':e instanceof Error&&e.message==='NOT_CONFIGURED'?'NOT_CONFIGURED':'READING_FAILED';}
 const completionCtx=await requireBusinessWriteAccess();if(completionCtx.workspaceId!==ctx.workspaceId)throw Error('Organization context changed while reading. Your evidence remains saved.');
 const accepted=output?[...output.accepted,...relationshipCandidates(output.accepted,d.source.snapshots.filter(x=>!x.initiative.archivedAt).map(x=>x.initiative),submission.initiativeId)]:[];
 const candidates=accepted.map(c=>({...c,baseRevision:c.type==='DELIVERY'?factFor(d.state.facts,submission.initiativeId,c.payload.factKind!)?.revision??0:0}));
 if(!isLocalAuth()){await rpc('finish_evidence_attempt',{p_attempt_id:attemptId,p_result:{candidates,model:output?.model??null,discardedCount:output?.discarded??0,errorCode}});return;}
 await withRepositoryContext(ctx,async()=>writeStoreAtomic(s=>{scopedInitiative(s,submission.initiativeId,ctx.workspaceId,true);const attempt=s.evidenceAttempts?.find(a=>a.id===attemptId&&a.workspaceId===ctx.workspaceId);if(!attempt||attempt.status!=='READING')return;for(const c of candidates){if(!verifyAnchor(submission.text,c.anchor,submission.textSha256))continue;const anchorId=randomUUID();(s.evidenceAnchors??=[]).push({id:anchorId,workspaceId:ctx.workspaceId,initiativeId:submission.initiativeId,submissionId,...c.anchor});(s.evidenceProposals??=[]).push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:submission.initiativeId,submissionId,attemptId,anchorId,type:c.type,payload:c.payload,version:1,baseRevision:c.baseRevision,status:'PENDING',decidedBy:null,decidedAt:null,reason:null,resultType:null,resultId:null});}attempt.status=errorCode==='TIMED_OUT'?'TIMED_OUT':errorCode?'FAILED':'READY';attempt.endedAt=now();attempt.errorCode=errorCode;attempt.model=output?.model??null;attempt.discardedCount=output?.discarded??0;}));
}
export async function decideProposal(input:{id:string;version:number;requestId:string;operation:'CONFIRM'|'REJECT'|'EDIT'|'HUMAN_ENTRY';reason:string;payload?:ProposalPayload;assigneeMemberId?:string|null;dueDate?:string|null;contextId?:string|null;effectiveDate?:string|null}):Promise<{type:string;id:string}|null>{
 if(!['CONFIRM','REJECT','EDIT','HUMAN_ENTRY'].includes(input.operation)||!Number.isInteger(input.version)||!/^[0-9a-f-]{36}$/i.test(input.requestId)||input.reason.length>2000)throw Error('Invalid proposal command.');
 const ctx=await requireBusinessWriteAccess();const d=await readDeliveryFresh();
 if(!isLocalAuth()){
  const {data:row,error}=await adminClient().from('evidence_proposals').select('data').eq('workspace_id',ctx.workspaceId).eq('id',input.id).maybeSingle();if(error||!row)throw Error('Proposal unavailable.');const proposal=row.data as import('./types').Proposal;
  const applies=await currentApplicability(proposal.initiativeId,input);
  let deliveryCommand:Record<string,unknown>|undefined;
  if(input.operation==='CONFIRM'&&proposal.type==='DELIVERY'&&proposal.status==='PENDING'){
   const evidence=await readEvidence(proposal.initiativeId),sub=evidence.submissions.find(s=>s.id===proposal.submissionId)!,anchor=evidence.anchors.find(a=>a.id===proposal.anchorId)!;
   if(!sub||!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('The evidence anchor could not be verified.');
   if((factFor(d.state.facts,proposal.initiativeId,proposal.payload.factKind!)?.revision??0)!==proposal.baseRevision){await rpc('control_anchored_evidence',{p_submission_id:sub.id,p_operation:'MARK_OUTDATED',p_proposal_id:proposal.id});throw Error('The delivery fact changed. Propose again from the current record.');}
   const next=recordFact(d.state,d.source,ctx,{initiativeId:proposal.initiativeId,...applies,kind:proposal.payload.factKind!,expectedRevision:proposal.baseRevision,value:{date:proposal.payload.date??null,text:proposal.payload.factKind==='NEXT_MILESTONE'?proposal.payload.value:null,memberId:null,extent:proposal.payload.extent??null},retract:false,basis:'EVIDENCE',note:input.reason.trim()||`From saved evidence: ${sub.title}`,evidenceId:sub.evidenceId,locator:`UTF16 ${anchor.start}–${anchor.end}`},now());
   deliveryCommand={expectedSource:d.rawSource,expectedState:d.state,nextState:next};
  }
  const decided=await rpc('decide_evidence_proposal',{p_input:{...input,delivery:deliveryCommand}});
  if(decided&&typeof decided==='object'&&'outdated' in decided)throw Error('The Knowledge entry this change targets was edited or superseded after the notes were read. Nothing was changed; review the current entry.');
  return decided;
 }
 return withRepositoryContext(ctx,async()=>withLocalOwnerLock(ctx,delivery=>{const s=readStore();const foundProposal=s.evidenceProposals?.find(p=>p.id===input.id&&p.workspaceId===ctx.workspaceId);if(!foundProposal)throw Error('Proposal unavailable.');let p:import('./types').Proposal=foundProposal;const initiative=scopedInitiative(s,p.initiativeId,ctx.workspaceId,true);const receipt=s.evidenceConfirmations?.find(c=>c.proposalId===p.id);if(receipt){if(receipt.requestId!==input.requestId)throw Error(`Already confirmed by ${receipt.actorLabel}. Open the existing record.`);return {type:receipt.resultType,id:receipt.resultId};}if(p.status!=='PENDING'||p.version!==input.version)throw Error('This proposal changed. Your input is retained; review the current record.');const sub=s.evidenceSubmissions?.find(x=>x.id===p.submissionId&&x.workspaceId===ctx.workspaceId),anchor=s.evidenceAnchors?.find(x=>x.id===p.anchorId&&x.workspaceId===ctx.workspaceId);if(!sub||!anchor||!verifyAnchor(sub.text,anchor,sub.textSha256))throw Error('The evidence anchor could not be verified. Nothing was changed.');
 if(p.type==='DELIVERY'&&!canManageInitiative(ctx,'DELIVERY',ownerFor(delivery.facts,p.initiativeId)))throw Error('Only the initiative owner or administration may decide delivery proposals.');
 if((input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY')&&p.type==='DELIVERY'&&(factFor(delivery.facts,p.initiativeId,p.payload.factKind!)?.revision??0)!==p.baseRevision){writeStoreAtomic(current=>{const stale=current.evidenceProposals!.find(x=>x.id===p.id)!;if(stale.status==='PENDING'&&stale.version===input.version){stale.status='OUTDATED';stale.version++;}});throw Error('The delivery fact changed since this proposal was read. Propose again from the current record.');}
 if(input.operation==='HUMAN_ENTRY'&&p.type==='DELIVERY')throw Error('Use the delivery editor for your own confirmed delivery entry.');
 if(p.type==='RELATIONSHIP'&&(input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY'))throw Error('Record a relationship from its proposal card; it needs a type and a reason.');
 if((input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY')&&p.type==='CHANGED_REQUIREMENT'){const target=s.claims.find(c=>c.id===p.payload.targetClaimId&&c.initiativeId===p.initiativeId);if(!target||target.updatedAt!==p.payload.targetClaimUpdatedAt||!SUPERSEDABLE.includes(target.status)){writeStoreAtomic(current=>{const stale=current.evidenceProposals!.find(x=>x.id===p.id)!;if(stale.status==='PENDING'&&stale.version===input.version){stale.status='OUTDATED';stale.version++;}});throw Error('The Knowledge entry this change targets was edited or superseded after the notes were read. Nothing was changed; review the current entry.');}}
 if(input.operation==='HUMAN_ENTRY'&&(!input.payload?.value.trim()||input.payload.value.length>4000||!input.reason.trim()))throw Error('Your own entry needs a value and a reason.');
 const applies=validateApplicability(input,s.contexts??[],ctx.workspaceId,initiative.id);const isOwn=input.operation==='HUMAN_ENTRY';if(isOwn)p={...p,payload:input.payload!};
 const at=now();if(input.operation==='EDIT'&&(!input.payload||!cosmeticPayload(p.payload,input.payload)))throw Error('This changes the meaning. Add your own entry without AI provenance instead.');
 let nextDelivery=delivery,result:{type:string;id:string}|null=null;
 if((input.operation==='CONFIRM'||input.operation==='HUMAN_ENTRY')&&p.type==='DELIVERY'){nextDelivery=recordFact(delivery,d.source,ctx,{initiativeId:initiative.id,...applies,kind:p.payload.factKind!,expectedRevision:p.baseRevision,value:{date:p.payload.date??null,text:p.payload.factKind==='NEXT_MILESTONE'?p.payload.value:null,memberId:null,extent:p.payload.extent??null},retract:false,basis:isOwn?'DIRECT_KNOWLEDGE':'EVIDENCE',note:input.reason.trim()||`From saved evidence: ${sub.title}`,evidenceId:isOwn?null:sub.evidenceId,locator:isOwn?null:`UTF16 ${anchor.start}–${anchor.end}`},at);result={type:'DELIVERY',id:factFor(nextDelivery.facts,initiative.id,p.payload.factKind!)!.id};}
 return writeStoreWithDelivery(localDeliveryPath(process.cwd(),ctx.workspaceId,configuredWorkspaceId()),nextDelivery,current=>{const proposal=current.evidenceProposals!.find(x=>x.id===p.id)!;
  if(input.operation==='EDIT'){proposal.payload=input.payload!;proposal.version++;return null;}
  if((input.operation==='CONFIRM'||isOwn)&&p.type==='ACTION'){const created=reviseCommitment(current.commitments??[],current.commitmentEvents??[],{requestId:input.requestId,expectedRevision:0,title:p.payload.value,assigneeMemberId:input.assigneeMemberId??null,dueDate:input.dueDate??null,status:'OPEN',blockedNote:null,evidenceId:isOwn?null:sub.evidenceId,note:input.reason,origin:isOwn?'HUMAN_ENTRY':sub.kind==='MEETING_NOTES'?'MEETING':'CONFIRMED_AI_PROPOSAL',originRefId:isOwn?null:p.id,originHref:isOwn?null:`/initiatives/${initiative.slug}/evidence/${sub.id}#proposal-${p.id}`},ctx,initiative,ownerFor(delivery.facts,initiative.id),d.source.members,[sub.evidenceId],at);(current.commitments??=[]).push(created.action);if(created.event)(current.commitmentEvents??=[]).push(created.event);result={type:'ACTION',id:created.action.id};}
  else if((input.operation==='CONFIRM'||isOwn)&&p.type==='OPEN_QUESTION'){const created=reviseQuestion(current.openQuestions??[],current.questionEvents??[],{operation:'CREATE',requestId:input.requestId,expectedRevision:0,question:p.payload.value,ownerMemberId:input.assigneeMemberId??null,dueDate:input.dueDate??null,origin:isOwn?'HUMAN_ENTRY':sub.kind==='MEETING_NOTES'?'MEETING':'CONFIRMED_AI_PROPOSAL',originRefId:isOwn?null:p.id,originHref:isOwn?null:`/initiatives/${initiative.slug}/evidence/${sub.id}#proposal-${p.id}`,originLabel:isOwn?null:sub.title,evidenceId:isOwn?null:sub.evidenceId,evidenceAnchorId:isOwn?null:anchor.id},ctx,initiative,ownerFor(delivery.facts,initiative.id),d.source.members,current.claims,at);(current.openQuestions??=[]).push(created.question);if(created.event)(current.questionEvents??=[]).push(created.event);result={type:'QUESTION',id:created.question.id};}
  else if((input.operation==='CONFIRM'||isOwn)&&p.type!=='DELIVERY'&&p.type!=='ACTION'){const id=randomUUID();const replaced=p.type==='CHANGED_REQUIREMENT'?current.claims.find(c=>c.id===p.payload.targetClaimId)!:null;current.claims.push({id,initiativeId:initiative.id,...applies,type:replaced?replaced.type:p.type as import('../domain/types').ClaimType,status:'UNVERIFIED',subject:p.payload.subject,attribute:p.payload.attribute,value:p.payload.value,domain:p.payload.domain,phase:p.payload.phase,confidence:null,supersededByClaimId:null,createdBy:ctx.actor.id,createdAt:at,updatedAt:at,origin:'HUMAN_ENTRY',evidenceSubmissionId:isOwn?null:sub.id,evidenceAnchorId:isOwn?null:anchor.id,verifiedAt:null,verifiedActorId:null,verifiedActorLabel:null,verificationBasis:null,verificationNote:null});if(!isOwn)current.claimEvidence.push({claimId:id,evidenceId:sub.evidenceId,createdAt:at,locator:`UTF16 ${anchor.start}–${anchor.end}`,excerpt:anchor.quote});if(replaced){replaced.status='SUPERSEDED';replaced.supersededByClaimId=id;replaced.updatedAt=at;current.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:initiative.id,eventType:'CLAIM_SUPERSEDED',summary:`${replaced.subject} · ${replaced.attribute} changed: “${replaced.value}” → “${p.payload.value}” (from ${sub.title}). New entry needs verification.`,occurredAt:at,entityType:'CLAIM',entityId:id,actorLabel:ctx.actor.label,payload:{previousClaimId:replaced.id,submissionId:sub.id,proposalId:p.id}});}result={type:'KNOWLEDGE',id};}
  proposal.status=input.operation==='REJECT'?'REJECTED':isOwn?'SUPERSEDED_BY_HUMAN_ENTRY':'CONFIRMED';proposal.version++;proposal.decidedAt=at;proposal.decidedBy=ctx.actor.id;proposal.reason=input.reason.trim()||null;proposal.resultType=result?.type??null;proposal.resultId=result?.id??null;if(result)(current.evidenceConfirmations??=[]).push({proposalId:p.id,workspaceId:ctx.workspaceId,initiativeId:initiative.id,proposalVersion:input.version,actorId:ctx.actor.id,actorLabel:ctx.actor.label,at,resultType:result.type,resultId:result.id,requestId:input.requestId});current.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:initiative.id,eventType:isOwn?'AI_PROPOSAL_SUPERSEDED':result?'AI_PROPOSAL_CONFIRMED':'AI_PROPOSAL_REJECTED',summary:result?`Human confirmed ${proposalNoun(p.type)} proposal from ${sub.title}${result.type==='KNOWLEDGE'?' · unverified Knowledge':''}`:`Proposal rejected from ${sub.title}`,occurredAt:at,entityType:result?.type??'EVIDENCE',entityId:result?.id??sub.evidenceId,actorLabel:ctx.actor.label,payload:{proposalId:p.id,submissionId:sub.id,anchorId:anchor.id,receipt:result}});return result;});}));
}
/** Title, date and attendees can be corrected; the pasted text never changes.
 * Allowed for the submitter, the initiative owner or administration. */
export async function correctMeeting(input:{submissionId:string;expectedRevision:number;title:string;meetingDate:string;attendeesText:string|null}):Promise<void>{
 const ctx=await requireBusinessWriteAccess();const title=input.title.trim(),attendees=input.attendeesText?.trim()||null;
 if(!title||title.length>160)throw Error('Enter a meeting title up to 160 characters.');if(!/^\d{4}-\d{2}-\d{2}$/.test(input.meetingDate)||new Date(input.meetingDate).toISOString().slice(0,10)!==input.meetingDate)throw Error('Add the meeting date so decisions and dates are placed correctly.');if(attendees&&attendees.length>500)throw Error('Keep attendees under 500 characters.');
 if(!isLocalAuth()){await rpc('correct_meeting_notes',{p_input:{...input,title,attendeesText:attendees}});return;}
 await withRepositoryContext(ctx,async()=>withLocalOwnerLock(ctx,delivery=>writeStoreAtomic(s=>{const m=s.meetingNotes?.find(x=>x.submissionId===input.submissionId&&x.workspaceId===ctx.workspaceId);if(!m)throw Error('Meeting unavailable.');const i=scopedInitiative(s,m.initiativeId,ctx.workspaceId,true);
  if(!(ctx.actor.id===m.createdBy||canManageInitiative(ctx,'DELIVERY',ownerFor(delivery.facts,i.id))))throw Error('Only the person who added these notes, the initiative owner or administration can correct them.');
  if(m.revision!==input.expectedRevision)throw Error(`These meeting details were changed by another person at ${m.updatedAt}. Your correction was not saved; your input is kept.`);
  const before={title:m.title,meetingDate:m.meetingDate,attendeesText:m.attendeesText};if(before.title===title&&before.meetingDate===input.meetingDate&&before.attendeesText===attendees)throw Error('Nothing changed.');
  const at=now();Object.assign(m,{title,meetingDate:input.meetingDate,attendeesText:attendees,revision:m.revision+1,updatedBy:ctx.actor.id,updatedAt:at});
  s.activity.push({id:randomUUID(),workspaceId:ctx.workspaceId,initiativeId:i.id,eventType:'MEETING_NOTES_CORRECTED',summary:`Meeting details corrected: ${before.title} (${before.meetingDate}) → ${title} (${input.meetingDate})`,occurredAt:at,entityType:'EVIDENCE',entityId:m.submissionId,actorLabel:ctx.actor.label,payload:{before,after:{title,meetingDate:input.meetingDate,attendeesText:attendees}}});})));
}
