'use client';
import {useActionState,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ScopeField} from '@/components/auth/WorkspaceScope';
import {canBusinessWrite} from '@/lib/auth/roles';
import type {DeliveryMember,WorkspaceAccess} from '@/lib/delivery/types';
import type {Commitment,CommitmentEvent} from '@/lib/workspace/commitments';
import {canChangeCommitment,ACTION_STATUSES} from '@/lib/workspace/commitment-policy';
import {commitmentAction} from '@/app/initiatives/[slug]/actions/actions';
import styles from './commitments.module.css';
const statusLabel=(s:string)=>s.toLowerCase().replaceAll('_',' ');
export function CommitmentWorkbench({slug,initiativeId,archived,actions,events,members,evidence,ctx,ownerId,writesEnabled,today,selectedId}:{slug:string;initiativeId:string;archived:boolean;actions:Commitment[];events:CommitmentEvent[];members:DeliveryMember[];evidence:{id:string;title:string}[];ctx:WorkspaceAccess;ownerId:string|null;writesEnabled:boolean;today:string;selectedId?:string}){
 const [selection,setSelection]=useState<{row:Commitment|null;requestId:string}|null>(null);const dialog=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null),add=useRef<HTMLButtonElement>(null);
 const canWrite=canBusinessWrite(ctx)&&writesEnabled&&!archived;
 const open=(row:Commitment|null)=>setSelection({row,requestId:crypto.randomUUID()});
 useEffect(()=>{if(selection){dialog.current?.showModal();heading.current?.focus();}},[selection]);
 useEffect(()=>{if(selectedId){const row=actions.find(a=>a.id===selectedId);if(row)setSelection({row,requestId:crypto.randomUUID()});}},[selectedId]);
 const close=()=>{dialog.current?.close();setSelection(null);add.current?.focus();};
 const weekEnd=new Date(today+'T12:00:00Z');weekEnd.setUTCDate(weekEnd.getUTCDate()+(7-weekEnd.getUTCDay())%7);const end=weekEnd.toISOString().slice(0,10);
 const groups=[['Overdue',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate<today)],['Due this week',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate>=today&&a.dueDate<=end)],['Later',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate>end)],['No due date',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&!a.dueDate)]] as const;
 const row=(a:Commitment)=><li key={a.id} className={styles.row}><div><Link prefetch={false} href={`/initiatives/${slug}/actions?action=${a.id}`} onClick={e=>{e.preventDefault();open(a);}}>{a.title}</Link><p>{members.find(m=>m.id===a.assigneeMemberId)?.displayName??'No assignee'} · {a.dueDate?`Due ${a.dueDate}`:'No due date'}{a.blockedNote&&<strong> · Blocked: {a.blockedNote}</strong>}</p><small>{a.origin==='HUMAN_ENTRY'?'Added by hand':`From ${statusLabel(a.origin)}`}</small></div><button type="button" onClick={()=>open(a)}>{statusLabel(a.status)} · Open</button></li>;
 return <div className={styles.page}><header className={styles.heading}><div><p className={styles.eyebrow}>Ownership into action</p><h2>Commitments</h2><p>Commitments from reviews, meetings and decisions — not delivery tickets.</p></div><Link prefetch={false} href={`/initiatives/${slug}`}>Back to Brief</Link></header>{canWrite?<button ref={add} className={styles.primary} type="button" onClick={()=>open(null)}>Add commitment</button>:<p>{archived?'Archived — restore to edit.':!canBusinessWrite(ctx)?'Your role is read-only.':'Changes are disabled in this environment.'}</p>}{actions.length===0&&<p className={styles.empty}>No commitments yet. Commitments you confirm from Weekly Review, meetings or evidence appear here — or add one.</p>}{groups.map(([title,rows])=>rows.length>0&&<section className={styles.group} key={title}><h3>{title} <span>{rows.length}</span></h3><ul>{rows.map(row)}</ul></section>)}<details className={styles.group}><summary>Done & cancelled ({actions.filter(a=>['DONE','CANCELLED'].includes(a.status)).length})</summary><ul>{actions.filter(a=>['DONE','CANCELLED'].includes(a.status)).map(row)}</ul></details>
 {selection&&<dialog ref={dialog} className={styles.dialog} onCancel={e=>{e.preventDefault();close();}} aria-labelledby="commitment-title"><header><h3 id="commitment-title" tabIndex={-1} ref={heading}>{selection.row?'Commitment details':'Add a commitment'}</h3><button type="button" onClick={close}>Close</button></header><CommitmentEditor key={selection.requestId} slug={slug} selection={selection} current={actions.find(a=>a.id===selection.row?.id)} members={members} evidence={evidence} ctx={ctx} ownerId={ownerId} editable={canWrite} onSaved={close}/>{selection.row&&<section><h4>History</h4><ol>{events.filter(e=>e.actionId===selection.row!.id).sort((a,b)=>b.seq-a.seq).map(e=><li key={e.id}>{e.type==='CREATED'?'Recorded':`Changed to ${statusLabel(e.after.status)}`} · {e.actor.label} · <time dateTime={e.at}>{new Date(e.at).toLocaleString()}</time>{e.note&&<p>{e.note}</p>}</li>)}</ol>{selection.row.originHref?.startsWith('/')&&<Link href={selection.row.originHref}>Open original context</Link>}</section>}</dialog>}</div>;
}
function CommitmentEditor({slug,selection,current,members,evidence,ctx,ownerId,editable,onSaved}:{slug:string;selection:{row:Commitment|null;requestId:string};current?:Commitment;members:DeliveryMember[];evidence:{id:string;title:string}[];ctx:WorkspaceAccess;ownerId:string|null;editable:boolean;onSaved:()=>void}){
 const a=selection.row;const [revision,setRevision]=useState(a?.revision??0);const [state,action,pending]=useActionState(commitmentAction,{error:null});const error=useRef<HTMLParagraphElement>(null);useEffect(()=>{if(state.error)error.current?.focus();else if(state.id)onSaved();},[state]);const statusAllowed=editable&&(!a||canChangeCommitment(ctx,a,ownerId,'STATUS')),detailsAllowed=editable&&(!a||canChangeCommitment(ctx,a,ownerId,'DETAILS'));
 return <form action={action} className={styles.form}><ScopeField/><input type="hidden" name="slug" value={slug}/><input type="hidden" name="id" value={a?.id??''}/><input type="hidden" name="requestId" value={selection.requestId}/><input type="hidden" name="revision" value={revision}/>{state.error&&<p ref={error} tabIndex={-1} role="alert" className={styles.error}>{state.error}</p>}{current&&current.revision!==revision&&<aside className={styles.conflict}><strong>Current record: {current.title} · {statusLabel(current.status)}</strong><p>Revision {current.revision}. Your proposed fields remain below.</p><button type="button" onClick={()=>setRevision(current.revision)}>Use current revision for my proposed edit</button></aside>}<fieldset disabled={!statusAllowed||pending}><label>Commitment<input name="title" required maxLength={200} defaultValue={a?.title??''} readOnly={!detailsAllowed}/></label><details open={!a}><summary>Commitment details</summary><label>Assignee<select name="assigneeMemberId" defaultValue={a?.assigneeMemberId??ownerId??''} disabled={!detailsAllowed}><option value="">No assignee</option>{members.filter(m=>m.active&&m.role!=='VIEWER').map(m=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select>{!detailsAllowed&&<input type="hidden" name="assigneeMemberId" value={a?.assigneeMemberId??''}/>}</label><label>Due date · optional<input type="date" name="dueDate" defaultValue={a?.dueDate??''} readOnly={!detailsAllowed}/></label><label>Evidence · optional<select name="evidenceId" defaultValue={a?.evidenceId??''} disabled={!detailsAllowed}><option value="">No linked evidence</option>{evidence.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select>{!detailsAllowed&&<input type="hidden" name="evidenceId" value={a?.evidenceId??''}/>}</label></details><label>Status<select name="status" defaultValue={a?.status??'OPEN'}>{ACTION_STATUSES.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Blocker · optional<textarea name="blockedNote" maxLength={2000} defaultValue={a?.blockedNote??''}/></label><p>Use a blocker only for open work. Clear it before completing or cancelling.</p><label>Change / completion note<textarea name="note" maxLength={2000}/></label><p>Required to cancel or reopen; optional when completing.</p>{statusAllowed&&<button className={styles.primary} type="submit">{pending?'Saving…':a?'Save commitment':'Confirm commitment'}</button>}</fieldset>{!statusAllowed&&<p>Only the assignee, initiative owner, creator, Product Lead or administration can update this commitment.</p>}</form>;
}
