'use client';
import { DateField } from '@/components/forms/DateField';
import {useFormAction} from '@/components/forms/useFormAction';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ScopeField} from '@/components/auth/WorkspaceScope';
import {canBusinessWrite} from '@/lib/auth/roles';
import type {DeliveryMember,WorkspaceAccess} from '@/lib/delivery/types';
import type {Commitment,CommitmentEvent} from '@/lib/workspace/commitments';
import {canChangeCommitment,ACTION_STATUSES} from '@/lib/workspace/commitment-policy';
import {commitmentAction} from '@/app/initiatives/[slug]/actions/actions';
import {displayDate} from '@/lib/delivery/display';
import {formatDateTime} from '@/lib/domain/labels';
import {Button} from '@/components/primitives/Button';
import {TabToolbar} from '@/components/workspace/TabToolbar';
import {CompleteCommitment} from './CompleteCommitment';
import styles from './commitments.module.css';
const statusLabel=(s:string)=>s.charAt(0)+s.slice(1).toLowerCase().replaceAll('_',' ');
const ORIGIN_LABEL:Record<string,string>={HUMAN_ENTRY:'Added by hand',WEEKLY_REVIEW:'From a weekly review',MEETING:'From meeting notes',DECISION:'From a decision',CONFIRMED_AI_PROPOSAL:'From confirmed evidence'};
export function CommitmentWorkbench({slug,initiativeId,archived,actions,events,members,evidence,ctx,ownerId,writesEnabled,today,selectedId}:{slug:string;initiativeId:string;archived:boolean;actions:Commitment[];events:CommitmentEvent[];members:DeliveryMember[];evidence:{id:string;title:string}[];ctx:WorkspaceAccess;ownerId:string|null;writesEnabled:boolean;today:string;selectedId?:string}){
 const [selection,setSelection]=useState<{row:Commitment|null;requestId:string}|null>(null);const [saved,setSaved]=useState<string|null>(null);const dialog=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null),add=useRef<HTMLSpanElement>(null);
 const canWrite=canBusinessWrite(ctx)&&writesEnabled&&!archived;
 const open=(row:Commitment|null)=>{setSaved(null);setSelection({row,requestId:crypto.randomUUID()});};
 useEffect(()=>{if(selection){dialog.current?.showModal();heading.current?.focus();}},[selection]);
 useEffect(()=>{if(selectedId){const row=actions.find(a=>a.id===selectedId);if(row)setSelection({row,requestId:crypto.randomUUID()});}},[selectedId]);
 const close=()=>{dialog.current?.close();setSelection(null);add.current?.querySelector('button')?.focus();};
 const weekEnd=new Date(today+'T12:00:00Z');weekEnd.setUTCDate(weekEnd.getUTCDate()+(7-weekEnd.getUTCDay())%7);const end=weekEnd.toISOString().slice(0,10);
 const groups=[['Overdue',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate<today)],['Due this week',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate>=today&&a.dueDate<=end)],['Later',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&a.dueDate&&a.dueDate>end)],['No due date',actions.filter(a=>!['DONE','CANCELLED'].includes(a.status)&&!a.dueDate)]] as const;
 const done=actions.filter(a=>['DONE','CANCELLED'].includes(a.status));const open_=actions.length-done.length;const overdue=groups[0][1].length;
 const row=(a:Commitment)=>{const late=a.dueDate&&a.dueDate<today&&!['DONE','CANCELLED'].includes(a.status);const canComplete=canWrite&&!a.blockedNote&&!['DONE','CANCELLED'].includes(a.status)&&canChangeCommitment(ctx,a,ownerId,'STATUS');return <li key={a.id} className={styles.row}>
  <span className={styles.statusGlyph} data-status={a.status} aria-hidden="true">{a.status==='DONE'?'✓':a.status==='CANCELLED'?'–':a.blockedNote?'▲':a.status==='IN_PROGRESS'?'◐':'○'}</span>
  <div className={styles.rowMain}><Link prefetch={false} className={styles.rowTitle} href={`/initiatives/${slug}/actions?action=${a.id}`} onClick={e=>{e.preventDefault();open(a);}}>{a.title.charAt(0).toUpperCase()+a.title.slice(1)}</Link>
   <span className={styles.rowMeta}>{ORIGIN_LABEL[a.origin]??'Recorded'}{a.blockedNote&&<strong> · Blocked: {a.blockedNote}</strong>}</span></div>
  <span className={styles.assignee}>{members.find(m=>m.id===a.assigneeMemberId)?.displayName??'No assignee'}</span>
  <span className={styles.due} data-late={late||undefined}>{a.dueDate?late?<><span aria-hidden="true">▲ </span>Overdue · {displayDate(a.dueDate)}</>:displayDate(a.dueDate):'No due date'}</span>
  <span className={styles.status} data-status={a.status}>{statusLabel(a.status)}</span>
  <span className={styles.rowAction}>{canComplete?<CompleteCommitment slug={slug} commitment={a}/>:null}</span>
 </li>;};
 return <div className={styles.page}>
 <TabToolbar title="Commitments" summary={actions.length?<><strong>{open_}</strong> open{overdue?<> · <span className={styles.lateText}>{overdue} overdue</span></>:null}{done.length?` · ${done.length} done or cancelled`:''}</>:'No commitments yet'}
  actions={canWrite?<span ref={add}><Button variant="primary" type="button" onClick={()=>open(null)}>Add commitment</Button></span>:<span className={styles.readOnly}>{archived?'Archived — restore to edit':!canBusinessWrite(ctx)?'Read-only':'Changes are disabled in this environment'}</span>}/>
 <p role="status" className={styles.saved}>{saved}</p>
 {actions.length===0&&<p className={styles.empty}>Commitments you confirm from Weekly Review, meetings or evidence appear here{canWrite?' — or add one':''}.</p>}
 {groups.map(([title,rows])=>rows.length>0&&<section className={styles.group} key={title} aria-label={title}><h3>{title} <span>{rows.length}</span></h3><ul>{rows.map(row)}</ul></section>)}
 {done.length>0&&<details className={styles.group}><summary>Done & cancelled <span>{done.length}</span></summary><ul>{done.map(row)}</ul></details>}
 {selection&&<dialog ref={dialog} className={styles.dialog} onCancel={e=>{e.preventDefault();close();}} aria-labelledby="commitment-title"><header><h3 id="commitment-title" tabIndex={-1} ref={heading}>{selection.row?'Commitment details':'Add a commitment'}</h3><button type="button" onClick={close}>Close</button></header><CommitmentEditor key={selection.requestId} slug={slug} selection={selection} current={actions.find(a=>a.id===selection.row?.id)} members={members} evidence={evidence} ctx={ctx} ownerId={ownerId} editable={canWrite} onSaved={()=>{setSaved(selection.row?'Commitment updated. Its history records the change.':'Commitment added. It appears in the list below.');close();}}/>{selection.row&&<section><h4>History</h4><ol>{events.filter(e=>e.actionId===selection.row!.id).sort((a,b)=>b.seq-a.seq).map(e=><li key={e.id}>{e.type==='CREATED'?'Recorded':`Changed to ${statusLabel(e.after.status)}`} · {e.actor.label} · <time dateTime={e.at}>{formatDateTime(e.at)}</time>{e.note&&<p>{e.note}</p>}</li>)}</ol>{selection.row.originHref?.startsWith('/')&&<Link href={selection.row.originHref}>Open original context</Link>}</section>}</dialog>}</div>;
}
function CommitmentEditor({slug,selection,current,members,evidence,ctx,ownerId,editable,onSaved}:{slug:string;selection:{row:Commitment|null;requestId:string};current?:Commitment;members:DeliveryMember[];evidence:{id:string;title:string}[];ctx:WorkspaceAccess;ownerId:string|null;editable:boolean;onSaved:()=>void}){
 const a=selection.row;const [revision,setRevision]=useState(a?.revision??0);const [state, action, pending, keepAction] = useFormAction(commitmentAction,{error:null});const error=useRef<HTMLParagraphElement>(null);useEffect(()=>{if(state.error)error.current?.focus();else if(state.id)onSaved();},[state]);const statusAllowed=editable&&(!a||canChangeCommitment(ctx,a,ownerId,'STATUS')),detailsAllowed=editable&&(!a||canChangeCommitment(ctx,a,ownerId,'DETAILS'));
 return <form action={action} onReset={keepAction} className={styles.form}><ScopeField/><input type="hidden" name="slug" value={slug}/><input type="hidden" name="id" value={a?.id??''}/><input type="hidden" name="requestId" value={selection.requestId}/><input type="hidden" name="revision" value={revision}/>{state.error&&<p ref={error} tabIndex={-1} role="alert" className={styles.error}>{state.error}</p>}{current&&current.revision!==revision&&<aside className={styles.conflict}><strong>Current record: {current.title} · {statusLabel(current.status)}</strong><p>Revision {current.revision}. Your proposed fields remain below.</p><button type="button" onClick={()=>setRevision(current.revision)}>Use current revision for my proposed edit</button></aside>}<fieldset disabled={!statusAllowed||pending}><label>Commitment<input name="title" required maxLength={200} defaultValue={a?.title??''} readOnly={!detailsAllowed}/></label><details open={!a}><summary>Commitment details</summary><label>Assignee<select name="assigneeMemberId" defaultValue={a?.assigneeMemberId??ownerId??''} disabled={!detailsAllowed}><option value="">No assignee</option>{members.filter(m=>m.active&&m.role!=='VIEWER').map(m=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select>{!detailsAllowed&&<input type="hidden" name="assigneeMemberId" value={a?.assigneeMemberId??''}/>}</label><label>Due date · optional<DateField name="dueDate" defaultValue={a?.dueDate??''} readOnly={!detailsAllowed}/></label><label>Evidence · optional<select name="evidenceId" defaultValue={a?.evidenceId??''} disabled={!detailsAllowed}><option value="">No linked evidence</option>{evidence.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select>{!detailsAllowed&&<input type="hidden" name="evidenceId" value={a?.evidenceId??''}/>}</label></details><label>Status<select name="status" defaultValue={a?.status??'OPEN'}>{ACTION_STATUSES.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></label><label>Blocker · optional<textarea name="blockedNote" maxLength={2000} defaultValue={a?.blockedNote??''}/></label><p>Use a blocker only for open work. Clear it before completing or cancelling.</p><label>Change / completion note<textarea name="note" maxLength={2000}/></label><p>Required to cancel or reopen; optional when completing.</p>{statusAllowed&&<button className={styles.primary} type="submit">{pending?'Saving…':a?'Save commitment':'Confirm commitment'}</button>}</fieldset>{!statusAllowed&&<p>Only the assignee, initiative owner, creator, Product Lead or administration can update this commitment.</p>}</form>;
}
