import Link from 'next/link';
import type {PortfolioSource,WorkspaceAccess,DeliveryFact} from '@/lib/delivery/types';
import {ownerFor,cairoDay,dayDifference} from '@/lib/delivery/model';
import styles from './commitments.module.css';
export function CommitmentSummary({source,ctx,facts,initiativeId}:{source:PortfolioSource;ctx:WorkspaceAccess;facts:DeliveryFact[];initiativeId?:string}){
 const today=cairoDay(new Date().toISOString());const rows=(source.commitments??[]).filter(a=>!['DONE','CANCELLED'].includes(a.status)&&source.snapshots.some(s=>s.initiative.id===a.initiativeId&&!s.initiative.archivedAt)&&(initiativeId?a.initiativeId===initiativeId:a.assigneeMemberId===ctx.memberId||!a.assigneeMemberId&&ownerFor(facts,a.initiativeId)===ctx.memberId));
 const groups=initiativeId?[['Open commitments',rows] as const]:[['Overdue',rows.filter(a=>a.dueDate&&a.dueDate<today)] as const,['Due in the next 3 days',rows.filter(a=>a.dueDate&&dayDifference(today,a.dueDate)>=0&&dayDifference(today,a.dueDate)<=3)] as const,['Blocked',rows.filter(a=>a.blockedNote)] as const];
 return <section className={styles.group} aria-label={initiativeId?'Initiative commitments':'My commitments'}><h2>{initiativeId?'Commitments':'My commitments'}</h2>{groups.map(([name,items])=>items.length>0&&<div key={name}><h3>{name}</h3><ul>{items.slice(0,3).map(a=>{const i=source.snapshots.find(s=>s.initiative.id===a.initiativeId)!.initiative;return <li className={styles.row} key={a.id}><div><Link prefetch={false} href={`/initiatives/${i.slug}/actions?action=${a.id}`}>{a.title}</Link><p>{initiativeId?'':`${i.name} · `}{a.dueDate?`Due ${a.dueDate}`:'No due date'} · {source.members.find(m=>m.id===a.assigneeMemberId)?.displayName??'No assignee'}</p>{a.blockedNote&&<p>Blocked: {a.blockedNote}</p>}</div></li>;})}</ul>{items.length>3&&<p>{items.length-3} more · open the initiative’s Commitments to review.</p>}</div>)}{!groups.some(([,items])=>items.length>0)&&<p>{initiativeId?'No open commitments.':'No overdue, due-soon or blocked commitments assigned to you.'}</p>}{initiativeId&&<Link prefetch={false} href={`/initiatives/${source.snapshots.find(s=>s.initiative.id===initiativeId)!.initiative.slug}/actions`}>Review commitments →</Link>}</section>;
}
