'use client';
import {useState} from 'react';
import type {DeliveryFact,DeliveryMember} from '@/lib/delivery/types';
import {saveDeliveryFactAction} from '@/lib/delivery/actions';
import {WeeklyActionForm} from '@/components/weekly/WeeklyActionForm';
import styles from './management.module.css';
export function OwnerManager({initiativeId,workspaceId,fact,members,editable}:{initiativeId:string;workspaceId:string;fact?:DeliveryFact;members:DeliveryMember[];editable:boolean}){
 const [draft,setDraft]=useState<{revision:number;memberId:string}|null>(null);
 const current=fact?.state==='SET'?members.find(m=>m.id===fact.value.memberId):null;
 return <><p><strong>Owner · </strong>{current?.displayName??'No owner recorded'}{current&&!current.active?' · no longer active':''}</p><p className={styles.muted}>This assignment is shared by Home, Brief, delivery and Weekly Review. Previous assignments remain in history.</p>{editable?(draft?<div className={styles.form}><WeeklyActionForm action={saveDeliveryFactAction} label="Confirm owner" scopeWorkspaceId={workspaceId} watchEdits onSaved={()=>setDraft(null)}><input type="hidden" name="initiativeId" value={initiativeId}/><input type="hidden" name="kind" value="OWNER"/><input type="hidden" name="revision" value={draft.revision}/><input type="hidden" name="basis" value="DIRECT_KNOWLEDGE"/><label>Primary owner<select name="memberId" value={draft.memberId} onChange={e=>setDraft({...draft,memberId:e.target.value})}><option value="">No owner — withdraw assignment</option>{members.filter(m=>m.active&&m.role!=='VIEWER'&&m.workspaceId===workspaceId).map(m=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select></label><p className={styles.muted}>Viewers cannot own initiatives. {draft.memberId?`Future owner-based responsibilities use ${members.find(m=>m.id===draft.memberId)?.displayName}.`:'With no owner, setup becomes incomplete.'} Past assignments and action assignees remain unchanged.</p><label>Reason<textarea name="note" required maxLength={2000}/></label></WeeklyActionForm><button type="button" onClick={()=>setDraft(null)}>Cancel owner change</button></div>:<div className={styles.actions}><button type="button" onClick={()=>setDraft({revision:fact?.revision??0,memberId:current?.id??''})}>Change owner</button></div>):<p className={styles.muted}>Only an admin or Product Lead can change the owner. Archived initiatives are read-only.</p>}</>;
}
