import {CommitmentSummary} from '@/components/initiative/CommitmentSummary';
import Link from 'next/link';
import type {Metadata} from 'next';
import {getRepository} from '@/lib/data';
import {readManagement} from '@/lib/data/management-read';
import {readDelivery} from '@/lib/delivery/repository';
import {isoWeek,nextReviewWeek} from '@/lib/delivery/model';
import {displayDate} from '@/lib/delivery/roadmap';
import {buildPortfolioProjection} from '@/lib/workspace/portfolio';
import {isDemoWriteEnabled} from '@/lib/env';
import {canBusinessWrite} from '@/lib/auth/roles';
import {isDemoGuestSession} from '@/lib/auth/service';
import {STAGE_LABEL,formatDate} from '@/lib/domain/labels';
import {FirstRunOrientation} from '@/components/shell/FirstRunOrientation';
import {readRelationships} from '@/lib/data/relationships';
import {readQuestions} from '@/lib/data/questions';
import {ownerAttention} from '@/lib/workspace/owner-attention';
import {WaitingOnYou} from '@/components/workspace/WaitingOnYou';
import styles from './home.module.css';
export const metadata:Metadata={title:'Home'};
export const dynamic='force-dynamic';
export default async function Home({searchParams}:{searchParams:Promise<{organizationChanged?:string}>}){
 const [d,activity,query,guest,management,rel,qs]=await Promise.all([readDelivery(),getRepository().listRecentActivity(100),searchParams,isDemoGuestSession(),readManagement(),readRelationships(),readQuestions()]);
 const p=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,activity,management,relationships:rel.relationships,asOf:d.presentation.scenarioAt??new Date().toISOString()});
 const waiting=ownerAttention({memberId:d.ctx.memberId??null,facts:d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId),relationships:rel.relationships,questions:qs.questions,ends:d.source.snapshots.map(x=>({id:x.initiative.id,name:x.initiative.name,slug:x.initiative.slug,archived:Boolean(x.initiative.archivedAt)})),today:p.today});
 const week=isoWeek(d.presentation.scenarioAt??new Date().toISOString());const review=d.state.reviews.find(r=>r.workspaceId===d.ctx.workspaceId&&r.week===week);const writer=canBusinessWrite(d.ctx)&&isDemoWriteEnabled;
 const reviewed=review?.sections.filter(s=>!s.needsRecheck&&(s.editedByMemberId||s.editedByUserId)).length??0;
 const baseline=review?d.state.reviews.find(r=>r.id===review.baselineReviewId):p.baseline;
 const next=review?.status==='FINAL'?nextReviewWeek(review.week):null;
 const nextExists=next?d.state.reviews.some(r=>r.workspaceId===d.ctx.workspaceId&&r.week===next.week):false;
 const nextAvailable=next&&next.week<=isoWeek(new Date().toISOString());
 const newChanges=p.changes.filter(c=>c.sentence==='Added to Prodwise');// One event touching two initiatives (a relationship) is shown once portfolio-wide.
 const seen=new Set<string>();const unique=p.changes.filter(c=>c.sentence!=='Added to Prodwise').filter(c=>{const key=`${c.sentence}|${c.occurredAt.slice(0,19)}`;if(seen.has(key))return false;seen.add(key);return true;});
 // Changes by the same person to the same initiative within ten minutes read as one line.
 const bursts:{c:(typeof unique)[number];more:string[]}[]=[];for(const c of unique){const last=bursts.at(-1);if(last&&last.c.initiativeId===c.initiativeId&&last.c.actorLabel===c.actorLabel&&Math.abs(Date.parse(last.c.occurredAt)-Date.parse(c.occurredAt))<=600000)last.more.push(c.sentence);else bursts.push({c,more:[]});}
 const changes=bursts.slice(0,6-(newChanges.length?1:0));
 return <div className={styles.page}>
 {query.organizationChanged&&<p role="status" className={styles.notice}>You are now working in {d.presentation.organizationName}.</p>}
 <FirstRunOrientation identity={{access:d.ctx,presentation:d.presentation,guest}}/>
 <div className={styles.workbench}><div className={styles.leftColumn}><header className={styles.intro}><p className={styles.eyebrow}>Portfolio · {d.presentation.organizationName}{d.presentation.isDemo?` · Scenario ${displayDate(p.today)}`:''}</p><h1 tabIndex={query.organizationChanged?-1:undefined}>What needs attention</h1>
 {p.summary.total>0&&<ul className={styles.counts} aria-label="Portfolio counts">{([[p.summary.total,'Initiatives','/initiatives'],[p.summary.attentionInitiatives,'Need attention','/initiatives?attention=any'],[p.summary.upcomingTargets,'Targets in 28 days','/initiatives?target=upcoming'],[p.summary.unknownTargets,'No Target Live','/initiatives?target=unknown'],[p.summary.setupIncomplete,'Setup incomplete','/initiatives?setup=incomplete']] as const).map(([n,label,href])=><li key={label}><Link prefetch={false} href={href}><strong>{n}</strong><span>{label}</span></Link></li>)}</ul>}</header>
{!p.summary.total?<section className={styles.empty}><h2>No initiatives recorded in {d.presentation.organizationName} yet.</h2><p>Record an initiative to build its scope, sources and delivery facts.</p>{writer&&<Link prefetch={false} href="/initiatives/new">Create initiative →</Link>}</section>:<section className={styles.attentionSection} aria-labelledby="attention-heading"><div className={styles.sectionHead}><h2 id="attention-heading">Needs attention</h2><p>{p.summary.attentionInitiatives} {p.summary.attentionInitiatives===1?'initiative':'initiatives'} · {p.summary.attentionReasons} {p.summary.attentionReasons===1?'reason':'reasons'}</p></div><p className={styles.meta}>Ordered by reason type, then date — not a priority score.</p>
 {p.attentionRows.length?<ul className={styles.attentionList}>{p.attentionRows.slice(0,5).map(r=><li key={r.initiative.id}><div className={styles.identity}><Link href={`/initiatives/${r.initiative.slug}`}>{r.initiative.name}</Link><span>{STAGE_LABEL[r.initiative.stage]} · {r.ownerLabel}</span></div><ul>{r.attention.map((a,index)=><li key={index}><strong>{a.label}</strong><p>{a.detail}</p><Link prefetch={false} href={a.href}>{a.kind==='DECISION'?'Review decision':a.kind==='DEPENDENCY'?'Review dependency':'Inspect record'} →</Link></li>)}</ul><p className={styles.next}>{r.nextStep?.value.text?`Recorded next step: ${r.nextStep.value.text}`:'No next step recorded.'}</p></li>)}</ul>:<p className={styles.empty}>{p.summary.setupIncomplete?`No recorded decisions, blockers or past dates. ${p.summary.setupIncomplete} {p.summary.setupIncomplete===1?'initiative has':'initiatives have'} setup incomplete, so their record coverage is not complete.`:'Nothing flagged under the current checks. This is not a readiness assessment.'}</p>}
 {p.attentionRows.length>3&&<Link prefetch={false} href="/initiatives?attention=any">View all attention →</Link>}{p.summary.setupIncomplete>0&&<p className={styles.support}>Setup to complete: <Link prefetch={false} href="/initiatives?setup=incomplete">{p.summary.setupIncomplete} {p.summary.setupIncomplete===1?'initiative has':'initiatives have'} setup incomplete</Link>.</p>}</section>
 }<div className={styles.yours}><WaitingOnYou rows={waiting}/><CommitmentSummary source={d.source} ctx={d.ctx} facts={d.state.facts}/></div></div><div className={styles.rightColumn}><section className={styles.weekly} aria-label="Weekly review"><p className={styles.eyebrow}>Weekly Product Review</p><h2>{week.replace(/^\d{4}-/,'')} review · {review?.status==='FINAL'?'Final':review?'Draft':'Not prepared'}</h2>
 <p>{review?.status==='DRAFT'?`${reviewed} of ${review.sections.length} sections reviewed`:review?.status==='FINAL'?`Finalized by ${review.finalizedByLabel??'Recorded actor'} · ${formatDate(review.finalizedAt??'')}`:`No review prepared for ${week.replace(/^\d{4}-/,'')}`}</p>
 <p className={styles.meta}>{baseline?`Compared with ${baseline.week.replace(/^\d{4}-/,'')} Final · ${formatDate(baseline.input.asOf)}`:'First review · no previous Final'}</p>
 {review?.status==='FINAL'&&writer&&next&&!nextAvailable&&!nextExists?<><button className={styles.primary} disabled>Prepare {next.week.replace(/^\d{4}-/,'')} review</button><p className={styles.meta}>{next.week.replace(/^\d{4}-/,'')} starts {displayDate(next.startsOn)}. <Link prefetch={false} href={`/weekly-review?week=${week}`}>Read Final</Link></p></>:<Link prefetch={false} className={styles.primary} href={`/weekly-review?week=${review?.status==='FINAL'&&writer&&next?next.week:week}`}>{review?.status==='DRAFT'?(writer?'Continue review':'Read review'):review?.status==='FINAL'?writer&&next?`${nextExists?'Open':'Prepare'} ${next.week.replace(/^\d{4}-/,'')} review`:'Read Final review':writer?`Prepare ${week.replace(/^\d{4}-/,'')} review`:'Read weekly review'}</Link>}
 <p className={styles.meta}>{!writer?'Read the preserved review. Changes require write access.':review?.status==='DRAFT'?(reviewed===review.sections.length?'All sections reviewed · check inputs before finalizing':`Your next step: review the ${review.sections.length-reviewed} remaining sections`):review?.status==='FINAL'?'This Final becomes the baseline for the next review. Prepare the next week from Weekly Review.':'Your next step: prepare the shared portfolio draft.'}</p></section><aside className={styles.contextRail} aria-label="Upcoming commitments"><div className={styles.sectionHead}><h2>Coming up</h2><Link prefetch={false} href="/roadmap">Roadmap →</Link></div><p className={styles.meta}>Next 28 days · confirmed dates</p>{p.upcoming.length?<ul className={styles.schedule}>{p.upcoming.slice(0,6).map(u=><li key={`${u.initiativeId}:${u.kind}`}><time dateTime={u.date}>{displayDate(u.date)}</time><Link prefetch={false} href={`/initiatives/${u.slug}/delivery`}><strong>{u.name}</strong><span>{u.label}</span></Link></li>)}</ul>:<p className={styles.empty}>No dated commitments in the next 28 days.</p>}<Link prefetch={false} className={styles.support} href="/initiatives?target=unknown">{p.summary.unknownTargets} {p.summary.unknownTargets===1?'initiative has':'initiatives have'} no Target Live.</Link></aside></div></div>
 <section className={styles.changes} aria-labelledby="changes-heading"><div className={styles.sectionHead}><h2 id="changes-heading">What changed {p.baseline?`since ${p.baseline.week.replace(/^\d{4}-/,'')} Final`:'in the last 28 days'}</h2><Link prefetch={false} href={p.baseline?`/weekly-review?week=${p.baseline.week}&view=since`:"/weekly-review"}>View all changes →</Link></div><ul>{newChanges.length>0&&<li><strong>{newChanges.length} initiatives added:</strong> {newChanges.map((c,index)=><span key={c.id}>{index?', ':''}<Link prefetch={false} href={c.href}>{c.name}</Link></span>)}</li>}{changes.map(({c,more})=><li key={c.id}><Link prefetch={false} href={c.href}>{c.name}</Link><p>{c.sentence}{more.length>0&&<span className={styles.burst}> · also {more.length===1?more[0]!.charAt(0).toLowerCase()+more[0]!.slice(1):`${more.length} related changes`}</span>}</p><small>{c.actorLabel} · {formatDate(c.occurredAt)}</small></li>)}</ul>{!p.changes.length&&<p className={styles.empty}>No recorded changes in this comparison.</p>}</section>
 <p className={styles.support}>Timing comes from human-confirmed facts. Knowledge checks compare recorded values; they do not assess release readiness or business impact.</p></div>;
}
