import {notFound} from 'next/navigation';import {readDelivery} from '@/lib/delivery/repository';import {readEvidence} from '@/lib/evidence/service';import {canBusinessWrite} from '@/lib/auth/roles';import {canManageInitiative} from '@/lib/workspace/management-policy';import {ownerFor} from '@/lib/delivery/model';import {isDemoWriteEnabled,isClaudeConfigured} from '@/lib/env';import {Workbench} from '@/components/evidence/Workbench';import {canManageRelationship} from '@/lib/workspace/relationships';import {readCommitments} from '@/lib/data/commitments';import {readQuestions} from '@/lib/data/questions';import {readRelationships} from '@/lib/data/relationships';import {alreadyRecorded,sameTextAs} from '@/lib/evidence/already-recorded';
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Review evidence" };
export const maxDuration=60;
export default async function EvidenceWorkbench({params}:{params:Promise<{slug:string;submissionId:string}>}){const [{slug,submissionId},d]=await Promise.all([params,readDelivery()]);const snap=d.source.snapshots.find(s=>s.initiative.slug===slug);const i=snap?.initiative;if(!snap||!i)notFound();const evidence=await readEvidence(i.id),submission=evidence.submissions.find(x=>x.id===submissionId);if(!submission)notFound();
 const [commitments,questions,relationships]=await Promise.all([readCommitments(),readQuestions(),readRelationships()]);
 const recorded=alreadyRecorded(evidence.proposals.filter(p=>p.submissionId===submission.id),{slug,initiativeId:i.id,claims:snap.claims,commitments:commitments.actions,questions:questions.questions,relationships:relationships.relationships,facts:d.state.facts,names:Object.fromEntries(d.source.snapshots.map(s=>[s.initiative.id,s.initiative.name]))});
 const same=sameTextAs(submission,evidence.submissions,id=>evidence.proposals.filter(p=>p.submissionId===id&&p.status!=='PENDING').length);
 const currentDates=Object.fromEntries(d.state.facts.filter(f=>f.initiativeId===i.id&&f.state==='SET').map(f=>[f.kind,f.value.date]));
 const owner=ownerFor(d.state.facts,i.id);const meeting=evidence.meetings?.find(m=>m.submissionId===submission.id);
 return <Workbench claudeReady={isClaudeConfigured} recorded={recorded} currentDates={currentDates} sameText={same?{id:same.id,title:evidence.meetings?.find(m=>m.submissionId===same.id)?.title??same.title,createdAt:same.createdAt}:null} slug={slug} initiativeName={i.name} submission={submission} evidence={evidence} writer={canBusinessWrite(d.ctx)&&!i.archivedAt&&isDemoWriteEnabled} canDelivery={canManageInitiative(d.ctx,'DELIVERY',owner)} canRelate={canManageRelationship(d.ctx,owner)} canCorrect={Boolean(meeting)&&(meeting!.createdBy===d.ctx.actor.id||canManageInitiative(d.ctx,'DELIVERY',owner))} contexts={(d.source.contexts??[]).filter(c=>c.initiativeId===i.id)} currentContextId={i.currentContextId??null} members={d.source.members}
  claims={snap.claims.map(c=>({id:c.id,subject:c.subject,attribute:c.attribute,value:c.value,status:c.status}))}
  targets={d.source.snapshots.filter(s=>s.initiative.id!==i.id).map(s=>({id:s.initiative.id,name:s.initiative.name}))}/>;}
