"use client";
import { DateField } from '@/components/forms/DateField';
import {useFormAction} from '@/components/forms/useFormAction';
import {useEffect,useId,useRef,useState} from "react";
import {applyRecordUpdatesAction} from "@/lib/delivery/actions";
import {DOMAINS,STAGES,type InitiativeSnapshot} from "@/lib/domain/types";
import {STAGE_LABEL,DOMAIN_LABEL} from "@/lib/domain/labels";
import type {DeliveryFact} from "@/lib/delivery/types";
import type {DeliveryActionState} from "@/lib/delivery/actions";
import {displayDate} from "@/lib/delivery/display";
import styles from "./weekly.module.css";
const fieldLabels={STAGE:"Lifecycle stage",DECISION:"New confirmed decision",TARGET_LIVE:"Target Live · planned",ACTUAL_LIVE:"Actual Live",NEXT_MILESTONE:"Next milestone",BLOCKER:"Blocker",NEXT_STEP:"Next step"};
type Field=keyof typeof fieldLabels;
export function RecordUpdatePanel({snapshot,facts,reviewId,reviewRevision,workspaceId,canFacts,canDecision,writesEnabled}:{snapshot:InitiativeSnapshot;facts:DeliveryFact[];reviewId:string;reviewRevision:number;workspaceId:string;canFacts:boolean;canDecision:boolean;writesEnabled:boolean}) {
  const[selected,setSelected]=useState<Field[]>([]);const[state,formAction,pending,keepFormAction]=useFormAction(async(previous:DeliveryActionState,form:FormData)=>{const result=await applyRecordUpdatesAction(previous,form);if(!result.error)setSelected([]);return result;},{error:null,message:null});const[summaries,setSummaries]=useState<string[]>([]);const[dirtyAt,setDirtyAt]=useState<typeof state|null>(null);const dirty=dirtyAt!==null&&(dirtyAt===state||Boolean(state.error));const[confirmation,setConfirmation]=useState<string[]>([]);
  const form=useRef<HTMLFormElement>(null),dialog=useRef<HTMLDialogElement>(null),reviewButton=useRef<HTMLButtonElement>(null);const title=useId();
  const current=(field:Field)=>facts.find(f=>f.initiativeId===snapshot.initiative.id&&f.kind===field);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};const navigate=(e:MouseEvent)=>{const link=(e.target as Element)?.closest("a[href]");if(link&&!(link as HTMLAnchorElement).getAttribute("href")?.startsWith("#")&&!window.confirm("Your proposed initiative updates are unsaved. Leave this section?")){e.preventDefault();e.stopPropagation();}};window.addEventListener("beforeunload",warn);document.addEventListener("click",navigate,true);return()=>{window.removeEventListener("beforeunload",warn);document.removeEventListener("click",navigate,true);};},[dirty]);
  function close(){dialog.current?.close();reviewButton.current?.focus();}
  function review(){if(!form.current?.reportValidity()||!selected.length)return;const data=new FormData(form.current);setSummaries(selected.map(field=>{
    const old=current(field);const before=field==="STAGE"?STAGE_LABEL[snapshot.initiative.stage]:field==="DECISION"?"No new decision record":old?.state==="SET"?[old.value.date?displayDate(old.value.date):null,old.value.text,old.value.extent==="FULL"?"Full named scope":old.value.extent==="PARTIAL"?"Partial named scope":null].filter(Boolean).join(" · "):"Not recorded";
    const proposed=field==="STAGE"?STAGE_LABEL[String(data.get("recordStage")) as typeof snapshot.initiative.stage]:field==="DECISION"?`${data.get("decisionSubject")} · ${data.get("decisionAttribute")} = ${data.get("decisionValue")}`:field==="BLOCKER"&&data.get("BLOCKER:retract")==="yes"?"Withdraw value; current blocker status unknown":[data.get(`${field}:date`)?displayDate(String(data.get(`${field}:date`))):null,data.get(`${field}:text`)||null,data.get(`${field}:extent`)==="FULL"?"Full named scope":data.get(`${field}:extent`)==="PARTIAL"?"Partial named scope":null].filter(Boolean).join(" · ");return `${fieldLabels[field]}: ${before} → ${proposed}`;
  }));setConfirmation([`Basis: ${data.get("recordBasis")==="EVIDENCE"?"Current-scope evidence":"Direct knowledge"}`,`Source: ${data.get("recordBasis")==="EVIDENCE"?`${snapshot.evidence.find(e=>e.id===data.get("recordEvidenceId"))?.title??"No linked source"}${data.get("recordLocator")?` · ${data.get("recordLocator")}`:""}`:"Not linked for direct knowledge"}`,`Reason: ${data.get("recordReason")}`]);dialog.current?.showModal();}
  function apply(){if(!form.current)return;const confirmation=form.current.elements.namedItem("confirmedRecordUpdates") as HTMLInputElement;confirmation.value="yes";close();form.current.requestSubmit();}
  return <section className={styles.block} aria-labelledby={`${title}-panel`}><h3 id={`${title}-panel`}>Update the initiative record</h3><p className={styles.meta}>Changes apply to {snapshot.initiative.name} after you confirm. They are separate from meeting commentary. Brief, Home, Roadmap and Analysis use these initiative records immediately.</p>{!canFacts&&<p className={styles.meta}>The assigned PM, Org Owner, Admin or Platform Owner maintains delivery facts and stage. Product Lead review authority does not expand fact authority.</p>}
    <form ref={form} action={formAction} onReset={keepFormAction} className={styles.form} onChange={()=>setDirtyAt(state)} onSubmit={()=>{dialog.current?.close();}}>
      <input type="hidden" name="scopeWorkspaceId" value={workspaceId}/><input type="hidden" name="reviewId" value={reviewId}/><input type="hidden" name="reviewRevision" value={reviewRevision}/><input type="hidden" name="initiativeId" value={snapshot.initiative.id}/><input type="hidden" name="initiativeUpdatedAt" value={snapshot.initiative.updatedAt}/><input type="hidden" name="confirmedRecordUpdates" defaultValue=""/>
      <fieldset disabled={pending||!writesEnabled}><div className={styles.updates}>{(Object.keys(fieldLabels) as Field[]).map(field=>{
        const fact=current(field),value=fact?.state==="SET"?fact.value:null,allowed=field==="DECISION"?canDecision:canFacts;
        return <div key={field} className={styles.updateRow}><label className={styles.choice}><input type="checkbox" name={`update:${field}`} value="yes" disabled={!allowed} checked={selected.includes(field)} onChange={event=>setSelected(items=>event.target.checked?[...items,field]:items.filter(i=>i!==field))}/>{fieldLabels[field]}</label>{selected.includes(field)&&<div className={styles.fields}>
          <input type="hidden" name={`${field}:revision`} value={fact?.revision??0}/>
          {field==="STAGE"&&<label className={styles.field}>Recorded stage<select aria-label="Recorded stage" name="recordStage" defaultValue={snapshot.initiative.stage}>{STAGES.map(s=><option key={s} value={s}>{STAGE_LABEL[s]}</option>)}</select></label>}
          {field==="DECISION"&&<><label className={styles.field}>Decision subject<input name="decisionSubject" maxLength={300} required/></label><label className={styles.field}>Attribute<input name="decisionAttribute" maxLength={300} required/></label><label className={styles.field}>Confirmed value<textarea name="decisionValue" maxLength={4000} required/></label><label className={styles.field}>Domain<select aria-label="Domain" name="decisionDomain">{DOMAINS.map(d=><option key={d} value={d}>{DOMAIN_LABEL[d]}</option>)}</select></label><label className={styles.field}>Phase / context<input name="decisionPhase" maxLength={300}/></label><p className={styles.meta}>Creates and confirms a DECISION in Knowledge. Resolve existing differing values through the Decisions workbench.</p></>}
          {["TARGET_LIVE","ACTUAL_LIVE","NEXT_MILESTONE"].includes(field)&&<label className={styles.field}>{field==="ACTUAL_LIVE"?"Actual live date":"Planned date"}<DateField name={`${field}:date`} defaultValue={value?.date??""} required={field!=="NEXT_MILESTONE"} warnPast={field==="TARGET_LIVE"||field==="NEXT_MILESTONE"}/></label>}
          {["ACTUAL_LIVE","NEXT_MILESTONE","BLOCKER","NEXT_STEP"].includes(field)&&<label className={styles.field}>{field==="ACTUAL_LIVE"?"Rollout description (required for partial)":"Description"}<textarea aria-label={field==="ACTUAL_LIVE"?"Rollout description (required for partial)":"Description"} name={`${field}:text`} maxLength={2000} defaultValue={value?.text??""}/></label>}
          {field==="ACTUAL_LIVE"&&<label className={styles.field}>Extent within named scope<select aria-label="Extent within named scope" name={`${field}:extent`} defaultValue={value?.extent??""} required><option value="">Choose extent</option><option value="FULL">Full named scope</option><option value="PARTIAL">Partial named scope</option></select></label>}
          {field==="BLOCKER"&&fact&&<label className={styles.choice}><input type="checkbox" name="BLOCKER:retract" value="yes"/>Withdraw the blocker value, retaining its history</label>}
        </div>}</div>;
      })}</div>{selected.length>0&&<div className={styles.fields}><label className={styles.field}>Confirmation basis<select aria-label="Confirmation basis" name="recordBasis"><option value="DIRECT_KNOWLEDGE">Direct knowledge</option><option value="EVIDENCE">Current-scope evidence</option></select></label><label className={styles.field}>Current-scope source<select aria-label="Current-scope source" name="recordEvidenceId"><option value="">No linked source</option>{snapshot.evidence.filter(e=>e.boundary==="CURRENT_SCOPE").map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label className={styles.field}>Source locator<input name="recordLocator" maxLength={500}/></label><label className={styles.field}>Confirmation / change reason<textarea name="recordReason" maxLength={2000} required/></label></div>}<button ref={reviewButton} type="button" className={styles.secondary} disabled={!selected.length} onClick={review}>{pending?"Applying initiative updates…":`Review ${selected.length||"selected"} ${selected.length===1?"update":"updates"}`}</button></fieldset>
      {dirty&&<p className={styles.meta}>Proposed values are unsaved. No initiative record changes until you confirm.</p>}{state.error&&<p role="alert" className={styles.error}>{state.error}</p>}{state.message&&<p role="status" className={styles.notice}>{state.message}</p>}{state.results&&<ul className={styles.results}>{state.results.map(r=><li key={r.field}><strong>{r.field.replaceAll("_"," ")} · {r.status.replaceAll("_"," ")}</strong> — {r.message}</li>)}</ul>}
    </form>
    <dialog ref={dialog} className={styles.dialog} aria-labelledby={title} onCancel={close}><h2 id={title}>Confirm initiative record updates</h2><p>{snapshot.initiative.name}</p><ul>{summaries.map(s=><li key={s}>{s}</li>)}</ul><ul>{confirmation.map(line=><li key={line}>{line}</li>)}</ul><p className={styles.meta}>The selected confirmation basis, source and reason will be recorded. These changes update the initiative truth. The Draft refreshes and affected sections need re-check; meeting commentary remains preserved. Stage and decision writes can succeed separately from delivery facts; results identify any partial failure.</p><div className={styles.links}><button type="button" className={styles.secondary} onClick={close}>Cancel</button><button type="button" className={styles.button} onClick={apply}>Apply {summaries.length} {summaries.length===1?"update":"updates"}</button></div></dialog>
  </section>;
}
