import Link from "next/link";
import {factFor,referencesFor,changesSince} from "@/lib/delivery/model";
import type {PortfolioInput,WeeklyReview,ReviewSection} from "@/lib/delivery/types";
import {displayDate} from "@/lib/delivery/roadmap";
import {STAGE_LABEL,BUSINESS_LINE_LABEL} from "@/lib/domain/labels";
import {buildPortfolioProjection} from "@/lib/workspace/portfolio";
import {weeklyChangeSentence} from "@/lib/delivery/weekly-copy";
import styles from "./weekly.module.css";
export function SectionRecord({review,section,baseline,returnTo}:{review:WeeklyReview;section:ReviewSection;baseline:PortfolioInput|null;returnTo:string}) {
  const snap=review.input.snapshots.find(s=>s.initiative.id===section.initiativeId);if(!snap)return null;
  const target=factFor(review.input.facts,section.initiativeId,"TARGET_LIVE"),actual=factFor(review.input.facts,section.initiativeId,"ACTUAL_LIVE"),milestone=factFor(review.input.facts,section.initiativeId,"NEXT_MILESTONE"),blocker=factFor(review.input.facts,section.initiativeId,"BLOCKER");
  const differences=referencesFor(review.input,baseline).filter(r=>r.initiativeId===section.initiativeId&&r.id.startsWith("finding:"));
  const changes=changesSince(review.input,baseline).filter(c=>c.initiativeId===section.initiativeId);
  const setup=buildPortfolioProjection({source:{snapshots:review.input.snapshots,members:review.input.members},state:{schema:1,facts:review.input.facts,events:review.input.events,reviews:[]},workspaceId:review.workspaceId,asOf:review.input.asOf}).rows.find(r=>r.initiative.id===section.initiativeId)!.coverage;
  return <section className={`${styles.block} ${styles.record}`}><h2><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}`}>{snap.initiative.name}</Link></h2><p className={styles.meta}>{BUSINESS_LINE_LABEL[snap.initiative.businessLine]} · {STAGE_LABEL[snap.initiative.stage]} · {factFor(review.input.facts,section.initiativeId,"SCOPE")?.value.text??"Scope not confirmed"}</p><h3>Record at cutoff</h3><p className={styles.meta}>Frozen initiative records. Meeting commentary below does not change these facts.</p><div className={styles.facts}><p><strong>Target Live · planned</strong>{displayDate(target?.value.date)}</p><p><strong>Actual Live</strong>{actual?.value.date?`${displayDate(actual.value.date)} · ${actual.value.extent==="FULL"?"Full named scope":`Partial · ${actual.value.text??"scope not described"}`}`:"Not recorded"}</p><p><strong>Next milestone</strong>{milestone?`${milestone.value.text} · ${milestone.value.date?displayDate(milestone.value.date):"Date not recorded"}`:"Not recorded"}</p></div><p className={styles.meta}>Recorded blocker: {blocker?.value.text??"No blocker recorded; this does not confirm there are none."}</p><p className={styles.meta}>Recorded next step: {factFor(review.input.facts,section.initiativeId,"NEXT_STEP")?.value.text??"Not recorded"}</p>
    <h3>{baseline?"Changes since the previous Final":"First review inventory"}</h3>{changes.length?<ul className={styles.changes}>{changes.map(c=><li key={c.id}>{weeklyChangeSentence(c,review.input,baseline)}</li>)}</ul>:<p className={styles.meta}>{baseline?"No recorded changes since the previous Final.":"No previous finalized baseline is assumed."}</p>}
    <h3>Recorded value differences</h3>{differences.length?<ul className={styles.changes}>{differences.map(r=><li key={r.id}><Link prefetch={false} href={`/initiatives/${snap.initiative.slug}/decisions?item=${encodeURIComponent(r.id.slice(8))}&returnTo=${encodeURIComponent(returnTo)}`}>{r.texts[0]}</Link></li>)}</ul>:<p className={styles.meta}>{setup.complete?"No open value differences under the current recorded checks. This is not a readiness assessment.":"Setup incomplete. Absence of a value difference does not mean this initiative is checked."}</p>}
  </section>;
}
