"use client";
import {announceSaved} from '@/components/forms/SavedNotice';
import {useFormAction} from '@/components/forms/useFormAction';
import {useEffect,useId,useRef,useState,type ReactNode} from "react";
import type {DeliveryActionState} from "@/lib/delivery/actions";
import {useRouter} from "next/navigation";
import styles from "./weekly.module.css";
export function WeeklyActionForm({action,children,label,scopeWorkspaceId,disabled=false,primary=false,pendingLabel="Saving…",describedBy,watchEdits=false,onSaved,redirectTo,confirm,validate}:{confirm?:{title:string;body:string;action:string};validate?:(form:HTMLFormElement)=>string|null;action:(state:DeliveryActionState,form:FormData)=>Promise<DeliveryActionState>;children?:ReactNode;label:string;scopeWorkspaceId:string;disabled?:boolean;primary?:boolean;pendingLabel?:string;describedBy?:string;watchEdits?:boolean;onSaved?:()=>void;redirectTo?:string}) {
  const[asking,setAsking]=useState(false);const confirmId=useId();const confirmButton=useRef<HTMLButtonElement>(null),trigger=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(asking)confirmButton.current?.focus();},[asking]);
  const router=useRouter();const[state,formAction,pending,keepFormAction]=useFormAction(async(previous:DeliveryActionState,form:FormData)=>{const result=await action(previous,form);setAsking(false);if(!result.error){if(result.message)announceSaved(result.message);onSaved?.();if(redirectTo?.startsWith("/weekly-review?week="))router.push(redirectTo);}return result;},{error:null,message:null});const[dirtyAt,setDirtyAt]=useState<typeof state|null>(null);
  // An error belongs to the submission that produced it; once the person edits, it is stale and clears.
  const[editedAfter,setEditedAfter]=useState<typeof state|null>(null);const[clientError,setClientError]=useState<string|null>(null);const serverError=state.error&&editedAfter!==state?state.error:null;const shownError=clientError??serverError;const dirty=dirtyAt!==null&&(dirtyAt===state||Boolean(state.error));
  useEffect(()=>{if(!watchEdits||!dirty)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();};const navigate=(event:MouseEvent)=>{const link=(event.target as Element)?.closest("a[href]");if(link&&!(link as HTMLAnchorElement).href.includes("#")&&!window.confirm("Your meeting commentary has unsaved changes. Leave this section?")){event.preventDefault();event.stopPropagation();}};window.addEventListener("beforeunload",unload);document.addEventListener("click",navigate,true);return()=>{window.removeEventListener("beforeunload",unload);document.removeEventListener("click",navigate,true);};},[dirty,watchEdits]);
  return <form action={formAction} onReset={keepFormAction} className={styles.form} onChange={event=>{if(watchEdits)setDirtyAt(state);setEditedAfter(state);if(clientError)setClientError(validate?.(event.currentTarget)??null);}} onSubmit={event=>{const problem=validate?.(event.currentTarget)??null;setClientError(problem);if(problem){event.preventDefault();setAsking(false);}}}><input type="hidden" name="scopeWorkspaceId" value={scopeWorkspaceId}/><fieldset disabled={disabled||pending}>{children}{confirm&&!pending?(asking?<div role="alertdialog" aria-labelledby={`${confirmId}-t`} aria-describedby={`${confirmId}-b`} className={styles.confirm} onKeyDown={e=>{if(e.key==='Escape'){setAsking(false);requestAnimationFrame(()=>trigger.current?.focus());}}}><p id={`${confirmId}-t`}><strong>{confirm.title}</strong></p><p id={`${confirmId}-b`}>{confirm.body}</p><div className={styles.confirmActions}><button ref={confirmButton} className="pw-btn" data-variant="primary" disabled={disabled}>{confirm.action}</button><button type="button" className="pw-btn" data-variant="secondary" onClick={()=>{setAsking(false);requestAnimationFrame(()=>trigger.current?.focus());}}>Cancel</button></div></div>:<button ref={trigger} type="button" className="pw-btn" data-variant={primary?'primary':'secondary'} disabled={disabled} aria-describedby={describedBy} onClick={()=>setAsking(true)}>{label}</button>):<button className="pw-btn" data-variant={primary?'primary':'secondary'} disabled={disabled||pending} aria-describedby={describedBy}>{pending?pendingLabel:label}</button>}</fieldset>{watchEdits&&dirty&&<p className={styles.meta}>Unsaved meeting commentary.</p>}{shownError&&<p role="alert" className={styles.error}>{shownError}</p>}{state.message&&<p role="status" className={styles.success}>{state.message}</p>}{state.results&&<ul className={styles.results}>{state.results.map(r=><li key={r.field}><strong>{r.field.replaceAll("_"," ")} · {r.status.replaceAll("_"," ")}</strong> — {r.message}</li>)}</ul>}</form>;
}
