"use client";
import {useActionState,useEffect,useState,type ReactNode} from "react";
import type {DeliveryActionState} from "@/lib/delivery/actions";
import {useRouter} from "next/navigation";
import styles from "./weekly.module.css";
export function WeeklyActionForm({action,children,label,scopeWorkspaceId,disabled=false,primary=false,pendingLabel="Saving…",describedBy,watchEdits=false,onSaved,redirectTo}:{action:(state:DeliveryActionState,form:FormData)=>Promise<DeliveryActionState>;children?:ReactNode;label:string;scopeWorkspaceId:string;disabled?:boolean;primary?:boolean;pendingLabel?:string;describedBy?:string;watchEdits?:boolean;onSaved?:()=>void;redirectTo?:string}) {
  const router=useRouter();const[state,formAction,pending]=useActionState(async(previous:DeliveryActionState,form:FormData)=>{const result=await action(previous,form);if(!result.error){onSaved?.();if(redirectTo?.startsWith("/weekly-review?week="))router.push(redirectTo);}return result;},{error:null,message:null});const[dirtyAt,setDirtyAt]=useState<typeof state|null>(null);const dirty=dirtyAt!==null&&(dirtyAt===state||Boolean(state.error));
  useEffect(()=>{if(!watchEdits||!dirty)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();};const navigate=(event:MouseEvent)=>{const link=(event.target as Element)?.closest("a[href]");if(link&&!(link as HTMLAnchorElement).href.includes("#")&&!window.confirm("Your meeting commentary has unsaved changes. Leave this section?")){event.preventDefault();event.stopPropagation();}};window.addEventListener("beforeunload",unload);document.addEventListener("click",navigate,true);return()=>{window.removeEventListener("beforeunload",unload);document.removeEventListener("click",navigate,true);};},[dirty,watchEdits]);
  return <form action={formAction} className={styles.form} onChange={()=>{if(watchEdits)setDirtyAt(state);}}><input type="hidden" name="scopeWorkspaceId" value={scopeWorkspaceId}/><fieldset disabled={disabled||pending}>{children}<button className={primary?styles.button:styles.secondary} disabled={disabled||pending} aria-describedby={describedBy}>{pending?pendingLabel:label}</button></fieldset>{watchEdits&&dirty&&<p className={styles.meta}>Unsaved meeting commentary.</p>}{state.error&&<p role="alert" className={styles.error}>{state.error}</p>}{state.message&&<p role="status" className={styles.success}>{state.message}</p>}{state.results&&<ul className={styles.results}>{state.results.map(r=><li key={r.field}><strong>{r.field.replaceAll("_"," ")} · {r.status.replaceAll("_"," ")}</strong> — {r.message}</li>)}</ul>}</form>;
}
