import Link from 'next/link';
import {readDelivery} from '@/lib/delivery/repository';
import {dateValid,factFor} from '@/lib/delivery/model';
import {displayDate,timelinePosition} from '@/lib/delivery/roadmap';
import {buildPortfolioProjection} from '@/lib/workspace/portfolio';
import {BUSINESS_LINE_LABEL,STAGE_LABEL} from '@/lib/domain/labels';
import {WriteNotice} from '@/components/delivery/WriteNotice';
import {readRelationships} from '@/lib/data/relationships';
import {relationshipsFor} from '@/lib/workspace/relationship-view';
import styles from './roadmap.module.css';
export default async function Roadmap({searchParams}:{searchParams:Promise<{businessLine?:string;owner?:string;cutoff?:string;view?:string}>}){
 const[d,f,rel]=await Promise.all([readDelivery(),searchParams,readRelationships()]);const scenario=d.presentation.scenarioAt??new Date().toISOString();const cutoff=f.cutoff&&dateValid(f.cutoff)?f.cutoff:scenario.slice(0,10);const p=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,asOf:`${cutoff}T12:00:00Z`});
 const ends=d.source.snapshots.map(x=>({id:x.initiative.id,name:x.initiative.name,slug:x.initiative.slug,archived:Boolean(x.initiative.archivedAt)}));const depFacts=d.state.facts.filter(x=>x.workspaceId===d.ctx.workspaceId);const depsOf=(id:string)=>relationshipsFor(id,rel.relationships,ends,depFacts).filter(x=>x.group==='DEPENDS_ON');
 const rows=p.rows.filter(r=>!r.initiative.archivedAt&&(!f.businessLine||r.initiative.businessLine===f.businessLine)&&(!f.owner||r.ownerId===f.owner)&&(!f.view||(f.view==='attention'?r.attention.length>0:f.view==='unknown'?!r.target?.value.date:f.view==='moved'?Boolean(r.targetMovement):f.view==='dependency'?depsOf(r.initiative.id).some(x=>x.late):true)));
 const facts=d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId);const dates=[cutoff,...rows.flatMap(r=>[r.target?.value.date,r.actual?.value.date,factFor(facts,r.initiative.id,'DEV_STARTED')?.value.date].filter((v):v is string=>Boolean(v)))].sort();const start=dates[0]!,end=dates.at(-1)!;
 const groups=[...new Set(rows.filter(r=>r.target?.value.date).map(r=>r.initiative.businessLine))].sort();const unknown=rows.filter(r=>!r.target?.value.date);
 const row=(r:typeof rows[number])=>{const i=r.initiative;const dev=factFor(facts,i.id,'DEV_STARTED');return <article className={styles.row} key={i.id}><div className={styles.identity}><Link prefetch={false} href={`/initiatives/${i.slug}/delivery?returnTo=${encodeURIComponent('/roadmap')}`}>{i.name}</Link><span>{STAGE_LABEL[i.stage]} · {r.ownerLabel}</span><p>{factFor(facts,i.id,'SCOPE')?.value.text??'Scope not confirmed'}</p></div><div className={styles.schedule}><div className={styles.timeline} aria-hidden="true"><span className={styles.cutoffMarker} style={{left:`${timelinePosition(cutoff,start,end)}%`}}/>{dev?.value.date&&r.target?.value.date&&dev.value.date<=r.target.value.date&&<span className={styles.duration} style={{left:`${timelinePosition(dev.value.date,start,end)}%`,width:`${timelinePosition(r.target.value.date,start,end)-timelinePosition(dev.value.date,start,end)}%`}}/>}{r.target?.value.date&&<span className={styles.targetMarker} style={{left:`${timelinePosition(r.target.value.date,start,end)}%`}}/>}{r.actual?.value.date&&<span className={styles.actualMarker} style={{left:`${timelinePosition(r.actual.value.date,start,end)}%`}}/>}{depsOf(i.id).filter(x=>x.late&&x.impact&&x.impact.assessed&&x.impact.late).map(x=><span key={x.relationship.id} className={styles.dependencyMarker} style={{left:`${timelinePosition((x.impact as {providerDate:string}).providerDate,start,end)}%`}}/>)}</div><p><strong>Target {displayDate(r.target?.value.date)}</strong>{r.target?.contextName&&<> · <Link prefetch={false} href={`/initiatives/${i.slug}/delivery#target-history`}>{r.target.contextName}</Link></>} · Live {r.actual?.value.date?`${displayDate(r.actual.value.date)} (${r.actual.value.extent==='PARTIAL'?'partial':'full'})`:'not recorded'}</p>{r.targetMovement&&<Link prefetch={false} href={`/initiatives/${i.slug}/delivery#target-history`}>Moved {r.targetMovement.days>0?'+':''}{r.targetMovement.days} d from {displayDate(r.targetMovement.from)}</Link>}<small>Development start · {displayDate(dev?.value.date)}</small></div><div className={styles.context}><strong>{r.milestone?.value.text??'Next milestone not recorded'}</strong><p>{r.milestone?.value.date?displayDate(r.milestone.value.date):'Date unknown'}</p>{r.attention.map((a,n)=><p className={styles.attention} key={n}>{a.label} · <Link prefetch={false} href={a.href}>Inspect</Link></p>)}{depsOf(i.id).map(x=><p key={x.relationship.id} className={x.late?styles.attention:styles.dependency}>{x.late?'▲ ':''}Depends on <Link prefetch={false} href={x.other?`/initiatives/${x.other.slug}`:'#'}>{x.other?.name??'an initiative you can’t access'}</Link> · {x.late?x.impactText:x.impact?.assessed?'no date impact on recorded dates':'date impact not assessed'}</p>)}<small>Next step: {r.nextStep?.value.text??'Not recorded'}</small></div></article>;};
 return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Delivery outlook · {d.presentation.organizationName}</p><h1>Roadmap</h1><p>Every date comes from a confirmed initiative fact.</p></div><Link prefetch={false} href="/weekly-review">Weekly Review →</Link></header><WriteNotice ctx={d.ctx}/>
 <p className={styles.pulse}><Link prefetch={false} href="/roadmap">{rows.length} {rows.length===1?'initiative':'initiatives'}</Link> · <Link prefetch={false} href="/roadmap?view=attention">{p.summary.attentionInitiatives} need attention</Link> · <Link prefetch={false} href="/roadmap?view=moved">{p.rows.filter(r=>r.targetMovement).length} with target changes</Link> · <Link prefetch={false} href="/roadmap?view=unknown">{p.summary.unknownTargets} without Target Live</Link></p>
 <form className={styles.filters}><label>Business line<select name="businessLine" defaultValue={f.businessLine??''}><option value="">All</option>{[...new Set(p.rows.map(r=>r.initiative.businessLine))].map(line=><option key={line} value={line}>{BUSINESS_LINE_LABEL[line]}</option>)}</select></label><label>Owner<select name="owner" defaultValue={f.owner??''}><option value="">All</option>{d.source.members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select></label><label>Review cutoff<input name="cutoff" type="date" defaultValue={cutoff}/></label><label>Show<select name="view" defaultValue={f.view??''}><option value="">All initiatives</option><option value="attention">Needs attention</option><option value="unknown">No Target Live</option><option value="moved">Target changes</option><option value="dependency">Dependency date impact</option></select></label><button>Apply filters</button></form>
 <p className={styles.note}>Current facts · cutoff {displayDate(cutoff)}{d.presentation.isDemo?` · scenario date ${displayDate(scenario.slice(0,10))}`:''}. Changing cutoff does not reconstruct historical records.</p>
 <div className={styles.axis}><span>Initiative / scope</span><div><p>{displayDate(start)} <span>Recorded schedule</span> {displayDate(end)}</p><span className={styles.axisCutoff} style={{left:`${timelinePosition(cutoff,start,end)}%`}}/></div><span>Next milestone / attention</span></div>
 <p className={styles.legend}><span className={styles.targetKey}/> Target · planned <span className={styles.actualKey}/> Actual Live · recorded <span className={styles.dependencyKey}/> Date a dependency lands (only when it is later than needed) │ Cutoff {displayDate(cutoff)}</p>
 {groups.map(group=><section key={group}><h2 className={styles.group}>{BUSINESS_LINE_LABEL[group]}</h2>{rows.filter(r=>r.target?.value.date&&r.initiative.businessLine===group).sort((a,b)=>a.target!.value.date!.localeCompare(b.target!.value.date!)).map(row)}</section>)}
 {unknown.length>0&&<section><h2 className={styles.group}>No known Target Live ({unknown.length})</h2>{unknown.map(row)}</section>}
 {!rows.length&&<section className={styles.empty}><h2>No initiatives in this view</h2><Link prefetch={false} href="/roadmap">Clear filters</Link></section>}
 <p className={styles.note}>Missing Actual Live does not mean a launch failed or has not happened. A past target requests a human update. Lines connect recorded dates; they never represent estimated progress.</p></div>;
}
