-- Prodwise Demo · additive synthetic metrics for the ACTIVE hosted Demo generation.
-- GENERATED by scripts/demo/render-demo-metrics-additive.mjs from src/lib/demo/metric-fixtures.ts — do not edit by hand.
--
-- What it does: inserts 24 metric_definitions and 151 metric_observations (migration 0017 columns),
-- every row origin SYNTHETIC_DEMO, into the one ACTIVE registered Demo workspace. Ids are the same deterministic
-- demo ids the operator plan (scripts/demo/provision-hosted.mjs) gives a fresh generation, so a later reset agrees.
--
-- Safety:
--  * Additive only: no update, delete or truncate. One transaction; any refusal rolls everything back.
--  * Target resolution: demo_entry_config -> ACTIVE workspace -> ACTIVE organization named 'Prodwise Demo'
--    with a demo_scenarios row (prodwise-graduation-2026-09-v1, 2026-09-26T10:00:00.000Z). Refuses unless that is exactly the one ACTIVE
--    registered Demo generation.
--  * Idempotent: a row that already exists with identical content is skipped; one that exists with different content
--    (or a period already recorded under another id) refuses the whole script.
--  * Initiatives are resolved by slug inside the Demo workspace (active, is_demo); a missing one refuses.
--  * Serialised with the Demo operator through the same advisory lock.
--
-- Review, then apply as the database owner (e.g. psql -v ON_ERROR_STOP=1 -f demo-metrics-additive.sql).
begin;
set local lock_timeout='10s';
set local statement_timeout='60s';
create function pg_temp.prodwise_demo_id(ws uuid,k text) returns uuid language sql immutable as $fn$
 select (substr(h,1,8)||'-'||substr(h,9,4)||'-4'||substr(h,14,3)||'-8'||substr(h,18,3)||'-'||substr(h,21,12))::uuid
 from (select encode(sha256(convert_to('prodwise-demo-only:'||ws::text||':'||k,'UTF8')),'hex') as h) x $fn$;
do $metrics$
declare
 payload constant jsonb := $payload$[
 {
  "key": "v2:metric:onboarding-time",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
  "name": "Median onboarding time",
  "definition": "Median elapsed days between completed merchant application and activation for the named rollout cohort.",
  "unit": "days",
  "formula": "Median(activation timestamp − completed application timestamp), expressed in days",
  "source_label": "Synthetic onboarding observation note",
  "period_grain": "Recorded weekly cohort",
  "timezone": "Africa/Cairo",
  "target_value": 3,
  "target_comparator": "AT_MOST",
  "target_owner_label": "Synthetic Operations owner",
  "target_approved_at": "2026-08-28T10:00:00.000Z",
  "target_note": "Synthetic target record supplied for the walkthrough; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-22T10:00:00.000Z",
  "observations": [
   {
    "key": "v2:metric-observation:time:launch",
    "period_start": "2026-09-10",
    "period_end": "2026-09-13",
    "value": 4.1,
    "captured_at": "2026-09-22T10:00:00.000Z",
    "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
    "note": "Synthetic observation. Partial launch period; compare with caution.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v2:metric-observation:time:week",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 3.4,
    "captured_at": "2026-09-22T10:00:00.000Z",
    "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
    "note": "Synthetic observation. Complete recorded weekly cohort.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v2:metric:first-transaction",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
  "name": "First transaction within seven days",
  "definition": "Share of newly activated merchants with a first accepted transaction within seven calendar days of activation.",
  "unit": "%",
  "formula": "Merchants with first accepted transaction within 7 days / activated cohort merchants × 100",
  "source_label": "Synthetic onboarding observation note",
  "period_grain": "Recorded weekly cohort",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": null,
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-22T10:00:00.000Z",
  "observations": [
   {
    "key": "v2:metric-observation:first:launch",
    "period_start": "2026-09-10",
    "period_end": "2026-09-13",
    "value": 48,
    "captured_at": "2026-09-22T10:00:00.000Z",
    "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
    "note": "Synthetic observation. Launch cohort's seven-day window completed; partial launch period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v2:metric-observation:first:week",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": null,
    "captured_at": "2026-09-22T10:00:00.000Z",
    "evidence_key": "v2:tap-to-pay-merchant-onboarding:evidence",
    "note": "Synthetic observation. Observation not recorded. Seven-day window completes 27 September; do not replace the missing value with zero.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ttp-gtv",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": null,
  "name": "Tap-to-Pay gross transaction value",
  "definition": "Total value of accepted Tap-to-Pay card transactions at onboarded merchants in the week. Declined, reversed and refunded transactions are excluded.",
  "unit": "EGP",
  "formula": "Σ accepted Tap-to-Pay transaction amount (EGP) in the period",
  "source_label": "Synthetic acquiring transaction export",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 4000000,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Acceptance business owner",
  "target_approved_at": "2026-08-28T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ttp-gtv:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 1420000,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 1610000,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 1780000,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 1950000,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 2120000,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 3050000,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Includes the first days of the full rollout (10 September).",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-gtv:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 4380000,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. First complete week of the full rollout.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ttp-transactions",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": null,
  "name": "Tap-to-Pay accepted transactions",
  "definition": "Count of accepted Tap-to-Pay card transactions at onboarded merchants in the week.",
  "unit": "transactions",
  "formula": "Count of accepted Tap-to-Pay transactions in the period",
  "source_label": "Synthetic acquiring transaction export",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 10000,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Acceptance business owner",
  "target_approved_at": "2026-08-28T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ttp-transactions:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 3880,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 4350,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 4720,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 5160,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 5540,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 7930,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Includes the first days of the full rollout (10 September).",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-transactions:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 11240,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. First complete week of the full rollout.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ttp-active-merchants",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": null,
  "name": "Active Tap-to-Pay merchants",
  "definition": "Onboarded merchants with at least one accepted Tap-to-Pay transaction in the week.",
  "unit": "merchants",
  "formula": "Distinct merchant IDs with ≥ 1 accepted Tap-to-Pay transaction in the period",
  "source_label": "Synthetic acquiring transaction export",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 600,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Acceptance business owner",
  "target_approved_at": "2026-08-28T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 212,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 236,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 251,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 268,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 284,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 402,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Includes the first days of the full rollout (10 September).",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-active-merchants:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 571,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. First complete week of the full rollout.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ttp-success-rate",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": null,
  "name": "Tap-to-Pay transaction success rate",
  "definition": "Share of Tap-to-Pay authorisation attempts that were approved. Merchant-cancelled attempts are excluded from the denominator.",
  "unit": "%",
  "formula": "Approved authorisations ÷ authorisation attempts (excluding merchant cancellations) × 100",
  "source_label": "Synthetic acquirer response log",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 97,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Payments Operations owner",
  "target_approved_at": "2026-08-28T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 96.1,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 96.4,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": null,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The acquirer response log export for this week was incomplete, so the rate was not calculated. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 96.9,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 97.2,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 95.8,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Includes the first days of the full rollout (10 September).",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-success-rate:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 96.6,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. First complete week of the full rollout.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ttp-average-value",
  "initiative_slug": "tap-to-pay-merchant-onboarding",
  "evidence_key": null,
  "name": "Average Tap-to-Pay transaction value",
  "definition": "Mean value of an accepted Tap-to-Pay transaction in the week. Monitored for context; no target is set.",
  "unit": "EGP",
  "formula": "Tap-to-Pay gross transaction value ÷ accepted Tap-to-Pay transactions",
  "source_label": "Synthetic acquiring transaction export",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": "Monitored for context only; no target has been proposed.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ttp-average-value:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 366,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 370,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 377,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 378,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 383,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pilot cohort week.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 385,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Includes the first days of the full rollout (10 September).",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ttp-average-value:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 390,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. First complete week of the full rollout.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:pwc-success-rate",
  "initiative_slug": "partner-wallet-checkout",
  "evidence_key": null,
  "name": "Partner wallet payment success rate",
  "definition": "Share of partner-wallet payment attempts at the terminal that complete with a receipt showing the correct merchant details.",
  "unit": "%",
  "formula": "Completed partner-wallet payments with a correct receipt ÷ partner-wallet payment attempts × 100",
  "source_label": "Synthetic partner wallet settlement file",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 97,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Payments Operations owner",
  "target_approved_at": "2026-09-15T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented. Measurement starts with the first live week after Target Live.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-15T10:00:00.000Z",
  "observations": []
 },
 {
  "key": "v3:metric:sct-raised",
  "initiative_slug": "service-complaint-tracker",
  "evidence_key": null,
  "name": "Complaints raised from the terminal",
  "definition": "Service complaints submitted by merchants from the terminal in the day. Complaints raised by phone are not included.",
  "unit": "complaints",
  "formula": "Count of complaints with channel = terminal created in the period",
  "source_label": "Synthetic complaint service export",
  "period_grain": "Daily · calendar day",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": "A target will be agreed at the 30-day live review; none is approved.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-26T06:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:sct-raised:2026-09-16",
    "period_start": "2026-09-16",
    "period_end": "2026-09-16",
    "value": 38,
    "captured_at": "2026-09-17T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-17",
    "period_start": "2026-09-17",
    "period_end": "2026-09-17",
    "value": 44,
    "captured_at": "2026-09-18T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-18",
    "period_start": "2026-09-18",
    "period_end": "2026-09-18",
    "value": 29,
    "captured_at": "2026-09-19T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Friday · weekend volume.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-19",
    "period_start": "2026-09-19",
    "period_end": "2026-09-19",
    "value": 26,
    "captured_at": "2026-09-20T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Saturday · weekend volume.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-20",
    "period_start": "2026-09-20",
    "period_end": "2026-09-20",
    "value": 47,
    "captured_at": "2026-09-21T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-21",
    "period_start": "2026-09-21",
    "period_end": "2026-09-21",
    "value": 52,
    "captured_at": "2026-09-22T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-22",
    "period_start": "2026-09-22",
    "period_end": "2026-09-22",
    "value": 49,
    "captured_at": "2026-09-23T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-23",
    "period_start": "2026-09-23",
    "period_end": "2026-09-23",
    "value": null,
    "captured_at": "2026-09-24T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The complaint service export failed for this day, so the count was not recorded. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-24",
    "period_start": "2026-09-24",
    "period_end": "2026-09-24",
    "value": 51,
    "captured_at": "2026-09-25T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-raised:2026-09-25",
    "period_start": "2026-09-25",
    "period_end": "2026-09-25",
    "value": 33,
    "captured_at": "2026-09-26T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Friday · weekend volume.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:sct-routing",
  "initiative_slug": "service-complaint-tracker",
  "evidence_key": null,
  "name": "Complaints routed correctly on first assignment",
  "definition": "Share of terminal complaints assigned to the owning team on their first assignment, without a manual re-route.",
  "unit": "%",
  "formula": "Complaints not re-routed after first assignment ÷ complaints raised from the terminal × 100",
  "source_label": "Synthetic complaint service export",
  "period_grain": "Daily · calendar day",
  "timezone": "Africa/Cairo",
  "target_value": 95,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Customer Support owner",
  "target_approved_at": "2026-09-10T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-26T06:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:sct-routing:2026-09-16",
    "period_start": "2026-09-16",
    "period_end": "2026-09-16",
    "value": 89.5,
    "captured_at": "2026-09-17T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-17",
    "period_start": "2026-09-17",
    "period_end": "2026-09-17",
    "value": 90.9,
    "captured_at": "2026-09-18T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-18",
    "period_start": "2026-09-18",
    "period_end": "2026-09-18",
    "value": 89.7,
    "captured_at": "2026-09-19T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-19",
    "period_start": "2026-09-19",
    "period_end": "2026-09-19",
    "value": 92.3,
    "captured_at": "2026-09-20T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-20",
    "period_start": "2026-09-20",
    "period_end": "2026-09-20",
    "value": 93.6,
    "captured_at": "2026-09-21T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-21",
    "period_start": "2026-09-21",
    "period_end": "2026-09-21",
    "value": 94.2,
    "captured_at": "2026-09-22T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-22",
    "period_start": "2026-09-22",
    "period_end": "2026-09-22",
    "value": 93.9,
    "captured_at": "2026-09-23T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-23",
    "period_start": "2026-09-23",
    "period_end": "2026-09-23",
    "value": null,
    "captured_at": "2026-09-24T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The complaint service export failed for this day, so the share was not calculated. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-24",
    "period_start": "2026-09-24",
    "period_end": "2026-09-24",
    "value": 94.1,
    "captured_at": "2026-09-25T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-routing:2026-09-25",
    "period_start": "2026-09-25",
    "period_end": "2026-09-25",
    "value": 93.9,
    "captured_at": "2026-09-26T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:sct-first-response",
  "initiative_slug": "service-complaint-tracker",
  "evidence_key": null,
  "name": "Median time to first response",
  "definition": "Median elapsed hours between a terminal complaint being raised and the owning team's first response.",
  "unit": "hours",
  "formula": "Median(first response timestamp − complaint created timestamp), in hours",
  "source_label": "Synthetic complaint service export",
  "period_grain": "Daily · calendar day",
  "timezone": "Africa/Cairo",
  "target_value": 4,
  "target_comparator": "AT_MOST",
  "target_owner_label": "Synthetic Customer Support owner",
  "target_approved_at": "2026-09-10T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-26T06:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-16",
    "period_start": "2026-09-16",
    "period_end": "2026-09-16",
    "value": 5.2,
    "captured_at": "2026-09-17T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-17",
    "period_start": "2026-09-17",
    "period_end": "2026-09-17",
    "value": 4.8,
    "captured_at": "2026-09-18T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-18",
    "period_start": "2026-09-18",
    "period_end": "2026-09-18",
    "value": 6.1,
    "captured_at": "2026-09-19T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-19",
    "period_start": "2026-09-19",
    "period_end": "2026-09-19",
    "value": 6.4,
    "captured_at": "2026-09-20T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-20",
    "period_start": "2026-09-20",
    "period_end": "2026-09-20",
    "value": 4.1,
    "captured_at": "2026-09-21T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-21",
    "period_start": "2026-09-21",
    "period_end": "2026-09-21",
    "value": 3.9,
    "captured_at": "2026-09-22T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-22",
    "period_start": "2026-09-22",
    "period_end": "2026-09-22",
    "value": 3.8,
    "captured_at": "2026-09-23T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-23",
    "period_start": "2026-09-23",
    "period_end": "2026-09-23",
    "value": null,
    "captured_at": "2026-09-24T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The complaint service export failed for this day, so the median was not calculated. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-24",
    "period_start": "2026-09-24",
    "period_end": "2026-09-24",
    "value": 3.7,
    "captured_at": "2026-09-25T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:sct-first-response:2026-09-25",
    "period_start": "2026-09-25",
    "period_end": "2026-09-25",
    "value": 4.6,
    "captured_at": "2026-09-26T06:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Recorded period.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ies-disbursed",
  "initiative_slug": "installment-early-settlement",
  "evidence_key": null,
  "name": "Installment amount disbursed",
  "definition": "Principal disbursed to merchants on new installment plans in the month.",
  "unit": "EGP",
  "formula": "Σ principal of installment plans disbursed in the period",
  "source_label": "Synthetic lending ledger extract",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": 22000000,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Lending business owner",
  "target_approved_at": "2026-02-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ies-disbursed:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 18600000,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-disbursed:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 19900000,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-disbursed:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 21400000,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-disbursed:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 20800000,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-disbursed:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 23100000,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-disbursed:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 24500000,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ies-borrowers",
  "initiative_slug": "installment-early-settlement",
  "evidence_key": null,
  "name": "Active installment borrowers",
  "definition": "Merchants with an outstanding installment balance at month end. A point-in-time count, not a monthly flow.",
  "unit": "borrowers",
  "formula": "Distinct merchants with outstanding principal > 0 at 23:59 on the last day of the period",
  "source_label": "Synthetic lending ledger extract",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": 4000,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Lending business owner",
  "target_approved_at": "2026-02-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ies-borrowers:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 3410,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-borrowers:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 3560,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-borrowers:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 3720,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-borrowers:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 3805,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-borrowers:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 3960,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-borrowers:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 4120,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ies-collection-rate",
  "initiative_slug": "installment-early-settlement",
  "evidence_key": null,
  "name": "Installment collection rate",
  "definition": "Share of installment amounts falling due in the month that were collected from settlements by month end.",
  "unit": "%",
  "formula": "Amount collected against installments due in the period ÷ amount due in the period × 100",
  "source_label": "Synthetic lending ledger extract",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": 97,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Lending business owner",
  "target_approved_at": "2026-02-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 96.8,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 97.1,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 96.5,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 95.9,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 96.2,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-collection-rate:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 96.4,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ies-overdue",
  "initiative_slug": "installment-early-settlement",
  "evidence_key": null,
  "name": "Overdue rate (30+ days)",
  "definition": "Share of outstanding installment principal that is 30 or more days past due at month end. A point-in-time rate.",
  "unit": "%",
  "formula": "Outstanding principal ≥ 30 days past due ÷ total outstanding principal × 100, at period end",
  "source_label": "Synthetic month-end portfolio snapshot",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": 3,
  "target_comparator": "AT_MOST",
  "target_owner_label": "Synthetic Credit Risk owner",
  "target_approved_at": "2026-02-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ies-overdue:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 2.9,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-overdue:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 2.8,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-overdue:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 3.1,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-overdue:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 3.4,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-overdue:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": null,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The July month-end portfolio snapshot was not recorded, so the rate was not calculated. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-overdue:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 3.3,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:ies-requests",
  "initiative_slug": "installment-early-settlement",
  "evidence_key": null,
  "name": "Early settlement requests handled manually",
  "definition": "Merchant requests to settle an installment plan early that Operations processed by hand in the month.",
  "unit": "requests",
  "formula": "Count of early settlement requests closed by Operations in the period",
  "source_label": "Synthetic operations request log",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": "A reduction target was proposed by the Synthetic Lending business owner; it has not been approved.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:ies-requests:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 118,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-requests:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 126,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-requests:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 131,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-requests:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 140,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-requests:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 152,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:ies-requests:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 149,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the existing installment product; this initiative is not live, so these values are not its results.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:crr-on-time",
  "initiative_slug": "collections-reporting-rebuild",
  "evidence_key": null,
  "name": "Collections pack delivered by 09:00",
  "definition": "Share of business days in the week on which the legacy daily collections pack reached Operations by 09:00 Cairo time.",
  "unit": "%",
  "formula": "Business days with pack delivered by 09:00 ÷ business days in the period × 100",
  "source_label": "Synthetic report distribution log",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 95,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Collections Operations owner",
  "target_approved_at": "2026-08-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:crr-on-time:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 80,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 100,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 60,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 80,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 100,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 80,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-on-time:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 60,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:crr-reconciliation",
  "initiative_slug": "collections-reporting-rebuild",
  "evidence_key": null,
  "name": "Manual reconciliation effort",
  "definition": "Hours Operations spent reconciling the legacy collections pack against the ledger in the week.",
  "unit": "hours",
  "formula": "Σ timesheet hours booked to collections reconciliation in the period",
  "source_label": "Synthetic Operations timesheet extract",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": null,
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 14.5,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 12,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 16.5,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": null,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Not recorded. The timesheet extract was not submitted for this week, so the hours were not recorded. Missing is not zero.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 13,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 15.5,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:crr-reconciliation:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 17,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the legacy collections pack; the rebuilt pack is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:mia-statements",
  "initiative_slug": "merchant-insights-app",
  "evidence_key": null,
  "name": "Statement requests to Merchant Support",
  "definition": "Merchant requests for transaction or settlement statements received by Merchant Support in the week.",
  "unit": "requests",
  "formula": "Count of support tickets categorised as statement request, created in the period",
  "source_label": "Synthetic support ticket export",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 250,
  "target_comparator": "AT_MOST",
  "target_owner_label": "Synthetic Merchant Support owner",
  "target_approved_at": "2026-07-20T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented. Post-launch goal; the app is not live yet.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:mia-statements:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 412,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 398,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 431,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 405,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 446,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 452,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mia-statements:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 437,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Pre-launch baseline; the app is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:isp-next-day",
  "initiative_slug": "instant-settlement-payout",
  "evidence_key": null,
  "name": "Payouts settled next business day",
  "definition": "Share of merchant payouts credited by the end of the next business day under the current payout schedule.",
  "unit": "%",
  "formula": "Payouts credited by end of T+1 business day ÷ payouts due in the period × 100",
  "source_label": "Synthetic settlement payout report",
  "period_grain": "Weekly · Monday–Sunday",
  "timezone": "Africa/Cairo",
  "target_value": 98,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Settlement Operations owner",
  "target_approved_at": "2026-06-10T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-21T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:isp-next-day:2026-08-03",
    "period_start": "2026-08-03",
    "period_end": "2026-08-09",
    "value": 97.4,
    "captured_at": "2026-08-10T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-08-10",
    "period_start": "2026-08-10",
    "period_end": "2026-08-16",
    "value": 97.9,
    "captured_at": "2026-08-17T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-08-17",
    "period_start": "2026-08-17",
    "period_end": "2026-08-23",
    "value": 96.8,
    "captured_at": "2026-08-24T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-08-24",
    "period_start": "2026-08-24",
    "period_end": "2026-08-30",
    "value": 98.1,
    "captured_at": "2026-08-31T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-08-31",
    "period_start": "2026-08-31",
    "period_end": "2026-09-06",
    "value": 97.6,
    "captured_at": "2026-09-07T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-09-07",
    "period_start": "2026-09-07",
    "period_end": "2026-09-13",
    "value": 98.3,
    "captured_at": "2026-09-14T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:isp-next-day:2026-09-14",
    "period_start": "2026-09-14",
    "period_end": "2026-09-20",
    "value": 97.9,
    "captured_at": "2026-09-21T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline of the current payout schedule; same-day payout is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:kyc-current",
  "initiative_slug": "merchant-kyc-refresh",
  "evidence_key": null,
  "name": "Merchants with current identity verification",
  "definition": "Share of active merchants whose identity verification is within its validity period at month end. A point-in-time rate.",
  "unit": "%",
  "formula": "Active merchants with unexpired verification ÷ active merchants × 100, at period end",
  "source_label": "Synthetic merchant registry snapshot",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": 98,
  "target_comparator": "AT_LEAST",
  "target_owner_label": "Synthetic Compliance owner",
  "target_approved_at": "2026-02-24T10:00:00.000Z",
  "target_note": "Synthetic target record; no live business approval represented.",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:kyc-current:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 91.8,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-current:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 91.2,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-current:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 90.6,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-current:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 90.1,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-current:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 89.7,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-current:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 89.2,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:kyc-reverification-time",
  "initiative_slug": "merchant-kyc-refresh",
  "evidence_key": null,
  "name": "Median re-verification time",
  "definition": "Median days from a merchant's re-verification request to a completed verification, for requests completed in the month.",
  "unit": "days",
  "formula": "Median(verification completed − re-verification requested), in days",
  "source_label": "Synthetic merchant registry snapshot",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": null,
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 9.5,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 10,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 11.5,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 10.5,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 12,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:kyc-reverification-time:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 12.5,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Baseline before the refresh; no re-verification campaign is live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:mpu-fee-revenue",
  "initiative_slug": "merchant-pricing-update",
  "evidence_key": null,
  "name": "Merchant service fee revenue",
  "definition": "Merchant service fees earned on accepted card transactions in the month, before refunds of fees.",
  "unit": "EGP",
  "formula": "Σ merchant service fee charged on accepted transactions in the period",
  "source_label": "Synthetic fee revenue ledger",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": "No target approved: it depends on the open fee rate decision (1.50% or 1.75%).",
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 4120000,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 4300000,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 4510000,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 4440000,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 4830000,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-fee-revenue:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 5020000,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 },
 {
  "key": "v3:metric:mpu-blended-rate",
  "initiative_slug": "merchant-pricing-update",
  "evidence_key": null,
  "name": "Blended merchant fee rate",
  "definition": "Merchant service fee revenue as a share of accepted card transaction value in the month.",
  "unit": "%",
  "formula": "Merchant service fee revenue ÷ accepted card transaction value × 100",
  "source_label": "Synthetic fee revenue ledger",
  "period_grain": "Calendar month",
  "timezone": "Africa/Cairo",
  "target_value": null,
  "target_comparator": null,
  "target_owner_label": null,
  "target_approved_at": null,
  "target_note": null,
  "origin": "SYNTHETIC_DEMO",
  "revision": 1,
  "updated_at": "2026-09-05T09:00:00.000Z",
  "observations": [
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-03-01",
    "period_start": "2026-03-01",
    "period_end": "2026-03-31",
    "value": 1.48,
    "captured_at": "2026-04-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-04-01",
    "period_start": "2026-04-01",
    "period_end": "2026-04-30",
    "value": 1.49,
    "captured_at": "2026-05-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-05-01",
    "period_start": "2026-05-01",
    "period_end": "2026-05-31",
    "value": 1.47,
    "captured_at": "2026-06-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-06-01",
    "period_start": "2026-06-01",
    "period_end": "2026-06-30",
    "value": 1.48,
    "captured_at": "2026-07-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-07-01",
    "period_start": "2026-07-01",
    "period_end": "2026-07-31",
    "value": 1.49,
    "captured_at": "2026-08-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   },
   {
    "key": "v3:metric-observation:mpu-blended-rate:2026-08-01",
    "period_start": "2026-08-01",
    "period_end": "2026-08-31",
    "value": 1.48,
    "captured_at": "2026-09-05T09:00:00.000Z",
    "evidence_key": null,
    "note": "Synthetic observation. Current fee schedule; the pricing update is not live.",
    "origin": "SYNTHETIC_DEMO"
   }
  ]
 }
]$payload$::jsonb;
 ws uuid; org uuid; n integer; spec jsonb; ob jsonb; iid uuid; eid uuid; oeid uuid; mid uuid; obid uuid;
 d public.metric_definitions; o public.metric_observations;
 new_definitions integer := 0; same_definitions integer := 0; new_observations integer := 0; same_observations integer := 0;
begin
 perform pg_advisory_xact_lock(13142026);
 select count(*) into n from public.demo_entry_config;
 if n<>1 then raise exception 'DEMO_ENTRY_CONFIG_REQUIRED'; end if;
 select w.id,org_row.id into ws,org
 from public.demo_entry_config c
 join public.workspaces w on w.id=c.workspace_id and w.status='ACTIVE'
 join public.organizations org_row on org_row.id=w.organization_id and org_row.status='ACTIVE' and org_row.name='Prodwise Demo'
 join public.demo_scenarios s on s.workspace_id=w.id and s.organization_id=org_row.id
 where s.canonical_version='prodwise-graduation-2026-09-v1' and s.scenario_at='2026-09-26T10:00:00.000Z'::timestamptz;
 if ws is null then raise exception 'DEMO_ENTRY_NOT_REGISTERED_ACTIVE_DEMO'; end if;
 select count(*) into n from public.demo_scenarios s
 join public.workspaces w on w.id=s.workspace_id and w.organization_id=s.organization_id and w.status='ACTIVE'
 join public.organizations org_row on org_row.id=s.organization_id and org_row.status='ACTIVE';
 if n<>1 then raise exception 'DEMO_ACTIVE_GENERATION_NOT_UNIQUE: % active registered Demo generations', n; end if;
 perform 1 from public.workspaces where id=ws for share;
 for spec in select value from jsonb_array_elements(payload) loop
  select count(*),min(i.id::text)::uuid into n,iid from public.initiatives i
   where i.workspace_id=ws and i.slug=spec->>'initiative_slug' and i.is_demo and i.archived_at is null;
  if n<>1 then raise exception 'DEMO_METRIC_INITIATIVE_MISSING: %', spec->>'initiative_slug'; end if;
  eid := case when spec->>'evidence_key' is null then null else pg_temp.prodwise_demo_id(ws,spec->>'evidence_key') end;
  if eid is not null and not exists(select 1 from public.evidence e where e.id=eid and e.workspace_id=ws and e.initiative_id=iid) then
   raise exception 'DEMO_METRIC_SOURCE_MISSING: %', spec->>'name'; end if;
  mid := pg_temp.prodwise_demo_id(ws,spec->>'key');
  select * into d from public.metric_definitions where id=mid;
  if found then
   if (d.workspace_id,d.organization_id,d.initiative_id,d.name,d.definition,d.unit,d.formula,d.source_label,d.source_evidence_id,d.period_grain,d.timezone,
       d.target_value,d.target_comparator,d.target_owner_label,d.target_approved_at,d.target_note,d.origin,d.revision,d.updated_at)
      is distinct from
      (ws,org,iid,spec->>'name',spec->>'definition',spec->>'unit',spec->>'formula',spec->>'source_label',eid,spec->>'period_grain',spec->>'timezone',
       (spec->>'target_value')::numeric,spec->>'target_comparator',spec->>'target_owner_label',(spec->>'target_approved_at')::timestamptz,spec->>'target_note',
       spec->>'origin',(spec->>'revision')::integer,(spec->>'updated_at')::timestamptz) then
    raise exception 'DEMO_METRIC_CONTENT_DIFFERS: definition %', spec->>'name';
   end if;
   same_definitions := same_definitions+1;
  else
   insert into public.metric_definitions(id,organization_id,workspace_id,initiative_id,name,definition,unit,formula,source_label,source_evidence_id,period_grain,timezone,
    target_value,target_comparator,target_owner_label,target_approved_at,target_note,origin,revision,updated_at)
   values(mid,org,ws,iid,spec->>'name',spec->>'definition',spec->>'unit',spec->>'formula',spec->>'source_label',eid,spec->>'period_grain',spec->>'timezone',
    (spec->>'target_value')::numeric,spec->>'target_comparator',spec->>'target_owner_label',(spec->>'target_approved_at')::timestamptz,spec->>'target_note',
    spec->>'origin',(spec->>'revision')::integer,(spec->>'updated_at')::timestamptz);
   new_definitions := new_definitions+1;
  end if;
  for ob in select value from jsonb_array_elements(spec->'observations') loop
   obid := pg_temp.prodwise_demo_id(ws,ob->>'key');
   oeid := case when ob->>'evidence_key' is null then null else pg_temp.prodwise_demo_id(ws,ob->>'evidence_key') end;
   if exists(select 1 from public.metric_observations x where x.metric_id=mid and x.period_start=(ob->>'period_start')::date and x.period_end=(ob->>'period_end')::date and x.id<>obid) then
    raise exception 'DEMO_METRIC_CONTENT_DIFFERS: % period % recorded under another id', spec->>'name', ob->>'period_start';
   end if;
   select * into o from public.metric_observations where id=obid;
   if found then
    if (o.metric_id,o.workspace_id,o.period_start,o.period_end,o.value,o.captured_at,o.source_evidence_id,o.note,o.origin)
       is distinct from
       (mid,ws,(ob->>'period_start')::date,(ob->>'period_end')::date,(ob->>'value')::numeric,(ob->>'captured_at')::timestamptz,oeid,ob->>'note',ob->>'origin') then
     raise exception 'DEMO_METRIC_CONTENT_DIFFERS: % period %', spec->>'name', ob->>'period_start';
    end if;
    same_observations := same_observations+1;
   else
    insert into public.metric_observations(id,metric_id,workspace_id,period_start,period_end,value,captured_at,source_evidence_id,note,origin)
    values(obid,mid,ws,(ob->>'period_start')::date,(ob->>'period_end')::date,(ob->>'value')::numeric,(ob->>'captured_at')::timestamptz,oeid,ob->>'note',ob->>'origin');
    new_observations := new_observations+1;
   end if;
  end loop;
 end loop;
 raise notice 'DEMO_METRICS_ADDITIVE workspace=% definitions inserted=% unchanged=% observations inserted=% unchanged=%',ws,new_definitions,same_definitions,new_observations,same_observations;
end $metrics$;
commit;
