import {CommitmentSummary} from '@/components/initiative/CommitmentSummary';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {readManagement} from '@/lib/data/management-read';
import {readDelivery} from '@/lib/delivery/repository';
import {getRepository} from '@/lib/data';
import {buildPortfolioProjection} from '@/lib/workspace/portfolio';
import {deriveInstrumentSnapshot} from '@/lib/workspace/instrument';
import {SetupGuide} from '@/components/workspace/SetupGuide';
import {displayDate} from '@/lib/delivery/roadmap';
import {factFor} from '@/lib/delivery/model';
import {hasOrganizationAdminAuthority,canBusinessWrite} from '@/lib/auth/roles';
import {isDemoWriteEnabled} from '@/lib/env';
import {STAGE_LABEL} from '@/lib/domain/labels';
import {safeUserLabel} from '@/lib/demo/presentation';
import styles from './brief.module.css';
export const metadata={title:'Brief'};export const dynamic='force-dynamic';
export default async function Brief({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const [d,management]=await Promise.all([readDelivery(),readManagement()]);const snapshot=d.source.snapshots.find(s=>s.initiative.slug===slug);if(!snapshot)notFound();const activity=await getRepository().listActivity(snapshot.initiative.id,50);const p=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,activity,management,asOf:d.presentation.scenarioAt??new Date().toISOString()});const r=p.rows.find(r=>r.initiative.slug===slug)!;const base=`/initiatives/${slug}`;const get=(kind:Parameters<typeof factFor>[2])=>factFor(d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId),r.initiative.id,kind);const instrument=deriveInstrumentSnapshot(snapshot);const scope=get('SCOPE');const risks=snapshot.claims.filter(c=>c.status==='ACTIVE'&&['RISK','DEPENDENCY'].includes(c.type));const writer=!r.initiative.archivedAt&&canBusinessWrite(d.ctx)&&isDemoWriteEnabled;const factWriter=writer&&(hasOrganizationAdminAuthority(d.ctx)||r.ownerId===d.ctx.memberId);
 return <div className={styles.page}><div className={styles.dossier}>
 <section className={styles.current} aria-labelledby="current-state"><div className={styles.sectionHead}><h2 id="current-state">Current state</h2><span>{STAGE_LABEL[r.initiative.stage]}</span></div>{r.initiative.description&&<p className={styles.description}>{r.initiative.description}</p>}<dl><dt>Current scope / phase</dt><dd>{management.contexts.find(c=>c.id===r.initiative.currentContextId&&!c.retiredAt)?.label??(scope?.value.text?`Legacy scope: ${scope.value.text}`:'Not recorded')}</dd><dt>Recorded next step</dt><dd>{r.nextStep?.value.text??'Not recorded'}{r.nextStep&&<small>{r.nextStep.preparedAsFixture?'Prepared by':'Confirmed by'} {safeUserLabel(r.nextStep)} · {displayDate(r.nextStep.updatedAt.slice(0,10))}</small>}</dd></dl><p className={styles.coverage}>{r.coverage.label}</p></section>
 <section className={styles.attention} aria-label="Initiative attention"><div className={styles.sectionHead}><h2>Needs attention</h2><span>{r.attention.length} recorded reasons</span></div>{r.attention.length?<ul>{r.attention.map((a,n)=><li key={n}><strong>{a.label}</strong><p>{a.detail}</p><Link prefetch={false} href={a.href}>{a.kind==='DECISION'?'Review decision':'Inspect confirmation'} →</Link></li>)}</ul>:<p className={styles.empty}>No open differences or delivery attention under the current checks. This is not a readiness assessment.</p>}<div className={styles.coverage}><strong>{r.setup.label} · {r.setup.completed} of {r.setup.total}</strong><p>{r.setup.next?.detail??'Setup coverage does not imply release approval.'}</p><Link href={`${base}/setup?step=review`}>{r.setup.ready?'Review setup':'Complete setup'} →</Link></div></section>
 <aside className={styles.context} aria-label="Initiative delivery facts"><h2>Delivery facts</h2><dl className={styles.factGrid}><div><dt>Owner</dt><dd>{r.ownerLabel}</dd></div><div><dt>Target Live · planned</dt><dd>{displayDate(r.target?.value.date)}{r.targetMovement&&<small>Moved {r.targetMovement.days>0?'+':''}{r.targetMovement.days} d from {displayDate(r.targetMovement.from)} · <Link prefetch={false} href={`${base}/delivery#target-history`}>History</Link></small>}</dd></div><div><dt>Actual Live</dt><dd>{r.actual?.value.date?displayDate(r.actual.value.date):'Not recorded'}{r.actual&&<small>{r.actual.value.extent==='PARTIAL'?`Partial · ${r.actual.value.text}`:'Full named scope'}</small>}</dd></div><div><dt>Next milestone</dt><dd>{r.milestone?.value.text??'Not recorded'}{r.milestone&&<small>{r.milestone.value.date?displayDate(r.milestone.value.date):'Date unknown'}</small>}</dd></div><div><dt>Development start</dt><dd>{displayDate(get('DEV_STARTED')?.value.date)}</dd></div></dl><Link prefetch={false} className={factWriter?styles.primary:styles.contextLink} href={`${base}/delivery?returnTo=${encodeURIComponent(base)}`}>{factWriter?'Update delivery facts':'View delivery facts'}</Link><p className={styles.note}>Missing Actual Live does not establish whether the initiative launched.</p><div className={styles.recordLinks}><Link prefetch={false} href={`${base}/knowledge`}>Knowledge · {snapshot.claims.filter(c=>c.status==='ACTIVE').length} confirmed entries</Link><Link prefetch={false} href={`${base}/sources`}>Sources · {snapshot.evidence.length} recorded</Link><Link prefetch={false} href="/roadmap">Portfolio Roadmap →</Link></div></aside>
 <section className={styles.changes} aria-labelledby="changed"><div className={styles.sectionHead}><h2 id="changed">What changed {p.baseline?`since ${p.baseline.week.replace(/^\d{4}-/,'')} Final`:''}</h2><Link prefetch={false} href="/weekly-review">Weekly Review →</Link></div>{p.changes.filter(c=>c.initiativeId===r.initiative.id).length?<ul>{p.changes.filter(c=>c.initiativeId===r.initiative.id).slice(0,6).map(c=><li key={c.id}><Link prefetch={false} href={c.href}>{c.sentence}</Link><small>{c.actorLabel} · {displayDate(c.occurredAt.slice(0,10))}</small></li>)}</ul>:<p className={styles.empty}>No recent changes recorded in this comparison.</p>}</section>
 <section className={styles.risks} aria-labelledby="risks"><div className={styles.sectionHead}><h2 id="risks">Recorded risks and dependencies</h2></div>{risks.length?<ul>{risks.map(c=><li key={c.id}><span>{c.type==='RISK'?'Risk':'Dependency'}</span><Link prefetch={false} href={`${base}/knowledge#claim-${c.id}`}><strong>{c.subject}</strong><p>{c.value}</p></Link></li>)}</ul>:<p className={styles.empty}>No risks or dependencies have been recorded.</p>}</section>
 <CommitmentSummary source={d.source} ctx={d.ctx} facts={d.state.facts} initiativeId={r.initiative.id}/></div></div>;
}
