import {factDate} from '@/lib/delivery/display';
import {notCompared} from '@/lib/review/applicability';
import {CommitmentSummary} from '@/components/initiative/CommitmentSummary';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {readManagement} from '@/lib/data/management-read';
import {readDelivery} from '@/lib/delivery/repository';
import {getRepository} from '@/lib/data';
import {buildPortfolioProjection} from '@/lib/workspace/portfolio';
import {deriveInstrumentSnapshot} from '@/lib/workspace/instrument';
import {SetupGuide} from '@/components/workspace/SetupGuide';
import {displayDate} from '@/lib/delivery/roadmap';
import {factFor} from '@/lib/delivery/model';
import {hasOrganizationAdminAuthority,canBusinessWrite} from '@/lib/auth/roles';
import {isDemoWriteEnabled} from '@/lib/env';
import {STAGE_LABEL} from '@/lib/domain/labels';
import {safeUserLabel} from '@/lib/demo/presentation';
import {readRelationships} from '@/lib/data/relationships';
import {readQuestions} from '@/lib/data/questions';
import {readRisks} from '@/lib/data/risks';
import {riskViews,RISK_STATUS_LABEL} from '@/lib/workspace/risks';
import {questionOverdueDays} from '@/lib/workspace/questions';
import {relationshipsFor,GROUP_LABEL} from '@/lib/workspace/relationship-view';
import styles from './brief.module.css';
export const metadata={title:'Brief'};export const dynamic='force-dynamic';
export default async function Brief({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const [d,management,rel,qs,rs]=await Promise.all([readDelivery(),readManagement(),readRelationships(),readQuestions(),readRisks()]);const snapshot=d.source.snapshots.find(s=>s.initiative.slug===slug);if(!snapshot)notFound();const activity=await getRepository().listActivity(snapshot.initiative.id,50);const p=buildPortfolioProjection({source:d.source,state:d.state,workspaceId:d.ctx.workspaceId,activity,management,relationships:rel.relationships,asOf:d.presentation.scenarioAt??new Date().toISOString()});const r=p.rows.find(r=>r.initiative.slug===slug)!;const base=`/initiatives/${slug}`;const get=(kind:Parameters<typeof factFor>[2])=>factFor(d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId),r.initiative.id,kind);const instrument=deriveInstrumentSnapshot(snapshot);const scope=get('SCOPE');const today=(d.presentation.scenarioAt??new Date().toISOString()).slice(0,10);const riskRows=riskViews(snapshot.claims.map(c=>({id:c.id,initiativeId:snapshot.initiative.id,type:c.type,status:c.status,subject:c.subject,value:c.value,supersededByClaimId:c.supersededByClaimId??null})),rs.tracking.filter(t=>t.initiativeId===snapshot.initiative.id),snapshot.initiative.id).filter(v=>v.state!=='SUPERSEDED'&&(!v.tracking||['OPEN','MITIGATING'].includes(v.tracking.status)));const openQs=qs.questions.filter(q=>q.initiativeId===snapshot.initiative.id&&q.status==='OPEN').map(q=>({q,overdue:questionOverdueDays(q,today)})).sort((a,b)=>(b.overdue??-1)-(a.overdue??-1));const relRows=relationshipsFor(r.initiative.id,rel.relationships,d.source.snapshots.map(x=>({id:x.initiative.id,name:x.initiative.name,slug:x.initiative.slug,archived:Boolean(x.initiative.archivedAt)})),d.state.facts.filter(f=>f.workspaceId===d.ctx.workspaceId));const writer=!r.initiative.archivedAt&&canBusinessWrite(d.ctx)&&isDemoWriteEnabled;const factWriter=writer&&(hasOrganizationAdminAuthority(d.ctx)||r.ownerId===d.ctx.memberId);
 return <div className={styles.page}><div className={styles.dossier}>
 <section className={styles.current} aria-labelledby="current-state"><div className={styles.sectionHead}><h2 id="current-state">Current state</h2><span>{STAGE_LABEL[r.initiative.stage]}</span></div><p className={styles.statement}>{/* Composed only from recorded facts; it is not a readiness judgement. */}In <strong>{STAGE_LABEL[r.initiative.stage]}</strong>. {r.attention.length?<><strong>{r.attention.length} recorded {r.attention.length===1?'reason needs':'reasons need'} attention</strong>, starting with {r.attention[0]!.label.toLowerCase()}. </>:'No recorded attention reasons under the current checks. '}Target Live {r.target?.value.date?<strong>{factDate(r.target)}</strong>:'not recorded'}{r.milestone?.value.text?<>; next milestone {r.milestone.value.text}{r.milestone.value.date?` on ${factDate(r.milestone)}`:''}</>:''}.</p>{r.initiative.description&&<p className={styles.description}><span className={styles.label}>Objective</span> {r.initiative.description}</p>}<dl><dt>Current scope / phase</dt><dd>{management.contexts.find(c=>c.id===r.initiative.currentContextId&&!c.retiredAt)?.label??(scope?.value.text?`Legacy scope: ${scope.value.text}`:'Not recorded')}</dd><dt>Relationships</dt><dd>{relRows.length?<ul className={styles.relations}>{relRows.map(x=><li key={x.relationship.id}><span>{GROUP_LABEL[x.group]}</span> {x.other?<Link prefetch={false} href={`/initiatives/${x.other.slug}`}>{x.other.name}</Link>:'An initiative you can’t access'}{x.other?.archived&&' · archived'}{x.group==='DEPENDS_ON'&&x.impactText&&<small className={x.late?styles.late:undefined}>{x.late?'▲ ':''}{x.impactText}</small>}</li>)}</ul>:'None recorded'}<small><Link prefetch={false} href={`${base}/manage?section=relationships#relationships`}>{relRows.length?'Manage relationships':'Record a relationship'} →</Link></small></dd><dt>Recorded next step</dt><dd>{r.nextStep?.value.text??'Not recorded'}{r.nextStep&&<small>{r.nextStep.preparedAsFixture?'Prepared by':'Confirmed by'} {safeUserLabel(r.nextStep)} · {displayDate(r.nextStep.updatedAt.slice(0,10))}</small>}</dd></dl><p className={styles.coverage}>{r.coverage.label}</p></section>
 <section id="attention" className={styles.attention} aria-label="Initiative attention">{notCompared(snapshot.claims).length>0&&<p>Some Knowledge entries were not compared because applicability differs or is not recorded. <Link href={`${base}/knowledge?view=all`}>Review applicability</Link></p>}<div className={styles.sectionHead}><h2>Needs attention</h2><span>{r.attention.length} recorded {r.attention.length===1?'reason':'reasons'}</span></div>{r.attention.length?<ul>{r.attention.map((a,n)=><li key={n}><strong>{a.label}</strong><p>{a.detail}</p><Link prefetch={false} href={a.href}>{a.kind==='DECISION'?'Review decision':a.kind==='DEPENDENCY'?'Review dependency':'Inspect record'} →</Link></li>)}</ul>:<p className={styles.empty}>No open differences or delivery attention under the current checks. This is not a readiness assessment.</p>}<div className={styles.coverage}><strong>{r.setup.label} · {r.setup.completed} of {r.setup.total}</strong><p>{r.setup.next?.detail??'Setup coverage does not imply release approval.'}</p><Link href={`${base}/setup?step=review`}>{r.setup.ready?'Review setup':'Complete setup'} →</Link></div></section>
 <aside className={styles.context} aria-label="Initiative delivery facts"><h2>Delivery facts</h2><dl className={styles.factGrid}><div><dt>Owner</dt><dd>{r.ownerLabel}</dd></div><div><dt>Target Live · planned</dt><dd>{factDate(r.target)}{r.targetMovement&&<small>Moved {r.targetMovement.days>0?'+':''}{r.targetMovement.days} d from {displayDate(r.targetMovement.from)} · <Link prefetch={false} href={`${base}/delivery#target-history`}>History</Link></small>}</dd></div><div><dt>Actual Live</dt><dd>{r.actual?.value.date?factDate(r.actual):'Not recorded'}{r.actual&&<small>{r.actual.value.extent==='PARTIAL'?`Partial · ${r.actual.value.text}`:'Full named scope'}</small>}</dd></div><div><dt>Next milestone</dt><dd>{r.milestone?.value.text??'Not recorded'}{r.milestone&&<small>{factDate(r.milestone)}</small>}</dd></div><div><dt>Development start</dt><dd>{displayDate(get('DEV_STARTED')?.value.date)}</dd></div></dl><Link prefetch={false} className={factWriter?styles.primary:styles.contextLink} href={`${base}/delivery?returnTo=${encodeURIComponent(base)}`}>{factWriter?'Update delivery facts':'View delivery facts'}</Link><p className={styles.note}>Missing Actual Live does not establish whether the initiative launched.</p><div className={styles.recordLinks}><Link prefetch={false} href={`${base}/knowledge`}>Knowledge · {snapshot.claims.filter(c=>c.status==='ACTIVE').length} confirmed entries</Link><Link prefetch={false} href={`${base}/sources`}>Sources · {snapshot.evidence.length} recorded</Link><Link prefetch={false} href="/roadmap">Portfolio Roadmap →</Link></div></aside>
 <section className={styles.changes} aria-labelledby="changed"><div className={styles.sectionHead}><h2 id="changed">What changed {p.baseline?`since ${p.baseline.week.replace(/^\d{4}-/,'')} Final`:''}</h2><span className={styles.headLinks}><Link prefetch={false} href={`${base}/history`}>Full history →</Link><Link prefetch={false} href="/weekly-review">Weekly Review →</Link></span></div>{p.changes.filter(c=>c.initiativeId===r.initiative.id).length?<ul>{p.changes.filter(c=>c.initiativeId===r.initiative.id).slice(0,6).map(c=><li key={c.id}><Link prefetch={false} href={c.href}>{c.sentence}</Link><small>{c.actorLabel} · {displayDate(c.occurredAt.slice(0,10))}</small></li>)}</ul>:<p className={styles.empty}>No recent changes recorded in this comparison.</p>}</section>
 <section className={styles.risks} aria-labelledby="risks"><div className={styles.sectionHead}><h2 id="risks">Risks & open questions</h2><Link prefetch={false} href={`${base}/context`}>View all →</Link></div>
  <div className={styles.riskColumns}><div><h3>Risks <span>{riskRows.length} open</span></h3>{riskRows.length?<ul>{riskRows.slice(0,3).map(v=><li key={v.claim.id}><span className={styles.riskState}>{v.state==='AWAITING_VERIFICATION'?'Awaiting verification':v.tracking?RISK_STATUS_LABEL[v.tracking.status]:'Open · not tracked'}</span><Link prefetch={false} href={`${base}/context#risk-${v.claim.id}`}><strong>{v.claim.subject}</strong> {v.claim.value}</Link></li>)}</ul>:<p className={styles.empty}>No risks recorded.</p>}</div>
  <div><h3>Open questions <span>{openQs.length}</span></h3>{openQs.length?<ul>{openQs.slice(0,3).map(({q,overdue})=><li key={q.id}><span className={overdue?styles.overdue:styles.riskState}>{overdue?`Overdue ${overdue} ${overdue===1?'day':'days'}`:q.dueDate?`Needed by ${displayDate(q.dueDate)}`:'Open'}</span><Link prefetch={false} href={`${base}/context#question-${q.id}`}>{q.question}</Link></li>)}</ul>:<p className={styles.empty}>No open questions.</p>}</div></div></section>
 <div className={styles.commitments}><CommitmentSummary source={d.source} ctx={d.ctx} facts={d.state.facts} initiativeId={r.initiative.id}/></div></div></div>;
}
