import type {MetricObservation,ProjectMetric} from "../analysis/metric-types.ts";
/** Fictional observations persisted by the reviewed Demo operator; never UI defaults. */
export function demoProjectMetrics(workspaceId:string,initiativeId:string,evidenceId:string,id:(key:string)=>string):ProjectMetric[] {
  const base={workspaceId,initiativeId,sourceLabel:"Synthetic onboarding observation note",sourceEvidenceId:evidenceId,periodGrain:"Recorded weekly cohort",timezone:"Africa/Cairo",origin:"SYNTHETIC_DEMO" as const,revision:1,updatedAt:"2026-09-22T10:00:00.000Z"};
  const obs=(key:string,periodStart:string,periodEnd:string,value:number|null,note:string)=>({id:id(`metric-observation:${key}`),periodStart,periodEnd,value,capturedAt:"2026-09-22T10:00:00.000Z",sourceEvidenceId:evidenceId,note:`Synthetic observation. ${note}`,origin:"SYNTHETIC_DEMO" as const});
  return [
    {...base,id:id("metric:onboarding-time"),name:"Median onboarding time",definition:"Median elapsed days between completed merchant application and activation for the named rollout cohort.",unit:"days",formula:"Median(activation timestamp − completed application timestamp), expressed in days",targetValue:3,targetComparator:"AT_MOST",targetOwnerLabel:"Synthetic Operations owner",targetApprovedAt:"2026-08-28T10:00:00.000Z",targetNote:"Synthetic target record supplied for the walkthrough; no live business approval represented.",observations:[obs("time:launch","2026-09-10","2026-09-13",4.1,"Partial launch period; compare with caution."),obs("time:week","2026-09-14","2026-09-20",3.4,"Complete recorded weekly cohort.")]},
    {...base,id:id("metric:first-transaction"),name:"First transaction within seven days",definition:"Share of newly activated merchants with a first accepted transaction within seven calendar days of activation.",unit:"%",formula:"Merchants with first accepted transaction within 7 days / activated cohort merchants × 100",targetValue:null,targetComparator:null,targetOwnerLabel:null,targetApprovedAt:null,targetNote:null,observations:[obs("first:launch","2026-09-10","2026-09-13",48,"Launch cohort's seven-day window completed; partial launch period."),obs("first:week","2026-09-14","2026-09-20",null,"Observation not recorded. Seven-day window completes 27 September; do not replace the missing value with zero.")]},
  ];
}

/* ── Demo v3 portfolio metrics ─────────────────────────────────────────────
   Fictional business measures for the enriched Demo portfolio. Every value is
   a synthetic record written for the walkthrough: related measures are kept
   internally consistent (GTV = transactions × average value, routed share =
   routed ÷ raised), a few periods are deliberately NOT recorded (null, never
   zero) and several measures have no approved target. Pre-launch initiatives
   carry baselines of the product area they change — labelled as such — and
   never results attributed to the initiative. */

type Target={value:number;comparator:"AT_MOST"|"AT_LEAST"|"EQUAL";owner:string;approvedAt:string;note?:string}|{value:null;note:string|null};
interface Spec {key:string;slug:string;name:string;definition:string;unit:string;formula:string;source:string;grain:string;target:Target;periods:readonly (readonly [string,string])[];values:readonly (number|null)[];missing?:string;notes?:Readonly<Record<number,string>>;baseline?:string}

const WEEKS=[["2026-08-03","2026-08-09"],["2026-08-10","2026-08-16"],["2026-08-17","2026-08-23"],["2026-08-24","2026-08-30"],["2026-08-31","2026-09-06"],["2026-09-07","2026-09-13"],["2026-09-14","2026-09-20"]] as const;
const MONTHS=[["2026-03-01","2026-03-31"],["2026-04-01","2026-04-30"],["2026-05-01","2026-05-31"],["2026-06-01","2026-06-30"],["2026-07-01","2026-07-31"],["2026-08-01","2026-08-31"]] as const;
const DAYS=["2026-09-16","2026-09-17","2026-09-18","2026-09-19","2026-09-20","2026-09-21","2026-09-22","2026-09-23","2026-09-24","2026-09-25"].map(d=>[d,d] as const);
const WEEKLY="Weekly · Monday–Sunday",MONTHLY="Calendar month",DAILY="Daily · calendar day";
const approved=(value:number,comparator:"AT_MOST"|"AT_LEAST"|"EQUAL",owner:string,approvedAt:string,note?:string):Target=>({value,comparator,owner,approvedAt,note});
/** Tap-to-Pay pilot weeks run until the full rollout recorded as Actual Live on 10 September. */
const TAP_CONTEXT:Record<number,string>={0:"Pilot cohort week.",1:"Pilot cohort week.",2:"Pilot cohort week.",3:"Pilot cohort week.",4:"Pilot cohort week.",5:"Includes the first days of the full rollout (10 September).",6:"First complete week of the full rollout."};
const LENDING_BASELINE="Baseline of the existing installment product; this initiative is not live, so these values are not its results.";

const SPECS:Spec[]=[
  // Tap-to-Pay Merchant Onboarding · payments acceptance · Actual Live 10 September.
  {key:"ttp-gtv",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay gross transaction value",definition:"Total value of accepted Tap-to-Pay card transactions at onboarded merchants in the week. Declined, reversed and refunded transactions are excluded.",unit:"EGP",formula:"Σ accepted Tap-to-Pay transaction amount (EGP) in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(4000000,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[1420000,1610000,1780000,1950000,2120000,3050000,4380000],notes:TAP_CONTEXT},
  {key:"ttp-transactions",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay accepted transactions",definition:"Count of accepted Tap-to-Pay card transactions at onboarded merchants in the week.",unit:"transactions",formula:"Count of accepted Tap-to-Pay transactions in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(10000,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[3880,4350,4720,5160,5540,7930,11240],notes:TAP_CONTEXT},
  {key:"ttp-active-merchants",slug:"tap-to-pay-merchant-onboarding",name:"Active Tap-to-Pay merchants",definition:"Onboarded merchants with at least one accepted Tap-to-Pay transaction in the week.",unit:"merchants",formula:"Distinct merchant IDs with ≥ 1 accepted Tap-to-Pay transaction in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(600,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[212,236,251,268,284,402,571],notes:TAP_CONTEXT},
  {key:"ttp-success-rate",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay transaction success rate",definition:"Share of Tap-to-Pay authorisation attempts that were approved. Merchant-cancelled attempts are excluded from the denominator.",unit:"%",formula:"Approved authorisations ÷ authorisation attempts (excluding merchant cancellations) × 100",source:"Synthetic acquirer response log",grain:WEEKLY,target:approved(97,"AT_LEAST","Synthetic Payments Operations owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[96.1,96.4,null,96.9,97.2,95.8,96.6],missing:"The acquirer response log export for this week was incomplete, so the rate was not calculated.",notes:TAP_CONTEXT},
  {key:"ttp-average-value",slug:"tap-to-pay-merchant-onboarding",name:"Average Tap-to-Pay transaction value",definition:"Mean value of an accepted Tap-to-Pay transaction in the week. Monitored for context; no target is set.",unit:"EGP",formula:"Tap-to-Pay gross transaction value ÷ accepted Tap-to-Pay transactions",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:{value:null,note:"Monitored for context only; no target has been proposed."},periods:WEEKS,values:[366,370,377,378,383,385,390],notes:TAP_CONTEXT},
  // Partner Wallet Checkout · acceptance · not live: definition and target exist, observations start after launch.
  {key:"pwc-success-rate",slug:"partner-wallet-checkout",name:"Partner wallet payment success rate",definition:"Share of partner-wallet payment attempts at the terminal that complete with a receipt showing the correct merchant details.",unit:"%",formula:"Completed partner-wallet payments with a correct receipt ÷ partner-wallet payment attempts × 100",source:"Synthetic partner wallet settlement file",grain:WEEKLY,target:approved(97,"AT_LEAST","Synthetic Payments Operations owner","2026-09-15T10:00:00.000Z","Measurement starts with the first live week after Target Live."),periods:[],values:[]},
  // Service Complaint Tracker · internal tool · Actual Live 16 September · daily observations.
  {key:"sct-raised",slug:"service-complaint-tracker",name:"Complaints raised from the terminal",definition:"Service complaints submitted by merchants from the terminal in the day. Complaints raised by phone are not included.",unit:"complaints",formula:"Count of complaints with channel = terminal created in the period",source:"Synthetic complaint service export",grain:DAILY,target:{value:null,note:"A target will be agreed at the 30-day live review; none is approved."},periods:DAYS,values:[38,44,29,26,47,52,49,null,51,33],missing:"The complaint service export failed for this day, so the count was not recorded.",notes:{2:"Friday · weekend volume.",3:"Saturday · weekend volume.",9:"Friday · weekend volume."}},
  {key:"sct-routing",slug:"service-complaint-tracker",name:"Complaints routed correctly on first assignment",definition:"Share of terminal complaints assigned to the owning team on their first assignment, without a manual re-route.",unit:"%",formula:"Complaints not re-routed after first assignment ÷ complaints raised from the terminal × 100",source:"Synthetic complaint service export",grain:DAILY,target:approved(95,"AT_LEAST","Synthetic Customer Support owner","2026-09-10T10:00:00.000Z"),periods:DAYS,values:[89.5,90.9,89.7,92.3,93.6,94.2,93.9,null,94.1,93.9],missing:"The complaint service export failed for this day, so the share was not calculated."},
  {key:"sct-first-response",slug:"service-complaint-tracker",name:"Median time to first response",definition:"Median elapsed hours between a terminal complaint being raised and the owning team's first response.",unit:"hours",formula:"Median(first response timestamp − complaint created timestamp), in hours",source:"Synthetic complaint service export",grain:DAILY,target:approved(4,"AT_MOST","Synthetic Customer Support owner","2026-09-10T10:00:00.000Z"),periods:DAYS,values:[5.2,4.8,6.1,6.4,4.1,3.9,3.8,null,3.7,4.6],missing:"The complaint service export failed for this day, so the median was not calculated."},
  // Installment Early Settlement · lending · in delivery: baseline of the existing installment product.
  {key:"ies-disbursed",slug:"installment-early-settlement",name:"Installment amount disbursed",definition:"Principal disbursed to merchants on new installment plans in the month.",unit:"EGP",formula:"Σ principal of installment plans disbursed in the period",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(22000000,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[18600000,19900000,21400000,20800000,23100000,24500000],baseline:LENDING_BASELINE},
  {key:"ies-borrowers",slug:"installment-early-settlement",name:"Active installment borrowers",definition:"Merchants with an outstanding installment balance at month end. A point-in-time count, not a monthly flow.",unit:"borrowers",formula:"Distinct merchants with outstanding principal > 0 at 23:59 on the last day of the period",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(4000,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[3410,3560,3720,3805,3960,4120],baseline:LENDING_BASELINE},
  {key:"ies-collection-rate",slug:"installment-early-settlement",name:"Installment collection rate",definition:"Share of installment amounts falling due in the month that were collected from settlements by month end.",unit:"%",formula:"Amount collected against installments due in the period ÷ amount due in the period × 100",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(97,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[96.8,97.1,96.5,95.9,96.2,96.4],baseline:LENDING_BASELINE},
  {key:"ies-overdue",slug:"installment-early-settlement",name:"Overdue rate (30+ days)",definition:"Share of outstanding installment principal that is 30 or more days past due at month end. A point-in-time rate.",unit:"%",formula:"Outstanding principal ≥ 30 days past due ÷ total outstanding principal × 100, at period end",source:"Synthetic month-end portfolio snapshot",grain:MONTHLY,target:approved(3,"AT_MOST","Synthetic Credit Risk owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[2.9,2.8,3.1,3.4,null,3.3],missing:"The July month-end portfolio snapshot was not recorded, so the rate was not calculated.",baseline:LENDING_BASELINE},
  {key:"ies-requests",slug:"installment-early-settlement",name:"Early settlement requests handled manually",definition:"Merchant requests to settle an installment plan early that Operations processed by hand in the month.",unit:"requests",formula:"Count of early settlement requests closed by Operations in the period",source:"Synthetic operations request log",grain:MONTHLY,target:{value:null,note:"A reduction target was proposed by the Synthetic Lending business owner; it has not been approved."},periods:MONTHS,values:[118,126,131,140,152,149],baseline:LENDING_BASELINE},
  // Collections Reporting Rebuild · reporting · in definition: baseline of the legacy pack.
  {key:"crr-on-time",slug:"collections-reporting-rebuild",name:"Collections pack delivered by 09:00",definition:"Share of business days in the week on which the legacy daily collections pack reached Operations by 09:00 Cairo time.",unit:"%",formula:"Business days with pack delivered by 09:00 ÷ business days in the period × 100",source:"Synthetic report distribution log",grain:WEEKLY,target:approved(95,"AT_LEAST","Synthetic Collections Operations owner","2026-08-24T10:00:00.000Z"),periods:WEEKS,values:[80,100,60,80,100,80,60],baseline:"Baseline of the legacy collections pack; the rebuilt pack is not live."},
  {key:"crr-reconciliation",slug:"collections-reporting-rebuild",name:"Manual reconciliation effort",definition:"Hours Operations spent reconciling the legacy collections pack against the ledger in the week.",unit:"hours",formula:"Σ timesheet hours booked to collections reconciliation in the period",source:"Synthetic Operations timesheet extract",grain:WEEKLY,target:{value:null,note:null},periods:WEEKS,values:[14.5,12,16.5,null,13,15.5,17],missing:"The timesheet extract was not submitted for this week, so the hours were not recorded.",baseline:"Baseline of the legacy collections pack; the rebuilt pack is not live."},
  // Merchant Insights App · in delivery: baseline of the support demand it aims to reduce.
  {key:"mia-statements",slug:"merchant-insights-app",name:"Statement requests to Merchant Support",definition:"Merchant requests for transaction or settlement statements received by Merchant Support in the week.",unit:"requests",formula:"Count of support tickets categorised as statement request, created in the period",source:"Synthetic support ticket export",grain:WEEKLY,target:approved(250,"AT_MOST","Synthetic Merchant Support owner","2026-07-20T10:00:00.000Z","Post-launch goal; the app is not live yet."),periods:WEEKS,values:[412,398,431,405,446,452,437],baseline:"Pre-launch baseline; the app is not live."},
  // Instant Settlement Payout · payments · release preparation: baseline of next-business-day payouts.
  {key:"isp-next-day",slug:"instant-settlement-payout",name:"Payouts settled next business day",definition:"Share of merchant payouts credited by the end of the next business day under the current payout schedule.",unit:"%",formula:"Payouts credited by end of T+1 business day ÷ payouts due in the period × 100",source:"Synthetic settlement payout report",grain:WEEKLY,target:approved(98,"AT_LEAST","Synthetic Settlement Operations owner","2026-06-10T10:00:00.000Z"),periods:WEEKS,values:[97.4,97.9,96.8,98.1,97.6,98.3,97.9],baseline:"Baseline of the current payout schedule; same-day payout is not live."},
  // Merchant KYC Refresh · onboarding / KYC · alignment: baseline of verification currency.
  {key:"kyc-current",slug:"merchant-kyc-refresh",name:"Merchants with current identity verification",definition:"Share of active merchants whose identity verification is within its validity period at month end. A point-in-time rate.",unit:"%",formula:"Active merchants with unexpired verification ÷ active merchants × 100, at period end",source:"Synthetic merchant registry snapshot",grain:MONTHLY,target:approved(98,"AT_LEAST","Synthetic Compliance owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[91.8,91.2,90.6,90.1,89.7,89.2],baseline:"Baseline before the refresh; no re-verification campaign is live."},
  {key:"kyc-reverification-time",slug:"merchant-kyc-refresh",name:"Median re-verification time",definition:"Median days from a merchant's re-verification request to a completed verification, for requests completed in the month.",unit:"days",formula:"Median(verification completed − re-verification requested), in days",source:"Synthetic merchant registry snapshot",grain:MONTHLY,target:{value:null,note:null},periods:MONTHS,values:[9.5,10,11.5,10.5,12,12.5],baseline:"Baseline before the refresh; no re-verification campaign is live."},
  // Merchant Pricing Update · finance · validation: current fee revenue, target depends on the open fee decision.
  {key:"mpu-fee-revenue",slug:"merchant-pricing-update",name:"Merchant service fee revenue",definition:"Merchant service fees earned on accepted card transactions in the month, before refunds of fees.",unit:"EGP",formula:"Σ merchant service fee charged on accepted transactions in the period",source:"Synthetic fee revenue ledger",grain:MONTHLY,target:{value:null,note:"No target approved: it depends on the open fee rate decision (1.50% or 1.75%)."},periods:MONTHS,values:[4120000,4300000,4510000,4440000,4830000,5020000],baseline:"Current fee schedule; the pricing update is not live."},
  {key:"mpu-blended-rate",slug:"merchant-pricing-update",name:"Blended merchant fee rate",definition:"Merchant service fee revenue as a share of accepted card transaction value in the month.",unit:"%",formula:"Merchant service fee revenue ÷ accepted card transaction value × 100",source:"Synthetic fee revenue ledger",grain:MONTHLY,target:{value:null,note:null},periods:MONTHS,values:[1.48,1.49,1.47,1.48,1.49,1.48],baseline:"Current fee schedule; the pricing update is not live."},
];

/* ── Demo v4 additions ─────────────────────────────────────────────────────
   Fictional measures for the V4 initiatives. Together with the V3 set they
   exercise every Analysis condition: AT_LEAST and AT_MOST targets met and
   missed, a series improving but still below target, one declining while
   still above it, an EQUAL target, a period that is "Not recorded" (null,
   never zero), fresh and stale capture dates (stale = last captured more than
   six weeks before the scenario date), sparse and dense series, a target
   approved days before the scenario date with no observation yet, and a long
   definition. Pre-launch initiatives carry labelled baselines only. */
const WEEKS_RECENT=WEEKS.slice(4) as unknown as readonly (readonly [string,string])[];
/** Stale example: monthly periods that end in June, last captured in early July — well over six weeks before the scenario date. */
const MONTHS_STALE=MONTHS.slice(0,4) as unknown as readonly (readonly [string,string])[];
const FIRMWARE_CONTEXT:Record<number,string>={5:"Includes the first days of wave 1 (12 September).",6:"First complete week with wave 1 live in two regions."};
const LONG_DEFINITION="Merchants that accepted at least one card transaction in the calendar month, counted once regardless of the number of terminals. A merchant is counted from the first accepted transaction after activation and stops being counted in the first full month with no accepted transaction. Refunds, reversals and declined attempts do not count as acceptance. Merchants suspended for compliance reasons during the month are excluded for that month even if they transacted before the suspension. Franchise groups are counted per outlet, not per brand, because points will be awarded per outlet. This baseline describes the card acceptance population the loyalty scheme will address; it is not a result of the scheme, which is not live.";
const SPECS_V4:Spec[]=[
  // Merchant Flex Finance · showcase · not live: the eligible pool for the pilot cap, and settlement cadence as context for the divisor review.
  {key:"mff-eligible",slug:"merchant-flex-finance",name:"Merchants eligible for the financing pilot",definition:"Active merchants meeting the pilot eligibility rule at week end: at least six months of continuous settlement activity and a current identity verification.",unit:"merchants",formula:"Distinct merchants with ≥ 6 months of continuous settlement activity and unexpired verification, at period end",source:"Synthetic merchant registry snapshot",grain:WEEKLY,target:approved(40,"AT_LEAST","Synthetic Lending business owner","2026-09-25T16:00:00.000Z","Enough eligible merchants to fill the 40-merchant pilot cap."),periods:WEEKS,values:[31,33,34,36,38,41,44],baseline:"Eligible pool before launch; not a result of the pilot."},
  {key:"mff-settlement-days",slug:"merchant-flex-finance",name:"Settlement days per eligible merchant",definition:"Median number of calendar days in the month on which an eligible merchant received at least one settlement.",unit:"days",formula:"Median over eligible merchants of (days with ≥ 1 settlement in the period)",source:"Synthetic settlement ledger extract",grain:MONTHLY,target:{value:null,note:"No target: recorded as context for the Finance review of the daily repayment divisor."},periods:MONTHS,values:[24.1,23.8,24.6,23.9,24.4,24.2],baseline:"Baseline of existing settlement activity; this initiative is not live, so these values are not its results."},
  // Terminal Firmware Rollout · acceptance · wave 1 live (partial) 12 September.
  {key:"tfr-certified",slug:"terminal-firmware-rollout",name:"Terminals on certified firmware",definition:"Share of active legacy terminals running the certified contactless firmware at the end of the week.",unit:"%",formula:"Terminals reporting the certified firmware version ÷ active legacy terminals × 100, at period end",source:"Synthetic terminal management export",grain:WEEKLY,target:approved(95,"AT_LEAST","Synthetic Acceptance operations owner","2026-06-20T10:00:00.000Z"),periods:WEEKS,values:[58,61,64,68,71,76,84],notes:FIRMWARE_CONTEXT},
  {key:"tfr-approval",slug:"terminal-firmware-rollout",name:"Contactless authorisation approval rate",definition:"Share of contactless authorisation attempts on legacy terminals that were approved in the week.",unit:"%",formula:"Approved contactless authorisations ÷ contactless authorisation attempts × 100",source:"Synthetic acquirer response log",grain:WEEKLY,target:approved(98,"AT_LEAST","Synthetic Payments Operations owner","2026-06-20T10:00:00.000Z"),periods:WEEKS,values:[99.4,99.3,99.2,99.0,98.9,98.7,98.6],notes:{...FIRMWARE_CONTEXT,6:"First complete week with wave 1 live; the decline is being watched, no cause is established."}},
  // Merchant App Arabic Localisation · live 28 August · sparse recent weeks.
  {key:"mal-arabic-share",slug:"merchant-app-arabic-localisation",name:"Merchant app sessions in Arabic",definition:"Share of merchant app sessions in the week that ran with the Arabic interface selected.",unit:"%",formula:"Sessions with interface language = Arabic ÷ all merchant app sessions × 100",source:"Synthetic app analytics export",grain:WEEKLY,target:approved(60,"AT_LEAST","Synthetic Digital business owner","2026-08-20T10:00:00.000Z"),periods:WEEKS_RECENT,values:[58.2,63.5,66.1],notes:{0:"First complete week after the 28 August release."}},
  {key:"mal-language-tickets",slug:"merchant-app-arabic-localisation",name:"Support tickets about app language",definition:"Merchant Support tickets in the week whose category is app language or translation.",unit:"tickets",formula:"Count of support tickets categorised as app language, created in the period",source:"Synthetic support ticket export",grain:WEEKLY,target:approved(40,"AT_MOST","Synthetic Merchant Support owner","2026-08-20T10:00:00.000Z"),periods:WEEKS_RECENT,values:[71,52,37]},
  // Agent Float Top-Up · not live: baseline of the manual process, plus a target approved days before the scenario date.
  {key:"aft-shortfall",slug:"agent-float-top-up",name:"Agent float shortfall events",definition:"Occasions in the week on which a field agent could not complete a cash-in because their float was exhausted.",unit:"events",formula:"Count of cash-in attempts refused with reason = float exhausted in the period",source:"Synthetic agent operations log",grain:WEEKLY,target:approved(25,"AT_MOST","Synthetic Field Operations owner","2026-07-27T10:00:00.000Z"),periods:WEEKS,values:[41,38,44,null,39,42,40],missing:"The agent operations log for this week was not exported, so the count was not recorded.",baseline:"Baseline of the manual top-up process; same-day top-up is not live."},
  {key:"aft-completion",slug:"agent-float-top-up",name:"Top-up completion time",definition:"Median elapsed hours between an agent's top-up request and the float being available on the terminal.",unit:"hours",formula:"Median(float available timestamp − top-up requested timestamp), in hours",source:"Synthetic agent operations log",grain:WEEKLY,target:approved(6,"AT_MOST","Synthetic Field Operations owner","2026-09-24T10:00:00.000Z","Approved on 24 September; measurement starts with the first live week after Target Live."),periods:[],values:[]},
  // Bill Payment Refund Desk · stale baseline of the manual desk; an EQUAL target.
  {key:"bpr-aged",slug:"bill-payment-refund-desk",name:"Refund requests older than five days",definition:"Bill-payment refund requests still open at month end that were raised more than five business days earlier. A point-in-time count.",unit:"requests",formula:"Count of open refund requests with age > 5 business days at 23:59 on the last day of the period",source:"Synthetic refund desk register",grain:MONTHLY,target:approved(30,"AT_MOST","Synthetic Bill Payments operations owner","2026-03-02T10:00:00.000Z"),periods:MONTHS_STALE,values:[64,58,61,55],baseline:"Baseline of the manual refund desk; the new desk is not live. No period has been captured since June."},
  {key:"bpr-files",slug:"bill-payment-refund-desk",name:"Biller reversal files received per business day",definition:"Average number of reversal files received from billers per business day in the month. Three billers each send one file per day under the current agreement.",unit:"files",formula:"Reversal files received in the period ÷ business days in the period",source:"Synthetic refund desk register",grain:MONTHLY,target:approved(3,"EQUAL","Synthetic Bill Payments operations owner","2026-03-02T10:00:00.000Z","One file per biller per business day is the agreed volume; more or fewer both need explanation."),periods:MONTHS_STALE,values:[3,3,2,3],notes:{2:"One biller sent no files for a week; the desk reconciled by hand."},baseline:"Baseline of the manual refund desk; the new desk is not live. No period has been captured since June."},
  // Merchant Loyalty Points · not live: baseline with a long definition and no approved target.
  {key:"mlp-active",slug:"merchant-loyalty-points",name:"Merchants active on card acceptance",definition:LONG_DEFINITION,unit:"merchants",formula:"Distinct merchant IDs with ≥ 1 accepted card transaction in the period, excluding merchants suspended during the period",source:"Synthetic acquiring transaction export",grain:MONTHLY,target:{value:null,note:"A growth target was proposed by the Synthetic FS business owner; it has not been approved."},periods:MONTHS,values:[2860,2915,2990,3040,3125,3210],baseline:"Pre-launch baseline of the card acceptance population; the loyalty scheme is not live."},
  // Supplier Payment Financing · alignment: baseline of the existing supplier payment volume.
  {key:"spf-volume",slug:"supplier-payment-financing",name:"Supplier payments made from merchant settlements",definition:"Value of supplier invoices merchants paid directly from their settlement balance in the month, under the existing payment feature.",unit:"EGP",formula:"Σ supplier payment amount (EGP) settled in the period",source:"Synthetic settlement ledger extract",grain:MONTHLY,target:approved(9000000,"AT_LEAST","Synthetic Merchant Finance business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[8400000,8900000,9300000,9100000,9800000,10200000],baseline:"Baseline of the existing supplier payment feature; financing is not live."},
  // Card-Present Fraud Rule Tuning · release preparation: improving but above the AT_MOST target; a worsening rate.
  {key:"cpf-fraud-rate",slug:"card-present-fraud-rule-tuning",name:"Card-present fraud rate",definition:"Confirmed fraudulent card-present transaction value as a share of accepted card-present transaction value in the week, in basis points.",unit:"bps",formula:"Confirmed fraud value ÷ accepted card-present value × 10 000",source:"Synthetic fraud case register",grain:WEEKLY,target:approved(8,"AT_MOST","Synthetic Fraud Risk owner","2026-07-20T10:00:00.000Z"),periods:WEEKS,values:[11.2,10.8,10.4,9.9,9.1,8.8,8.6],notes:{4:"Tuned rules running in shadow mode from this week."}},
  {key:"cpf-false-decline",slug:"card-present-fraud-rule-tuning",name:"Genuine transactions declined by fraud rules",definition:"Share of card-present transactions declined by a fraud rule in the week that were later confirmed genuine by the merchant or cardholder.",unit:"%",formula:"Rule declines later confirmed genuine ÷ accepted card-present transactions × 100",source:"Synthetic fraud case register",grain:WEEKLY,target:approved(1.5,"AT_MOST","Synthetic Fraud Risk owner","2026-07-20T10:00:00.000Z"),periods:WEEKS,values:[1.2,1.2,1.3,1.3,1.4,1.5,1.6],notes:{6:"First week above the target; the cause is being reviewed, not inferred."}},
  // Dispute Resolution Portal · not live: sparse baseline of the email process with a period not recorded.
  {key:"drp-on-time",slug:"dispute-resolution-portal",name:"Disputes answered within the scheme deadline",definition:"Share of chargeback disputes in the month for which the merchant's response reached the scheme before its deadline.",unit:"%",formula:"Disputes answered before the scheme deadline ÷ disputes raised in the period × 100",source:"Synthetic dispute case export",grain:MONTHLY,target:approved(80,"AT_LEAST","Synthetic Acceptance operations owner","2026-06-15T10:00:00.000Z"),periods:MONTHS.slice(3),values:[74,null,79],missing:"The July dispute case export was rejected by the scheme portal and never re-issued, so the share was not calculated.",baseline:"Baseline of the email-based dispute process; the portal is not live."},
];

/** Capture the morning after the period ends; always on or before the scenario cutoff. */
function capturedFor(periodEnd:string,grain:string) {
  const end=new Date(periodEnd+"T00:00:00.000Z");
  end.setUTCDate(end.getUTCDate()+(grain===MONTHLY?5:1));
  end.setUTCHours(grain===DAILY?6:9);
  return end.toISOString();
}

/** Synthetic Demo v3 portfolio metrics. `initiativeIdFor` resolves the canonical record by slug. */
export function demoPortfolioMetrics(workspaceId:string,initiativeIdFor:(slug:string)=>string,id:(key:string)=>string):ProjectMetric[] {
  return buildSyntheticMetrics(SPECS,workspaceId,initiativeIdFor,id);
}
/** Synthetic Demo v4 additions: the same builder over the V4 initiatives (see scenario-v4.ts). */
export function demoPortfolioMetricsV4(workspaceId:string,initiativeIdFor:(slug:string)=>string,id:(key:string)=>string):ProjectMetric[] {
  return buildSyntheticMetrics(SPECS_V4,workspaceId,initiativeIdFor,id);
}
function buildSyntheticMetrics(specs:Spec[],workspaceId:string,initiativeIdFor:(slug:string)=>string,id:(key:string)=>string):ProjectMetric[] {
  return specs.map(spec=>{
    const observations:MetricObservation[]=spec.periods.map(([periodStart,periodEnd],index)=>{
      const value=spec.values[index]??null;
      const detail=value===null?`Not recorded. ${spec.missing??"No value was captured for this period."} Missing is not zero.`:[spec.notes?.[index],spec.baseline].filter(Boolean).join(" ")||"Recorded period.";
      return {id:id(`metric-observation:${spec.key}:${periodStart}`),periodStart,periodEnd,value,capturedAt:capturedFor(periodEnd,spec.grain),sourceEvidenceId:null,note:`Synthetic observation. ${detail}`,origin:"SYNTHETIC_DEMO"};
    });
    const updatedAt=observations.map(o=>o.capturedAt).sort().at(-1)??(spec.target.value!==null?spec.target.approvedAt:"2026-09-22T10:00:00.000Z");
    const target=spec.target.value===null
      ?{targetValue:null,targetComparator:null,targetOwnerLabel:null,targetApprovedAt:null,targetNote:spec.target.note}
      :{targetValue:spec.target.value,targetComparator:spec.target.comparator,targetOwnerLabel:spec.target.owner,targetApprovedAt:spec.target.approvedAt,targetNote:`Synthetic target record; no live business approval represented.${spec.target.note?" "+spec.target.note:""}`};
    return {id:id(`metric:${spec.key}`),workspaceId,initiativeId:initiativeIdFor(spec.slug),name:spec.name,definition:spec.definition,unit:spec.unit,formula:spec.formula,sourceLabel:spec.source,sourceEvidenceId:null,periodGrain:spec.grain,timezone:"Africa/Cairo",...target,origin:"SYNTHETIC_DEMO",revision:1,updatedAt,observations};
  });
}
