import type {MetricObservation,ProjectMetric} from "../analysis/metric-types.ts";
/** Fictional observations persisted by the reviewed Demo operator; never UI defaults. */
export function demoProjectMetrics(workspaceId:string,initiativeId:string,evidenceId:string,id:(key:string)=>string):ProjectMetric[] {
  const base={workspaceId,initiativeId,sourceLabel:"Synthetic onboarding observation note",sourceEvidenceId:evidenceId,periodGrain:"Recorded weekly cohort",timezone:"Africa/Cairo",origin:"SYNTHETIC_DEMO" as const,revision:1,updatedAt:"2026-09-22T10:00:00.000Z"};
  const obs=(key:string,periodStart:string,periodEnd:string,value:number|null,note:string)=>({id:id(`metric-observation:${key}`),periodStart,periodEnd,value,capturedAt:"2026-09-22T10:00:00.000Z",sourceEvidenceId:evidenceId,note:`Synthetic observation. ${note}`,origin:"SYNTHETIC_DEMO" as const});
  return [
    {...base,id:id("metric:onboarding-time"),name:"Median onboarding time",definition:"Median elapsed days between completed merchant application and activation for the named rollout cohort.",unit:"days",formula:"Median(activation timestamp − completed application timestamp), expressed in days",targetValue:3,targetComparator:"AT_MOST",targetOwnerLabel:"Synthetic Operations owner",targetApprovedAt:"2026-08-28T10:00:00.000Z",targetNote:"Synthetic target record supplied for the walkthrough; no live business approval represented.",observations:[obs("time:launch","2026-09-10","2026-09-13",4.1,"Partial launch period; compare with caution."),obs("time:week","2026-09-14","2026-09-20",3.4,"Complete recorded weekly cohort.")]},
    {...base,id:id("metric:first-transaction"),name:"First transaction within seven days",definition:"Share of newly activated merchants with a first accepted transaction within seven calendar days of activation.",unit:"%",formula:"Merchants with first accepted transaction within 7 days / activated cohort merchants × 100",targetValue:null,targetComparator:null,targetOwnerLabel:null,targetApprovedAt:null,targetNote:null,observations:[obs("first:launch","2026-09-10","2026-09-13",48,"Launch cohort's seven-day window completed; partial launch period."),obs("first:week","2026-09-14","2026-09-20",null,"Observation not recorded. Seven-day window completes 27 September; do not replace the missing value with zero.")]},
  ];
}

/* ── Demo v3 portfolio metrics ─────────────────────────────────────────────
   Fictional business measures for the enriched Demo portfolio. Every value is
   a synthetic record written for the walkthrough: related measures are kept
   internally consistent (GTV = transactions × average value, routed share =
   routed ÷ raised), a few periods are deliberately NOT recorded (null, never
   zero) and several measures have no approved target. Pre-launch initiatives
   carry baselines of the product area they change — labelled as such — and
   never results attributed to the initiative. */

type Target={value:number;comparator:"AT_MOST"|"AT_LEAST"|"EQUAL";owner:string;approvedAt:string;note?:string}|{value:null;note:string|null};
interface Spec {key:string;slug:string;name:string;definition:string;unit:string;formula:string;source:string;grain:string;target:Target;periods:readonly (readonly [string,string])[];values:readonly (number|null)[];missing?:string;notes?:Readonly<Record<number,string>>;baseline?:string}

const WEEKS=[["2026-08-03","2026-08-09"],["2026-08-10","2026-08-16"],["2026-08-17","2026-08-23"],["2026-08-24","2026-08-30"],["2026-08-31","2026-09-06"],["2026-09-07","2026-09-13"],["2026-09-14","2026-09-20"]] as const;
const MONTHS=[["2026-03-01","2026-03-31"],["2026-04-01","2026-04-30"],["2026-05-01","2026-05-31"],["2026-06-01","2026-06-30"],["2026-07-01","2026-07-31"],["2026-08-01","2026-08-31"]] as const;
const DAYS=["2026-09-16","2026-09-17","2026-09-18","2026-09-19","2026-09-20","2026-09-21","2026-09-22","2026-09-23","2026-09-24","2026-09-25"].map(d=>[d,d] as const);
const WEEKLY="Weekly · Monday–Sunday",MONTHLY="Calendar month",DAILY="Daily · calendar day";
const approved=(value:number,comparator:"AT_MOST"|"AT_LEAST",owner:string,approvedAt:string,note?:string):Target=>({value,comparator,owner,approvedAt,note});
/** Tap-to-Pay pilot weeks run until the full rollout recorded as Actual Live on 10 September. */
const TAP_CONTEXT:Record<number,string>={0:"Pilot cohort week.",1:"Pilot cohort week.",2:"Pilot cohort week.",3:"Pilot cohort week.",4:"Pilot cohort week.",5:"Includes the first days of the full rollout (10 September).",6:"First complete week of the full rollout."};
const LENDING_BASELINE="Baseline of the existing installment product; this initiative is not live, so these values are not its results.";

const SPECS:Spec[]=[
  // Tap-to-Pay Merchant Onboarding · payments acceptance · Actual Live 10 September.
  {key:"ttp-gtv",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay gross transaction value",definition:"Total value of accepted Tap-to-Pay card transactions at onboarded merchants in the week. Declined, reversed and refunded transactions are excluded.",unit:"EGP",formula:"Σ accepted Tap-to-Pay transaction amount (EGP) in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(4000000,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[1420000,1610000,1780000,1950000,2120000,3050000,4380000],notes:TAP_CONTEXT},
  {key:"ttp-transactions",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay accepted transactions",definition:"Count of accepted Tap-to-Pay card transactions at onboarded merchants in the week.",unit:"transactions",formula:"Count of accepted Tap-to-Pay transactions in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(10000,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[3880,4350,4720,5160,5540,7930,11240],notes:TAP_CONTEXT},
  {key:"ttp-active-merchants",slug:"tap-to-pay-merchant-onboarding",name:"Active Tap-to-Pay merchants",definition:"Onboarded merchants with at least one accepted Tap-to-Pay transaction in the week.",unit:"merchants",formula:"Distinct merchant IDs with ≥ 1 accepted Tap-to-Pay transaction in the period",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:approved(600,"AT_LEAST","Synthetic Acceptance business owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[212,236,251,268,284,402,571],notes:TAP_CONTEXT},
  {key:"ttp-success-rate",slug:"tap-to-pay-merchant-onboarding",name:"Tap-to-Pay transaction success rate",definition:"Share of Tap-to-Pay authorisation attempts that were approved. Merchant-cancelled attempts are excluded from the denominator.",unit:"%",formula:"Approved authorisations ÷ authorisation attempts (excluding merchant cancellations) × 100",source:"Synthetic acquirer response log",grain:WEEKLY,target:approved(97,"AT_LEAST","Synthetic Payments Operations owner","2026-08-28T10:00:00.000Z"),periods:WEEKS,values:[96.1,96.4,null,96.9,97.2,95.8,96.6],missing:"The acquirer response log export for this week was incomplete, so the rate was not calculated.",notes:TAP_CONTEXT},
  {key:"ttp-average-value",slug:"tap-to-pay-merchant-onboarding",name:"Average Tap-to-Pay transaction value",definition:"Mean value of an accepted Tap-to-Pay transaction in the week. Monitored for context; no target is set.",unit:"EGP",formula:"Tap-to-Pay gross transaction value ÷ accepted Tap-to-Pay transactions",source:"Synthetic acquiring transaction export",grain:WEEKLY,target:{value:null,note:"Monitored for context only; no target has been proposed."},periods:WEEKS,values:[366,370,377,378,383,385,390],notes:TAP_CONTEXT},
  // Partner Wallet Checkout · acceptance · not live: definition and target exist, observations start after launch.
  {key:"pwc-success-rate",slug:"partner-wallet-checkout",name:"Partner wallet payment success rate",definition:"Share of partner-wallet payment attempts at the terminal that complete with a receipt showing the correct merchant details.",unit:"%",formula:"Completed partner-wallet payments with a correct receipt ÷ partner-wallet payment attempts × 100",source:"Synthetic partner wallet settlement file",grain:WEEKLY,target:approved(97,"AT_LEAST","Synthetic Payments Operations owner","2026-09-15T10:00:00.000Z","Measurement starts with the first live week after Target Live."),periods:[],values:[]},
  // Service Complaint Tracker · internal tool · Actual Live 16 September · daily observations.
  {key:"sct-raised",slug:"service-complaint-tracker",name:"Complaints raised from the terminal",definition:"Service complaints submitted by merchants from the terminal in the day. Complaints raised by phone are not included.",unit:"complaints",formula:"Count of complaints with channel = terminal created in the period",source:"Synthetic complaint service export",grain:DAILY,target:{value:null,note:"A target will be agreed at the 30-day live review; none is approved."},periods:DAYS,values:[38,44,29,26,47,52,49,null,51,33],missing:"The complaint service export failed for this day, so the count was not recorded.",notes:{2:"Friday · weekend volume.",3:"Saturday · weekend volume.",9:"Friday · weekend volume."}},
  {key:"sct-routing",slug:"service-complaint-tracker",name:"Complaints routed correctly on first assignment",definition:"Share of terminal complaints assigned to the owning team on their first assignment, without a manual re-route.",unit:"%",formula:"Complaints not re-routed after first assignment ÷ complaints raised from the terminal × 100",source:"Synthetic complaint service export",grain:DAILY,target:approved(95,"AT_LEAST","Synthetic Customer Support owner","2026-09-10T10:00:00.000Z"),periods:DAYS,values:[89.5,90.9,89.7,92.3,93.6,94.2,93.9,null,94.1,93.9],missing:"The complaint service export failed for this day, so the share was not calculated."},
  {key:"sct-first-response",slug:"service-complaint-tracker",name:"Median time to first response",definition:"Median elapsed hours between a terminal complaint being raised and the owning team's first response.",unit:"hours",formula:"Median(first response timestamp − complaint created timestamp), in hours",source:"Synthetic complaint service export",grain:DAILY,target:approved(4,"AT_MOST","Synthetic Customer Support owner","2026-09-10T10:00:00.000Z"),periods:DAYS,values:[5.2,4.8,6.1,6.4,4.1,3.9,3.8,null,3.7,4.6],missing:"The complaint service export failed for this day, so the median was not calculated."},
  // Installment Early Settlement · lending · in delivery: baseline of the existing installment product.
  {key:"ies-disbursed",slug:"installment-early-settlement",name:"Installment amount disbursed",definition:"Principal disbursed to merchants on new installment plans in the month.",unit:"EGP",formula:"Σ principal of installment plans disbursed in the period",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(22000000,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[18600000,19900000,21400000,20800000,23100000,24500000],baseline:LENDING_BASELINE},
  {key:"ies-borrowers",slug:"installment-early-settlement",name:"Active installment borrowers",definition:"Merchants with an outstanding installment balance at month end. A point-in-time count, not a monthly flow.",unit:"borrowers",formula:"Distinct merchants with outstanding principal > 0 at 23:59 on the last day of the period",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(4000,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[3410,3560,3720,3805,3960,4120],baseline:LENDING_BASELINE},
  {key:"ies-collection-rate",slug:"installment-early-settlement",name:"Installment collection rate",definition:"Share of installment amounts falling due in the month that were collected from settlements by month end.",unit:"%",formula:"Amount collected against installments due in the period ÷ amount due in the period × 100",source:"Synthetic lending ledger extract",grain:MONTHLY,target:approved(97,"AT_LEAST","Synthetic Lending business owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[96.8,97.1,96.5,95.9,96.2,96.4],baseline:LENDING_BASELINE},
  {key:"ies-overdue",slug:"installment-early-settlement",name:"Overdue rate (30+ days)",definition:"Share of outstanding installment principal that is 30 or more days past due at month end. A point-in-time rate.",unit:"%",formula:"Outstanding principal ≥ 30 days past due ÷ total outstanding principal × 100, at period end",source:"Synthetic month-end portfolio snapshot",grain:MONTHLY,target:approved(3,"AT_MOST","Synthetic Credit Risk owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[2.9,2.8,3.1,3.4,null,3.3],missing:"The July month-end portfolio snapshot was not recorded, so the rate was not calculated.",baseline:LENDING_BASELINE},
  {key:"ies-requests",slug:"installment-early-settlement",name:"Early settlement requests handled manually",definition:"Merchant requests to settle an installment plan early that Operations processed by hand in the month.",unit:"requests",formula:"Count of early settlement requests closed by Operations in the period",source:"Synthetic operations request log",grain:MONTHLY,target:{value:null,note:"A reduction target was proposed by the Synthetic Lending business owner; it has not been approved."},periods:MONTHS,values:[118,126,131,140,152,149],baseline:LENDING_BASELINE},
  // Collections Reporting Rebuild · reporting · in definition: baseline of the legacy pack.
  {key:"crr-on-time",slug:"collections-reporting-rebuild",name:"Collections pack delivered by 09:00",definition:"Share of business days in the week on which the legacy daily collections pack reached Operations by 09:00 Cairo time.",unit:"%",formula:"Business days with pack delivered by 09:00 ÷ business days in the period × 100",source:"Synthetic report distribution log",grain:WEEKLY,target:approved(95,"AT_LEAST","Synthetic Collections Operations owner","2026-08-24T10:00:00.000Z"),periods:WEEKS,values:[80,100,60,80,100,80,60],baseline:"Baseline of the legacy collections pack; the rebuilt pack is not live."},
  {key:"crr-reconciliation",slug:"collections-reporting-rebuild",name:"Manual reconciliation effort",definition:"Hours Operations spent reconciling the legacy collections pack against the ledger in the week.",unit:"hours",formula:"Σ timesheet hours booked to collections reconciliation in the period",source:"Synthetic Operations timesheet extract",grain:WEEKLY,target:{value:null,note:null},periods:WEEKS,values:[14.5,12,16.5,null,13,15.5,17],missing:"The timesheet extract was not submitted for this week, so the hours were not recorded.",baseline:"Baseline of the legacy collections pack; the rebuilt pack is not live."},
  // Merchant Insights App · in delivery: baseline of the support demand it aims to reduce.
  {key:"mia-statements",slug:"merchant-insights-app",name:"Statement requests to Merchant Support",definition:"Merchant requests for transaction or settlement statements received by Merchant Support in the week.",unit:"requests",formula:"Count of support tickets categorised as statement request, created in the period",source:"Synthetic support ticket export",grain:WEEKLY,target:approved(250,"AT_MOST","Synthetic Merchant Support owner","2026-07-20T10:00:00.000Z","Post-launch goal; the app is not live yet."),periods:WEEKS,values:[412,398,431,405,446,452,437],baseline:"Pre-launch baseline; the app is not live."},
  // Instant Settlement Payout · payments · release preparation: baseline of next-business-day payouts.
  {key:"isp-next-day",slug:"instant-settlement-payout",name:"Payouts settled next business day",definition:"Share of merchant payouts credited by the end of the next business day under the current payout schedule.",unit:"%",formula:"Payouts credited by end of T+1 business day ÷ payouts due in the period × 100",source:"Synthetic settlement payout report",grain:WEEKLY,target:approved(98,"AT_LEAST","Synthetic Settlement Operations owner","2026-06-10T10:00:00.000Z"),periods:WEEKS,values:[97.4,97.9,96.8,98.1,97.6,98.3,97.9],baseline:"Baseline of the current payout schedule; same-day payout is not live."},
  // Merchant KYC Refresh · onboarding / KYC · alignment: baseline of verification currency.
  {key:"kyc-current",slug:"merchant-kyc-refresh",name:"Merchants with current identity verification",definition:"Share of active merchants whose identity verification is within its validity period at month end. A point-in-time rate.",unit:"%",formula:"Active merchants with unexpired verification ÷ active merchants × 100, at period end",source:"Synthetic merchant registry snapshot",grain:MONTHLY,target:approved(98,"AT_LEAST","Synthetic Compliance owner","2026-02-24T10:00:00.000Z"),periods:MONTHS,values:[91.8,91.2,90.6,90.1,89.7,89.2],baseline:"Baseline before the refresh; no re-verification campaign is live."},
  {key:"kyc-reverification-time",slug:"merchant-kyc-refresh",name:"Median re-verification time",definition:"Median days from a merchant's re-verification request to a completed verification, for requests completed in the month.",unit:"days",formula:"Median(verification completed − re-verification requested), in days",source:"Synthetic merchant registry snapshot",grain:MONTHLY,target:{value:null,note:null},periods:MONTHS,values:[9.5,10,11.5,10.5,12,12.5],baseline:"Baseline before the refresh; no re-verification campaign is live."},
  // Merchant Pricing Update · finance · validation: current fee revenue, target depends on the open fee decision.
  {key:"mpu-fee-revenue",slug:"merchant-pricing-update",name:"Merchant service fee revenue",definition:"Merchant service fees earned on accepted card transactions in the month, before refunds of fees.",unit:"EGP",formula:"Σ merchant service fee charged on accepted transactions in the period",source:"Synthetic fee revenue ledger",grain:MONTHLY,target:{value:null,note:"No target approved: it depends on the open fee rate decision (1.50% or 1.75%)."},periods:MONTHS,values:[4120000,4300000,4510000,4440000,4830000,5020000],baseline:"Current fee schedule; the pricing update is not live."},
  {key:"mpu-blended-rate",slug:"merchant-pricing-update",name:"Blended merchant fee rate",definition:"Merchant service fee revenue as a share of accepted card transaction value in the month.",unit:"%",formula:"Merchant service fee revenue ÷ accepted card transaction value × 100",source:"Synthetic fee revenue ledger",grain:MONTHLY,target:{value:null,note:null},periods:MONTHS,values:[1.48,1.49,1.47,1.48,1.49,1.48],baseline:"Current fee schedule; the pricing update is not live."},
];

/** Capture the morning after the period ends; always on or before the scenario cutoff. */
function capturedFor(periodEnd:string,grain:string) {
  const end=new Date(periodEnd+"T00:00:00.000Z");
  end.setUTCDate(end.getUTCDate()+(grain===MONTHLY?5:1));
  end.setUTCHours(grain===DAILY?6:9);
  return end.toISOString();
}

/** Synthetic Demo v3 portfolio metrics. `initiativeIdFor` resolves the canonical record by slug. */
export function demoPortfolioMetrics(workspaceId:string,initiativeIdFor:(slug:string)=>string,id:(key:string)=>string):ProjectMetric[] {
  return SPECS.map(spec=>{
    const observations:MetricObservation[]=spec.periods.map(([periodStart,periodEnd],index)=>{
      const value=spec.values[index]??null;
      const detail=value===null?`Not recorded. ${spec.missing??"No value was captured for this period."} Missing is not zero.`:[spec.notes?.[index],spec.baseline].filter(Boolean).join(" ")||"Recorded period.";
      return {id:id(`metric-observation:${spec.key}:${periodStart}`),periodStart,periodEnd,value,capturedAt:capturedFor(periodEnd,spec.grain),sourceEvidenceId:null,note:`Synthetic observation. ${detail}`,origin:"SYNTHETIC_DEMO"};
    });
    const updatedAt=observations.map(o=>o.capturedAt).sort().at(-1)??(spec.target.value!==null?spec.target.approvedAt:"2026-09-22T10:00:00.000Z");
    const target=spec.target.value===null
      ?{targetValue:null,targetComparator:null,targetOwnerLabel:null,targetApprovedAt:null,targetNote:spec.target.note}
      :{targetValue:spec.target.value,targetComparator:spec.target.comparator,targetOwnerLabel:spec.target.owner,targetApprovedAt:spec.target.approvedAt,targetNote:`Synthetic target record; no live business approval represented.${spec.target.note?" "+spec.target.note:""}`};
    return {id:id(`metric:${spec.key}`),workspaceId,initiativeId:initiativeIdFor(spec.slug),name:spec.name,definition:spec.definition,unit:spec.unit,formula:spec.formula,sourceLabel:spec.source,sourceEvidenceId:null,periodGrain:spec.grain,timezone:"Africa/Cairo",...target,origin:"SYNTHETIC_DEMO",revision:1,updatedAt,observations};
  });
}
