import type {ProjectMetric} from "../analysis/metric-types.ts";
/** Fictional observations persisted by the reviewed Demo operator; never UI defaults. */
export function demoProjectMetrics(workspaceId:string,initiativeId:string,evidenceId:string,id:(key:string)=>string):ProjectMetric[] {
  const base={workspaceId,initiativeId,sourceLabel:"Synthetic onboarding observation note",sourceEvidenceId:evidenceId,periodGrain:"Recorded weekly cohort",timezone:"Africa/Cairo",origin:"SYNTHETIC_DEMO" as const,revision:1,updatedAt:"2026-09-22T10:00:00.000Z"};
  const obs=(key:string,periodStart:string,periodEnd:string,value:number|null,note:string)=>({id:id(`metric-observation:${key}`),periodStart,periodEnd,value,capturedAt:"2026-09-22T10:00:00.000Z",sourceEvidenceId:evidenceId,note:`Synthetic observation. ${note}`,origin:"SYNTHETIC_DEMO" as const});
  return [
    {...base,id:id("metric:onboarding-time"),name:"Median onboarding time",definition:"Median elapsed days between completed merchant application and activation for the named rollout cohort.",unit:"days",formula:"Median(activation timestamp − completed application timestamp), expressed in days",targetValue:3,targetComparator:"AT_MOST",targetOwnerLabel:"Synthetic Operations owner",targetApprovedAt:"2026-08-28T10:00:00.000Z",targetNote:"Synthetic target record supplied for the walkthrough; no live business approval represented.",observations:[obs("time:launch","2026-09-10","2026-09-13",4.1,"Partial launch period; compare with caution."),obs("time:week","2026-09-14","2026-09-20",3.4,"Complete recorded weekly cohort.")]},
    {...base,id:id("metric:first-transaction"),name:"First transaction within seven days",definition:"Share of newly activated merchants with a first accepted transaction within seven calendar days of activation.",unit:"%",formula:"Merchants with first accepted transaction within 7 days / activated cohort merchants × 100",targetValue:null,targetComparator:null,targetOwnerLabel:null,targetApprovedAt:null,targetNote:null,observations:[obs("first:launch","2026-09-10","2026-09-13",48,"Launch cohort's seven-day window completed; partial launch period."),obs("first:week","2026-09-14","2026-09-20",null,"Observation not recorded. Seven-day window completes 27 September; do not replace the missing value with zero.")]},
  ];
}
