-- Local candidate only. Global identities + platform + organization authority.
begin;
drop trigger workspace_admin_backstop on public.workspaces;
drop trigger membership_admin_backstop on public.memberships;
alter table public.users add column platform_role text check(platform_role is null or platform_role='PLATFORM_OWNER');
alter table public.users add column active boolean not null default true;
create function public.email_policy_valid(p_domains text[],p_exact text[]) returns boolean language sql immutable set search_path='' as $$select p_domains is not null and p_exact is not null and not exists(select 1 from unnest(p_domains) d where d is null or d<>lower(btrim(d)) or d!~'^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$') and not exists(select 1 from unnest(p_exact) e where e is null or e<>lower(btrim(e)) or e!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$');$$;
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null check(length(btrim(name)) between 1 and 120),status text not null default 'BOOTSTRAPPING' check(status in ('BOOTSTRAPPING','ACTIVE')),allowed_email_domains text[] not null,allowed_exact_emails text[] not null,created_at timestamptz not null default now(),check(public.email_policy_valid(allowed_email_domains,allowed_exact_emails)));
-- Explicit existing AMAN workspace mapping. No universal company default.
insert into public.organizations(id,name,allowed_email_domains,allowed_exact_emails) values('90000000-0000-4000-8000-000000000001','AMAN',array['aman.eg','rayacorp.com'],array['mohamedhassanpe@outlook.com']);
alter table public.workspaces add column organization_id uuid references public.organizations(id);
update public.workspaces set organization_id='90000000-0000-4000-8000-000000000001',status='BOOTSTRAPPING' where id='10000000-0000-4000-8000-000000000001';
alter table public.workspaces alter column organization_id set not null;
alter table public.memberships rename to organization_memberships;
alter table public.organization_memberships drop constraint memberships_workspace_id_fkey;
alter table public.organization_memberships rename column workspace_id to organization_id;
update public.organization_memberships m set organization_id=w.organization_id from public.workspaces w where m.organization_id=w.id;
alter table public.organization_memberships add constraint organization_membership_org foreign key(organization_id) references public.organizations(id);
alter table public.organization_memberships drop constraint memberships_role_check;
alter table public.organization_memberships drop constraint memberships_check;
update public.organization_memberships set role=case when upper(role)='OWNER' then 'ORG_OWNER' else upper(role) end;
alter table public.organization_memberships add constraint organization_role_check check(role in ('ORG_OWNER','ADMIN','MEMBER','VIEWER'));
alter table public.organization_memberships add constraint organization_lead_check check(not is_product_lead or role in ('ORG_OWNER','ADMIN','MEMBER'));
alter table public.organization_memberships add column policy_override boolean not null default false;
alter table public.organization_memberships add column policy_override_reason text;
alter table public.organization_memberships add constraint policy_override_reason_required check(not policy_override or (policy_override_reason is not null and length(btrim(policy_override_reason)) between 1 and 500));
create view public.memberships as select m.id,w.id as workspace_id,m.user_id,m.role,m.is_product_lead,m.active,m.created_at from public.organization_memberships m join public.workspaces w on w.organization_id=m.organization_id;
alter table public.workspace_invitations drop constraint workspace_invitations_role_check;
update public.workspace_invitations set role=upper(role),revoked_at=coalesce(revoked_at,clock_timestamp()) where used_at is null;
update public.workspace_invitations set role=upper(role);
alter table public.workspace_invitations add constraint invitation_role_check check(role in ('ORG_OWNER','ADMIN','MEMBER','VIEWER'));
alter table public.workspace_invitations add column organization_id uuid references public.organizations(id);
update public.workspace_invitations i set organization_id=w.organization_id from public.workspaces w where i.workspace_id=w.id;
alter table public.workspace_invitations alter column organization_id set not null;
alter table public.workspace_invitations add column provisioned_by_platform boolean not null default false;
alter table public.workspace_invitations add column policy_override boolean not null default false;
alter table public.workspace_invitations add column policy_override_reason text;
alter table public.workspace_invitations add constraint platform_invitation_owner check(role<>'ORG_OWNER' or provisioned_by_platform);
alter table public.workspace_invitations add constraint platform_invitation_override check(not policy_override or (provisioned_by_platform and policy_override_reason is not null and length(btrim(policy_override_reason)) between 1 and 500));
create unique index one_pending_organization_invite on public.workspace_invitations(organization_id,email) where revoked_at is null and used_at is null;
alter table public.workspace_sessions add column organization_id uuid references public.organizations(id);
update public.workspace_sessions s set organization_id=w.organization_id from public.workspaces w where s.workspace_id=w.id;
alter table public.workspace_sessions alter column organization_id set not null;
delete from public.workspace_sessions;
alter table public.membership_events add column organization_id uuid references public.organizations(id);
update public.membership_events e set organization_id=w.organization_id from public.workspaces w where e.workspace_id=w.id;
alter table public.membership_events add column reason text;
alter table public.membership_events add column policy_overridden boolean not null default false;
create table public.platform_events(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id),organization_id uuid references public.organizations(id),actor_id uuid not null references public.users(id),actor_label text not null,target_id text not null,action text not null,before_state jsonb,after_state jsonb,reason text not null check(length(btrim(reason)) between 1 and 500),policy_overridden boolean not null default false,occurred_at timestamptz not null default now());
create function public.organization_email_allowed(p_organization_id uuid,p_email text) returns boolean language sql stable set search_path='' as $$select coalesce((select lower(btrim(p_email))~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' and (split_part(lower(btrim(p_email)),'@',2)=any(o.allowed_email_domains) or lower(btrim(p_email))=any(o.allowed_exact_emails)) from public.organizations o where o.id=p_organization_id),false);$$;
create function public.workspace_email_allowed(p_workspace_id uuid,p_email text) returns boolean language sql stable set search_path='' as $$select public.organization_email_allowed((select organization_id from public.workspaces where id=p_workspace_id),p_email);$$;
create function public.is_workspace_administrator(p_role text) returns boolean language sql immutable set search_path='' as $$select coalesce(p_role in ('ORG_OWNER','ADMIN'),false);$$;
create function public.principal_is_platform(p_user_id uuid) returns boolean language sql stable set search_path='' as $$select exists(select 1 from public.users where id=p_user_id and active and not is_system and platform_role='PLATFORM_OWNER' and auth_user_id is not null);$$;
create function public.principal_is_admin(p_user_id uuid,p_role text) returns boolean language sql stable set search_path='' as $$select public.principal_is_platform(p_user_id) or public.is_workspace_administrator(p_role);$$;
create function public.principal_is_owner(p_user_id uuid,p_role text) returns boolean language sql stable set search_path='' as $$select public.principal_is_platform(p_user_id) or coalesce(p_role='ORG_OWNER',false);$$;
create or replace function public.workspace_admin_invariant() returns trigger language plpgsql set search_path='' as $$declare oid uuid;begin
 if tg_table_name='organizations' then oid:=new.id;elsif tg_op='DELETE' then oid:=old.organization_id;else oid:=new.organization_id;end if;perform 1 from public.organizations where id=oid for update;
 if exists(select 1 from public.organizations where id=oid and status='ACTIVE') and not exists(select 1 from public.organization_memberships m join public.users u on u.id=m.user_id where m.organization_id=oid and m.active and m.role='ORG_OWNER' and u.active and not u.is_system) then raise exception 'LAST_ORG_OWNER';end if;return null;end;$$;
create constraint trigger membership_admin_backstop after insert or update or delete on public.organization_memberships deferrable initially deferred for each row execute function public.workspace_admin_invariant();
create constraint trigger workspace_admin_backstop after insert or update on public.workspaces deferrable initially deferred for each row execute function public.workspace_admin_invariant();
create constraint trigger organization_owner_backstop after insert or update on public.organizations deferrable initially deferred for each row execute function public.workspace_admin_invariant();
create function public.organization_membership_immutable_keys() returns trigger language plpgsql set search_path='' as $$begin if new.id<>old.id or new.organization_id<>old.organization_id or new.user_id<>old.user_id then raise exception 'MEMBERSHIP_IDENTITY_IMMUTABLE';end if;return new;end;$$;
create trigger organization_membership_keys before update on public.organization_memberships for each row execute function public.organization_membership_immutable_keys();
create function public.global_identity_guard() returns trigger language plpgsql set search_path='' as $$declare oid uuid;begin
 if not new.active then for oid in select organization_id from public.organization_memberships where user_id=new.id and active and role='ORG_OWNER' loop perform 1 from public.organizations where id=oid for update;if exists(select 1 from public.organizations where id=oid and status='ACTIVE') and not exists(select 1 from public.organization_memberships m join public.users u on u.id=m.user_id where m.organization_id=oid and m.active and m.role='ORG_OWNER' and u.active and u.id<>new.id) then raise exception 'LAST_ORG_OWNER';end if;end loop;end if;
 if old.active and old.platform_role='PLATFORM_OWNER' and (not new.active or new.platform_role is distinct from 'PLATFORM_OWNER') then perform pg_advisory_xact_lock(121204);if not exists(select 1 from public.users where active and platform_role='PLATFORM_OWNER' and id<>new.id) then raise exception 'LAST_PLATFORM_OWNER';end if;end if;return new;end;$$;
create trigger global_identity_active_guard before update on public.users for each row execute function public.global_identity_guard();
create function public.attach_organization_scope() returns trigger language plpgsql set search_path='' as $$declare oid uuid;begin select organization_id into oid from public.workspaces where id=new.workspace_id;if new.organization_id is null then new.organization_id:=oid;end if;if oid is null or oid<>new.organization_id then raise exception 'ORGANIZATION_SCOPE';end if;return new;end;$$;
create trigger invitation_org_scope before insert or update on public.workspace_invitations for each row execute function public.attach_organization_scope();
create trigger session_org_scope before insert or update on public.workspace_sessions for each row execute function public.attach_organization_scope();
create trigger event_org_scope before insert or update on public.membership_events for each row execute function public.attach_organization_scope();
create or replace function public.require_workspace_member(p_workspace_id uuid,p_member_id uuid,p_admin boolean default false,p_write boolean default false) returns public.organization_memberships language plpgsql set search_path='' as $$declare m public.organization_memberships;u public.users;oid uuid;platform boolean;begin
 select organization_id into oid from public.workspaces where id=p_workspace_id;if oid is null then raise exception 'ACCESS_DENIED';end if;
 select * into m from public.organization_memberships where id=p_member_id and organization_id=oid for share;if found then select * into u from public.users where id=m.user_id for share;else select * into u from public.users where id=p_member_id for share;end if;
 if u.id is null or not u.active or u.is_system or u.auth_user_id is null then raise exception 'ACCESS_DENIED';end if;platform:=u.platform_role='PLATFORM_OWNER';
 if not coalesce(platform,false) then
  if m.id is null or not m.active then raise exception 'ACCESS_DENIED';end if;if not m.policy_override and not public.organization_email_allowed(oid,u.email) then raise exception 'EMAIL_NOT_ALLOWED';end if;
  if not exists(select 1 from public.organizations where id=oid and status='ACTIVE') or not exists(select 1 from public.organization_memberships x join public.users y on y.id=x.user_id where x.organization_id=oid and x.active and x.role='ORG_OWNER' and y.active) then raise exception 'OWNER_BOOTSTRAP_REQUIRED';end if;
 elsif m.id is null or not m.active then m.id:=null;m.role:=null;m.is_product_lead:=false;m.organization_id:=oid;m.user_id:=u.id;m.active:=true;m.policy_override:=false;m.policy_override_reason:=null;end if;
 if p_admin and not public.principal_is_admin(u.id,m.role) then raise exception 'ADMIN_REQUIRED';end if;if p_write and not coalesce(platform,false) and coalesce(m.role,'VIEWER')='VIEWER' then raise exception 'VIEW_ONLY';end if;return m;end;$$;
create or replace function public.change_workspace_membership(p_workspace_id uuid,p_member_id uuid,p_target_id uuid,p_role text,p_active boolean,p_is_product_lead boolean) returns void language plpgsql set search_path='' as $$declare actor public.organization_memberships;previous public.organization_memberships;oid uuid;begin
 select organization_id into oid from public.workspaces where id=p_workspace_id;perform 1 from public.organizations where id=oid for update;actor:=public.require_workspace_member(p_workspace_id,p_member_id,true,false);
 select * into previous from public.organization_memberships where id=p_target_id and organization_id=oid for update;if not found then raise exception 'ACCESS_DENIED';end if;
 if previous.role='ORG_OWNER' then raise exception 'OWNER_PROTECTED';end if;if public.principal_is_platform(previous.user_id) then raise exception 'PLATFORM_IDENTITY_PROTECTED';end if;
 if p_role not in ('ADMIN','MEMBER','VIEWER') or p_role is null or p_active is null or p_is_product_lead is null then raise exception 'INVALID_MEMBERSHIP';end if;
 if (previous.role='ADMIN' or p_role='ADMIN') and not public.principal_is_owner(actor.user_id,actor.role) then raise exception 'OWNER_REQUIRED';end if;if p_is_product_lead and p_role='VIEWER' then raise exception 'VIEWER_CANNOT_LEAD';end if;
 update public.organization_memberships set role=p_role,active=p_active,is_product_lead=p_is_product_lead where id=p_target_id;if not p_active then delete from public.workspace_sessions where organization_id=oid and user_id=previous.user_id;end if;
 insert into public.membership_events(workspace_id,organization_id,actor_id,target_id,action,before_state,after_state) values(p_workspace_id,oid,actor.user_id,p_target_id::text,'MEMBERSHIP_CHANGED',to_jsonb(previous),jsonb_build_object('role',p_role,'active',p_active,'isProductLead',p_is_product_lead));end;$$;
create or replace function public.manage_workspace_invitation(p_workspace_id uuid,p_member_id uuid,p_action text,p_invitation_id uuid,p_email text,p_role text,p_token_hash text) returns uuid language plpgsql set search_path='' as $$declare actor public.organization_memberships;item public.workspace_invitations;oid uuid;begin
 select organization_id into oid from public.workspaces where id=p_workspace_id;perform 1 from public.organizations where id=oid for update;actor:=public.require_workspace_member(p_workspace_id,p_member_id,true,false);
 if p_action='INVITE' then
  if p_role is null or p_role not in ('ADMIN','MEMBER','VIEWER') then raise exception 'OWNER_RESERVED';end if;if p_role='ADMIN' and not public.principal_is_owner(actor.user_id,actor.role) then raise exception 'OWNER_REQUIRED';end if;if not public.organization_email_allowed(oid,p_email) then raise exception 'EMAIL_NOT_ALLOWED';end if;if exists(select 1 from public.users where lower(email)=lower(btrim(p_email)) and platform_role='PLATFORM_OWNER') then raise exception 'PLATFORM_IDENTITY_PROTECTED';end if;
  if exists(select 1 from public.organization_memberships m join public.users u on u.id=m.user_id where m.organization_id=oid and lower(u.email)=lower(btrim(p_email))) then raise exception 'MEMBERSHIP_ALREADY_EXISTS';end if;
  update public.workspace_invitations set revoked_at=clock_timestamp() where organization_id=oid and email=lower(btrim(p_email)) and used_at is null and revoked_at is null and expires_at<=clock_timestamp();
  insert into public.workspace_invitations(workspace_id,organization_id,email,role,token_hash,expires_at,invited_by) values(p_workspace_id,oid,lower(btrim(p_email)),p_role,p_token_hash,clock_timestamp()+interval '7 days',actor.user_id) returning * into item;
 else
  select * into item from public.workspace_invitations where id=p_invitation_id and workspace_id=p_workspace_id for update;if not found or item.used_at is not null or item.revoked_at is not null or item.provisioned_by_platform then raise exception 'INVITE_INVALID';end if;
  if item.role='ADMIN' and not public.principal_is_owner(actor.user_id,actor.role) then raise exception 'OWNER_REQUIRED';end if;
  if p_action='RESEND' then if not public.organization_email_allowed(oid,item.email) then raise exception 'EMAIL_NOT_ALLOWED';end if;update public.workspace_invitations set token_hash=p_token_hash,expires_at=clock_timestamp()+interval '7 days' where id=item.id;
  elsif p_action='REVOKE' then update public.workspace_invitations set revoked_at=clock_timestamp() where id=item.id;else raise exception 'INVALID_ACTION';end if;
 end if;
 insert into public.membership_events(workspace_id,organization_id,actor_id,target_id,action,after_state) values(p_workspace_id,oid,actor.user_id,item.id::text,'INVITATION_'||p_action,jsonb_build_object('email',item.email,'role',item.role));return item.id;end;$$;
create function public.inspect_workspace_invitation(p_workspace_id uuid,p_token_hash text) returns jsonb language plpgsql set search_path='' as $$declare item public.workspace_invitations;m public.organization_memberships;begin
 select * into item from public.workspace_invitations where token_hash=p_token_hash and (p_workspace_id is null or workspace_id=p_workspace_id);if not found or item.revoked_at is not null or item.used_at is not null or item.expires_at<=clock_timestamp() then raise exception 'INVITE_INVALID';end if;
 if item.provisioned_by_platform then if not public.principal_is_platform(item.invited_by) then raise exception 'INVITE_INVALID';end if;
 else if exists(select 1 from public.users where lower(email)=item.email and platform_role='PLATFORM_OWNER') then raise exception 'PLATFORM_IDENTITY_PROTECTED';end if;m:=public.require_workspace_member(item.workspace_id,coalesce((select id from public.organization_memberships where organization_id=item.organization_id and user_id=item.invited_by),item.invited_by),true,false);if item.role='ORG_OWNER' or (item.role='ADMIN' and not public.principal_is_owner(m.user_id,m.role)) then raise exception 'INVITE_INVALID';end if;end if;
 if not item.policy_override and not public.organization_email_allowed(item.organization_id,item.email) then raise exception 'EMAIL_NOT_ALLOWED';end if;
 return jsonb_build_object('email',item.email,'role',item.role,'expiresAt',item.expires_at,'workspaceId',item.workspace_id,'organizationId',item.organization_id);end;$$;
create or replace function public.accept_workspace_invitation(p_workspace_id uuid,p_token_hash text,p_auth_user_id uuid,p_display_name text) returns uuid language plpgsql security definer set search_path='' as $$declare item public.workspace_invitations;uid uuid;mid uuid;provider_email text;oid uuid;begin
 select organization_id into oid from public.workspaces where id=p_workspace_id;perform 1 from public.organizations where id=oid for update;select * into item from public.workspace_invitations where workspace_id=p_workspace_id and token_hash=p_token_hash for update;perform public.inspect_workspace_invitation(p_workspace_id,p_token_hash);
 if nullif(btrim(p_display_name),'') is null or length(btrim(p_display_name))>120 then raise exception 'NAME_REQUIRED';end if;select lower(btrim(email)) into provider_email from auth.users where id=p_auth_user_id;if provider_email is distinct from item.email then raise exception 'INVITATION_IDENTITY_MISMATCH';end if;
 select id into uid from public.users where auth_user_id=p_auth_user_id and lower(email)=item.email and active and not is_system;if uid is null then insert into public.users(email,display_name,auth_user_id) values(item.email,btrim(p_display_name),p_auth_user_id) returning id into uid;end if;
 if exists(select 1 from public.organization_memberships where organization_id=oid and user_id=uid) then raise exception 'MEMBERSHIP_ALREADY_EXISTS';end if;
 insert into public.organization_memberships(organization_id,user_id,role,policy_override,policy_override_reason) values(oid,uid,item.role,item.policy_override,item.policy_override_reason) returning id into mid;update public.workspace_invitations set used_at=clock_timestamp() where id=item.id;
 if item.role='ORG_OWNER' then update public.organizations set status='ACTIVE' where id=oid;update public.workspaces set status='ACTIVE' where organization_id=oid;end if;
 insert into public.membership_events(workspace_id,organization_id,actor_id,target_id,action,after_state,reason,policy_overridden) values(p_workspace_id,oid,uid,mid::text,'INVITATION_ACCEPTED',jsonb_build_object('role',item.role),item.policy_override_reason,item.policy_override);return mid;end;$$;
create or replace function public.bootstrap_workspace_admin(p_workspace_id uuid,p_email text,p_token_hash text) returns uuid language plpgsql set search_path='' as $$begin raise exception 'EXPLICIT_PLATFORM_BOOTSTRAP_REQUIRED';end;$$;
create function public.require_platform_owner(p_actor_id uuid) returns public.users language plpgsql set search_path='' as $$declare actor public.users;begin select * into actor from public.users where id=p_actor_id and active and platform_role='PLATFORM_OWNER' and not is_system and auth_user_id is not null for share;if not found then raise exception 'PLATFORM_OWNER_REQUIRED';end if;return actor;end;$$;
create function public.platform_audit(p_actor_id uuid,p_organization_id uuid,p_workspace_id uuid,p_target_id text,p_action text,p_before jsonb,p_after jsonb,p_reason text,p_override boolean default false) returns void language plpgsql set search_path='' as $$declare label text;begin
 if nullif(btrim(p_reason),'') is null or length(btrim(p_reason))>500 then raise exception 'AUDIT_REASON_REQUIRED';end if;if p_workspace_id is not null and (p_organization_id is null or not exists(select 1 from public.workspaces where id=p_workspace_id and organization_id=p_organization_id)) then raise exception 'ORGANIZATION_SCOPE';end if;
 select display_name into label from public.users where id=p_actor_id;insert into public.platform_events(actor_id,actor_label,organization_id,workspace_id,target_id,action,before_state,after_state,reason,policy_overridden) values(p_actor_id,label,p_organization_id,p_workspace_id,p_target_id,p_action,p_before,p_after,btrim(p_reason),p_override);end;$$;
-- Trusted operator only, no service_role/public/application EXECUTE.
create function public.bootstrap_platform_owner(p_user_id uuid) returns void language plpgsql security definer set search_path='' as $$begin perform pg_advisory_xact_lock(121204);if exists(select 1 from public.users where platform_role='PLATFORM_OWNER') then raise exception 'PLATFORM_BOOTSTRAP_ALREADY_COMPLETE';end if;update public.users set platform_role='PLATFORM_OWNER' where id=p_user_id and active and not is_system and auth_user_id is not null;if not found then raise exception 'ACCESS_DENIED';end if;perform public.platform_audit(p_user_id,null,null,p_user_id::text,'PLATFORM_BOOTSTRAPPED',null,jsonb_build_object('platformRole','PLATFORM_OWNER'),'Trusted operator bootstrap',false);end;$$;
create function public.grant_platform_owner(p_actor_id uuid,p_target_user_id uuid,p_reason text) returns void language plpgsql security definer set search_path='' as $$declare oldrole text;begin perform public.require_platform_owner(p_actor_id);perform pg_advisory_xact_lock(121204);select platform_role into oldrole from public.users where id=p_target_user_id and active and not is_system and auth_user_id is not null for update;if not found then raise exception 'ACCESS_DENIED';end if;update public.users set platform_role='PLATFORM_OWNER' where id=p_target_user_id;perform public.platform_audit(p_actor_id,null,null,p_target_user_id::text,'PLATFORM_ROLE_GRANTED',jsonb_build_object('platformRole',oldrole),jsonb_build_object('platformRole','PLATFORM_OWNER'),p_reason,false);end;$$;
create function public.platform_create_organization(p_actor_id uuid,p_name text,p_domains text[],p_exact_emails text[]) returns jsonb language plpgsql set search_path='' as $$declare oid uuid;wid uuid;begin perform public.require_platform_owner(p_actor_id);insert into public.organizations(name,allowed_email_domains,allowed_exact_emails) values(btrim(p_name),p_domains,p_exact_emails) returning id into oid;insert into public.workspaces(name,organization_id) values(btrim(p_name),oid) returning id into wid;perform public.platform_audit(p_actor_id,oid,wid,oid::text,'ORGANIZATION_CREATED',null,jsonb_build_object('name',p_name,'domains',p_domains,'exactEmails',p_exact_emails),'Platform organization creation',false);return jsonb_build_object('organizationId',oid,'workspaceId',wid);end;$$;
create function public.platform_configure_policy(p_actor_id uuid,p_organization_id uuid,p_domains text[],p_exact_emails text[]) returns void language plpgsql set search_path='' as $$declare previous public.organizations;begin perform public.require_platform_owner(p_actor_id);select * into previous from public.organizations where id=p_organization_id for update;if not found then raise exception 'ACCESS_DENIED';end if;update public.organizations set allowed_email_domains=p_domains,allowed_exact_emails=p_exact_emails where id=p_organization_id;perform public.platform_audit(p_actor_id,p_organization_id,null,p_organization_id::text,'ORGANIZATION_POLICY_CHANGED',jsonb_build_object('domains',previous.allowed_email_domains,'exactEmails',previous.allowed_exact_emails),jsonb_build_object('domains',p_domains,'exactEmails',p_exact_emails),'Platform policy update',false);end;$$;
create function public.platform_provision_membership(p_actor_id uuid,p_organization_id uuid,p_email text,p_role text,p_policy_override boolean,p_reason text,p_token_hash text) returns jsonb language plpgsql set search_path='' as $$declare uid uuid;mid uuid;wid uuid;iid uuid;previous public.organization_memberships;begin
 perform public.require_platform_owner(p_actor_id);perform 1 from public.organizations where id=p_organization_id for update;if not found then raise exception 'ACCESS_DENIED';end if;
 if p_role is null or p_role not in ('ORG_OWNER','ADMIN','MEMBER','VIEWER') or p_policy_override is null or nullif(btrim(p_reason),'') is null or length(btrim(p_reason))>500 then raise exception 'INVALID_MEMBERSHIP';end if;
 if p_email is null or lower(btrim(p_email))!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'INVALID_EMAIL';end if;if not p_policy_override and not public.organization_email_allowed(p_organization_id,p_email) then raise exception 'EMAIL_NOT_ALLOWED';end if;
 select id into wid from public.workspaces where organization_id=p_organization_id order by created_at,id limit 1;if wid is null then raise exception 'WORKSPACE_REQUIRED';end if;select id into uid from public.users where lower(email)=lower(btrim(p_email)) and active and not is_system and auth_user_id is not null for share;
 if uid is null then
  if exists(select 1 from public.users where lower(email)=lower(btrim(p_email))) then raise exception 'IDENTITY_UNAVAILABLE';end if;
  update public.workspace_invitations set revoked_at=clock_timestamp() where organization_id=p_organization_id and email=lower(btrim(p_email)) and used_at is null and revoked_at is null;
  insert into public.workspace_invitations(workspace_id,organization_id,email,role,token_hash,expires_at,invited_by,provisioned_by_platform,policy_override,policy_override_reason) values(wid,p_organization_id,lower(btrim(p_email)),p_role,p_token_hash,clock_timestamp()+interval '7 days',p_actor_id,true,p_policy_override,case when p_policy_override then btrim(p_reason) else null end) returning id into iid;
 else
  select * into previous from public.organization_memberships where organization_id=p_organization_id and user_id=uid for update;
  insert into public.organization_memberships(organization_id,user_id,role,policy_override,policy_override_reason) values(p_organization_id,uid,p_role,p_policy_override,case when p_policy_override then btrim(p_reason) else null end) on conflict(organization_id,user_id) do update set role=excluded.role,active=true,is_product_lead=case when excluded.role='VIEWER' then false else organization_memberships.is_product_lead end,policy_override=excluded.policy_override,policy_override_reason=excluded.policy_override_reason returning id into mid;
  if p_role='ORG_OWNER' then update public.organizations set status='ACTIVE' where id=p_organization_id;update public.workspaces set status='ACTIVE' where organization_id=p_organization_id;end if;
 end if;
 perform public.platform_audit(p_actor_id,p_organization_id,wid,coalesce(uid::text,iid::text),'PLATFORM_MEMBERSHIP_GRANTED',case when previous.id is null then null else to_jsonb(previous) end,jsonb_build_object('userId',uid,'email',lower(btrim(p_email)),'memberId',mid,'invitationId',iid,'role',p_role),p_reason,p_policy_override);return jsonb_build_object('userId',uid,'memberId',mid,'invitationId',iid,'workspaceId',wid);end;$$;
create function public.platform_replace_org_owner(p_actor_id uuid,p_organization_id uuid,p_target_user_id uuid,p_reason text) returns void language plpgsql set search_path='' as $$declare target public.organization_memberships;previous jsonb;begin
 perform public.require_platform_owner(p_actor_id);perform 1 from public.organizations where id=p_organization_id for update;if not found then raise exception 'ACCESS_DENIED';end if;
 select m.* into target from public.organization_memberships m join public.users u on u.id=m.user_id where m.organization_id=p_organization_id and m.user_id=p_target_user_id and m.active and u.active for update of m;if not found then raise exception 'ACCESS_DENIED';end if;
 if not target.policy_override and not public.organization_email_allowed(p_organization_id,(select email from public.users where id=p_target_user_id)) then raise exception 'EMAIL_NOT_ALLOWED';end if;
 select jsonb_agg(to_jsonb(m)) into previous from public.organization_memberships m where organization_id=p_organization_id and role='ORG_OWNER';update public.organization_memberships set role='ADMIN' where organization_id=p_organization_id and role='ORG_OWNER';update public.organization_memberships set role='ORG_OWNER' where id=target.id;
 update public.organizations set status='ACTIVE' where id=p_organization_id;update public.workspaces set status='ACTIVE' where organization_id=p_organization_id;
 perform public.platform_audit(p_actor_id,p_organization_id,null,p_target_user_id::text,'ORGANIZATION_OWNERS_REPLACED',previous,jsonb_build_object('ownerUserId',p_target_user_id),p_reason,target.policy_override);end;$$;
create function public.rename_workspace(p_workspace_id uuid,p_member_id uuid,p_name text) returns void language plpgsql set search_path='' as $$declare actor public.organization_memberships;previous text;begin actor:=public.require_workspace_member(p_workspace_id,p_member_id,true,false);if not public.principal_is_owner(actor.user_id,actor.role) then raise exception 'OWNER_REQUIRED';end if;select name into previous from public.workspaces where id=p_workspace_id for update;update public.workspaces set name=btrim(p_name) where id=p_workspace_id;insert into public.membership_events(workspace_id,organization_id,actor_id,target_id,action,before_state,after_state) values(p_workspace_id,actor.organization_id,actor.user_id,p_workspace_id::text,'WORKSPACE_RENAMED',jsonb_build_object('name',previous),jsonb_build_object('name',p_name));end;$$;
create function public.review_actor_allowed(p_workspace_id uuid,p_member_id text,p_user_id text) returns boolean language sql stable set search_path='' as $$select exists(select 1 from public.users u where u.id::text=p_user_id and u.active and not u.is_system and ((u.platform_role='PLATFORM_OWNER' and (p_member_id is null or exists(select 1 from public.memberships m where m.id::text=p_member_id and m.workspace_id=p_workspace_id and m.user_id=u.id and m.active))) or exists(select 1 from public.organization_memberships m join public.workspaces w on w.organization_id=m.organization_id where w.id=p_workspace_id and m.id::text=p_member_id and m.user_id=u.id and m.active and m.role<>'VIEWER' and (m.policy_override or public.organization_email_allowed(m.organization_id,u.email)))));$$;
revoke insert,update on public.users from service_role;
grant insert(id,email,display_name,created_at,auth_user_id,is_system,active) on public.users to service_role;
grant update(email,display_name) on public.users to service_role;
create function public.platform_rotate_invitation(p_actor_id uuid,p_invitation_id uuid,p_revoke boolean,p_token_hash text,p_reason text) returns void language plpgsql set search_path='' as $$declare item public.workspace_invitations;oid uuid;begin
 perform public.require_platform_owner(p_actor_id);select organization_id into oid from public.workspace_invitations where id=p_invitation_id;perform 1 from public.organizations where id=oid for update;
 select * into item from public.workspace_invitations where id=p_invitation_id and provisioned_by_platform for update;if not found or item.revoked_at is not null or item.used_at is not null or p_revoke is null then raise exception 'INVITE_INVALID';end if;
 if p_revoke then update public.workspace_invitations set revoked_at=clock_timestamp() where id=item.id;
 else if not item.policy_override and not public.organization_email_allowed(oid,item.email) then raise exception 'EMAIL_NOT_ALLOWED';end if;update public.workspace_invitations set token_hash=p_token_hash,expires_at=clock_timestamp()+interval '7 days',invited_by=p_actor_id where id=item.id;end if;
 perform public.platform_audit(p_actor_id,oid,item.workspace_id,item.id::text,case when p_revoke then 'PLATFORM_INVITATION_REVOKED' else 'PLATFORM_INVITATION_RESENT' end,null,jsonb_build_object('email',item.email,'role',item.role),p_reason,item.policy_override);end;$$;
-- Existing semantic transaction validators retained. New writes bind global actor.
do $$declare body text;begin
 select pg_get_functiondef('public.delivery_source(uuid)'::regprocedure) into body;body:=replace(body,'''active'',m.active','''active'',m.active and u.active');execute body;
 select pg_get_functiondef('public.auth_business_rpc(uuid,uuid,text,jsonb)'::regprocedure) into body;body:=replace(body,'m public.memberships;','m public.organization_memberships;');execute body;
 select pg_get_functiondef('public.delivery_read_workspace(uuid,uuid)'::regprocedure) into body;body:=replace(body,'if not exists(select 1 from public.memberships m where m.id=p_member_id and m.workspace_id=p_workspace_id and m.active) then raise exception ''MEMBERSHIP_ACCESS''; end if;','');execute body;
 select pg_get_functiondef('public.delivery_commit_workspace(uuid,uuid,jsonb,jsonb,jsonb)'::regprocedure) into body;if position('SECTION_REVIEW_REQUIRED' in body)=0 then raise exception 'DELIVERY_VALIDATOR_VERSION';end if;
 body:=replace(body,'v_member public.memberships%rowtype;','v_member public.organization_memberships%rowtype;');body:=replace(body,'perform public.require_workspace_member(p_workspace_id,p_member_id,false,true);','v_member:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);');body:=replace(body,'select * into v_member from public.memberships where id=p_member_id and workspace_id=p_workspace_id and active for update;','');body:=replace(body,'if not found or v_member.role=''Viewer'' then raise exception ''WRITE_ACCESS''; end if;','');
 body:=replace(body,'''Admin''','''ADMIN''');body:=replace(body,'''Member''','''MEMBER''');body:=replace(body,'''Viewer''','''VIEWER''');body:=replace(body,'v_member.role=''ADMIN''','public.principal_is_admin(v_member.user_id,v_member.role)');body:=replace(body,'v_member.role<>''ADMIN''','not public.principal_is_admin(v_member.user_id,v_member.role)');
 body:=replace(body,'v_item->>''confirmedByMemberId'' is distinct from p_member_id::text','(v_item->>''confirmedByMemberId'' is distinct from v_member.id::text or v_item->>''confirmedByUserId'' is distinct from v_user::text)');body:=replace(body,'v_item->>''createdByMemberId'' is distinct from p_member_id::text','(v_item->>''createdByMemberId'' is distinct from v_member.id::text or v_item->>''createdByUserId'' is distinct from v_user::text)');body:=replace(body,'v_item->>''finalizedByMemberId'' is distinct from p_member_id::text','(v_item->>''finalizedByMemberId'' is distinct from v_member.id::text or v_item->>''finalizedByUserId'' is distinct from v_user::text)');body:=replace(body,'v_section->>''editedByMemberId'' is distinct from p_member_id::text','(v_section->>''editedByMemberId'' is distinct from v_member.id::text or v_section->>''editedByUserId'' is distinct from v_user::text or v_section->>''editedByLabel'' is distinct from v_label)');
 body:=replace(body,'''finalizedByMemberId'',''finalizedByLabel''','''finalizedByMemberId'',''finalizedByUserId'',''finalizedByLabel''');body:=replace(body,'v_item->>''finalizedByMemberId'' is not null','(v_item->>''finalizedByMemberId'' is not null or v_item->>''finalizedByUserId'' is not null)');body:=replace(body,'v_section->>''editedByMemberId'' is not null','(v_section->>''editedByMemberId'' is not null or v_section->>''editedByUserId'' is not null)');body:=replace(body,'not exists(select 1 from public.memberships m where m.id=(v_item#>>''{value,memberId}'')::uuid and m.workspace_id=p_workspace_id and m.active and m.role<>''VIEWER'')','not public.review_actor_allowed(p_workspace_id,v_item#>>''{value,memberId}'',(select user_id::text from public.memberships where id=(v_item#>>''{value,memberId}'')::uuid and workspace_id=p_workspace_id))');body:=replace(body,'not exists(select 1 from public.memberships m where m.id=(s->>''editedByMemberId'')::uuid and m.workspace_id=p_workspace_id and m.active and m.role<>''VIEWER'')','not public.review_actor_allowed(p_workspace_id,s->>''editedByMemberId'',s->>''editedByUserId'')');execute body;
end;$$;
-- New global actor fields allow platform principals with nullable member ids.
do $$declare c record;begin
 for c in select conname from pg_constraint where conrelid='public.delivery_facts'::regclass and contype='c' and pg_get_constraintdef(oid) like '%confirmedByMemberId%' loop execute format('alter table public.delivery_facts drop constraint %I',c.conname);end loop;
 for c in select conname from pg_constraint where conrelid='public.weekly_reviews'::regclass and contype='c' and pg_get_constraintdef(oid) like '%finalizedByMemberId%' loop execute format('alter table public.weekly_reviews drop constraint %I',c.conname);end loop;
end;$$;
alter table public.delivery_facts add constraint delivery_actor_reference check((data->>'confirmedByMemberId' is not null or data->>'confirmedByUserId' is not null) and data->>'updatedAt' is not null);
alter table public.weekly_reviews add constraint review_final_actor_reference check(status<>'FINAL' or ((data->>'finalizedByMemberId' is not null or data->>'finalizedByUserId' is not null) and data->>'finalizedAt' is not null));
do $$declare t text;f record;begin
 foreach t in array array['organizations','organization_memberships','platform_events'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select,insert,update,delete on public.%I to service_role',t);end loop;
 revoke all on public.memberships from public,anon,authenticated;grant select,update on public.memberships to service_role;
 for f in select oid from pg_proc where pronamespace='public'::regnamespace and proname in ('email_policy_valid','organization_email_allowed','workspace_email_allowed','is_workspace_administrator','principal_is_platform','principal_is_admin','principal_is_owner','organization_membership_immutable_keys','global_identity_guard','attach_organization_scope','inspect_workspace_invitation','require_platform_owner','platform_audit','bootstrap_platform_owner','grant_platform_owner','platform_create_organization','platform_configure_policy','platform_provision_membership','platform_rotate_invitation','platform_replace_org_owner','rename_workspace','review_actor_allowed') loop
 execute format('revoke all on function %s from public,anon,authenticated,service_role',f.oid::regprocedure);if f.oid<> 'public.bootstrap_platform_owner(uuid)'::regprocedure then execute format('grant execute on function %s to service_role',f.oid::regprocedure);end if;
 end loop;
end;$$;
commit;
