-- Additive evidence proposals. No canonical write until an explicit confirmation.
begin;
create table public.evidence_submissions(id uuid primary key,workspace_id uuid not null references public.workspaces(id),initiative_id uuid not null,request_id uuid not null,data jsonb not null,unique(workspace_id,request_id),foreign key(initiative_id,workspace_id) references public.initiatives(id,workspace_id));
create table public.evidence_attempts(id uuid primary key,workspace_id uuid not null references public.workspaces(id),initiative_id uuid not null,submission_id uuid not null references public.evidence_submissions(id),request_id uuid not null,data jsonb not null,unique(submission_id,request_id),foreign key(initiative_id,workspace_id) references public.initiatives(id,workspace_id));
create table public.evidence_anchors(id uuid primary key,workspace_id uuid not null references public.workspaces(id),initiative_id uuid not null,submission_id uuid not null references public.evidence_submissions(id),data jsonb not null,foreign key(initiative_id,workspace_id) references public.initiatives(id,workspace_id));
create table public.evidence_proposals(id uuid primary key,workspace_id uuid not null references public.workspaces(id),initiative_id uuid not null,submission_id uuid not null references public.evidence_submissions(id),attempt_id uuid not null references public.evidence_attempts(id),anchor_id uuid not null references public.evidence_anchors(id),data jsonb not null,foreign key(initiative_id,workspace_id) references public.initiatives(id,workspace_id));
create table public.evidence_confirmations(proposal_id uuid primary key references public.evidence_proposals(id),workspace_id uuid not null references public.workspaces(id),initiative_id uuid not null,data jsonb not null,foreign key(initiative_id,workspace_id) references public.initiatives(id,workspace_id));
do $$declare t text;begin foreach t in array array['evidence_submissions','evidence_attempts','evidence_anchors','evidence_proposals','evidence_confirmations'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);execute format('grant select,insert on public.%I to service_role',t);end loop;end$$;
grant update on public.evidence_attempts,public.evidence_proposals to service_role;
create index evidence_submission_initiative on public.evidence_submissions(workspace_id,initiative_id);
create index evidence_proposal_initiative on public.evidence_proposals(workspace_id,initiative_id);
alter table public.claims add column evidence_submission_id uuid references public.evidence_submissions(id),add column evidence_anchor_id uuid references public.evidence_anchors(id);

create function public.assert_initiative_not_archived(p_workspace_id uuid,p_initiative_id uuid) returns void language plpgsql set search_path='' as $$begin if not exists(select 1 from public.initiatives where id=p_initiative_id and workspace_id=p_workspace_id) then raise exception 'INITIATIVE_ACCESS';end if;if exists(select 1 from public.initiatives where id=p_initiative_id and workspace_id=p_workspace_id and archived_at is not null) then raise exception 'INITIATIVE_ARCHIVED';end if;end$$;
create function public.evidence_utf16_slice(p_text text,p_start integer,p_end integer) returns text language plpgsql immutable set search_path='' as $$
declare n integer:=0;position integer:=1;ch text;units integer;result text:='';begin
 if p_start<0 or p_end<=p_start then return null;end if;
 while position<=length(p_text) loop ch:=substr(p_text,position,1);units:=case when ascii(ch)>65535 then 2 else 1 end;
 if (p_start>n and p_start<n+units) or (p_end>n and p_end<n+units) then return null;end if;
 if n>=p_start and n+units<=p_end then result:=result||ch;end if;n:=n+units;position:=position+1;end loop;
 if p_end>n then return null;end if;return result;end$$;
create function public.guard_evidence_anchor() returns trigger language plpgsql set search_path='' as $$declare s public.evidence_submissions;begin select * into s from public.evidence_submissions where id=new.submission_id and workspace_id=new.workspace_id and initiative_id=new.initiative_id;if not found or public.evidence_utf16_slice(s.data->>'text',(new.data->>'start')::integer,(new.data->>'end')::integer) is distinct from new.data->>'quote' then raise exception 'ANCHOR_INVALID';end if;return new;end$$;
create trigger evidence_anchor_exact before insert on public.evidence_anchors for each row execute function public.guard_evidence_anchor();
create function public.guard_evidence_proposal() returns trigger language plpgsql set search_path='' as $$begin if old.data->>'status' in ('CONFIRMED','REJECTED','SUPERSEDED_BY_HUMAN_ENTRY') or new.workspace_id<>old.workspace_id or new.initiative_id<>old.initiative_id or new.submission_id<>old.submission_id or new.attempt_id<>old.attempt_id or new.anchor_id<>old.anchor_id or (new.data->>'version')::integer<>(old.data->>'version')::integer+1 or (new.data-array['payload','version','status','decidedBy','decidedAt','reason','resultType','resultId']) is distinct from (old.data-array['payload','version','status','decidedBy','decidedAt','reason','resultType','resultId']) then raise exception 'PROPOSAL_IMMUTABLE_OR_STALE';end if;return new;end$$;
create trigger evidence_proposal_revision before update on public.evidence_proposals for each row execute function public.guard_evidence_proposal();
create function public.read_anchored_evidence(p_workspace_id uuid,p_member_id uuid,p_initiative_id uuid) returns jsonb language plpgsql stable set search_path='' as $$
begin perform public.require_workspace_member(p_workspace_id,p_member_id,false,false);if not exists(select 1 from public.initiatives where id=p_initiative_id and workspace_id=p_workspace_id) then raise exception 'INITIATIVE_ACCESS';end if;
return jsonb_build_object('submissions',coalesce((select jsonb_agg(data order by data->>'createdAt') from public.evidence_submissions where workspace_id=p_workspace_id and initiative_id=p_initiative_id),'[]'::jsonb),'attempts',coalesce((select jsonb_agg(data order by data->>'startedAt') from public.evidence_attempts where workspace_id=p_workspace_id and initiative_id=p_initiative_id),'[]'::jsonb),'anchors',coalesce((select jsonb_agg(data) from public.evidence_anchors where workspace_id=p_workspace_id and initiative_id=p_initiative_id),'[]'::jsonb),'proposals',coalesce((select jsonb_agg(data order by id) from public.evidence_proposals where workspace_id=p_workspace_id and initiative_id=p_initiative_id),'[]'::jsonb),'confirmations',coalesce((select jsonb_agg(data) from public.evidence_confirmations where workspace_id=p_workspace_id and initiative_id=p_initiative_id),'[]'::jsonb));end$$;
create function public.submit_anchored_evidence(p_workspace_id uuid,p_member_id uuid,p_input jsonb) returns uuid language plpgsql set search_path='' as $$
declare actor public.organization_memberships;i public.initiatives;prior public.evidence_submissions;sid uuid:=gen_random_uuid();eid uuid:=gen_random_uuid();item_id uuid:=nullif(p_input->>'sourceItemId','')::uuid;at_time timestamptz:=clock_timestamp();text_value text:=p_input->>'text';title text:=btrim(p_input->>'title');payload jsonb;begin
actor:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);select * into i from public.initiatives where id=(p_input->>'initiativeId')::uuid and workspace_id=p_workspace_id for update;if not found then raise exception 'INITIATIVE_ACCESS';end if;if i.archived_at is not null then raise exception 'ARCHIVED';end if;
if length(btrim(text_value))=0 or length(text_value)>20000 or coalesce((p_input->>'charLength')::integer,0) not between 1 and 20000 or length(title) not between 1 and 200 or p_input->>'textSha256' is distinct from encode(sha256(convert_to(text_value,'UTF8')),'hex') then raise exception 'INVALID_EVIDENCE';end if;
select * into prior from public.evidence_submissions where workspace_id=p_workspace_id and request_id=(p_input->>'requestId')::uuid;if found then if prior.data->>'createdBy'<>actor.user_id::text or prior.data->>'text' is distinct from text_value or prior.data->>'title' is distinct from title or prior.initiative_id<>i.id then raise exception 'REQUEST_REUSED';end if;return prior.id;end if;
if item_id is null then perform public.map_initiative_sources(p_workspace_id,p_member_id,jsonb_build_object('initiativeId',i.id,'provider','PASTED_EVIDENCE','providerWorkspace',p_workspace_id,'containerReference','pasted-evidence','containerName','Saved pasted evidence','role','GENERAL','items',jsonb_build_array(jsonb_build_object('reference',sid,'name',title,'kind','PASTED','url',null))));select id into item_id from public.source_items where workspace_id=p_workspace_id and reference=sid::text;
elsif not exists(select 1 from public.source_mappings where workspace_id=p_workspace_id and initiative_id=i.id and source_mappings.item_id=submit_anchored_evidence.item_id and unlinked_at is null) then raise exception 'SOURCE_ACCESS';end if;
insert into public.evidence(id,workspace_id,initiative_id,title,source_type,source_reference,content_summary,boundary,captured_at,created_by) values(eid,p_workspace_id,i.id,title,'DOCUMENT',sid::text,text_value,'CURRENT_SCOPE',at_time,actor.user_id);
payload:=jsonb_build_object('id',sid,'workspaceId',p_workspace_id,'organizationId',actor.organization_id,'initiativeId',i.id,'sourceItemId',item_id,'evidenceId',eid,'kind','PASTED','title',title,'text',text_value,'textSha256',p_input->>'textSha256','charLength',(p_input->>'charLength')::integer,'createdBy',actor.user_id,'createdAt',at_time,'requestId',p_input->>'requestId');
insert into public.evidence_submissions values(sid,p_workspace_id,i.id,(p_input->>'requestId')::uuid,payload);insert into public.activity_log(workspace_id,initiative_id,event_type,summary,entity_type,entity_id,actor_label,payload) values(p_workspace_id,i.id,'EVIDENCE_SAVED','Evidence saved: '||title||'. No product facts confirmed.','EVIDENCE',eid,(select display_name from public.users where id=actor.user_id),jsonb_build_object('submissionId',sid,'sourceItemId',item_id));return sid;end$$;
create function public.start_evidence_attempt(p_workspace_id uuid,p_member_id uuid,p_submission_id uuid,p_request_id uuid) returns jsonb language plpgsql set search_path='' as $$
declare actor public.organization_memberships;s public.evidence_submissions;a public.evidence_attempts;aid uuid:=gen_random_uuid();begin actor:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);select * into s from public.evidence_submissions where id=p_submission_id and workspace_id=p_workspace_id;if not found then raise exception 'EVIDENCE_ACCESS';end if;perform 1 from public.initiatives where id=s.initiative_id and workspace_id=p_workspace_id for update;perform public.assert_initiative_not_archived(p_workspace_id,s.initiative_id);select * into a from public.evidence_attempts where submission_id=s.id and request_id=p_request_id;if found then return jsonb_build_object('replay',true,'attemptId',a.id,'submission',s.data);end if;
insert into public.evidence_attempts values(aid,p_workspace_id,s.initiative_id,s.id,p_request_id,jsonb_build_object('id',aid,'workspaceId',p_workspace_id,'initiativeId',s.initiative_id,'submissionId',s.id,'requestId',p_request_id,'status','READING','startedAt',clock_timestamp(),'endedAt',null,'errorCode',null,'model',null,'promptVersion','ANCHORED_EVIDENCE_V1','discardedCount',0));return jsonb_build_object('replay',false,'attemptId',aid,'submission',s.data);end$$;
create function public.finish_evidence_attempt(p_workspace_id uuid,p_member_id uuid,p_attempt_id uuid,p_result jsonb) returns void language plpgsql set search_path='' as $$
declare actor public.organization_memberships;a public.evidence_attempts;s public.evidence_submissions;c jsonb;anchor_id uuid;pid uuid;begin actor:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);select * into a from public.evidence_attempts where id=p_attempt_id and workspace_id=p_workspace_id for update;if not found then raise exception 'ATTEMPT_ACCESS';end if;perform public.assert_initiative_not_archived(p_workspace_id,a.initiative_id);if a.data->>'status'<>'READING' then return;end if;select * into s from public.evidence_submissions where id=a.submission_id;
if jsonb_typeof(p_result->'candidates') is distinct from 'array' or jsonb_array_length(p_result->'candidates')>50 then raise exception 'INVALID_PROPOSALS';end if;
for c in select value from jsonb_array_elements(p_result->'candidates') loop
 if c->>'type' is null or c->>'type' not in ('REQUIREMENT','DECISION','BUSINESS_RULE','RISK','DEPENDENCY','ASSUMPTION','DELIVERY','ACTION') or public.evidence_utf16_slice(s.data->>'text',(c#>>'{anchor,start}')::integer,(c#>>'{anchor,end}')::integer) is distinct from c#>>'{anchor,quote}' or length(coalesce(c#>>'{payload,value}',''))=0 or position(c#>>'{payload,value}' in c#>>'{anchor,quote}')=0 then raise exception 'ANCHOR_INVALID';end if;
 anchor_id:=gen_random_uuid();pid:=gen_random_uuid();insert into public.evidence_anchors values(anchor_id,p_workspace_id,a.initiative_id,s.id,c->'anchor'||jsonb_build_object('id',anchor_id,'workspaceId',p_workspace_id,'initiativeId',a.initiative_id,'submissionId',s.id));
 insert into public.evidence_proposals values(pid,p_workspace_id,a.initiative_id,s.id,a.id,anchor_id,jsonb_build_object('id',pid,'workspaceId',p_workspace_id,'initiativeId',a.initiative_id,'submissionId',s.id,'attemptId',a.id,'anchorId',anchor_id,'type',c->>'type','payload',c->'payload','version',1,'baseRevision',coalesce((c->>'baseRevision')::integer,0),'status','PENDING','decidedBy',null,'decidedAt',null,'reason',null,'resultType',null,'resultId',null));
end loop;update public.evidence_attempts set data=data||jsonb_build_object('status',case when p_result->>'errorCode'='TIMED_OUT' then 'TIMED_OUT' when p_result->>'errorCode' is not null then 'FAILED' else 'READY' end,'endedAt',clock_timestamp(),'errorCode',p_result->>'errorCode','model',p_result->>'model','discardedCount',coalesce((p_result->>'discardedCount')::integer,0)) where id=a.id;end$$;

-- Reuse the commitment command under an internal confirmation transaction only.
do $$declare def text;begin select pg_get_functiondef('public.save_commitment(uuid,uuid,uuid,jsonb)'::regprocedure) into def;
def:=replace(def,$needle$elsif prior.id is null and coalesce(p_input->>'origin','HUMAN_ENTRY')<>'HUMAN_ENTRY' then raise exception 'ORIGIN_CONFIRMATION_REQUIRED';end if;$needle$,$patch$elsif prior.id is null and p_input->>'origin'='CONFIRMED_AI_PROPOSAL' and current_setting('prodwise.confirming_proposal',true)=p_input->>'originRefId' then
 origin:='CONFIRMED_AI_PROPOSAL';origin_ref:=p_input->>'originRefId';origin_href:=p_input->>'originHref';
elsif prior.id is null and coalesce(p_input->>'origin','HUMAN_ENTRY')<>'HUMAN_ENTRY' then raise exception 'ORIGIN_CONFIRMATION_REQUIRED';end if;$patch$);
execute def;end$$;

create function public.decide_evidence_proposal(p_workspace_id uuid,p_member_id uuid,p_input jsonb) returns jsonb language plpgsql set search_path='' as $$
declare actor public.organization_memberships;p public.evidence_proposals;s public.evidence_submissions;a public.evidence_anchors;receipt public.evidence_confirmations;i public.initiatives;op text:=p_input->>'operation';at_time timestamptz:=clock_timestamp();result_id uuid;result_type text;payload jsonb;actor_label text;owner_id uuid;begin
actor:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);select * into p from public.evidence_proposals where id=(p_input->>'id')::uuid and workspace_id=p_workspace_id;if not found then raise exception 'PROPOSAL_ACCESS';end if;
select * into i from public.initiatives where id=p.initiative_id and workspace_id=p_workspace_id for update;perform public.assert_initiative_not_archived(p_workspace_id,i.id);select * into p from public.evidence_proposals where id=p.id for update;
select * into receipt from public.evidence_confirmations where proposal_id=p.id;if found then if receipt.data->>'requestId'<>p_input->>'requestId' then raise exception 'PROPOSAL_HANDLED';end if;return jsonb_build_object('type',receipt.data->>'resultType','id',receipt.data->>'resultId');end if;
if op is null or op not in ('CONFIRM','REJECT','EDIT','HUMAN_ENTRY') or p.data->>'status'<>'PENDING' or (p.data->>'version')::integer is distinct from (p_input->>'version')::integer then raise exception 'STALE_PROPOSAL';end if;
select * into s from public.evidence_submissions where id=p.submission_id and workspace_id=p_workspace_id;select * into a from public.evidence_anchors where id=p.anchor_id and workspace_id=p_workspace_id;
if s.id is null or a.id is null or a.submission_id<>s.id or s.data->>'textSha256' is distinct from encode(sha256(convert_to(s.data->>'text','UTF8')),'hex') or public.evidence_utf16_slice(s.data->>'text',(a.data->>'start')::integer,(a.data->>'end')::integer) is distinct from a.data->>'quote' then raise exception 'ANCHOR_INVALID';end if;
select nullif(data#>>'{value,memberId}','')::uuid into owner_id from public.delivery_facts where workspace_id=p_workspace_id and initiative_id=i.id and kind='OWNER' and data->>'state'='SET';
if p.data->>'type'='DELIVERY' and not coalesce(public.principal_is_platform(actor.user_id) or actor.role in ('ORG_OWNER','ADMIN') or owner_id=actor.id,false) then raise exception 'DELIVERY_AUTHORITY';end if;
select display_name into actor_label from public.users where id=actor.user_id;payload:=p.data->'payload';
if op='EDIT' then
 if p_input->'payload' is null or ((p_input->'payload')-'value') is distinct from (payload-'value') or lower(regexp_replace(regexp_replace(btrim(p_input#>>'{payload,value}'),'\s+',' ','g'),'[.!?]+$','')) is distinct from lower(regexp_replace(regexp_replace(btrim(payload->>'value'),'\s+',' ','g'),'[.!?]+$','')) then raise exception 'VALUE_EDIT_REQUIRES_NEW_ENTRY';end if;
 update public.evidence_proposals set data=data||jsonb_build_object('payload',p_input->'payload','version',(data->>'version')::integer+1) where id=p.id;return null;
end if;

if op='HUMAN_ENTRY' then if p.data->>'type'='DELIVERY' or ((p_input->'payload')-'value') is distinct from (payload-'value') or coalesce(length(btrim(p_input#>>'{payload,value}')),0) not between 1 and 4000 or coalesce(length(btrim(p_input->>'reason')),0) not between 1 and 2000 then raise exception 'HUMAN_ENTRY_INVALID';end if;payload:=p_input->'payload';end if;
if op in ('CONFIRM','HUMAN_ENTRY') then
 if p.data->>'type'='DELIVERY' then
  if p_input->'delivery' is null then raise exception 'DELIVERY_COMMAND_REQUIRED';end if;
  perform public.delivery_commit_workspace(p_workspace_id,p_member_id,p_input#>'{delivery,expectedSource}',p_input#>'{delivery,expectedState}',p_input#>'{delivery,nextState}');
  select id into result_id from public.delivery_facts where workspace_id=p_workspace_id and initiative_id=i.id and kind=payload->>'factKind' and revision=(p.data->>'baseRevision')::integer+1;
  if result_id is null then raise exception 'STALE_TARGET';end if;result_type:='DELIVERY';
 elsif p.data->>'type'='ACTION' then
  if op='CONFIRM' then perform set_config('prodwise.confirming_proposal',p.id::text,true);end if;
  result_id:=public.save_commitment(p_workspace_id,p_member_id,i.id,jsonb_build_object('requestId',p_input->>'requestId','expectedRevision',0,'title',payload->>'value','assigneeMemberId',p_input->>'assigneeMemberId','dueDate',p_input->>'dueDate','status','OPEN','evidenceId',case when op='CONFIRM' then s.data->>'evidenceId' else null end,'note',coalesce(p_input->>'reason',''),'origin',case when op='CONFIRM' then 'CONFIRMED_AI_PROPOSAL' else 'HUMAN_ENTRY' end,'originRefId',case when op='CONFIRM' then p.id else null end,'originHref',case when op='CONFIRM' then '/initiatives/'||i.slug||'/evidence/'||s.id::text else null end));result_type:='ACTION';perform set_config('prodwise.confirming_proposal','',true);
 else
  if p.data->>'type' not in ('REQUIREMENT','DECISION','BUSINESS_RULE','RISK','DEPENDENCY','ASSUMPTION') then raise exception 'TARGET_UNAVAILABLE';end if;result_id:=gen_random_uuid();result_type:='KNOWLEDGE';
  insert into public.claims(id,workspace_id,initiative_id,type,status,subject,attribute,value,domain,phase,created_by,origin,evidence_submission_id,evidence_anchor_id) values(result_id,p_workspace_id,i.id,(p.data->>'type')::public.claim_type,'UNVERIFIED',payload->>'subject',payload->>'attribute',payload->>'value',payload->>'domain',nullif(payload->>'phase',''),actor.user_id,'HUMAN_ENTRY',case when op='CONFIRM' then s.id else null end,case when op='CONFIRM' then a.id else null end);
  if op='CONFIRM' then insert into public.claim_evidence(claim_id,evidence_id,locator,excerpt) values(result_id,(s.data->>'evidenceId')::uuid,'UTF16 '||(a.data->>'start')||'–'||(a.data->>'end'),a.data->>'quote');end if;
 end if;
 insert into public.evidence_confirmations values(p.id,p_workspace_id,i.id,jsonb_build_object('proposalId',p.id,'workspaceId',p_workspace_id,'initiativeId',i.id,'proposalVersion',(p.data->>'version')::integer,'actorId',actor.user_id,'actorLabel',actor_label,'at',at_time,'resultType',result_type,'resultId',result_id,'requestId',p_input->>'requestId'));
end if;
update public.evidence_proposals set data=data||jsonb_build_object('status',case when op='CONFIRM' then 'CONFIRMED' when op='HUMAN_ENTRY' then 'SUPERSEDED_BY_HUMAN_ENTRY' else 'REJECTED' end,'version',(data->>'version')::integer+1,'decidedBy',actor.user_id,'decidedAt',at_time,'reason',nullif(btrim(p_input->>'reason'),''),'resultType',result_type,'resultId',result_id) where id=p.id;
insert into public.activity_log(workspace_id,initiative_id,event_type,summary,entity_type,entity_id,actor_label,payload) values(p_workspace_id,i.id,case when op='CONFIRM' then 'AI_PROPOSAL_CONFIRMED' when op='HUMAN_ENTRY' then 'AI_PROPOSAL_SUPERSEDED' else 'AI_PROPOSAL_REJECTED' end,'Human '||lower(op)||'ed evidence proposal from '||(s.data->>'title'),coalesce(result_type,'EVIDENCE'),coalesce(result_id,(s.data->>'evidenceId')::uuid),actor_label,jsonb_build_object('proposalId',p.id,'submissionId',s.id,'anchorId',a.id));
return case when result_id is null then null else jsonb_build_object('type',result_type,'id',result_id) end;end$$;
create function public.control_anchored_evidence(p_workspace_id uuid,p_member_id uuid,p_submission_id uuid,p_operation text,p_proposal_id uuid default null) returns void language plpgsql set search_path='' as $$
declare actor public.organization_memberships;s public.evidence_submissions;p public.evidence_proposals;owner_id uuid;current_revision integer;new_id uuid:=gen_random_uuid();begin
 actor:=public.require_workspace_member(p_workspace_id,p_member_id,false,true);select * into s from public.evidence_submissions where id=p_submission_id and workspace_id=p_workspace_id;if not found then raise exception 'EVIDENCE_ACCESS';end if;perform 1 from public.initiatives where id=s.initiative_id and workspace_id=p_workspace_id for update;perform public.assert_initiative_not_archived(p_workspace_id,s.initiative_id);
 if p_operation='STOP' then update public.evidence_attempts set data=data||jsonb_build_object('status','STOPPED','endedAt',clock_timestamp()) where submission_id=s.id and workspace_id=p_workspace_id and data->>'status'='READING';return;end if;
 select * into p from public.evidence_proposals where id=p_proposal_id and workspace_id=p_workspace_id and submission_id=s.id for update;if not found or p.data->>'type'<>'DELIVERY' then raise exception 'PROPOSAL_ACCESS';end if;
 select nullif(data#>>'{value,memberId}','')::uuid into owner_id from public.delivery_facts where workspace_id=p_workspace_id and initiative_id=s.initiative_id and kind='OWNER' and data->>'state'='SET';if not coalesce(public.principal_is_admin(actor.user_id,actor.role) or owner_id=actor.id,false) then raise exception 'DELIVERY_AUTHORITY';end if;
 select revision into current_revision from public.delivery_facts where workspace_id=p_workspace_id and initiative_id=s.initiative_id and kind=p.data#>>'{payload,factKind}';current_revision:=coalesce(current_revision,0);
 if p_operation='MARK_OUTDATED' and p.data->>'status'='PENDING' and current_revision<>(p.data->>'baseRevision')::integer then update public.evidence_proposals set data=data||jsonb_build_object('status','OUTDATED','version',(data->>'version')::integer+1) where id=p.id;return;end if;
 if p_operation<>'REPROPOSE' or p.data->>'status'<>'OUTDATED' then raise exception 'PROPOSAL_NOT_OUTDATED';end if;
 insert into public.evidence_proposals values(new_id,p_workspace_id,p.initiative_id,p.submission_id,p.attempt_id,p.anchor_id,p.data||jsonb_build_object('id',new_id,'status','PENDING','version',1,'baseRevision',current_revision,'decidedBy',null,'decidedAt',null,'reason',null,'resultType',null,'resultId',null,'supersededFrom',p.id));end$$;
revoke all on function public.control_anchored_evidence(uuid,uuid,uuid,text,uuid) from public,anon,authenticated;grant execute on function public.control_anchored_evidence(uuid,uuid,uuid,text,uuid) to service_role;
do $$declare t text;begin foreach t in array array['evidence_submissions','evidence_attempts','evidence_anchors','evidence_proposals','evidence_confirmations'] loop execute format('create trigger reject_archived_write before insert or update or delete on public.%I for each row execute function public.guard_archived_product_write()',t);end loop;end$$;
revoke all on function public.read_anchored_evidence(uuid,uuid,uuid),public.submit_anchored_evidence(uuid,uuid,jsonb),public.start_evidence_attempt(uuid,uuid,uuid,uuid),public.finish_evidence_attempt(uuid,uuid,uuid,jsonb),public.decide_evidence_proposal(uuid,uuid,jsonb) from public,anon,authenticated;
grant execute on function public.read_anchored_evidence(uuid,uuid,uuid),public.submit_anchored_evidence(uuid,uuid,jsonb),public.start_evidence_attempt(uuid,uuid,uuid,uuid),public.finish_evidence_attempt(uuid,uuid,uuid,jsonb),public.decide_evidence_proposal(uuid,uuid,jsonb) to service_role;
commit;
