import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalDemoData,DEMO_CUTOFF} from '../demo/canonical.ts';
import {buildPortfolioProjection,filterPortfolioRows} from './portfolio.ts';
import {factFor,recordFact} from '../delivery/model.ts';
import type {WorkspaceAccess} from '../delivery/types.ts';
const identity={workspaceId:'11111111-1111-4111-8111-111111111111',organizationId:'22222222-2222-4222-8222-222222222222',reviewerMemberId:'33333333-3333-4333-8333-333333333333',reviewerUserId:'44444444-4444-4444-8444-444444444444'};
const fixture=()=>canonicalDemoData(identity);
const projection=(d:ReturnType<typeof fixture>)=>buildPortfolioProjection({source:d.source,state:d.deliveryState,workspaceId:identity.workspaceId,activity:d.productStore.activity,asOf:DEMO_CUTOFF});
test('overlapping reasons count once per initiative, separately from reasons',()=>{const p=projection(fixture());const merchant=p.rows.find(r=>r.initiative.slug==='merchant-flex-finance')!;assert.ok(merchant.attention.some(a=>a.kind==='DECISION'));assert.ok(merchant.attention.some(a=>a.kind==='BLOCKER'));assert.equal(p.attentionRows.filter(r=>r.initiative.id===merchant.initiative.id).length,1);assert.equal(p.summary.attentionReasons,p.rows.reduce((n,r)=>n+r.attention.length,0));assert.equal(p.summary.attentionInitiatives,p.attentionRows.length);assert.ok(merchant.attention.every(a=>a.href.startsWith(`/initiatives/${merchant.initiative.slug}/`)));});
test('absence of claims is setup incomplete, never a checked clean record',()=>{const d=fixture();const empty=d.source.snapshots.find(s=>!s.claims.length)!;const row=projection(d).rows.find(r=>r.initiative.id===empty.initiative.id)!;assert.equal(row.coverage.complete,false);assert.match(row.coverage.label,/Evidence coverage incomplete/);assert.doesNotMatch(row.coverage.label,/no open differences|Healthy|Clear|Assessed/);});
test('register drilldowns exactly match shared counts',()=>{const p=projection(fixture());assert.equal(filterPortfolioRows(p.rows,{attention:'any'},p.today).length,p.summary.attentionInitiatives);assert.equal(filterPortfolioRows(p.rows,{setup:'incomplete'},p.today).length,p.summary.setupIncomplete);assert.equal(filterPortfolioRows(p.rows,{target:'unknown'},p.today).length,p.summary.unknownTargets);assert.equal(filterPortfolioRows(p.rows,{target:'upcoming'},p.today).length,p.summary.upcomingTargets);});
test('unconfirmed entries remain visible and do not manufacture completion',()=>{const d=fixture();const snap=d.source.snapshots.find(s=>s.claims.length)!;snap.claims=snap.claims.map(c=>({...c,status:'UNVERIFIED'}));const row=projection(d).rows.find(r=>r.initiative.id===snap.initiative.id)!;assert.equal(row.coverage.complete,false);assert.match(row.coverage.label,/nothing confirmed/);assert.match(row.coverage.label,/not yet confirmed/);});
test('full actual removes upcoming target; partial rollout retains it',()=>{const d=fixture();const r=projection(d).rows.find(r=>r.target&&r.target.value.date!>='2026-09-26')!;const target=r.target!;d.deliveryState.facts.push({...target,id:'actual',kind:'ACTUAL_LIVE',value:{...target.value,date:'2026-09-25',extent:'FULL'}});let p=projection(d);assert.equal(p.upcoming.filter(u=>u.initiativeId===r.initiative.id&&u.kind==='TARGET_LIVE').length,0);d.deliveryState.facts.find(f=>f.id==='actual')!.value.extent='PARTIAL';p=projection(d);assert.equal(p.upcoming.filter(u=>u.initiativeId===r.initiative.id&&u.kind==='TARGET_LIVE').length,1);});
test('foreign workspace facts/events cannot add attention, dates or history',()=>{const d=fixture();const before=projection(d);const target=d.deliveryState.facts.find(f=>f.kind==='TARGET_LIVE')!;d.deliveryState.facts.push({...target,id:'foreign-blocker',workspaceId:'foreign',kind:'BLOCKER',value:{date:null,text:'foreign secret',memberId:null,extent:null}});d.deliveryState.events.push({...d.deliveryState.events[0]!,id:'foreign-event',workspaceId:'foreign',occurredAt:DEMO_CUTOFF,after:{...target,value:{...target.value,text:'foreign secret'}}});assert.deepEqual(projection(d),before);});
test('confirmed changes after fixed scenario date remain current history',()=>{const d=fixture();const i=d.source.snapshots.find(s=>s.initiative.slug==='merchant-flex-finance')!.initiative;const old=factFor(d.deliveryState.facts,i.id,'TARGET_LIVE')!;const ctx:WorkspaceAccess={workspaceId:identity.workspaceId,organizationId:identity.organizationId,memberId:identity.reviewerMemberId,role:'ORG_OWNER',platformRole:null,isProductLead:false,actor:{id:identity.reviewerUserId,label:'Fictional reviewer'}};const finalBefore=JSON.stringify(d.deliveryState.reviews.filter(r=>r.status==='FINAL'));d.deliveryState=recordFact(d.deliveryState,d.source,ctx,{initiativeId:i.id,kind:'TARGET_LIVE',expectedRevision:old.revision,value:{...old.value,date:'2026-10-09'},retract:false,basis:'DIRECT_KNOWLEDGE',note:'Fictional local acceptance update.',evidenceId:null,locator:null},'2026-09-27T12:00:00.000Z');const p=projection(d);assert.equal(p.rows.find(r=>r.initiative.id===i.id)!.target!.value.date,'2026-10-09');assert.ok(p.changes.some(c=>c.occurredAt==='2026-09-27T12:00:00.000Z'&&c.sentence.includes('Target Live moved')));assert.equal(JSON.stringify(d.deliveryState.reviews.filter(r=>r.status==='FINAL')),finalBefore);});
test('projection leaves source, state and historical Final unchanged',()=>{const d=fixture();const before=JSON.stringify(d);projection(d);assert.equal(JSON.stringify(d),before);});

test('archived initiatives retain context but leave active portfolio attention and filters',()=>{
 const d=fixture(),before=projection(d),id=before.attentionRows[0]!.initiative.id;
 d.source.snapshots.find(s=>s.initiative.id===id)!.initiative.archivedAt='2026-09-27T10:00:00Z';
 const p=projection(d);assert.ok(p.rows.some(r=>r.initiative.id===id));assert.ok(!p.attentionRows.some(r=>r.initiative.id===id));assert.ok(!p.upcoming.some(r=>r.initiativeId===id));assert.equal(filterPortfolioRows(p.rows,{record:'archived'},p.today).length,1);assert.equal(filterPortfolioRows(p.rows,{},p.today).length,before.rows.length-1);
});

test('a late dependency is one attention reason in the shared model, counted the same everywhere',()=>{
 const d=fixture();const [a,b]=d.source.snapshots;const base=d.deliveryState.facts.find(f=>f.kind==='TARGET_LIVE')!;
 const mk=(id:string,kind:'TARGET_LIVE'|'NEXT_MILESTONE',date:string)=>({...base,id:`${id}-${kind}`,initiativeId:id,kind,state:'SET' as const,value:{date,text:kind==='NEXT_MILESTONE'?'Milestone':null,memberId:null,extent:null}});
 d.deliveryState.facts=[...d.deliveryState.facts.filter(f=>!((f.initiativeId===a!.initiative.id&&f.kind==='NEXT_MILESTONE')||(f.initiativeId===b!.initiative.id&&f.kind==='TARGET_LIVE'))),mk(a!.initiative.id,'NEXT_MILESTONE','2099-01-01'),mk(b!.initiative.id,'TARGET_LIVE','2099-02-01')];
 const rel={id:'r1',workspaceId:identity.workspaceId,fromInitiativeId:a!.initiative.id,toInitiativeId:b!.initiative.id,type:'DEPENDS_ON' as const,rationale:'x',providerFactKind:'TARGET_LIVE' as const,neededByFactKind:'NEXT_MILESTONE' as const,evidenceId:null,evidenceAnchorId:null,originProposalId:null,originHref:null,status:'ACTIVE' as const,createdBy:'u',confirmedBy:'u',confirmedByLabel:'U',confirmedAt:'2026-01-01',endedBy:null,endedByLabel:null,endedAt:null,endReason:null,updatedAt:'2026-01-01',revision:1};
 const run=(relationships:typeof rel[])=>buildPortfolioProjection({source:d.source,state:d.deliveryState,workspaceId:identity.workspaceId,activity:d.productStore.activity,asOf:DEMO_CUTOFF,relationships}).rows.find(r=>r.initiative.id===a!.initiative.id)!;
 const without=run([]),withRel=run([rel]);
 assert.equal(withRel.attention.filter(x=>x.kind==='DEPENDENCY').length,1);assert.equal(withRel.attention.length,without.attention.length+1);
});

test('Roadmap and Analysis count "Dependency date impact" identically: initiatives on either end, not relationship rows',async()=>{
 const {applyFilters,hasDependencyImpact}=await import('./roadmap-layout.ts');
 const d=fixture();const [a,b,c]=d.source.snapshots;const base=d.deliveryState.facts.find(f=>f.kind==='TARGET_LIVE')!;
 const mk=(id:string,kind:'TARGET_LIVE'|'NEXT_MILESTONE',date:string)=>({...base,id:`${id}-${kind}`,initiativeId:id,kind,state:'SET' as const,value:{date,text:kind==='NEXT_MILESTONE'?'Milestone':null,memberId:null,extent:null}});
 const ids=[a!,b!,c!].map(s=>s.initiative.id);
 d.deliveryState.facts=[...d.deliveryState.facts.filter(f=>!(ids.includes(f.initiativeId)&&(f.kind==='NEXT_MILESTONE'||f.kind==='TARGET_LIVE'))),mk(ids[0]!,'NEXT_MILESTONE','2099-01-01'),mk(ids[1]!,'TARGET_LIVE','2099-02-01'),mk(ids[2]!,'NEXT_MILESTONE','2099-01-01')];
 const rel=(id:string,from:string,to:string)=>({id,workspaceId:identity.workspaceId,fromInitiativeId:from,toInitiativeId:to,type:'DEPENDS_ON' as const,rationale:'x',providerFactKind:'TARGET_LIVE' as const,neededByFactKind:'NEXT_MILESTONE' as const,evidenceId:null,evidenceAnchorId:null,originProposalId:null,originHref:null,status:'ACTIVE' as const,createdBy:'u',confirmedBy:'u',confirmedByLabel:'U',confirmedAt:'2026-01-01',endedBy:null,endedByLabel:null,endedAt:null,endReason:null,updatedAt:'2026-01-01',revision:1});
 // Two late relationship rows over three initiatives (a→b, c→b): the count is 3 initiatives, never 2 rows.
 const p=buildPortfolioProjection({source:d.source,state:d.deliveryState,workspaceId:identity.workspaceId,activity:d.productStore.activity,asOf:DEMO_CUTOFF,relationships:[rel('r1',ids[0]!,ids[1]!),rel('r2',ids[2]!,ids[1]!)]});
 const analysis=filterPortfolioRows(p.rows,{attention:'dependency'},p.today).length;
 const items=p.rows.filter(r=>!r.initiative.archivedAt).map(r=>({attention:r.attention.map(x=>({kind:x.kind,label:x.label,detail:x.detail,href:x.href})),businessLine:r.initiative.businessLine,ownerId:r.ownerId,target:null,movement:null}));
 const roadmap=applyFilters(items as unknown as Parameters<typeof applyFilters>[0],{businessLine:'',owner:'',view:'dependency'}).length;
 assert.equal(analysis,3);assert.equal(roadmap,analysis);assert.equal(items.filter(hasDependencyImpact).length,analysis);
});
